---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2023/11/24 17:35
---

_G.CityFsmState = {
    Idle = 1,
    Path = 2,
}
---主界面小人状态
_G.CityPeopleFsmState = {
    Birth = 0,
    Idle = 1,
    FindPath = 2,
    None = 3,
    GoToPoint = 4
}
_G.CityUnitType = {
    MainRole = 0, --主角
    Role = 1, --玩家
    NPC = 2,
}

_G.CityTypeEnum = {
    city = 1,
    ins = 2,
}

_G.CityEvent = {
    ShowBuildNameHudInfo = 101,--显示建筑名字HUD
    FadeHideBuildNameHudInfo = 102,--渐隐建筑名字HUD
    RefreshBuildUpgrade = 103,--刷新建筑升级HUD
    PeopleGotoWork = 104,--居民去工作
    PeopleGotoSleep = 105,--居民去睡觉
    PeopleGotoEat = 106,--居民去睡觉
    NewPeoples = 107,--新增居民或流民
    RefreshBuildProductionTask = 108,--刷新建筑生产任务
    DeletePeople = 109,--居民逃跑或死亡
    UsePeopleSkill = 110,--使用民心技能
    GotoHospital = 111,--去医院
    OutHospital = 112,--康复，从医院出来
    RefreshCityMonster = 113,--刷新主城怪物
    RefreshCityMonsterHUD = 114,--刷新主城怪物HUD
    ShowCityMonster = 115,--显示主城怪物（暂时用在剧情结束）
    HideCityMonster = 116,--隐藏主城怪物（暂时用在剧情开始）
    HidePeopleHUD = 117,--隐藏居民HUD(暂时用在剧情开始)
    ShowPeopleHUD = 117,--显示居民HUD(暂时用在剧情结束)
    RefreshBuildBoxState = 119,--刷新建筑宝箱状态
    RefreshBuildGuildHelp = 120,--刷新同盟帮助
    RefreshCallHeroTipsInfo = 121,--刷新英雄召唤
    RefreshShopInfo = 122,--刷新商店气泡
    RefreshHeroUpStarInfo = 123,--刷新英雄升星气泡
    RefreshArenaIconInfo = 124,--刷新竞技场气泡
    PeopleRecruitChange = 125,--流民变为居民
}