---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2025/7/17 12:29
---

---变身类型
---
---@class LBattleSkillActObjTransform
local LBattleSkillActObjTransform = classX("LBattleSkillActObjTransform", nil)

---@param player LBattleSkillPlayer
---@param effData LSkillEffectData
---@param playState LBattleSkillPlayState
function LBattleSkillActObjTransform.Execute(player,effData, playState)
    local obj = player:GetTargetAtkUnitView()
    --动作名字
    local ani = effData.effRes
    --动作时间
    local time = effData.playTime
    time = effData.actionReset == 0 and time or 0


    if not player._treasureObj then
        ---# http://192.168.16.2:3002/issues/597
        --- SkillVfxRef中effType=2时，统一做成隐藏自己的血条（包括所有普攻、技能释放动作）
        obj:PlayBlockStickSHTween(time)
    end

    obj:PlayAni(ani, false, time)
end

return LBattleSkillActObjTransform