---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by H.
--- DateTime: 2023/8/29 15:29
---

--需要先初始化一些前置声明
require("LApp.LLauncherInit")

---@class LxLauncher
local LxLauncher = classX("LxLauncher", nil)

function LxLauncher:LxLauncher()

end

function LxLauncher:SetEnv(env)
    self._initEnv = env
end

function LxLauncher:GetEnv()
    return self._initEnv
end

function LxLauncher:ResetEnv(env)
    local curG = _G
    local initG = env.initG
    for k,v in pairs(curG) do
        if not initG[k] then
            curG[k] = nil
        end
    end

    local tblLoaded = package.loaded
    local initLoaded = env.initLoaded
    for k,v in pairs(tblLoaded) do
        if not initLoaded[k] then
            tblLoaded[k] = nil
        end
    end

    local tblPreLoad = package.preload
    local initPreload = env.initPreLoad
    for k,v in pairs(tblPreLoad) do
        if not initPreload[k] then
            tblPreLoad[k] = nil
        end
    end
end

function LxLauncher:Startup()
    gLxMain = require("LApp.LxMain"):New()
    gLxMain:Initialize(self._isReload)

    if CS.IsWebGL() then
        LDisplayCtrl.Init()

        --设置低分辨率，暂时只设置ios低端
        if LGameSettings.isSetPixelRatio and LWxHelper.IsLowMemory() and LWxHelper.IsInIos() then
            gprint("setPixelRatio")
            CS.CallCsFun(CsFunType.PixelRatio)
        end
    end
end

function LxLauncher:Shutdown()
    if (gLxMain) then
        gLxMain:Exit()
        gLxMain = nil
    end
end

function LxLauncher:Restart()
    printInfo("Launcher", "%s", "Restart...")

    --refresh fontengine
    --refresh tmprofont

    local env = self:GetEnv()
    self:ResetEnv(env)

    require("LApp.LxLauncher").Launcher(env)
end

function LxLauncher:RestartByReload()
    printInfo("Launcher", "%s", "RestartByReload...")

    local env = self:GetEnv()
    local inst = self
    inst:Shutdown()
    inst:ResetEnv(env)

    require("LApp.LLauncherInit")

    gLxLauncher = inst

    inst:SetEnv(env)
    inst:SetReload(true)
    inst:Startup()
end

function LxLauncher:SetReload(bReload)
    self._isReload = bReload
end

function LxLauncher.Launcher(env)
    local inst = LxLauncher:New()
    gLxLauncher = inst
    inst:SetEnv(env)
    inst:Startup()
end

return LxLauncher