---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2023/11/23 18:00
---

--伪单例
local _city_Base_eventMgr = require("LApp.gameplay.base.LGpEvent"):new()

local LGpBase = require("LApp.gameplay.base.LGpBase")
---@class LCityBase:LGpBase
local LCityBase = classX("LCityBase", LGpBase)

function LCityBase:ctor()
    LGpBase.ctor(self)
    self._eventSystem = _city_Base_eventMgr
end

return LCityBase