---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-02 10:58
---
-----------------------------------------------------------------
---@class LFightTest
local LFightTest = LxClass("LFightTest", nil)
-----------------------------------------------------------------
LFightTest._recordPlayerId = ""
LFightTest._formations = nil
-----------------------------------------------------------------
function LFightTest.TranslateFormation(formation)
	local formationData = {}
	formationData.formationType = LCombatTypeConst.COMBAT_TEST_BATTLE
	formationData.formationRefId = formation.formationRefId
	-- 【G公共支持】删除神器功能相关数据
	-- formationData.artifactId = formation.artifactId
	formationData.treasureSkilIds = formation.treasureSkilIds
	-- formationData.treasurePassiveSkill = formation.treasurePassiveSkill
	formationData.teamIndex = 1
	formationData.power = 0
	local gridA = {}
	formationData.grids = gridA
	formationData.divineWeaponStarRefIds = formation.divineWeaponStarRefIds or {}

	for k,v in pairs(formation.grids) do
		table.insert(gridA, {
			id = tostring(v.id),
			grid = v.grid
		})
	end
	-- 【C宠物系统】删掉宠物系统相关
	-- if formation.petFights then
	-- 	local petFights = {}
	-- 	for k,v in pairs(formation.petFights) do
	-- 		table.insert(petFights, v)
	-- 	end
	-- 	formationData.petFights = petFights

	-- end

	-- if formation.petHelps then
	-- 	local petHelps = {}
	-- 	for k,v in pairs(formation.petHelps) do
	-- 		table.insert(petHelps, v)
	-- 	end

	-- 	formationData.petHelps = petHelps
	-- end

	return formationData
end

function LFightTest.SetFormationData(formation, index)
	local formations = LFightTest.GetFormations()
	local key = LFightTest.GetSaveKey(index)
	formations[key] = LFightTest.TranslateFormation(formation)
end

function LFightTest.SaveFormations()
	local formations = LFightTest._formations
	if not formations then
		return
	end
	local playerId = tostring(gModelPlayer:GetPlayerId())
	local iniPath = CS.AppPersistentDataPath().."fmt_dat_"..playerId
	if string.isempty(iniPath) then return end
	local content = JSON.encode(formations)
	if string.isempty(content) then return end
	LFileHelper.WriteAllTextToCache(iniPath,content)
end

function LFightTest.GetFormations()
	local playerId = tostring(gModelPlayer:GetPlayerId())
	local curPlayerId = LFightTest._recordPlayerId
	if playerId ~= curPlayerId then
		LFightTest._formations = nil
		LFightTest._recordPlayerId = ""
	end
	local formations = LFightTest._formations
	if not formations then
		LFightTest._recordPlayerId = playerId
		local iniPath = CS.AppPersistentDataPath().."fmt_dat_"..playerId
		local strContent = LFileHelper.ReadAllTextFromCache(iniPath)
		if not string.isempty(strContent) then
			formations = JSON.decode(strContent)
		end
		formations = formations or {}
		LFightTest._formations = formations
	end
	return formations
end

function LFightTest.GetSaveKey(index)
	return "fmt_"..tostring(index)
end

-- 1 team a ,  2 team b
function LFightTest.GetFormationData(index)
	local key = LFightTest.GetSaveKey(index)
	local formations = LFightTest.GetFormations()
	return formations[key] or {}
end
------------------------------------------------------------------
return LFightTest