---
--- Generated by wzz finger
--- Created by wzz
--- DateTime: 2025-03-11
--- 保卫战 英雄
---
local LDefenceWarBaseCtrl = LXImport(".LDefenceWarBaseCtrl")

---@class LDefenceWarHeroCtrl:LDefenceWarBaseCtrl
local LDefenceWarHeroCtrl = LxClass("LDefenceWarHeroCtrl", LDefenceWarBaseCtrl)
-----------------------------------------------------------------

local typeOfTextMesh      = typeof(CS.TextMeshPro)
local Tweening            = DG.Tweening
local Color               = Color
local Vector3             = Vector3
local table               = table
local math                = math
local pairs               = pairs
local ipairs              = ipairs
local string              = string

local LDefenceWarHero     = LXImport("..Object.LDefenceWarHero")

-----------------------------------------------------------------
function LDefenceWarHeroCtrl:LDefenceWarHeroCtrl()
    self._cardDataList = {}
    for i = 1, 5 do
        local data  = {}
        data.heroId = 0

        local list  = {}
        for j = 1, 4 do
            local tab       = {}
            tab.skillId     = 0
            tab.skillLev    = 0
            tab.skillInitCd = 0
            tab.skillCd     = 0
            list[j]         = tab
        end
        data.skillList        = list
        data.buffList         = {}

        self._cardDataList[i] = data
    end
end

-- 销毁
function LDefenceWarHeroCtrl:OnDestroy()
    for _, v in ipairs(self._heroObjList) do
        v:Destroy()
    end
    self._heroObjList = {}
end

-- 初始化
function LDefenceWarHeroCtrl:Init()
    self._heroObjList = {}

    -- 技能配置
    self._skillSetting = {}

    for k, v in ipairs(gModelDefenceWar:GetFormationList()) do
        local heroId  = v.heroId
        local heroRef = gModelDefenceWar:GetHeroRef(heroId)

        local tab     = {}
        tab.skillId   = heroRef.startSkill
        tab.heroId    = heroId

        local list    = {}
        for i, v in ipairs(string.split(heroRef.skillId, ",")) do
            local skillId = tonumber(v)
            local data    = {}
            data.skillId  = skillId
            table.insert(list, data)
        end
        tab.skillList = list

        table.insert(self._skillSetting, tab)
    end

    self._objCtrl = self:GetCtrl("Objs")

    self:AddFirstHero()
end

-- 增加第一个英雄
function LDefenceWarHeroCtrl:AddFirstHero()
    -- 添加初始英雄
    local heroId = gModelDefenceWar:GetUseRefId(1)
    local heorRef = gModelDefenceWar:GetHeroRef(heroId)
    local skillId = heorRef.startSkill
    local skillLev = 1
    self:AddOrUpdateSkill(heroId, skillId, skillLev)
end

-- Update
function LDefenceWarHeroCtrl:Update(dt)
    local monsterInSkillRange = false

    local needCheck = false
    for _, heroObj in ipairs(self._heroObjList) do
        for _, skillObj in ipairs(heroObj:GetSkillObjList()) do
            if not skillObj:IsSkillCd() then
                needCheck = true
            end
        end
        if needCheck then
            break
        end
    end
    if needCheck then
        monsterInSkillRange = self._objCtrl:HasMonsterInSKillRange()
    end
    for _, v in ipairs(self._heroObjList) do
        if v:Update(dt, monsterInSkillRange) then
            break
        end
    end
end

-- 添加技能
function LDefenceWarHeroCtrl:AddOrUpdateSkill(heroId, skillId, skillLev)
    for k, obj in ipairs(self._heroObjList) do
        if obj:GetHeroId() == heroId then
            obj:AddOrUpdateSkill(skillId, skillLev)
            return
        end
    end

    local obj = LDefenceWarHero:New(self)
    obj:Init(heroId)
    obj:AddOrUpdateSkill(skillId, skillLev)
    table.insert(self._heroObjList, obj)
end

-- 增加buff
function LDefenceWarHeroCtrl:AddBuff(heroId, skillId, skillLev, attrName, attrType, attrVal, targetNum)
    targetNum = targetNum or 0
    if targetNum == 0 then
        targetNum = #self._heroObjList
    end
    for index, obj in ipairs(self._heroObjList) do
        if index > targetNum then
            break
        end
        obj:AddBuff(heroId, skillId, skillLev, attrName, attrType, attrVal)
    end

    FireEvent(EventNames.DEFENCEWAR_BUFF_CHANGE)
end

-- 移除buff
function LDefenceWarHeroCtrl:RemoveBuff(heroId, skillId)
    for index, obj in ipairs(self._heroObjList) do
        obj:RemoveBuff(heroId, skillId)
    end

    FireEvent(EventNames.DEFENCEWAR_BUFF_CHANGE)
end

-- 获取英雄对象
function LDefenceWarHeroCtrl:GetHeroObj(heroId)
    for k, obj in ipairs(self._heroObjList) do
        if obj:GetHeroId() == heroId then
            return obj
        end
    end
    return nil
end

-- 获取技能对象
function LDefenceWarHeroCtrl:GetSkillObj(heroId, skillId)
    local heorObj = self:GetHeroObj(heroId)
    if heorObj then
        return heorObj:GetSkillObj(skillId)
    end
    return nil
end

-- 获取当前技能数据列表(实时数据)
function LDefenceWarHeroCtrl:GetCurSkillDataList()
    local list = self._cardDataList

    for k, obj in ipairs(self._heroObjList) do
        local tab  = list[k]
        tab.heroId = obj:GetHeroId()
        for index, skillObj in ipairs(obj:GetSkillObjList()) do
            local data       = tab.skillList[index]
            data.skillId     = skillObj:GetSkillId()
            data.skillLev    = skillObj:GetSkillLev()
            data.skillInitCd = skillObj:GetSkillInitCd()
            data.skillCd     = skillObj:GetSkillCd()
        end
        tab.buffList = obj:GetBuffList()

        for _, v in ipairs(tab.buffList) do
            local skillObj = self:GetSkillObj(tab.heroId, v.skillId)
            if skillObj then
                v.duration = skillObj:GetDuration()
                v.endTime = skillObj:GetEndTime()
            end
        end
    end
    return list
end

-- 获取当前随机技能池
function LDefenceWarHeroCtrl:GetRandomSkillPool()
    local heroIdMap = {}
    for _, obj in ipairs(self._heroObjList) do
        heroIdMap[obj:GetHeroId()] = true
    end

    local list = {}
    local model = gModelDefenceWar
    for _, tab in ipairs(self._skillSetting) do
        local heroId = tab.heroId
        local skillId = tab.skillId
        local skillLev, isActive = self:GetCurSkillLev(heroId, skillId)
        if not model:IsMaxLev(skillId, skillLev) then
            table.insert(list, {
                heroId   = heroId,
                skillId  = skillId,
                weight   = self:GetSkillWeight(true),
                skillLev = skillLev + 1,
            })
        end

        if heroIdMap[heroId] then
            for _, v in ipairs(tab.skillList) do
                heroId = heroId
                skillId = v.skillId
                skillLev, isActive = self:GetCurSkillLev(heroId, skillId)
                if not model:IsMaxLev(skillId, skillLev) then
                    table.insert(list, {
                        heroId   = heroId,
                        skillId  = skillId,
                        weight   = self:GetSkillWeight(false, true),
                        skillLev = skillLev + 1,
                    })
                end
            end
        end
    end
    return list, heroIdMap
end

-- 获取随机技能列表
function LDefenceWarHeroCtrl:GetRandomSkillList()
    local poolList, heroIdMap = self:GetRandomSkillPool()

    local showMax = 3
    local randomList = {}
    if #poolList > showMax then
        for i = 1, 3 do
            local totalWeight = 0
            for _, v in ipairs(poolList) do
                totalWeight = totalWeight + v.weight
                v.weightIndex = totalWeight
            end
            local weight = math.random(100, totalWeight * 100) * 0.01
            for k, v in ipairs(poolList) do
                if v.weightIndex >= weight then
                    table.insert(randomList, table.remove(poolList, k))
                    break
                end
            end
        end
    else
        randomList = poolList
    end

    for k, v in ipairs(randomList) do
        v.isNewHero = not heroIdMap[v.heroId]
    end
    return randomList
end

-- 获取技能权重
function LDefenceWarHeroCtrl:GetSkillWeight(isMain, isActive)
    if not self._skillWeightList then
        self._skillWeightList = {}
        local activeWebData = gModelDefenceWar:GetWebActivityData()
        if activeWebData then
            local list = string.split(activeWebData.config.roguelikeHeroWeight, ":")
            self._skillWeightList[1] = tonumber(list[1]) or 1
            self._skillWeightList[2] = tonumber(list[2]) or 1
            self._skillWeightList[3] = tonumber(list[3]) or 1
        end
    end


    if isMain then
        return self._skillWeightList[1] or 1
    end

    if isActive then
        return self._skillWeightList[3] or 1
    end

    return self._skillWeightList[2] or 1
end

-- 获取当前技能等级
function LDefenceWarHeroCtrl:GetCurSkillLev(heroId, skillId)
    for k, obj in ipairs(self._heroObjList) do
        if obj:GetHeroId() == heroId then
            for index, skillObj in ipairs(obj:GetSkillObjList()) do
                if skillObj:GetSkillId() == skillId then
                    return skillObj:GetSkillLev(), skillObj:IsActiveSkill()
                end
            end
        end
    end
    return 0, false
end

-- 获取英雄伤害列表
function LDefenceWarHeroCtrl:GetHeroHurtList()
    local list = {}
    for k, obj in ipairs(self._heroObjList) do
        local tab = {}
        tab.heroId = obj:GetHeroId()
        tab.hurt = obj:GetTotalHurt()
        table.insert(list, tab)
    end
    return list
end

-- 暂停
function LDefenceWarHeroCtrl:OnPauseGame()
    for k, v in ipairs(self._heroObjList) do
        v:OnPauseGame()
    end
end

-- 恢复
function LDefenceWarHeroCtrl:OnResumeGame()
    for k, v in ipairs(self._heroObjList) do
        v:OnResumeGame()
    end
end

return LDefenceWarHeroCtrl
