---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-16 19:22
---
---@type LWnd
local LWnd = LWnd

function LWnd:InitWndThemeShow(themeName)
	if string.isempty(themeName) then
		themeName = "default"
	end

	if self._curThemeName == nil then
		self._curThemeName = "default"
	end
	if self._curThemeName == themeName then
		return
	end
	self:ClearWndThemeShow()
	self._curThemeName = themeName
	local wndName = self:GetWndName()
	-- local showWndRef = GameTable.ThemeConfigRef[wndName]
	local showWndRef = nil
	if not showWndRef then
		return
	end
	
	local useShow = showWndRef.useShow
	if useShow == 0 then
		return
	end
	
	local showFileName = showWndRef.showName
	local showFileRef = GameTable[showFileName]
	if not showFileRef then
		return
	end
	
	local cfgStr = nil
	for k,themeData in pairs(showFileRef) do
		local path = themeData.path
		cfgStr = themeData[themeName]
		self:_ShowWndThemeNode(path, cfgStr)
	end
end
function LWnd:ClearWndThemeShow()
	if not self._curThemeName then
		return
	end
	
	if self._themeEffMap then
		for key,effDp in pairs(self._themeEffMap) do
			self:DestroyWndEffectByKey(key)
		end
	end
	
	if self._themeSpineMap then
		for key,spineDp in pairs(self._themeSpineMap) do
			self:DestroyWndSpineByKey(key)
		end
	end
	
	self._themeEffMap = {}
	self._themeSpineMap = {}
end

function LWnd:_ShowWndThemeNode(nodePath, cfgStr)
	if string.isempty(cfgStr) then
		return
	end
	
	local wndTrans = self:GetWndTrans()
	if CS.IsNullObject(wndTrans) then
		return
	end
	
	local nodeTrans = self:FindWndTrans(wndTrans, nodePath)
	if CS.IsNullObject(nodeTrans) then
		return
	end
	
	local showCfgList = string.split(cfgStr, ';')
	
	local typeKey= nil
	local valueStr = nil
	local itemList = nil
	
	local typeFunc = {
		["img"] = function(key, node, value, onLoadFunc) self:_ShowWndThemeNodeImg(key, node, value, onLoadFunc) end,
		["spine"] = function(key, node, value, onLoadFunc) self:_ShowWndThemeNodeSpine(key, node, value, onLoadFunc) end,
		["eff"] = function(key, node, value, onLoadFunc) self:_ShowWndThemeNodeEff(key, node, value, onLoadFunc) end,
		["enable"] = function(key, node, value, onLoadFunc) self:_ShowWndThemeNodeEnable(key, node, value, onLoadFunc) end,
		["alpha"] = function(key, node, value, onLoadFunc) self:_ShowWndThemeNodeAlpha(key, node, value, onLoadFunc) end,
	}
	
	local loadCnt = 0
	local loadIdx = 0
	
	for idx,showCfgItem in ipairs(showCfgList) do
		itemList = string.split(showCfgItem, '=')
		typeKey = itemList[1]
		valueStr = itemList[2]
		
		local func = typeFunc[typeKey]
		if func then
			loadCnt = loadCnt + 1
			func(nodePath, nodeTrans, valueStr, function()
				loadIdx = loadIdx + 1
				if loadIdx >= loadCnt then
					self:_OnLoadAllNode()
				end
			end)
		end
	end
	
end

function LWnd:_OnLoadAllNode()
	if self._themeSpineMap then
		local ani = nil
		for k,spine in pairs(self._themeSpineMap) do
			if spine:IsDpValid() then
				ani = spine:GetCurAnimationName()
				if not string.isempty(ani) then
					spine:ClearAnimation(0)
					spine:PlayAnimation(0, ani, true, false, 0)
				end 
			end
		end
	end
end

function LWnd:_ShowWndThemeNodeImg(nodePath, nodeTrans, valueStr, onLoadFunc)
	if onLoadFunc then
		onLoadFunc()
	end
end

function LWnd:_ShowWndThemeNodeSpine(nodePath, nodeTrans, valueStr, onLoadFunc)
	if string.isempty(valueStr) then
		return
	end

	local valueStrlist = string.split(valueStr, "|")
	local spineName = valueStrlist[1]
	local ani = valueStrlist[2]

	local dp = self:CreateWndSpine(nodeTrans, spineName, nodePath, false, function(dpSpine)
		dpSpine:SetRaycastTarget(false)
		local dpTrans = dpSpine:GetDisplayTrans()
		dpTrans.anchorMin = Vector2.New(0.5,0.5)
		dpTrans.anchorMax = Vector2.New(0.5,0.5)
		if not string.isempty(ani) then
			dpSpine:PlayAnimation(0, ani, true, false, 0)
		end
		
		if onLoadFunc then
			onLoadFunc()
		end
	end)
	self._themeSpineMap[nodePath] = dp
end

function LWnd:_ShowWndThemeNodeEff(nodePath, nodeTrans, valueStr, onLoadFunc)
	if onLoadFunc then
		onLoadFunc()
	end
end

function LWnd:_ShowWndThemeNodeEnable(nodePath, nodeTrans, valueStr, onLoadFunc)
	if CS.IsNullObject(nodeTrans) then
		return
	end
	local val = tonumber(valueStr) or 0
	local enable = val == 1
	CS.ShowObject(nodeTrans, enable)
	
	if onLoadFunc then
		onLoadFunc()
	end
end

function LWnd:_ShowWndThemeNodeAlpha(nodePath, nodeTrans, valueStr, onLoadFunc)
	if onLoadFunc then
		onLoadFunc()
	end
end