---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-22 20:56
---

---@class LFightFormationData
local LFightFormationData = LxClass("LFightFormationData",nil)
LXImport(".LFightHeroGrid")
LXImport(".LFightUnitData")

function LFightFormationData:LFightFormationData()

end

function LFightFormationData:CreateByPb(pb)
    self.playerId = pb.playerId
    self.refId = pb.refId
    self.monster = pb.monster == 1

    local grids = {}
    for k,v in ipairs(pb.grids) do
        local grid = LFightHeroGrid:New()
        grid:CreateByPb(v,pb.monster) --兼容旧战报
        table.insert(grids,grid)
    end
    self.grids = grids
    self.power = math.floor(tonumber(pb.power) or 0)
    self.robot = pb.robot == 1
    self.mvpHeroRefId = pb.mvpHeroRefId
    self.mvpHeroId = pb.mvpHeroId
    local list = {}
    for k,v in ipairs(pb.combatUnits) do
        local unit= LFightUnitData:New()
        unit:CreateByPb(v)
        table.insert(list,unit)
    end

    self.combatUnits = list
    self.monsterFormationRefId = pb.monsterFormationRefId

    self.tacticsId = pb.tactics

    local formationName = pb.formationName
    if tonumber(self.playerId) == 0 and formationName then
        local translate = ccLngText(formationName)
        if not string.isempty(translate) then
            formationName = translate
        end
    end
    self.formationName = formationName
    printErrorN(string.format("report formationName %s",formationName))
end

function LFightFormationData:SetServerId(serverId)
    if serverId and serverId>0 then
        self.serverId = serverId
    end
end

--英雄战力与怪物战力都计算
function LFightFormationData:GetGridPower()
    local gridPower = 0
    for k,v in pairs(self.grids) do
        local curPower = 0
        local monster = v.monster
        if monster and monster == 1 then
            local monsterRef = gModelHero:GetMonsterAttrByRefId(v.refId)
            if monsterRef then
                curPower = monsterRef.monsterPower
            end
        else
            curPower = v.fightPower or 0
        end

        gridPower = gridPower + curPower
    end

    return gridPower
end

function LFightFormationData:GetFormationName()
    return self.formationName or ""
end

function LFightFormationData:GetTreasureData()
    for k,v in pairs(self.combatUnits) do
        if v.type == LFightConst.OBJ_TREASURE then
            return v
        end
    end
end

function LFightFormationData:GetDivineWeaponData()
    for k,v in pairs(self.combatUnits) do
        if v.type == LFightConst.OBJ_DIVINEWEAPON then
            return v
        end
    end
end

return LFightFormationData