---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023-10-23 21:45
---
------------------------------------------------------------------
---模块基础
------------------------------------------------------------------
---
---@class LModel
local LModel = LxClass("LModel", nil)

local LxBehaviour = LxRequire("LApp.component.LxBehaviour")
------------------------------------------------------------------
function LModel:LModel()
	self._modelName = nil
	self._isFinished = false
	self._bModelInit = nil -- model 初始化

	---@type LxBehaviour
	self._behaviour = LxBehaviour:New()
end

function LModel:ModelClear()
	self:OnModelClear()
	self._isFinished = false
end

function LModel:ModelCreate()
	self:OnModelCreate()
end

function LModel:ModelRequest()
	self:OnModelRequest()
end

function LModel:ModelInit()
	if self._bModelInit then return end
	self._bModelInit = true
	self:OnModelInit()
end

--模块数据处理完成后自行调用
function LModel:ModelFinish()
	local isFinished = self._isFinished
	if (isFinished) then
		return
	end
	self._isFinished = true
	gLModelManager:OnModelFinish(self)
end

function LModel:ModelDestroy()
	if self._behaviour then
		self._behaviour:Dispose()
		self._behaviour = nil
	end

	self:ModelClear()
	self:OnModelDestroy()

	local modelName = self._modelName
	table.removeall(self)
	self._modelName = modelName
	self._isFinished = false
	self._isDestroy = true

end

------------------------------------------------------------------
---派生类重写的
------------------------------------------------------------------
--类创建时候，会在创建完后调用一次
function LModel:OnModelCreate()

end

--开始登陆请求，或者重连登录都会调用
function LModel:OnModelRequest()

end

--OnModelRequest 之前调用，重连会在 OnModelRequest 之前调用
--销毁也会调用改函数一次
function LModel:OnModelClear()

end

--销毁的时候调用
function LModel:OnModelDestroy()

end

--在登录之前会调用一次，本次登录不会再调用
function LModel:OnModelInit()

end
-----------------------------------------------------------------

function LModel:GetInstanceName()
	return "g"..self:GetClassName()
end

------------------------------------------------------------------
---名字设置
------------------------------------------------------------------
function LModel:GetModelName()
	return self._modelName
end
function LModel:SetModelName(v)
	self._modelName = v
end

------------------------------------------------------------------
--- model event
------------------------------------------------------------------
--remove all event
function LModel:ModelRemoveAllEvent()
	if self._behaviour then
		self._behaviour:RemoveEventHandlerList()
	end
end

--remove by event
function LModel:ModelEventRemove(event)
	if self._behaviour then
		self._behaviour:RemoveEventHandler(event)
	end
end

--register event
function LModel:ModelEventRecv(event, func, target)
	if self._behaviour then
		self._behaviour:AddEventHandler(event, func, target)
	end
end

------------------------------------------------------------------
--- model netmsg
------------------------------------------------------------------
-- remove all msg
function LModel:ModelRemoveAllNetMsg()
	if self._behaviour then
		self._behaviour:RemoveMsgHandlerList()
	end
end

--register msg
function LModel:ModelNetMsgRecv(msg, func, target)
	if self._behaviour then
		self._behaviour:AddMsgHandler(msg, func, target)
	end
end

---获取配置表
function LModel:GetModelConfig(configName)
	--if not self._configList then
	--	self._configList = {}
	--end

	--local config = self._configList[configName]
	--if not config then
		local config = GameTable[configName]
	--	self._configList[configName] = config
	--end

	return config
end

function LModel:GetCacheParaValueByKey(refName,key)
	if not self._refParaCache then
		return
	end

	local refTable = self._refParaCache[refName]
	if not refTable then
		return
	end

	return refTable[key]
end

function LModel:SetCacheParaValueByKey(refName,key,value)
	if not self._refParaCache then
		self._refParaCache = {}
	end

	local refTable = self._refParaCache[refName]
	if not refTable then
		refTable = {}
		self._refParaCache = refTable
	end

	refTable[key] = value
end

function LModel:GetCacheValueByKey(refName,refId,key)
	if not self._refCache then
		return
	end

	local refTableList = self._refCache[refName]
	if not refTableList then
		return
	end

	local refTable = refTableList[refId]
	if not refTable then
		return
	end

	return refTable[key]
end

function LModel:SetCacheValueByKey(refName,refId,key,value)
	if not self._refCache then
		self._refCache = {}
	end

	local refTableList = self._refCache[refName]
	if not refTableList then
		refTableList = {}
		self._refCache = refTableList
	end

	local refTable = refTableList[refId]
	if not refTable then
		refTable = {}
		refTableList[refId] = refTable
	end

	refTable[key] = value
end

function LModel:GetConfigValueImpl(refName,refId,key,parseFun)
	local value = self:GetCacheValueByKey(refName,refId,key)
	if value then
		return value
	end
	local ref = self:GetModelConfig(refName)
	if not ref then
		return
	end

	value = ref[refId]
	if not value then
		return
	end
	value = value[key]
	if not value then
		return
	end
	if parseFun then
		value = parseFun(value)
	end

	self:SetCacheValueByKey(refName,refId,key,value)
	return value
end

function LModel:GetParaConfigValueImpl(refName,key,parseFun)
	local value = self:GetCacheParaValueByKey(refName,key)
	if value then
		return value
	end

	local ref = self:GetModelConfig(refName)
	if not ref then
		return
	end

	value = ref[key]
	if value and parseFun then
		value = parseFun(value)
	end

	self:SetCacheParaValueByKey(refName,key,value)
	return value
end


-----------------------------------------------------------------
function LModel:IsFinished()
	return self._isFinished
end

function LModel:IsDestroy()
	return self._isDestroy
end


return LModel