---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by H.
--- DateTime: 2023/8/29 15:29
---

---@class LxBatchTask
local LxBatchTask = classX("LxBatchTask", nil)

local BatchTaskState = {
    Stop = 0,
    Running = 1
}

local InvokeCallback = InvokeCallback

function LxBatchTask:Initialize()
    self._taskState = BatchTaskState.Stop
end

function LxBatchTask:InitBatchTask(cbText, cbProgress, execOK, cbObj)
    if self._taskState == BatchTaskState.Stop then
        self._cbObj = cbObj
        self._loadOk = execOK
        self._cbText = cbText
        self._cbProgress = cbProgress
        self._taskList = {}
    end
end

function LxBatchTask:AddBatchTask(name, desc, execOK, execObj)
    if self._taskState == BatchTaskState.Stop then
        local task = {
            name = name,
            desc = desc,
            execOK = execOK,
            execObj = execObj
        }
        table.insert(self._taskList, task)
    end
end

function LxBatchTask:StartBatchTask()
    if self._taskState == BatchTaskState.Stop then
        self._refIndex = 0
        self._taskState = BatchTaskState.Running
        self._refCount = #self._taskList
        self:NextBatchTask()
    end
end

function LxBatchTask:NextBatchTask()
    if self._refIndex >= self._refCount then
        if LOG_INFO_ENABLED then
            printInfo("BatchTask", "Finished Task !!!");
        end
        self:StopBatchTask()
        return
    end
    local task = table.remove(self._taskList, 1)
    if task ~= nil then
        if LOG_INFO_ENABLED then
            printInfo("BatchTask", "New Task---->>> name:%s, desc:>%s", tostring(task.name), tostring(task.desc));
        end
        if self._cbText ~= nil then
            InvokeCallback(self._cbText, self._cbObj, task.desc)
        end
        if task.execOK ~= nil then
            local execOK = task.execOK
            local execObj = task.execObj
            task.execOK = nil
            task.execObj = nil
            InvokeCallback(execOK, execObj, self.OnBatchTaskOK, self)

        end
    end
end

function LxBatchTask:StopBatchTask()
    local loadOk = self._loadOk
    local cbObj = self._cbObj
    self._loadOk = nil
    self._cbText = nil
    self._cbProgress = nil
    self._cbObj = nil
    if self._taskList then
        for k,v in ipairs(self._taskList) do
            v.execOK = nil
            v.execObj = nil
        end
        self._taskList = nil
    end
    self._taskState = BatchTaskState.Stop

    if loadOk ~= nil then
        InvokeCallback(loadOk, cbObj)
    end
end

function LxBatchTask:OnBatchTaskOK()
    self._refIndex = self._refIndex + 1
    if self._cbProgress ~= nil then
        InvokeCallback(self._cbProgress, self._cbObj, self._refIndex, self._refCount)
    end
    self:NextBatchTask()
end

return LxBatchTask
