---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-10 18:12
---
local CS = CS

---@type LPoolItem
local LPoolItem = LXImport(".LPoolItem")
---@type LPoolArgs
local LPoolArgs = LXImport(".LPoolArgs")

--------------------------------------------------------------------------------
---@class LSimplePool
local LSimplePool = LxClass("LSimplePool", nil)
--------------------------------------------------------------------------------
LSimplePool.ROOT_TAG = "simple_pool"
LSimplePool.ROOT_ITEM = "item_root"
LSimplePool.ROOT_TEMPLATE = "temple_root"

function LSimplePool.Static_MakeArgs(itemPath,itemName,resTag,itemType)
	local itemKey = string.gsub(itemPath,"/"..itemName..".prefab", "")
	--local itemKey = itemPath.."/"..itemName
	itemKey = itemKey.."/"..itemName
	itemKey = string.gsub(itemKey,"/", "_")
	return LPoolArgs:New(itemKey,itemPath,itemName,resTag,itemType)
end

function LSimplePool.Static_MakeWndArgs(itemPath,itemName,resTag, itemType)
	local itemKey = string.gsub(itemPath,"/"..itemName..".prefab", "")
	itemKey = itemKey.."/"..itemName
	itemKey = string.gsub(itemKey,"/", "_")
	return LPoolArgs:New(itemKey,itemPath,itemName,resTag, itemType)
end
--------------------------------------------------------------------
function LSimplePool:LSimplePool()
	self._poolName = nil
	self._rootTrans = nil
	self._itemRootTrans = nil
	self._templateRootTrans = nil

	---@type table<LPoolItem>
	self._dicPoolItem = {}

	self._isObjectActive = false
end

function LSimplePool:InitPool(rootTrans,poolName)
	self._rootTrans = rootTrans

	poolName = poolName or LSimplePool.ROOT_ITEM

	self._poolName = poolName
	local itemRootTrans = CS.FindTrans(rootTrans,poolName)
	if not itemRootTrans then
		itemRootTrans = CS.NewObject(poolName,rootTrans)
	end
	self._itemRootTrans = itemRootTrans

	local templateRootTrans = CS.FindTrans(itemRootTrans, LSimplePool.ROOT_TEMPLATE)
	if not templateRootTrans then
		templateRootTrans = CS.NewObject(LSimplePool.ROOT_TEMPLATE, itemRootTrans)
	end
	self._templateRootTrans = templateRootTrans
end

function LSimplePool:SetItemRootTransPos(pos)
	self._itemRootTrans.localPosition = pos
end

function LSimplePool:SetObjectActive(bActive)
	self._isObjectActive = bActive
end

function LSimplePool:MakeArgs(itemPath,itemName,resTag, itemType)
	return LSimplePool.Static_MakeArgs(itemPath,itemName,resTag, itemType)
end


-----------------------------------------------------------------
--还回预制体
function LSimplePool:ReturnItem(itemKey,trans)
	if not CS.IsValidObject(self._rootTrans) then
		return false
	end
	local poolItem = self._dicPoolItem[itemKey]
	if not poolItem then return false end
	if poolItem:ReturnItem(trans) then
		return true
	end
	return false
end

-----------------------------------------------------------------
--获预制体
---@param args LPoolArgs
function LSimplePool:MakeItemAsync(args,func)
	if not CS.IsValidObject(self._rootTrans) then
		func(nil,args)
		return
	end

	local poolItem = self:GetPoolItem(args)
	local item = poolItem:GetItem()
	if not item then
		poolItem:AddItemFunc(func)
	else
		func(item,args)
	end
end

---@param args LPoolArgs
function LSimplePool:MakeItem(args)
	if not CS.IsValidObject(self._rootTrans) then
		return
	end
	
	local poolItem = self:GetPoolItem(args)
	local item = poolItem:GetItem()
	return item
end

function LSimplePool:ClearLongTimeUnused(clearUnusedTime)
	for k,v in pairs(self._dicPoolItem) do
		v:ClearLongTimeUnused(clearUnusedTime)
	end
end

function LSimplePool:ClearPoolItemUnused(clearUnusedTime)
	for k,v in pairs(self._dicPoolItem) do
		if v:IsDestroy() or v:CheckClearUnused(clearUnusedTime) then
			self._dicPoolItem[k] = nil
			v:ClearItem()
			v:Destroy()
		end
	end
end
-----------------------------------------------------------------
function LSimplePool:InitPoolItem(args)
	self:PreparePoolItem(args)
end

function LSimplePool:PreparePoolItem(args,func, poolInitSize)
	local itemKey = args:GetItemKey()
	local poolItem = self._dicPoolItem[itemKey]
	if not poolItem then
		poolItem = self:GeneratePoolItemCls(itemKey, args)
		self._dicPoolItem[itemKey] = poolItem
	end

	if poolItem:IsDestroy() then
		if (func) then func(nil) end
		return
	end

	poolItem:SetPrepareSize(poolInitSize)

	if poolItem:IsInstanted() then
		if (func) then func(poolItem) end
		return
	end

	if func then poolItem:AddLoadedFunc(func) end

	if not poolItem:IsLoading() then
		poolItem:StartLoad()
	end
end

function LSimplePool:GeneratePoolItemCls(itemKey, args)
	local poolItem = LPoolItem:New(self._itemRootTrans,self._templateRootTrans,LPoolArgs.Copy(args))
	poolItem:SetObjectActive(self._isObjectActive)
	return poolItem
end

---@return LPoolItem
function LSimplePool:GetPoolItem(args)
	local itemKey = args:GetItemKey()
	local poolItem = self._dicPoolItem[itemKey]
	if not poolItem then
		poolItem = self:GeneratePoolItemCls(itemKey, args)
		self._dicPoolItem[itemKey] = poolItem
		poolItem:StartLoad()
	end
	return poolItem
end

function LSimplePool:IsDestroy()
	return self._isDestroy
end

function LSimplePool:ClearPool()
	if not CS.IsValidObject(self._rootTrans) then return end
	for k,v in pairs(self._dicPoolItem) do
		v:ClearItem()
		v:Destroy()
	end
	self._dicPoolItem = {}
end

function LSimplePool:Destroy()
	if self._isDestroy then return end
	for k,v in pairs(self._dicPoolItem or {}) do
		v:Destroy()
	end
	table.removeall(self)
	self._isDestroy = true
end



return LSimplePool

















