--- Generated by wzz finger
--- Created by wzz
--- DateTime: 2024/11/18
--- 新手剧情地图
-----------------------------------------------------------------

local LMapBase = LMapBase
---@class LGuideStoryMap:LMapBase
local LGuideStoryMap = LxClass("LGuideStoryMap", LMapBase)

local Vector3 = Vector3

-----------------------------------------------------------------

-----------------------------------------------------------------
function LGuideStoryMap:LGuideStoryMap()
    self:InitEvents()
end

function LGuideStoryMap:OnDestroy()
    self:DelayFuncClear()

    if self._mainRoleEff then
        self._mainRoleEff:Destroy()
        self._mainRoleEff = nil
    end

    if self._mgr then
        self._mgr:Destroy()
        self._mgr = nil
    end
    LMapBase.OnDestroy(self)
end

function LGuideStoryMap:OnCreate()
    LMapBase.OnCreate(self)
end

function LGuideStoryMap:OnResetMap()
    GF.OpenWnd("UIMinFight")
    GF.OpenWnd("UIGueStory")


    self:SetMapName("MapGuideStory")
end

function LGuideStoryMap:OnEnterMap()
    GF.CloseWndByName("UIPerCreateName")


    self:InitPosData()

    self._mgr = gLGpManager:GetGuideStoryMgrImpl()
    self._mgr:EnterMap(self)
    self._objCtrl = self._mgr:GetObjCtrl()


    self:InitCamera()
    self._onEnterMap = true


    -- 在引导点击进入新手地图时，由于点击完了，执行点击的逻辑，才会执行下一步的引导逻辑，所在在点击时，就进入了地图时，
    -- 导在初始化地图时，引导数据还未完成（实际已完）
    self:DelayFunc(function()
        self:ReadyStartStory()
    end, 0.2)
end

function LGuideStoryMap:OnExitMap()
    self:ReSetCameraSize()

    GF.CloseWndByName("UIGueStory")

    -- local cameraCom = self:GetMapCameraCom()
    -- cameraCom:StartFollowState(nil, Vector3(0, 0, 0), 0)

    local refId = gModelGuideStory:GetCurRefId()
    local step = gModelGuideStory:GetCurStep()
    if refId > 1 and step > 1 and gModelGuideStory:IsStroy(refId) then
        local ref = gModelGuideStory:GetRef(refId)
        local stepRef = gModelGuideStory:GetStepRef(ref.id, step)
        if stepRef and stepRef.stepId then
            gModelGuideStory:SendStoryStep(stepRef.stepId)
        end
    end
    if self._mainRoleEff then
        self._mainRoleEff:Destroy()
        self._mainRoleEff = nil
    end

    self._onEnterMap = nil
    self:DelayFuncClear()
    self._mgr:ExitMap()
end

-- 初始事件
function LGuideStoryMap:InitEvents()
    self:MapEventRecv(EventNames.GUIDE_STORY_STEP_FINISH, function()
        if not self._onEnterMap then
            return
        end
        self:StartGuideNextStep()
    end)
end

-- 初始化位置数据
function LGuideStoryMap:InitPosData()
    -- 地图对象坐标
    self._objPosMap = {}
    local root = self:GetMapTrans()
    local ObjPosTrans = CS.FindTrans(root, "ObjPos")
    for i = 0, ObjPosTrans.childCount - 1 do
        local trans             = ObjPosTrans:GetChild(i)
        local objKey            = trans.name
        local pos               = trans.position
        self._objPosMap[objKey] = pos
    end

    -- 路径坐标
    self._pathMap = {}
    local PathPosTrans = CS.FindTrans(root, "PathList")
    for i = 0, PathPosTrans.childCount - 1 do
        local trans = PathPosTrans:GetChild(i)
        local list  = {}
        for j = 0, trans.childCount - 1 do
            local child  = trans:GetChild(j)
            local objKey = tonumber(child.name)
            local pos    = child.position
            list[objKey] = pos
        end
        self._pathMap[trans.name] = list
    end

    CS.ShowObject(ObjPosTrans, false)
    CS.ShowObject(PathPosTrans, false)
end

-- 获取对象坐标
function LGuideStoryMap:GetObjInitPosByKey(objKey)
    if not self._objPosMap[objKey] then
        printErrorN2("GuideStory", "不存在对象, key:" .. tostring(objKey) .. " 的坐标，请在ui中添加！")
        return Vector3(0, 0, 0)
    end

    return self._objPosMap[objKey]
end

-- 获取路径列表
function LGuideStoryMap:GetPathListByKey(key)
    if not self._pathMap[key] then
        printErrorN2("GuideStory", "路径:" .. tostring(key) .. "，请在ui中添加！")
        return Vector3(0, 0, 0)
    end

    return self._pathMap[key]
end

-- 初始化相机
function LGuideStoryMap:InitCamera()
    local bgImgW = 640
    local bgImgH = 1400
    local mapW = bgImgW * 4 * 0.01
    local mapH = bgImgH * 2 * 0.01

    local UScreen = UnityEngine.Screen
    local screenWidth = UScreen.width * 0.01

    local orthgraphicSize = LUtil.GetCameraSize()
    local cameraCom = self:GetMapCameraCom()
    local min = Vector2(screenWidth * 0.5, orthgraphicSize)
    local max = Vector2(mapW - screenWidth * 0.5, mapH - orthgraphicSize)

    local sceneCamera = gLGameScene:GetCurrentSceneCamera()
    self._OldOrthgraphicSize = sceneCamera.orthographicSize
    sceneCamera.orthographicSize = gModelGuideStory:GetMapCameraSize()
    cameraCom:SetRange(min, max)

    -- 初始位置
    local group = LGuideStoryConst.ObjGroup[1]
    local obj1 = self:GetObjInitPosByKey(group[1].key)
    local obj2 = self:GetObjInitPosByKey(group[2].key)
    local pos = Vector3((obj1.x + obj2.x) * 0.5, (obj1.y + obj2.y) * 0.5, 0)
    local posList = { pos }
    self:CameraMoveByPosList(posList, 0)
end

-- 还原相机设置
function LGuideStoryMap:ReSetCameraSize()
    local sceneCamera = gLGameScene:GetCurrentSceneCamera()
    sceneCamera.orthographicSize = self._OldOrthgraphicSize
end

-- 准备开始剧情
function LGuideStoryMap:ReadyStartStory()
    local refId = gModelGuideStory:GetCurRefId()
    local step = gModelGuideStory:GetCurStep()
    if refId == 0 then
        refId, step = gModelGuideStory:GetUnFinishRefId()
    end

    if refId == 0 or gModelGuideStory:IsGuideStoryFinish() then
        -- 所有引导已完成
        GF.ChangeMap("LFightIdleMap")
        return
    end

    local initMapRefId = refId
    local initMapStep = step

    if gModelGuideStory:IsStroy(refId) then
        if step == 0 then
            -- self:InitMap(refId, 1)
            initMapStep = 1
            step = 2
        else
            local ref = gModelGuideStory:GetRef(refId)
            local groupId = ref.id
            local stepRef = gModelGuideStory:GetStepRef(groupId, step + 1)
            if not stepRef then
                gModelGuideStory:StartGuideStory(ref.next, 0)
                self:ReadyStartStory()
                return
            end

            local index = string.find(stepRef.type or "", "InitMap") or 0
            if index ~= 1 then
                if LOG_INFO_ENABLED then
                    gModelGuideStory:Log("初始化地图失误:" .. refId .. " 步骤:" .. step)
                end
                initMapStep = 1
                step = 2
            else
                initMapStep = step + 1
                step = initMapStep + 1
            end
        end
    else
        local ref = gModelGuideStory:GetRef(refId)
        if gModelGuideStory:IsGuideFinish(refId) then
            gModelGuideStory:StartGuideStory(ref.next, 0)
            self:ReadyStartStory()
            return
        end

        if step == 0 then
            local refId3, step3 = gModelGuideStory:GetUnFinishRefId()
            step = step3
        end

        local refId2 = gModelGuideStory:GetInitMapRefId(refId)
        initMapRefId = refId2
        initMapStep = 1
    end

    self:InitMap(initMapRefId, initMapStep, refId, step)
end

-- 初始化地图
function LGuideStoryMap:InitMap(initMapRefId, initMapStep, refId, step)
    local ref = gModelGuideStory:GetRef(initMapRefId)
    local groupId = ref.id
    local stepRef = gModelGuideStory:GetStepRef(groupId, initMapStep)

    if LOG_INFO_ENABLED then
        gModelGuideStory:Log("初始化地图开始:refId:" ..
            initMapRefId .. " 组:" .. groupId .. " 步骤:" .. initMapStep .. " 即将执行:" .. refId .. " 步骤:" .. step)
    end

    local time = os.clock()
    self[stepRef.type](self, stepRef, function()
        self:InitMapFinish(initMapRefId, initMapStep, refId, step, time)
    end)
end

-- 初始化地图完成
function LGuideStoryMap:InitMapFinish(initMapRefId, initMapStep, refId, step, time)
    local ref = gModelGuideStory:GetRef(initMapRefId)
    local groupId = ref.id
    local leftTime = os.clock() - time
    if LOG_INFO_ENABLED then
        gModelGuideStory:Log("初始化地图结束:refId:" ..
            initMapRefId ..
            " 组:" .. groupId .. " 步骤:" .. initMapStep .. " 即将执行:" .. refId .. " 步骤:" .. step .. " 耗时:" .. leftTime)
    end

    leftTime = math.max(1.5, leftTime + 0.5) -- 可防多次进入地图与等待视觉缓冲

    gModelGuide:EndGuide()
    if gModelGuideStory:IsStroy(refId) then
        self:DelayFunc(function() self:StartGuideStory(refId, step) end, leftTime)
    else
        gModelGuideStory:StartGuideStory(refId, step)

        if LOG_INFO_ENABLED then
            gModelGuideStory:Log("开始引导:" .. step)
        end
        local ref = GameTable.NewPlayerGuideEventRef[step]
        local origin = ref and ref.origin or 0
        if LGuideStoryConst.NeedInCityMap[origin] then
            GF.ChangeMap("LCityMap")
        end
        gModelGuide:StartGuide(step)
    end
end

-- 相机按路径移动
function LGuideStoryMap:CameraMoveByPosList(posList, speed)
    local cameraCom = self:GetMapCameraCom()
    if speed <= 0 then
        cameraCom:SetCameraPos(posList[#posList], 0)
        return 0
    end

    local camera = gLGameScene:GetCurrentSceneCamera()
    local cameraTrans = camera.transform
    local curPos = cameraTrans.position
    curPos.z = 0
    local totalTime = 0
    for i, pos in ipairs(posList) do
        local dis
        if i == 1 then
            dis = Vector3.Distance(curPos, pos)
        else
            dis = Vector3.Distance(posList[i - 1], pos)
        end
        local time = dis / speed
        self:DelayFunc(function() cameraCom:SetCameraPos(pos, time) end, totalTime)
        totalTime = totalTime + time
    end
    return totalTime
end

-- 延迟函数
function LGuideStoryMap:DelayFunc(func, delayTime)
    self._delayFuncList = self._delayFuncList or {}
    local key = LxTimer.DelayTimeCall(func, delayTime)
    table.insert(self._delayFuncList, key)
end

-- 清除延迟函数
function LGuideStoryMap:DelayFuncClear()
    for _, key in ipairs(self._delayFuncList or {}) do
        LxTimer.DelayTimeStop(key)
    end
    self._delayFuncList = {}
end

-- 游戏对象根节点
function LGuideStoryMap:GetObjRootTrans()
    if not self._objRootTrans then
        local root = self:GetMapTrans()
        self._objRootTrans = CS.FindTrans(root, "ObjRoot")
    end
    return self._objRootTrans
end

-- 游戏特效节点
function LGuideStoryMap:GetEffRootTrans()
    if not self._effRootTrans then
        local root = self:GetMapTrans()
        self._effRootTrans = CS.FindTrans(root, "EffRoot")
    end
    return self._effRootTrans
end

-----------------------------------------------------------------
--引导
-----------------------------------------------------------------
-- 开始引导
function LGuideStoryMap:StartGuideStory(refId, step)
    gModelGuideStory:StartGuideStory(refId, step)

    local ref = gModelGuideStory:GetRef(refId)
    local groupId = ref.id
    local stepRef = gModelGuideStory:GetStepRef(groupId, step)
    if not self[stepRef.type] then
        if LOG_INFO_ENABLED then
            gModelGuideStory:Log("不存在引导类型,id:" .. tostring(refId) .. " 步骤:" .. tostring(step), stepRef)
        end
        return
    end

    if LOG_INFO_ENABLED then
        if tostring(stepRef.type) == "Dialogue" then
            gModelGuideStory:Log("开始执行函数:" .. tostring(stepRef.type) .. ":" .. tostring(stepRef.dialogueId))
        else
            gModelGuideStory:Log("开始执行函数:" .. tostring(stepRef.type))
        end
    end

    if step > 1 then
        local lastStepRef = gModelGuideStory:GetStepRef(groupId, step - 1)
        if lastStepRef.stepId then
            gModelGuideStory:SendStoryStep(lastStepRef.stepId)
        end
    end

    local delayTime = self[stepRef.type](self, stepRef) or 0

    if stepRef.save then
        gModelGuideStory:PreSaveCurGuide()
    elseif stepRef.saveCur then
        gModelGuideStory:SaveCurGuide()
    end

    if delayTime == -1 then
        return
    end
    delayTime = delayTime + (stepRef.delay or 0)
    if delayTime > 0 then
        self:DelayFunc(function() self:StartGuideNextStep() end, delayTime)
        return
    end
    self:StartGuideNextStep()
end

-- 开始引导下一步
function LGuideStoryMap:StartGuideNextStep()
    local refId = gModelGuideStory:GetCurRefId()

    if not gModelGuideStory:IsStroy(refId) then
        return
    end

    local step        = gModelGuideStory:GetCurStep()
    local ref         = gModelGuideStory:GetRef(refId)
    local groupId     = ref.id
    local nextStepRef = gModelGuideStory:GetStepRef(groupId, step + 1)

    if nextStepRef then
        self:StartGuideStory(refId, step + 1)
        return
    end

    if ref.next == 0 then
        -- 引导已完成
        GF.ChangeMap("LFightIdleMap")
        return
    end

    local nextRef = gModelGuideStory:GetRef(ref.next)
    if gModelGuideStory:IsStroy(nextRef.refId) then
        self:StartGuideStory(nextRef.refId, 1)
        return
    end

    step = gModelGuideStory:GetFirstGuideId(nextRef.refId)
    gModelGuideStory:StartGuideStory(nextRef.refId, step)
    gModelGuide:StartGuide(step)
end

-- 相机移动
function LGuideStoryMap:CameraMove(stepRef)
    local time = 0
    local posList = stepRef.posList
    local speed = gModelGuideStory:GetDefaultCameraSpeed()
    if stepRef.speedType == 1 then
        speed = gModelGuideStory:GetBlockCameraSpeed()
    end

    local list = {}
    if posList == "ToMainRole" then
        local obj = self._objCtrl:GetMainRoleObj()
        local pos = obj:GetPosition()
        table.insert(list, pos)
    elseif posList == "ToGroup" then
        local groups = LGuideStoryConst.ObjGroup
        for _, index in ipairs(stepRef.groupList) do
            local group = groups[index]
            local obj1 = self:GetObjInitPosByKey(group[1].key)
            local obj2 = self:GetObjInitPosByKey(group[2].key)
            local pos = Vector3((obj1.x + obj2.x) * 0.5, (obj1.y + obj2.y) * 0.5, 0)
            table.insert(list, pos)
        end
    elseif posList == "ToKey" then
        local obj = self._objCtrl:GetObjByKey(stepRef.objKey)
        local pos = obj:GetPosition()
        table.insert(list, pos)
    end

    if stepRef.endOffset then
        local endPos = list[#list]
        endPos.x = endPos.x + stepRef.endOffset.x
        endPos.y = endPos.y + stepRef.endOffset.y
    end
    time = time + self:CameraMoveByPosList(list, speed)

    return time
end

-- 黑幕故事
function LGuideStoryMap:Block(stepRef)
    local param = {}
    param.dialogueId = stepRef.dialogueId
    FireEvent(EventNames.GUIDE_STORY_BLACK, param)
    return -1
end

-- 对白
function LGuideStoryMap:Dialogue(stepRef)
    local obj = self._objCtrl:GetObjByKey(stepRef.objKey)
    if not obj then
        printErrorN2("GuideStory", "地图不存在对象, key:" .. tostring(stepRef.objKey))
        return -1
    end

    local worldPos = obj:GetPosition()
    worldPos.y = worldPos.y

    local param = {}
    param.dialogueId = stepRef.dialogueId
    param.worldPos = worldPos

    FireEvent(EventNames.GUIDE_STORY_DIALOGUE, param)
    return -1
end

-- 地图对象消失
function LGuideStoryMap:DisappearsObj(stepRef)
    self._objCtrl:DeleteObjByKey(stepRef.objKey)
    return 0
end

-- 主角移动
function LGuideStoryMap:MainRoleMove(stepRef)
    local obj = self._objCtrl:GetMainRoleObj()
    if not obj then
        printErrorN2("GuideStory", "地图不存在主角")
        return -1
    end

    local time = self._objCtrl:MainRoleMove(stepRef)
    local cameraCom = self:GetMapCameraCom()
    cameraCom:StartFollowState(obj:GetDisplayTrans(), Vector3(0, 0, 0), 0)
    return time
end

-- 创建主角
function LGuideStoryMap:CreateMainRole(stepRef)
    local param = {
        pos = self:GetObjInitPosByKey(stepRef.posKey),
        noFollow = stepRef.noFollow,
    }
    if stepRef.showAni then
        self._objCtrl:CreateMainRole(param, function() self:ShowEnterAnim() end)
    else
        self._objCtrl:CreateMainRole(param, function() self:StartGuideNextStep() end)
    end
    return -1
end

-- 显示出场动画
function LGuideStoryMap:ShowEnterAnim()
    if self._mainRoleEff then
        self._mainRoleEff:Destroy()
        self._mainRoleEff = nil
    end

    local mainObj = self._objCtrl:GetMainRoleObj()
    local mainRoleTrans = mainObj:GetDisplayTrans()

    local dp = LDisplayEffect:New()
    dp:CreateEffect(self:GetObjRootTrans(), "fx_xsjq_chuchang")
    dp:SetResTag(CS.RES_TAG_SCENE)
    self._mainRoleEff = dp
    dp:SetLoadedFunction(function()
        if not self._mainRoleEff then
            return
        end

        local curPos = mainRoleTrans.position
        local trans = self._mainRoleEff:GetDisplayTrans()
        curPos.x = curPos.x
        trans.position = curPos

        self._objCtrl:PlayEnterAnim(function() self:StartGuideNextStep() end)
    end)

    self._objCtrl:ShowMainRoleAndFollow(false)
    dp:StartLoadEffect()
end

-- 对象加入跟随着
function LGuideStoryMap:AddFollow(stepRef)
    local heroRefId = nil
    if stepRef.addCur then
        local ref = gModelGuideStory:GetObjRef(stepRef.objKey)
        local heroEffectRef = GameTable.CharacterEffectRef[ref.heroEff]
        heroRefId = heroEffectRef and heroEffectRef.heroType
    end

    self._objCtrl:AddFollow(stepRef.objKey, function()
        gModelHero:PopGetHero(function()
            self:StartGuideNextStep()
            gModelBattle:DoOneKeyMainFormation()
        end, heroRefId)
    end)
    return -1
end

-- 创新新角色
function LGuideStoryMap:NewObj(stepRef)
    self._objCtrl:NewObj(stepRef, function() self:StartGuideNextStep() end)

    return -1
end

-- 执行引导
function LGuideStoryMap:Guide(guideStep)
    gModelGuide:StartGuide(guideStep.guideId)
    return -1
end

-- 进入战斗
function LGuideStoryMap:EnterFight()
    -- local combatData = {
    --     combatType = LCombatTypeConst.COMBAT_MAIN,
    --     -- meName = gModelPlayer:GetPlayerName()
    -- }
    -- gModelBattle:StartAfterSetFormation(combatData)

    gModelBattle:DoOneKeyMainBattle()

    return -1
end

-- 初始化地图1
function LGuideStoryMap:InitMap1(stepRef, callback)
    self:InitMapObj(nil, nil, function()
        if callback then
            callback()
        else
            self:StartGuideNextStep()
        end
    end)

    -- local pos = self:GetObjInitPosByKey("Role1")


    local group = LGuideStoryConst.ObjGroup[1]
    local obj1 = self:GetObjInitPosByKey(group[1].key)
    local obj2 = self:GetObjInitPosByKey(group[2].key)
    local pos = Vector3((obj1.x + obj2.x) * 0.5, (obj1.y + obj2.y) * 0.5, 0)


    -- local pos = self:GetObjInitPosByKey("Role1")

    local posList = { pos }
    self:CameraMoveByPosList(posList, 0)
    return -1
end

-- 初始化地图2
function LGuideStoryMap:InitMap1_2(stepRef, callback)
    local pos = stepRef.pos
    if stepRef.posType == "EndPath" then
        local posList = self:GetPathListByKey(pos)
        pos = posList[#posList]
    elseif stepRef.posType == "ToKey" then
        pos = self:GetObjInitPosByKey(stepRef.objKey)
    end

    local posList = { pos }
    self:CameraMoveByPosList(posList, 0)

    local times = 2
    local function finish()
        times = times - 1
        if times <= 0 then
            if callback then
                callback()
            else
                self:StartGuideNextStep()
            end
        end
    end

    local param = {
        pathKey = stepRef.pos,
        pos = pos,
        flipx = stepRef.flipx,
    }

    self._objCtrl:CreateMainRole(param, finish, stepRef.ignoreEnd)

    self:InitMapObj(stepRef.disappears, stepRef.idles, finish)
    return -1
end

-- 初始化地图2
function LGuideStoryMap:InitMap2(stepRef, callback)
    local mainObj = self._objCtrl:GetMainRoleObj()
    if mainObj then
        -- 地图已初始化完

        if stepRef.saveFormation then
            gModelBattle:DoOneKeyMainFormation()
        end

        if callback then
            callback()
        else
            self:StartGuideNextStep()
        end

        return -1
    end

    -- 重新登陆进入
    return self:InitMap1_2(stepRef, callback)
end

-- 初始化地图3
function LGuideStoryMap:InitMap3(stepRef, callback)
    local mainObj = self._objCtrl:GetMainRoleObj()
    if mainObj then
        -- 地图已初始化完

        if callback then
            callback()
        else
            self:StartGuideNextStep()
        end

        return -1
    end
    -- self:CreateLoopDialogueObj(stepRef) -- 去掉：2020-12-6

    return self:InitMap1_2(stepRef, callback)
end

-- 创建循环对白
function LGuideStoryMap:CreateLoopDialogueObj(stepRef, callback)
    local monsterList = {}
    local parent      = self:GetObjRootTrans()
    for k, v in ipairs(stepRef.dialogueList) do
        local pos = self:GetObjInitPosByKey(v.key .. v.keySuffix)

        local ref = gModelGuideStory:GetObjRef(v.key)
        table.insert(monsterList, {
            key     = v.key,
            flipx   = v.flipx,
            heroEff = ref.heroEff,
            scale   = ref.scale,
            parent  = parent,
            pos     = pos,

        })
    end
    self._objCtrl:CreateObjList(monsterList, callback)
end

-- 初始化Boss
function LGuideStoryMap:InitMapBoss(stepRef, callback)
    local pos = stepRef.pos
    if stepRef.posType == "EndPath" then
        local posList = self:GetPathListByKey(pos)
        pos = posList[#posList]
    end
    local posList = { pos }
    self:CameraMoveByPosList(posList, 0)

    local monsterFlipx = stepRef.monsterFlipx
    local monsterList  = {}
    local parent       = self:GetObjRootTrans()
    for _, v in ipairs(stepRef.monsterList) do
        local pos = self:GetObjInitPosByKey(v.key)
        local ref = gModelGuideStory:GetObjRef(v.key)
        local heroEff = v.heroEff or ref.heroEff
        table.insert(monsterList, {
            key     = v.key,
            flipx   = ref.flipx == 0,
            heroEff = heroEff,
            parent  = parent,
            pos     = pos,
            scale   = ref.scale,
        })
    end
    local times = 2
    local function finish()
        times = times - 1
        if times <= 0 then
            if callback then
                callback()
            else
                self:StartGuideNextStep()
            end
        end
    end

    local param = {
        flipx   = not monsterFlipx,
        pos     = pos,
        pathKey = stepRef.pos,
    }
    self._objCtrl:CreateMainRole(param, finish)
    self._objCtrl:CreateObjList(monsterList, finish)

    return -1
end

-- 循环对白
function LGuideStoryMap:LoopDialogue(stepRef)
    local dataList = {}
    for k, data in ipairs(stepRef.dialogueList) do
        local obj = self._objCtrl:GetObjByKey(data.key)
        if obj then
            local worldPos = obj:GetPosition()
            worldPos.y = worldPos.y

            table.insert(dataList, {
                id       = data.id,
                worldPos = worldPos,
                delay    = data.delay,
            })
        end
    end
    FireEvent(EventNames.GUIDE_STORY_DIALOGUE_LOOP, { delay = stepRef.delay, dataList = dataList })

    return 0
end

-- 初始化地图对象
function LGuideStoryMap:InitMapObj(disappears, idles, callback)
    local dataList = {}

    local disappearMap = {}
    for _, v in ipairs(disappears or {}) do
        disappearMap[v] = true
    end

    local idleMap = {}
    for _, v in ipairs(idles or {}) do
        idleMap[v] = true
    end

    local effTrans = self:GetEffRootTrans()
    local objTrans = self:GetObjRootTrans()
    for k, v in ipairs(LGuideStoryConst.ObjGroup) do
        for kk, data in ipairs(v) do
            if not disappearMap[data.key] then
                local ref = gModelGuideStory:GetObjRef(data.key)
                local atkData = {}

                local status = ref.spine == "attack1" and LGuideStoryConst.ObjStatus.Atk or LGuideStoryConst.ObjStatus.Idle
                if idleMap[data.key] then
                    status = LGuideStoryConst.ObjStatus.Idle
                end

                local pos = self:GetObjInitPosByKey(data.key)
                if #v == 2 then
                    -- 只有当为2个人时，才存在两两互打的情况
                    local effPos
                    if kk == 1 then
                        effPos = self:GetObjInitPosByKey(v[2].key)
                    else
                        effPos = self:GetObjInitPosByKey(v[1].key)
                    end

                    atkData = {
                        effRes   = ref.atkEff,
                        effTrans = effTrans,
                        effPos   = effPos,
                        effTime  = ref.effTime
                    }
                end
                local param = {
                    flipx   = ref.flipx == 0,
                    atkData = atkData,
                    heroEff = ref.heroEff,
                    parent  = objTrans,
                    status  = status,
                    pos     = pos,
                    key     = data.key,
                    scale   = ref.scale
                }

                table.insert(dataList, param)
            end
        end
    end

    if #dataList == 0 then
        if callback then
            callback()
        end
        return
    end

    self._objCtrl:CreateObjList(dataList, callback)
end

return LGuideStoryMap
