---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/11 21:44
---


---@class LFastDreamTripBase
local LFastDreamTripBase = LxClass("LFastDreamTripBase")

function LFastDreamTripBase:LFastDreamTripBase()

    self._isDisposed = false
end

function LFastDreamTripBase:Dispose()
    if self:IsDisposed() then return end
    table.remove(self)
    self._isDisposed = true
end

function LFastDreamTripBase:IsDisposed()
    return self._isDisposed
end

return LFastDreamTripBase