---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-18 09:45
---
local LxNodeBase = require("LApp.component.LxNodeBase")
---@class CommonEmptyList:LxNodeBase
local CommonEmptyList = LxClass("CommonEmptyList",LxNodeBase)


--[[
data=
{
    refId
    IntroTran,
    TextBgTran,
    IconTran,
    GetBtn,
    GetBtnText
    ButtonRoot,
}
]]

function CommonEmptyList:CommonEmptyList(parentWnd)
    self._parentWnd = parentWnd
end

function CommonEmptyList:Destroy()
    self._parentWnd = nil
    LxNodeBase.Dispose(self)
end


function CommonEmptyList:RefreshUI(data)
    CS.ShowObject(data.IconTran,false)
    CS.ShowObject(data.TextBgTran,false)
    local refId = data.refId
    local cfg = GameTable.EmptyTipsRef[refId]
    if not cfg then
        printInfoN(string.format("emptylist is nil refid %s",refId))
        return
    end
    local para = data.para
    --self:SetWndText(self.mTitle,cfg.title)
    local text = ccLngText(cfg.text)
    if para and #para > 0 then
        text = string.replace(text,unpack(para))
    end
    self:SetXTextContent(data.IntroTran,text)
    self:SetWndEasyImage(data.TextBgTran,cfg.textBg,function ()
        CS.ShowObject(data.TextBgTran,true)
    end)
    self:SetWndEasyImage(data.IconTran,cfg.icon,function ()
        CS.ShowObject(data.IconTran,true)
    end,true)
    local showBtn = cfg.btn==1
    if data.GetBtn then
        CS.ShowObject(data.GetBtn,showBtn)
    end
    if showBtn then
        local btnName = ccLngText(cfg.btnName)
        self:SetXTextContent(data.GetBtnText,btnName)
        local btnIcon = cfg.btnIcon
        if btnIcon then
            self:SetWndEasyImage(data.GetBtn,btnIcon)
        end
        local func = nil
        local jumpItem = cfg.jumpItem
        if jumpItem and jumpItem > 1 then
            func = function()
                self:Jump(jumpItem)
            end
        end
        local jumpId = cfg.jumpId
        if jumpId and jumpId > 1 then
            func = function()
                self:JumpFunc(jumpId)
            end
        end
        LxUiHelper.SetTransClick(data.GetBtn,function ()if func then func() end end)
    end
    CS.ShowObject(data.ButtonRoot,showBtn)
end

function CommonEmptyList:Jump(refId)
    gModelGeneral:OpenGetWayWnd({itemId = refId})
end

function CommonEmptyList:JumpFunc(jumpId)
    gModelFunctionOpen:Jump(jumpId)
end

function CommonEmptyList:SetWndEasyImage(trans, imgPath, func, isNativeSize, rootTrans)
    if string.isempty(imgPath) then
        return
    end
	if rootTrans then
        self:SetImage(trans, imgPath, func,isNativeSize)
	elseif self._parentWnd then
        self:SetImage(trans, imgPath, func,isNativeSize)
	else
        self:SetImage(trans, imgPath, func,isNativeSize)
	end
end

return CommonEmptyList