---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-28 21:16
---
local LayoutRebuilder = UnityEngine.UI.LayoutRebuilder
---@type BaseIconNew
local BaseIconNew = LXImport(".BaseIconNew")
------------------------------------------------------------------
---@class PetIconNew:BaseIconNew
local PetIconNew = LxClass("PetIconNew", BaseIconNew)
-----------------------------------------------------------------

function PetIconNew:PetIconNew(wndClass)
	self._refId = 0
	self._num = nil
	self._star = 0
	self._showGou = false
	self._showNum = false
	self._showLv = false
	-----------------------------------------------------------------
	self._displayStar = 0
	self._displayShowIcon = nil
	self._displayShowIconBg = nil
	self._displayGray = false
	self._displayNum = 0
	self._lvTxtStr = 0

	self._displayName = nil
	self._displayColor = nil

	self._cacheStar = 0
end

function PetIconNew:OnDestroy()

end
-----------------------------------------------------------------
function PetIconNew:ResetIcon()
	BaseIconNew.ResetIcon(self)

	self._refId = 0
	self._num = nil
	self._star = 0
	self._showGou = false
	self._showNum = false
	self._showLv = false
end

-----------------------------------------------------------------
function PetIconNew:ApplyIconUI()
	BaseIconNew.ApplyIconUI(self)

	self:SetIcon(self._displayShowIcon)
	self:SetIconBg(self._displayShowIconBg)

	self:UpdateStarUI()

	self:SetGouTransVisible(self._showGou)
	self:SetEquipIconGray()

	self:SetNumUIVisible()
	self:SetLvUIVisible()

	self:ApplyNumTxt()
	self:ApplyLvTxt()
end

function PetIconNew:OnInitTrans()

	local iconInst = self._iconInst
	self._uiNumTxtTrans = CS.FindTrans(iconInst,"NumTxt")
	self._uiLvTxtTrans = CS.FindTrans(iconInst,"LvTxt")
	self._uiStarTrans = CS.FindTrans(iconInst,"StarList")
	self._uiGouTrans = CS.FindTrans(iconInst,"GouImg")
	self._uiMaskTrans = CS.FindTrans(iconInst,"ImgMask")
	self:InitStartList()
end

-----------------------------------------------------------------
function PetIconNew:EnableShowNum(bShow)
	self._showNum = bShow
	self:UpdateNumData()
end

function PetIconNew:ShowNum(b)
	self._showNum = b

	self:UpdateNumData()

	if not self:IsIconValid() then return end

	self:SetNumUIVisible()

end

function PetIconNew:UpdateNumData()
	if self._showNum and not self._num then
		-- local data = gModelPet:GetPetEquipByRefId(self._refId)
		-- local num = data and data:GetNum() or 0
		self._displayNum = 0--num or 0
		return
	end

	self._displayNum = self._num or 0

end

function PetIconNew:SetNumUIVisible()
	local b = self._showNum and self._showNum or false

	if self._uiNumTxtTrans.gameObject.activeSelf ~= b then
		CS.ShowObject(self._uiNumTxtTrans, b)
	end
end

function PetIconNew:ApplyNumTxt()
	if not self._showNum then return end
	local num = self._displayNum
	local numStr = tostring(num)
	if not num or num == -1 then
		numStr = ""
	end
	self:SetXUIText(self._uiNumTxtTrans,numStr)
end

function PetIconNew:SetShowLv(b)
    if self._showLv == b then
        return
    end
    self._showLv = b
    if not self:IsIconValid() then
        return
    end
    self:SetLvUIVisible(not b)
end

function PetIconNew:SetLvUIVisible()
    if self._uiLvTxtTrans and self._uiLvTxtTrans.gameObject.activeSelf ~= self._showLv then
        CS.ShowObject(self._uiLvTxtTrans, self._showLv)
    end
end

function PetIconNew:ApplyLvTxt()
    if self._uiLvTxtTrans then
        local lvColor, lvMat = LUtil.GetResonanceColor()
        lvColor = LUtil.ColorByHex(lvColor)
        self:SetXUIText(self._uiLvTxtTrans, self._lvTxtStr or "", nil, lvColor)
        if lvMat then
            self:SetWndTextMat(self._uiLvTxtTrans, lvMat)
        end
    end
end


function PetIconNew:SetItemNum(num)
	self._num = num

	self:UpdateNumData()

	if not self:IsIconValid() then return end
	self:ApplyNumTxt()
end

function PetIconNew:SetItemlv(num)
	self._lvTxtStr = num

	if not self:IsIconValid() then return end
	self:ApplyLvTxt()()
end


function PetIconNew:SetShowGouImg(b)
	b = b or false and true
	self._showGou = b
end

function PetIconNew:ShowGouImg(b)
	if self._showGou == b then return end
	self._showGou = b

	if not self:IsIconValid() then return end

	self:SetGouTransVisible(self._showGou)
	-- self:SetEquipIconGray()
	self:ShowMask(self._showGou)
end

function PetIconNew:ShowMask(bVisible)
	 bVisible = bVisible and bVisible or false
	local gameObj = self._uiMaskTrans.gameObject
	if gameObj.activeSelf ~= bVisible then
		CS.ShowObject(gameObj, bVisible)
	end
end

function PetIconNew:SetGouTransVisible(bVisible)
	bVisible = bVisible and bVisible or false
	local gameObj = self._uiGouTrans.gameObject
	if gameObj.activeSelf ~= bVisible then
		CS.ShowObject(gameObj, bVisible)
	end
end

function PetIconNew:SetEquipIconGray()
	local b = self._showGou
	self:SetImageGray(self._uiIconBgTrans,b)
	self:SetImageGray(self._uiIconTrans,b)
end
function PetIconNew:SetEmptyIconByPart(part)
	local iconPath = self:GetEquipPartRef(part).emptyIcon
	if iconPath then
		self._displayShowIcon = iconPath
		self:SetIcon(self._displayShowIcon)
	end
end
-----------------------------------------------------------------
function PetIconNew:SetPetData(petInfo)
	self._refId = petInfo.refId
	self._star = petInfo.star
	local petCfg = petInfo.petCfg or self:GetPetRef(self._refId)
	local quality = petCfg.quality
	local qualityRef = self:GetItemQualityRef(quality)
	local itemColor ,iconBgPath= nil,nil
	if qualityRef then
		iconBgPath = qualityRef.iconBg
		local color = qualityRef.nameColor
		if color then
			itemColor = LUtil.ColorByHex(color)
		end
	end
	self._showLv = not not petInfo
	self._lvTxtStr = petInfo.level
	self._displayName = ccLngText(petCfg.name)
	self._displayColor = itemColor

	self._displayStar = self._star or 0
	self._displayShowIcon = petCfg.icon
	self._displayShowIconBg = iconBgPath
end

function PetIconNew:SetData(refId, star ,itemNum, part)
	self._refId = refId
	-- self._num = itemNum
	local petRef = self:GetPetRef(refId)
	local iconPath = nil
	local iconBgPath = nil
	local itemName = nil
	local itemColor = nil

	self._petRef = petRef
	if petRef then
		iconPath = petRef.icon

		itemName = ccLngText(petRef.name)

		local quality = petRef.quality
		local qualityRef = self:GetItemQualityRef(quality)
		if qualityRef then
			iconBgPath = qualityRef.iconBg
			local color = qualityRef.nameColor
			if color then
				itemColor = LUtil.ColorByHex(color)
			end
		end
		local petInfo = gModelPet:GetPetById(refId)
		self._showLv = not not petInfo
		if petInfo then 
			self._lvTxtStr = petInfo._level
			star = petInfo._star
		end
		
		-- star = petRef.star
		-- self._isEquip = true
	else
		-- self._isEquip = false
		self._showNum = false
		self._showLv = false
		self._lvTxtStr = ""
		--self._showGou = false

		iconPath = "pet_icon_off"
		iconBgPath = "public_item_bg_1"
		-- if part then
		-- 	local partRef = self:GetEquipPartRef(part)
		-- 	iconPath = partRef and partRef.emptyIcon or iconPath
		-- end
	end

	self._displayName = itemName
	self._displayColor = itemColor

	self._displayStar = star or 0
	self._displayShowIcon = iconPath
	self._displayShowIconBg = iconBgPath

	self:UpdateNumData()
end

function PetIconNew:GetNameData()
	return self._displayName,self._displayColor
end

-----------------------------------------------------------------
function PetIconNew:GetPetRef(refId)

	return GameTable.MagicPetRef[refId]
end

function PetIconNew:GetEquipPartRef(refId)

	return GameTable.MagicPetArticleTypeRef[refId]
end

-----------------------------------------------------------------
return PetIconNew