---
--- Generated by UIEditor
--- Created by Administrator.
--- DateTime: 2023/10/10 18:39:18
---

local LxBaseCtrl = require("LApp.controller.LxBaseCtrl")
---@class LxGuildAssemblyCtrl:LxBaseCtrl
local LxGuildAssemblyCtrl = classX("LxGuildAssemblyCtrl", LxBaseCtrl)

function LxGuildAssemblyCtrl:Initialize()
    LxBaseCtrl.Initialize(self)

end

function LxGuildAssemblyCtrl:Dispose()
    LxBaseCtrl.Dispose(self)
end

return LxGuildAssemblyCtrl