---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/2/6 17:54
---

local _HeroPosEnum = {
    --- 前排
    FrontRow = 1,
    --- 后排
    BackRow = 2,
}

local LxBaseCtrl = require("LApp.controller.LxBaseCtrl")
---@class LxLineupRecomCtrl:LxBaseCtrl
local LxLineupRecomCtrl = classX("LxLineupRecomCtrl", LxBaseCtrl)

function LxLineupRecomCtrl:Initialize()
    LxBaseCtrl.Initialize(self)

    self._initLineupRecomRefList = nil
end

function LxLineupRecomCtrl:Dispose()
    LxBaseCtrl.Dispose(self)
end

---@param heroList string[]
---@param heroPosEnum @ _HeroPosEnum 1:前排,2:后排
function LxLineupRecomCtrl:_SplitHeroList(heroList,heroPosEnum)
    if heroList and #heroList > 0 then
        local list = {}
        for i,v in ipairs(heroList) do
            v = string.split(v,"=")
            table.insert(list,{
                heroRefId = checknumber(v[1]),
                type = ThingType.Hero,
                isCore = checknumber(v[2]) == 1,
                heroPosEnum = heroPosEnum,
                level = 1,
                grade = 1,
                star = 1,
            })
        end
        return list
    end
    return {}
end

function LxLineupRecomCtrl:GetLineupRecomList()
    if not self._initLineupRecomRefList then
        local initLineupRecomRefList = {}

        local questRefId
        local ref = GameTable.LineupRecomRef
        for k,v in pairs(ref) do
            questRefId = v.questRefId
            table.insert(initLineupRecomRefList,{
                refId = v.refId,
                name = I18nText(v.name),
                description = I18nText(v.description),
                heroList1 = self:_SplitHeroList(v.heroList1,_HeroPosEnum.FrontRow),
                heroList2 = self:_SplitHeroList(v.heroList2,_HeroPosEnum.BackRow),
                questRefId = questRefId,
                record = v.record,
                sort = v.sort,
            })
        end
        table.sort(initLineupRecomRefList,function(a,b)
            return a.sort < b.sort
        end)
        self._initLineupRecomRefList = initLineupRecomRefList
    end
    return self._initLineupRecomRefList
end

--- 获取阵容推荐页签列表数据
function LxLineupRecomCtrl:GetLineupRecomShowList()
    local list = {}
    local refList = self:GetLineupRecomList()
    ---@type LxQuestObj
    local questObj
    ---@type V_QuestRef
    local questRef
    local showOneReward = true
    for i,v in ipairs(refList) do
        local heroList = {}
        for _i,_v in ipairs(v.heroList1) do
            table.insert(heroList,_v)
        end
        for _i,_v in ipairs(v.heroList2) do
            table.insert(heroList,_v)
        end
        local questObjs = {}
        for _i,_v in ipairs(v.questRefId) do
            questObj = ModuleCenter.Quest:GetQuest(_v)
            if questObj then
                table.insert(questObjs,questObj)
            else
                if LOG_ERROR_ENABLED then
                    printError("LxLineupRecomCtrl",">> 没有任务数据：" .. _v)
                end
                questRef = GameTable.MissionRef[_v]
                if questRef then
                    table.insert(questObjs,{
                        refId = _v,state = 0,progress = 0,goal = 0,
                    })
                end
            end
        end
        local rewardList = {}
        local showQuest = self:_GetQuest(questObjs)
        if showQuest then
            local questRefId = showQuest.refId
            questRef = GameTable.MissionRef[questRefId]
            local reward = questRef and questRef.reward or {}
            if #reward > 0 then
                local _rewardList = LxDataHelper.ParseItemList(reward)
                if showOneReward then
                    table.insert(rewardList,{
                        rewardItem = _rewardList[1],
                        questObj = showQuest,
                    })
                else
                    for _i,_v in ipairs(_rewardList) do
                        table.insert(rewardList,{
                            rewardItem = _v,
                            questObj = showQuest,
                        })
                    end
                end
            end
        end
        table.insert(list,{
            name = v.name,
            description = v.description,
            heroList = heroList,
            questRefId = v.questRefId,
            questObjs = questObjs,
            rewardList = rewardList,
            record = v.record,
            sort = v.sort,
        })
    end
    return list
end

---@param questList LxQuestObj[]
---@return LxQuestObj
function LxLineupRecomCtrl:_GetQuest(questList)
    if not questList or #questList < 1 then return nil end

    ---@type LxQuestObj[]
    local _questList = {}
    local finishNum = 0
    for i,v in ipairs(questList) do
        if v.state == 2 then
            finishNum = finishNum + 1
        end
        table.insert(_questList,v)
    end
    if finishNum >= #_questList then
        --- 显示已完成任务，sort值最大
        table.sort(_questList,function(a, b)
            return LxDataHelper.GetQuestSort(a.refId) > LxDataHelper.GetQuestSort(b.refId)
        end)
        return _questList[1]
    end

    --- 以下都是sort值小的任务
    table.sort(_questList,function(a, b)
        return LxDataHelper.GetQuestSort(a.refId) < LxDataHelper.GetQuestSort(b.refId)
    end)

    for i,v in ipairs(_questList) do
        if v.state == 1 then
            --- 返回可领取的任务
            return v
        end
    end

    --- 返回未完成的任务
    return _questList[1]
end


function LxLineupRecomCtrl:CheckLineupRecomRedPoint()
    if not CtrlCenter.FuncOpen:IsFuncOpen(FuncOpnIdConst.FormationRecommend, FuncOpenTipsEnum.Normal) then
        return false
    end
    ---@type LxQuestObj
    local questObj
    local refList = self:GetLineupRecomList()
    for i,v in ipairs(refList) do
        for _i,_v in ipairs(v.questRefId) do
            questObj = ModuleCenter.Quest:GetQuest(_v)
            if questObj and questObj.state == 1 then
                return true
            end
        end
    end
    return false
end

function LxLineupRecomCtrl:GetLineupRecomRed()
    return self:CheckLineupRecomRedPoint() and 1 or 0
end

return LxLineupRecomCtrl