---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2023/12/19 20:17
---

local LxBaseCtrl = require("LApp.controller.LxBaseCtrl")
---@class LxPopupGiftCtrl:LxBaseCtrl
local LxPopupGiftCtrl = classX("LxPopupGiftCtrl", LxBaseCtrl)

function LxPopupGiftCtrl:Initialize()
    LxBaseCtrl.Initialize(self)
end

function LxPopupGiftCtrl:Dispose()
    LxBaseCtrl.Dispose(self)
end

--获取某个礼包组中某个礼包的自选奖励是否已经全部选择了
function LxPopupGiftCtrl:GetGiftIsAllSelect(groupId, giftId, curSlotPos)
    local giftInfo = ModuleCenter.PopupGift:GetGiftInfo(groupId, giftId)
    local slotNum = ModuleCenter.PopupGift:GetGiftSelectSlotNum(giftId)

    local isAllSelect = true
    local nextSlotPos = nil
    local emptySlotPosList = {}
    for slotPos = 1, slotNum do
        local rewardIndex = giftInfo:GetChooseIndexByPos(slotPos)
        if rewardIndex == nil then
            table.insert(emptySlotPosList, slotPos)
        end
    end

    if #emptySlotPosList > 0 then
        isAllSelect = false

        if curSlotPos ~= nil then
            local curSelectIndex = nil
            for index, pos in ipairs(emptySlotPosList) do
                if curSlotPos == pos then
                    curSelectIndex = index
                    break
                end
            end

            if curSelectIndex ~= nil then
                local nextSelectIndex = curSelectIndex + 1
                if nextSelectIndex > #emptySlotPosList then
                    nextSelectIndex = 1
                end
                nextSlotPos = emptySlotPosList[nextSelectIndex]
            else
                nextSlotPos = emptySlotPosList[1]
            end
        end
    end

    return { isAllSelect = isAllSelect, nextSlotPos = nextSlotPos }
end

--判断当前礼包的前置礼包是否已经全部购买
function LxPopupGiftCtrl:GetGiftPreAllBuy(groupId, giftId)
    local info = ModuleCenter.PopupGift:GetGiftInventoryList(groupId)

    if info.length == nil or info.length <= 1 then
        return { preAllBuy = true }
    end

    local giftIndex = 1
    for i, id in ipairs(info.list) do
        if giftId == checknumber(id) then
            giftIndex = i
            break
        end
    end

    if giftIndex == 1 then
        return { preAllBuy = true }
    end

    local notBuyIdList = {}
    for i = 1, giftIndex - 1 do
        local giftIdArr = info.list[i]
        local giftIdList = string.split(giftIdArr, ";")
        for j, id in ipairs(giftIdList) do
            local curId = checknumber(id)
            local data = ModuleCenter.PopupGift:GetGiftInfo(groupId, curId)
            if data ~= nil then
                local remainNum = ModuleCenter.PopupGift:GetGiftRemainNum(curId)
                if remainNum > 0 then
                    table.insert(notBuyIdList, curId)
                end
            end
        end
    end

    local preAllBuy = #notBuyIdList == 0
    return { preAllBuy = preAllBuy, notBuyIdList = notBuyIdList }
end

--根据每个礼包的ID把它们的礼包名字拼接起来
function LxPopupGiftCtrl:GetGiftCannotBuyNameStr(giftIdList)
    local result = ""
    for i, giftId in ipairs(giftIdList) do
        local giftCfg = ModuleCenter.PopupGift:GetGiftCfg(giftId)
        result = result .. I18nText(giftCfg.name)
        if i ~= #giftIdList then
            result = result .. "、"
        end
    end

    return result
end

return LxPopupGiftCtrl