---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/8 14:31
---@class LFightMoveActor
local LFightMoveActor = classX("LFightMoveActor",nil)

---@param battleViewUnit LBattleViewUnit
function LFightMoveActor:ctor(battleViewUnit)
    ---@type LBattleViewUnit
    self._battleViewUnit = battleViewUnit


    self._endTime = 0
    self._isMoving = false

    ---@type Vector3
    self._targetPos = nil

    --- Function
    self._endCall = nil
end

function LFightMoveActor:OnUpdate(time)
    if not self._isMoving then return end
    if self._endTime < time then
        self._battleViewUnit:SetPosition(self._targetPos)
        self:StopMove()
    end
end


function LFightMoveActor:MoveTo(pos,time,endCall)
    self._targetPos = pos

    local objectCtrl2d = self._battleViewUnit:GetObjectCtrl2D()
    if not objectCtrl2d then return end

    objectCtrl2d:MoveTo(pos,time)
    objectCtrl2d.moveType = 0
    objectCtrl2d.isMoving = true

    self._isMoving = true
    self._isJumping = false
    self._endTime = self._battleViewUnit:GetTime() + time
    self._endCall = endCall
end

function LFightMoveActor:JumpTo(pos,topPos,time)
    self._targetPos = pos

    local objectCtrl2d = self._battleViewUnit:GetObjectCtrl2D()
    if not objectCtrl2d then return end

    topPos = topPos:Clone()
    topPos.z = 0

    objectCtrl2d:SetTopPos(topPos)
    objectCtrl2d:MoveTo(pos, time, 0)
    objectCtrl2d.moveType = 1
    objectCtrl2d.isMoving = true

    self._isMoving = true
    self._isJumping = true
    self._endTime = self._battleViewUnit:GetTime() + time
end


function LFightMoveActor:StopMove()
    if not self._isMoving then return end
    self._isMoving = false
    self._isJumping = false
    local objectCtrl2d = self._battleViewUnit:GetObjectCtrl2D()
    objectCtrl2d.isMoving = false

    local endCall = self._endCall
    self._endCall = nil
    if endCall then
        endCall()
    end
end

function LFightMoveActor:IsMoving()
    return self._isMoving
end

function LFightMoveActor:Dispose()
    self._battleViewUnit = nil
    table.dispose(self)
    self._isDisposed = true
end

return LFightMoveActor