---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/22 18:33
---
---@class LBattleShowPathItem 战斗 路径 显示
local LBattleShowPathItem = {
    pathZ = 0.5,
    pathX = 0,
    pathY = 0,
    pathRandom = 0
}
---@class LBattleShowBaseItem 战斗 基础 显示
local LBattleShowBaseItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
}
---@class LBattleShowEffectItem 战斗 特效 显示
local LBattleShowEffectItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    prefabName = '',
    unitIndex = 0,
    hookType = '',
    hookName = '',
    hookOffsetX = 0,
    hookOffsetY = 0,
    hookOffsetZ = 0,
    hookRotateX = 0,
    hookRotateY = 0,
    hookRotateZ = 0,
    startTime = 0,
    callTime = 0,
    lifeTime = 0,
    createType = '',
    spaceTime = 0,
    rotateType = 0,
    scale = 1,
    boneName = '',
    isFullEffect = 0,
}
---@class LBattleShowBulletItem 战斗 子弹 显示
local LBattleShowBulletItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 1,
    prefabName = '',
    fromHookName = '',
    spaceTime = 0,
    unitIndex = 0,
    fromHookOffsetX = 0,
    fromHookOffsetY = 0,
    fromHookOffsetZ = 0,
    toHookName = '',
    toHookOffsetX = 0,
    toHookOffsetY = 0,
    toHookOffsetZ = 0,
    scale = 1,
    bulletType = '',
    bulletSpeed = 0,
    startTime = 0,
    lifeTime = 0,
    createType = '',
    ---@type table<LBattleShowPathItem>
    pathList = {}
}
---@class LBattleShowShockItem 战斗 震屏 显示
local LBattleShowShockItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    startTime = 0,
    lifeTime = 0,
    spaceTime = 0,
    stayTime = 0,
    unitIndex = 0,
    shockCount = 0,
    shockStrength = 0
}
---@class LBattleShowHurtItem 战斗 伤害 显示
local LBattleShowHurtItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    textType = '',
    unitSpaceTime = 0,
    startTime = 0,
    hurtProp = 1,
    hurtCount = 1,
    hurtSpaceTime = 0,
    unitIndex = 0,
    hurtTitle = ''
}
---@class LBattleShowFaceEffectItem 战斗 表情 显示
local LBattleShowFaceEffectItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    startTime = 0,
    lifeTime = 0,
    opsType = '',
    opsValue = 0,
    opsStr = "",
    fadeInTime = 0,
    fadeOutTime = 0,
    hideUI = 0,
    hideHUD = 0
}

---@class LBattleShowAniEffectItem 战斗 动画 显示
local LBattleShowAniEffectItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    startTime = 0,
    lifeTime = 0,
    startAniName = '',
    endAniName = '',
    useEndAni = 0,

    modelName = '',
    showInfo = "",

    hookName = '',
    offsetX = 0,
    offsetY = 0,
    offsetZ = 0,

    rotateType = 0,
    rotateX = 0,
    rotateY = 0,
    rotateZ = 0,

    createType = '',
}

---@class LBattleShowMoveEffectItem 战斗 移动效果 显示
local LBattleShowMoveEffectItem = {
    name = '',
    castType = '',
    effectType = '',
    targetType = '',
    mainEffect = 0,
    startTime = 0,
    lifeTime = 0,
    aniName = '',
    offsetX = 0,
    offsetY = 0,
    offsetZ = 0,
    useMoveTime = 0,
    moveSpeed = 1,
    moveType = 1,
    ---@type table<LBattleShowPathItem>
    pathList = {},

}
---@class LBattleModelEffectItem  战斗 模型 显示
local LBattleModelEffectItem = {
    name = '',
    prefabName = '',
    hookName = BattleShowHookNodeEnum.None,
    hookOffsetX = 0,
    hookOffsetY = 0,
    hookOffsetZ = 0,
    hookRotateX = 0,
    hookRotateY = 0,
    hookRotateZ = 0,
    scale = 1
}
---@class LBattleShowSkillData
local LBattleShowSkillData = classX("LBattleShowSkillData", nil)

function LBattleShowSkillData:ctor()
    self.dataName = nil
    self.skillAsset = nil
    self.skillJson = nil
    
    self.castEffect = {}
    self.eventEffect = {}
    self.hitEffect = {}
    self.moveToEffect = {}
    self.moveBackEffect = {}

    self.isModelData = false
    self.modelEffect = {}
    self.modelHudOffsetX = 0
    self.modelHudOffsetY = BattleHudHeight
    self.modelHudOffsetZ = 0

    -- 从hitEffect中抽取出来
    self.textEffect = {}

    self.castPos = BattleShowCastPosType.Stand
    self.moveTime = 0.18
    self.eventTime = 0.5
    self.backTime = 0.1
    self.stopTime = 0.1
    self.aniName = "attack1"
    self.testTarget = BattleShowTestTargetType.Enemy2
    self.isHurtText = false

    self._isLoading = false
    self._isLoaded = false
    self._loadCallbacks = {}
    self._isInitOk = false
end
function LBattleShowSkillData:Dispose()
    if self.skillAsset ~= nil then
        self.skillAsset:Dispose()
        self.skillAsset = nil
    end
end
---@param dataName string 格式必须是类似 Taolexi_skill1
function LBattleShowSkillData:LoadSkillData(dataName, callback, bForce)
    local strList = string.split(dataName, '_')
    if #strList ~= 3 then
        if callback then
            callback(self)
        end
        if LOG_INFO_ENABLED then
            ShowSysMsg("技能显示Id格式错误: id="..dataName)
        end
        return
    end

    if self._isLoaded and not bForce then
        if callback then
            callback(self)
        end
        return
    end

    self.dataName = dataName
    table.insert(self._loadCallbacks, callback)
    self.isModelData = false
    if string.endswith(self.dataName, 'idle') then
        self.isModelData = true
    end

    if not self._isLoading then
        self._isLoading = true
        local fileNames = {}
        for i = 1,#strList - 1 do
            table.insert(fileNames, strList[i])
        end
        local fileNameStr = table.concat(fileNames, "_")
        local assetPath = 'Spine/' .. fileNameStr.."/"..dataName..".json"
        self.skillAsset = require("LApp.component.res.LJsonAsset"):new()
        self.skillAsset:InitAsset(assetPath)
        self.skillAsset:SetLoadedCallback(function(asset)
            self:OnSkillDataLoad(asset)
            if self.skillAsset ~= nil then
                self.skillAsset:Dispose()
                self.skillAsset = nil
            end
        end)
        self.skillAsset:Load()
    end

end

---只能在编辑器使用这个方法
function LBattleShowSkillData:SaveSkillData()
    local filePath = nil
    local dataName = self.dataName
    local saveSpinePath = CtrlCenter.Battle:GetSpineSkillSavePath(dataName)
    if not saveSpinePath then
        if LOG_INFO_ENABLED then
            LogError("dataName = "..dataName.." 不符合规范！命名格式( XR_模型名_动作名 )")
        end
        return
    end

    filePath = saveSpinePath..'/'..dataName..".json"
    self._isInitOk = true
    local skillData = {}

    if self.isModelData then
        skillData.aniName = self.aniName
        skillData.modelHudOffsetX = self.modelHudOffsetX
        skillData.modelHudOffsetY = self.modelHudOffsetY
        skillData.modelHudOffsetZ = self.modelHudOffsetZ
        table.sort(self.modelEffect, function(a, b) return a.name < b.name end)
        skillData.modelEffect = self.modelEffect
    else
        skillData.dataName = self.dataName
        skillData.castPos = self.castPos
        skillData.aniName = self.aniName
        skillData.eventTime = self.eventTime
        skillData.moveTime = self.moveTime or 0.18
        skillData.testTarget = self.testTarget
        skillData.backTime = self.backTime or 0.1
        skillData.stopTime = self.stopTime or 0.1

        table.sort(self.castEffect, function(a, b) return a.name < b.name end)
        table.sort(self.eventEffect, function(a, b) return a.name < b.name end)
        table.sort(self.hitEffect, function(a, b) return a.name < b.name end)
        table.sort(self.moveToEffect, function(a, b) return a.name < b.name end)
        table.sort(self.moveBackEffect, function(a, b) return a.name < b.name end)

        skillData.castEffect = self.castEffect
        skillData.eventEffect = self.eventEffect
        skillData.hitEffect = self.hitEffect
        skillData.moveToEffect = self.moveToEffect
        skillData.moveBackEffect = self.moveBackEffect
    end

    local jsonStr = CJSON.encode(skillData)
    local savePath = UnityEngine.Application.dataPath .."/Res/"..filePath
    LFileHelper.WriteAllText(savePath, jsonStr, false)
end

function LBattleShowSkillData:OnSkillDataLoad(asset)
    self._isLoading = false
    self._isLoaded = true
    local jsonStr = asset:GetAsset()
    if jsonStr then
        self.skillJson = CJSON.decode(tostring(jsonStr))
        if self.isModelData then
            self:InitModelData(self.skillJson)
        else
            self:InitSkillData(self.skillJson)
        end

    end

    if self._loadCallbacks and #self._loadCallbacks > 0 then
        local loadCallbacks = self._loadCallbacks
        self._loadCallbacks = {}
        for i, callback in ipairs(loadCallbacks) do
            callback(self)
        end
    end
end
function LBattleShowSkillData:IsInitOk()
    return self._isInitOk
end
function LBattleShowSkillData:InitModelData(skillJson)
    if not skillJson then
        return
    end
    self._isInitOk = true
    self.aniName = skillJson.aniName
    self.modelEffect = {}
    self.modelHudOffsetX = tonumber(skillJson.modelHudOffsetX) or 0
    self.modelHudOffsetY = tonumber(skillJson.modelHudOffsetY) or BattleHudHeight
    self.modelHudOffsetZ = tonumber(skillJson.modelHudOffsetZ) or 0
    if skillJson.modelEffect then
        for i, v in ipairs(skillJson.modelEffect) do
            table.insert(self.modelEffect, v)
        end
    end
end
function LBattleShowSkillData:InitSkillData(skillJson)
    if not skillJson then
        return
    end
    self._isInitOk = true
    if string.isempty(self.dataName) then
        self.dataName = skillJson.dataName
    end
    self.castPos = skillJson.castPos
    self.aniName = skillJson.aniName
    self.testTarget = skillJson.testTarget
    self.eventTime = tonumber(skillJson.eventTime) or 0.5
    self.moveTime = tonumber(skillJson.moveTime) or 0.18
    self.backTime = tonumber(skillJson.backTime) or 0.1
    self.stopTime = tonumber(skillJson.stopTime) or 0.1
    self.castEffect = {}
    self.eventEffect = {}
    self.hitEffect = {}
    self.moveToEffect = {}
    self.moveBackEffect = {}
    self.textEffect = {}

    if skillJson.castEffect then
        for i, v in ipairs(skillJson.castEffect) do
            table.insert(self.castEffect, v)
        end
    end

    if skillJson.eventEffect then
        for i, v in ipairs(skillJson.eventEffect) do
            table.insert(self.eventEffect, v)
        end
    end

    if skillJson.hitEffect then
        for i, v in ipairs(skillJson.hitEffect) do
            table.insert(self.hitEffect, v)
            if v.effectType == BattleShowEffectType.HurtText then
                self.isHurtText = true
                table.insert(self.textEffect, v)
            end
        end
    end

    if skillJson.moveToEffect then
        for i, v in ipairs(skillJson.moveToEffect) do
            table.insert(self.moveToEffect, v)
        end
    end

    if skillJson.moveBackEffect then
        for i, v in ipairs(skillJson.moveBackEffect) do
            table.insert(self.moveBackEffect, v)
        end
    end
end

function LBattleShowSkillData:GetAllEffectList()
    local effectList = {}
    if self.castEffect then
        table.sort(self.castEffect, function(a, b) return a.name < b.name end)
        for i, v in ipairs(self.castEffect) do
            table.insert(effectList, v)
        end
    end
    if self.eventEffect then
        table.sort(self.eventEffect, function(a, b) return a.name < b.name end)
        for i, v in ipairs(self.eventEffect) do
            table.insert(effectList, v)
        end
    end
    if self.hitEffect then
        table.sort(self.hitEffect, function(a, b) return a.name < b.name end)
        for i, v in ipairs(self.hitEffect) do
            table.insert(effectList, v)
        end
    end

    if self.moveToEffect then
        table.sort(self.moveToEffect, function(a, b) return a.name < b.name end)
        for i, v in ipairs(self.moveToEffect) do
            table.insert(effectList, v)
        end
    end

    if self.moveBackEffect then
        table.sort(self.moveBackEffect, function(a, b) return a.name < b.name end)
        for i, v in ipairs(self.moveBackEffect) do
            table.insert(effectList, v)
        end
    end

    return effectList
end

function LBattleShowSkillData:GetEffectList(castType)
    local effectList = nil
    if castType == BattleShowCastType.Cast then
        effectList = self.castEffect or {}
        self.castEffect = effectList
    elseif castType == BattleShowCastType.Event then
        effectList = self.eventEffect or {}
        self.eventEffect = effectList
    elseif castType == BattleShowCastType.Hit then
        effectList = self.hitEffect or {}
        self.hitEffect = effectList
    elseif castType == BattleShowCastType.MoveTo then
        effectList = self.moveToEffect or {}
        self.moveToEffect = effectList
    elseif castType == BattleShowCastType.GoBack then
        effectList = self.moveBackEffect or {}
        self.moveBackEffect = effectList
    end
    return effectList
end

function LBattleShowSkillData:RemoveModelEffectItem(effectItem)
    if not effectItem then
        return
    end
    local name = effectItem.name
    local modelEffect = self.modelEffect or {}
    local idx = 0
    for i, v in ipairs(modelEffect) do
        if v.name == name then
            idx = i
            break
        end
    end
    if idx > 0 then
        table.remove(modelEffect, idx)
    end
end
---@return LBattleModelEffectItem
function LBattleShowSkillData:NewModelEffectItem(key)
    local modelEffect = self.modelEffect or {}
    self.modelEffect = modelEffect
    local idx = #modelEffect + 1
    ---@type LBattleModelEffectItem
    local item = {
        name = "特效-"..tostring(idx),
        prefabName = '',
        hookName = BattleShowHookNodeEnum.None,
        hookOffsetX = 0,
        hookOffsetY = 0,
        hookOffsetZ = 0,
        hookRotateX = 0,
        hookRotateY = 0,
        hookRotateZ = 0,
        scale = 1
    }
    table.insert(modelEffect, item)
    return item
end
---@return LBattleShowPathItem
function LBattleShowSkillData:NewPathItem()
    local pathItem = {
        pathZ = 0.5,
        pathX = 0,
        pathY = 0,
        pathRandom = 0,
    }
    return pathItem
end

function LBattleShowSkillData:NewItemData(nameKey, castType, effectType)
    local effectList = self:GetEffectList(castType)
    local isHasMain = false
    for i, v in ipairs(effectList) do
        if v.mainEffect == 1 then
            isHasMain = true
            break
        end
    end
    local index = #effectList + 1
    local name = nameKey.."-"..string.sub(castType, 1,1)..index
    local effectItem = {name = name, castType = castType, effectType = effectType, targetType = BattleShowTargetType.Auto, mainEffect = 0}
    if effectType == BattleShowEffectType.Effect then
         self:InitEffectData(effectItem)
    elseif effectType == BattleShowEffectType.Bullet then
        if castType ~= BattleShowCastType.Event then
            ShowSysMsg('子弹特效建议在事件阶段添加')
        end
        if not isHasMain then
            effectItem.mainEffect = 1
        end
        self:InitBulletData(effectItem)
    elseif effectType == BattleShowEffectType.Shock then
        self:InitShockData(effectItem)
    elseif effectType == BattleShowEffectType.HurtText then
        if castType ~= BattleShowCastType.Hit then
            ShowSysMsg('飘血效果建议在打击阶段添加')
        end
        self.isHurtText = true
        self:InitHurtData(effectItem)
        table.insert(self.textEffect, effectItem)
    elseif effectType == BattleShowEffectType.Face then
        self:InitFaceEffectData(effectItem)
    elseif effectType == BattleShowEffectType.Ani then
        self:InitAniEffectData(effectItem)
    elseif effectType == BattleShowEffectType.Move then
        if castType == BattleShowCastType.MoveTo or castType == BattleShowCastType.GoBack then
            if not isHasMain then
                effectItem.mainEffect = 1
            end
        end
        self:InitMoveEffectData(effectItem)
    end
    table.insert(effectList, effectItem)
    return effectItem
end

function LBattleShowSkillData:RemoveItemData(effectItem)
    local castType = effectItem.castType
    local effectType  = effectItem.effectType
    local name = effectItem.name
    local effectList = self:GetEffectList(castType)
    local idx = 0
    for i, v in ipairs(effectList) do
        if v.name == name then
            idx = i
            break
        end
    end
    if idx > 0 then
        table.remove(effectList, idx)
    end

    if castType == BattleShowCastType.Event then

    elseif castType == BattleShowCastType.Hit then
        self.isHurtText = false
        self.textEffect = {}
        for i, v in ipairs(effectList) do
            if v.effectType == BattleShowEffectType.HurtText then
                self.isHurtText = true
                table.insert(self.textEffect, v)
            end
        end
    elseif castType == BattleShowCastType.Cast then

    end
end
---@param effectItem LBattleShowEffectItem
function LBattleShowSkillData:InitEffectData(effectItem)
    effectItem.prefabName = ''
    effectItem.hookType = BattleShowHookType.Pos
    effectItem.hookName = BattleShowHookNodeEnum.Stand
    effectItem.unitIndex = 0
    effectItem.hookOffsetX = 0
    effectItem.hookOffsetY = 0
    effectItem.hookOffsetZ = 0
    effectItem.hookRotateX = 0
    effectItem.hookRotateY = 0
    effectItem.hookRotateZ = 0
    effectItem.startTime = 0
    effectItem.callTime = 0
    effectItem.lifeTime = 5
    effectItem.createType = BattleShowCreateType.Single
    effectItem.spaceTime = 0
    effectItem.rotateType = BattleShowEffectRotateType.None
    effectItem.scale = 1
end

---@param effectItem LBattleShowBulletItem
function LBattleShowSkillData:InitBulletData(effectItem)
    effectItem.prefabName = ''
    effectItem.fromHookName = BattleShowHookNodeEnum.Stand
    effectItem.toHookName = BattleShowHookNodeEnum.Stand
    effectItem.fromHookOffsetX = 0
    effectItem.fromHookOffsetY = 0
    effectItem.fromHookOffsetZ = 0
    effectItem.toHookOffsetX = 0
    effectItem.toHookOffsetY = 0
    effectItem.toHookOffsetZ = 0
    effectItem.spaceTime = 0
    effectItem.unitIndex = 0
    effectItem.scale = 1
    effectItem.bulletType = BattleShowBulletType.Line
    effectItem.bulletSpeed = 30
    effectItem.startTime = 0
    effectItem.lifeTime = 5
    effectItem.createType = BattleShowCreateType.Single
end
---@param effectItem LBattleShowShockItem
function LBattleShowSkillData:InitShockData(effectItem)
    effectItem.startTime = 0
    effectItem.lifeTime = 0.3
    effectItem.shockCount = 3
    effectItem.stayTime = 0
    effectItem.shockStrength = 0.1
    effectItem.spaceTime = 0
    effectItem.unitIndex = 0
end
---@param effectItem LBattleShowHurtItem
function LBattleShowSkillData:InitHurtData(effectItem)
    effectItem.textType = BattleShowHurtTextType.Auto
    effectItem.unitSpaceTime = 0
    effectItem.startTime = 0
    effectItem.hurtProp = 1
    effectItem.hurtCount = 1
    effectItem.hurtSpaceTime = 0
    effectItem.unitIndex = 0
    effectItem.hurtTitle = ''
end
---@param effectItem LBattleShowFaceEffectItem
function LBattleShowSkillData:InitFaceEffectData(effectItem)
    effectItem.startTime = 0
    effectItem.lifeTime = 5
    effectItem.opsType = ''
    effectItem.opsValue = 0
    effectItem.opsStr = ""
    effectItem.fadeInTime = 0
    effectItem.fadeOutTime = 0
    effectItem.hideUI = 0
    effectItem.hideHUD = 0
end
---@param effectItem LBattleShowAniEffectItem
function LBattleShowSkillData:InitAniEffectData(effectItem)
    effectItem.startTime = 0
    effectItem.lifeTime = 2
    effectItem.startAniName = ''
    effectItem.endAniName = ''
    effectItem.useEndAni = 0
    effectItem.modelName = ''
    effectItem.showInfo = ''
    effectItem.hookName = ''
    effectItem.offsetX = 0
    effectItem.offsetY = 0
    effectItem.offsetZ = 0
    effectItem.createType = BattleShowCreateType.Single

    effectItem.rotateType = 0
    effectItem.rotateX = 0
    effectItem.rotateY = 0
    effectItem.rotateZ = 0
end
---@param effectItem LBattleShowMoveEffectItem
function LBattleShowSkillData:InitMoveEffectData(effectItem)
    effectItem.startTime = 0
    effectItem.lifeTime = 0
    effectItem.aniName = ''
    effectItem.moveSpeed = 30
    effectItem.useMoveTime = 0
    effectItem.offsetX = 0
    effectItem.offsetY = 0
    effectItem.offsetZ = 0
    effectItem.moveType = BattleShowBulletType.Line
end

return LBattleShowSkillData