---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2025/7/10 22:18
---

local LCityBase = require("LApp.gameplay.city.base.LCityBase")
---@class LCityBuilding:LCityBase
local LCityBuilding = classX("LCityBuilding", LCityBase)
local typeOfBoxCollider = typeof(UnityEngine.BoxCollider)
local typeOfRoleObject = typeof(ProjectX.CRoleObject)
local typeOfRenderer2d = typeof(ProjectX.CRenderer2D)
local _aniEnums = {
    build = "build",
    building = "building",
    idle1 = "idle1",
    idle2 = "idle2",
    idle3 = "idle3",
    ruins = "ruins"
}
function LCityBuilding:ctor(cityView)
    LCityBase.ctor(self)
    ---@type LCityView
    self._cityView = cityView

end

function LCityBuilding:Initialize()
    LCityBase.Initialize(self)

    self._buildingMove = false
    self._buildingRefId = 0

    ---@type GameObject
    self._buildingObj = nil -- 建筑对象
    ---@type Transform
    self._buildingTrans = nil

    self._showState = 0

    self._cbOk = nil
    self._cbObj = nil
    ---@type LxBuildingObj
    self._buildingData = nil;
    self.spriteRenderer = nil;
    self._bodyObj = nil
    self._defaultObj = nil
    ---@type LxSpineDp
    self._spineDp = nil
    ---@type LxEffectDp
    self._levelUpEffectDp = nil
    self._oldLevel = -1
    self._inited = false
    self._modelName = ""
    self._boxCollider = nil
    self._cityWallEffect = nil
    self._curPlayAniName = nil
    self._inView = false
    ---@type table<string,LxSpineDp>
    self._innerSpineList = {}
    ---@type table<number,Transform>
    self._peopleNodeList = {}
    ---@type LxTimer
    self._disPoseTimer = nil
    ---@type table<string,number>
    self._eatingNodeNames = {}
    ---@type table<number,LCityBuildingDropHud>
    self._dropHudList = {}
    ---{节点名字,{节点名字，排序ID}}
    ---@type table<table<string,number>>
    self._orderList = {}
end

function LCityBuilding:Dispose()
    self:ResetParam()
    LCityBase.Dispose(self)
end

function LCityBuilding:ResetParam()
    if(self._eatingNodeNames)then
        table.dispose(self._eatingNodeNames)
    end
    if(self._dropHudList)then
        for i, v in pairs(self._dropHudList) do
            v:Dispose()
        end
        table.dispose(self._dropHudList)
    end
    if self._peopleNodeList then
        table.dispose(self._peopleNodeList)
    end
    self._cityView = nil
    self._buildingRefId = 0
    self._buildingObj = nil -- 建筑对象
    self._buildingTrans = nil
    self._showState = 0
    self._cbOk = nil
    self._cbObj = nil
    self._buildingData = nil;
    self.spriteRenderer = nil;
    if (self._spineDp) then
        self._spineDp:Dispose()
        self._spineDp = nil
    end
    table.dispose(self._orderList)
    for i, v in pairs(self._innerSpineList) do
        v:Dispose()
        v = nil
    end
    table.dispose(self._innerSpineList)

    if(self._disPoseTimer)then
        MgrCenter.TimerMgr:RemoveTimer(self._disPoseTimer)
    end
    if (self._levelUpEffectDp) then
        self._levelUpEffectDp:Dispose()
        self._levelUpEffectDp = nil
    end
    if (self._cityWallEffect) then
        self._cityWallEffect:Dispose()
        self._cityWallEffect = nil
    end
end
function LCityBuilding:SetLoadCallback(cbOk, cbObj)
    self._cbOk = cbOk
    self._cbObj = cbObj
end

function LCityBuilding:InitBuilding(refId, buildingTrans)
    self._innerSpineList =  {}
    self._orderList = {}
    self._dropHudList = {}
    self._buildingRefId = refId

    self:SetBuildingObj(buildingTrans)

    self._buildingRef = GameTable.BuildingRef[refId]
    self._buildingData = ModuleCenter.Building:GetBuildingInfo(refId);
    self._nodeName = self._buildingRef.nodeName
    --self:UpdateShow();
    self:CheckShow();


end
function LCityBuilding:Play1001Born(callBack)
    if (self._buildingRefId == 1001) then
        if (self._spineDp) then
            self._spineDp:PlayAniEx("born", false, false, function()
                if (callBack ~= nil) then
                    callBack();
                end
            end)
        end
    end
end
function LCityBuilding:ShowCityWallEffect()
    if (self._buildingRefId ~= 1006) then
        return
    end
    local levelData = self:GetLevelData()
    if (levelData.level > 0) then
        --显示特效
        if (self._cityWallEffect) then
            local go = self._cityWallEffect:GetDpGo()
            ShowObject(go, false)
            ShowObject(go, true)
            return
        end
        self._cityWallEffect = require("LApp.component.dp.LxEffectDp"):new()
        self._cityWallEffect:InitDp("fx_ui_chengqiang_baohu", self._buildingTrans)
        self._cityWallEffect:SetScale(1)
        self._cityWallEffect:SetLocalPosition(Vector3.zero)
        self._cityWallEffect:SetLoadedCallback(function(ef)
            self:CityWallEffectLoaded(ef)
        end)
        self._cityWallEffect:Load()

    end
end
function LCityBuilding:CityWallEffectLoaded(ef)
    PJXUtil.SetLayerMask(ef._dpTrans, "Default")
end

function LCityBuilding:CheckShow()
    if ((self._buildingObj == nil) or (self._cityView == nil)) then
        self._boxCollider.enabled = false
        return
    end
    local show = self._cityView._buildingMgr:GetBuildingShow(self._buildingRefId)
    if (show) then
        --显示建筑，隐藏树
        self._boxCollider.enabled = true
        ShowObject(self._bodyObj, true)
        ShowObject(self._defaultObj, false)
    else
        --隐藏建筑，显示树
        self._boxCollider.enabled = false
        ShowObject(self._bodyObj, false)
        ShowObject(self._defaultObj, true)
    end
    self:UpdateShow()
end
function LCityBuilding:SetBuildingObj(buildingTrans)
    self._buildingTrans = buildingTrans
    self._boxCollider = buildingTrans.gameObject:GetComponent(typeOfBoxCollider)
    self._bodyObj = FindChild(buildingTrans, "Body").gameObject
    self._defaultObj = FindChild(buildingTrans, "Default").gameObject
    if buildingTrans ~= nil then
        self._buildingObj = buildingTrans.gameObject
        self.spriteRenderer = FindChild(self._buildingTrans, "Body"):GetComponent(typeof(UnityEngine.SpriteRenderer))
    end
end
function LCityBuilding:GetPosition()
    if (self._buildingTrans == nil) then
        return Vector3.zero
    end
    return self._buildingTrans.position
end
function LCityBuilding:ExecuteClick()

    if (self._buildingRefId == 1001) then
        local buildStory = GameTable.StorylineConfigRef.buildStory
        local arr = string.split(buildStory, ",")
        local buildLlv = ModuleCenter.Building:GetBuildingLvl(self._buildingRefId)
        for i, v in pairs(arr) do
            if (checknumber(v) == buildLlv) then
                --直接升级，不弹界面
                local queueEnough, queueNum = CtrlCenter.Building:CheckBuildQueueIsEnough()
                HandlerCenter.Building:BuildingUpgradeReq(self._buildingRefId, 0, false, queueNum)
                return
            end
        end
    end

    if (self._cityView._buildingMgr:GetBuildingShow(self._buildingRefId) == false) then
        return
    end
    if CtrlCenter.Building:CheckProductionTaskFinish(self._buildingRefId) then
        --建筑是否有生产任务完成
        local task = ModuleCenter.Building:GetProductionTask(self._buildingRefId)
        if task then
            if task.taskType == BuildingTaskType.Soldier then
                HandlerCenter.Building:BuildingProductionFinishReq(task.id)
                return
            end
        end
    end
    local boxTime = ModuleCenter.Building:GetBuildingBoxTime(self._buildingRefId)
    if boxTime > 0 and boxTime <= GetTimestamp() then
        --建筑宝箱是否可以领取
        HandlerCenter.Building:BuildingReceiveBoxReq(self._buildingRefId)
        return
    end
    local buildType = CtrlCenter.Building:GetBuildType(self._buildingRefId)
    local buildLlv = ModuleCenter.Building:GetBuildingLvl(self._buildingRefId)
    if buildLlv > 0 then
        if buildType == BuildingType.ShangHang then
            ShowPanel(UiNames.Shop, { buildId = self._buildingRefId, isResetCamera = true })
            return
        end

    end
    if (self._buildingMove) then
        return
    end

    local resetCamera = CtrlCenter.City:GetCityView():GetResetCameraState()
    if (resetCamera) then
        return
    end
    local buildLlv = ModuleCenter.Building:GetBuildingLvl(self._buildingRefId)
    local buildInfo = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
    local upGradeTime = CtrlCenter.Building:GetBuildUpGradeTime(self._buildingRefId)
    if buildLlv == 0 then
        if buildInfo and checknumber(buildInfo.endTime) > 0 then
            --0级升1级 点击不打开
            return
        end
    end
    self._buildingMove = true
    self._cityView:MoveToBuild(self._buildingRefId, function()
        self._buildingMove = false
        local buildType = CtrlCenter.Building:GetBuildType(self._buildingRefId)
        if buildLlv == 0 then
            --0级打开建造界面
            ShowPanel(UiNames.BuildCreate, { buildId = self._buildingRefId, isResetCamera = true })
            self:ShowPreBuildAni()
        else
            local upGradeTime = CtrlCenter.Building:GetBuildUpGradeTime(self._buildingRefId)
            if buildType == BuildingType.BingYingBu then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBarrackPanel = BarrackSoldierEnum.BuBing })
                else
                    ShowPanel(UiNames.BarrackTrain, { buildId = self._buildingRefId, soldierType = BarrackSoldierEnum.BuBing, isResetCamera = true })
                end

            elseif buildType == BuildingType.BingYingQi then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBarrackPanel = BarrackSoldierEnum.QiBing })
                else
                    ShowPanel(UiNames.BarrackTrain, { buildId = self._buildingRefId, soldierType = BarrackSoldierEnum.QiBing, isResetCamera = true })
                end
            elseif buildType == BuildingType.BingYingGong then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBarrackPanel = BarrackSoldierEnum.GongBing })
                else
                    ShowPanel(UiNames.BarrackTrain, { buildId = self._buildingRefId, soldierType = BarrackSoldierEnum.GongBing, isResetCamera = true })
                end
            elseif buildType == BuildingType.Arena then
                ShowPanel(UiNames.ArtsArena)
            elseif buildType == BuildingType.NoticeBoard then
                local notice = gLxServerList:GetPlatformNotices()
                if (table.nums(notice) > 0) then
                    ShowPanel(UiNames.SystemNotice)
                else
                    ShowSysMsg(I18nText(10305))
                end

            elseif buildType == BuildingType.ZhaoXianGe then
                if upGradeTime > 0 then

                else
                    local jumpType = HeroCall_RefIds.Common
                    local isShow = CtrlCenter.HeroCall:CheckCallHeroRedByRefId(HeroCall_RefIds.Water, FuncIds.RaceCall)
                    if isShow then
                        jumpType = HeroCall_RefIds.Race
                    else
                        isShow = CtrlCenter.HeroCall:CheckCallHeroRedByRefId(HeroCall_RefIds.Higher, FuncIds.HigherCall)
                        if isShow then
                            jumpType = HeroCall_RefIds.Higher
                        end
                    end
                    ShowPanel(UiNames.HeroSummons, { refId = jumpType })
                end
            elseif buildType == BuildingType.YingHunDian then
                if upGradeTime > 0 then

                else
                    ShowPanel(UiNames.HeroCorrelation)
                end
            elseif buildType == BuildingType.CangKu then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBuildPanelId = UiNames.BuildWareHouse})
                else
                    ShowPanel(UiNames.BuildWareHouse, { buildId = self._buildingRefId, isResetCamera = true})
                end
            elseif buildType == BuildingType.TaiXueYuan then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBuildPanelId = UiNames.Science})
                else
                    ShowPanel(UiNames.Science, { buildId = self._buildingRefId, isResetCamera = true })
                end
            elseif buildType == BuildingType.ChengQiang then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBuildPanelId = UiNames.BuildPort})
                else
                    ShowPanel(UiNames.BuildPort, { buildId = self._buildingRefId, isResetCamera = true })
                end
            elseif buildType == BuildingType.ShiGuan then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBuildPanelId = UiNames.Embassy})
                else
                    ShowPanel(UiNames.Embassy, { buildId = self._buildingRefId, isResetCamera = true })
                end
            elseif buildType == BuildingType.JunYiSuo then
                if upGradeTime > 0 then
                    ShowPanel(UiNames.BuildCreateTwo, { buildId = self._buildingRefId, isOpenBuildPanelId = UiNames.MilitaryInstit})
                else
                    ShowPanel(UiNames.MilitaryInstit, { buildId = self._buildingRefId, isResetCamera = true })
                end
            else
                CtrlCenter.Building:OpenBuildUpLevelPanel(self._buildingRefId, true)
            end
        end
    end);
end

function LCityBuilding:Show(bShow)
    self._showState = bShow
    self:UpdateShow()
end
function LCityBuilding:StoryBuildDie()

    self._modelName = nil
    if(self._spineDp ~= nil)then
        self._spineDp:Dispose()
    end
end
function LCityBuilding:StoryBuildBirth(callBack)
    local levelData = self:GetLevelData()
    if(self._modelName == levelData.levelShow)then
        if(callBack ~= nil)then
            callBack();
        end
        self:SetPeopleNodeList()
        self:LoadedCallBack(self._spineDp)

        return
    end
    ShowObject(self._bodyObj,true)
    ShowObject(self._defaultObj,false)
    self._boxCollider.enabled = true
    self:SetImage(self.spriteRenderer, "")

    if(self._spineDp ~= nil)then
        self._spineDp:Dispose()
    end
    self._spineDp = require("LApp.component.dp.LxSpineDp"):new()
    self._modelName = levelData.levelShow
    self._spineDp:InitDp(levelData.levelShow,self.spriteRenderer.transform)
    self._spineDp:SetLocalPosition(Vector3(0,0,0))
    self._spineDp:SetScale(1)
    local defaultLayer = 5
    local layerOrder = checknumber(self._buildingRef.layer)
    if(layerOrder >= 0)then
        defaultLayer = layerOrder
    end
    self._spineDp:SetRenderOrder(defaultLayer)
    self._spineDp:SetLoadedCallback(function(dp)
        self:SetPeopleNodeList()
        self:LoadedCallBack(dp)
        if(callBack ~= nil)then
            callBack();
        end
    end)
    self._spineDp:Load()
end
function LCityBuilding:GetLevelData()
    self._buildingData = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
    local buildLevel = 0;--默认未建造，0级
    if (self._buildingData ~= nil) then
        --已经建造
        buildLevel = self._buildingData.level;
    end
    local buildType = self._buildingRef.type;

    local refId = buildType * 1000 + buildLevel;
    local levelData = GameTable.BuildingLvRef[refId];
    return levelData
end

function LCityBuilding:PlayInView()

    if(self._buildingRef.showIn == 1)then
        if(self._inView)then
            return
        end
        local levelData = self:GetLevelData()
        if(levelData.level <= 0)then
            return
        end
        if(self._spineDp:ExistsAniName("inview"))then
            if(self._curPlayAniName == nil)then
                self._curPlayAniName = self._spineDp:GetCurAniName()
            end
            self:PlayAni("inview",true)
            self._inView = true

            local buildingObj = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
            if(buildingObj)then
                for i, v in ipairs(buildingObj.workers) do
                    if(v > 0)then
                        local people = CtrlCenter.City:GetPeopleObj(v)
                        if(people)then
                            people:BuildInView()
                        end
                    end

                end
                if(self._dropHudList)then
                    for i, v in pairs(self._dropHudList) do
                        v:PlayInView()
                    end
                end
            end
        end
        self:LoadInViewSpine()
        self:RefreshInView()
    end

end
function LCityBuilding:PlayOutView()
    --self:PlayAni(self._curPlayAniName,true)
    if(self._inView == false or self._inView == nil)then
        return
    end
    if(self._curPlayAniName ~= nil)then
        --self:PlayAni(_aniEnums.idle1,true)

        self._inView = false
        if(self._curPlayAniName == "idle2" or self._curPlayAniName == "idle1")then
            local timeState = CtrlCenter.City:GetCurTimeState()
            if(timeState == 1 or timeState == 3)then
                self._curPlayAniName = "idle1"
                self:BuildRest()
            else
                self._curPlayAniName = "idle2"
                self:BuildWork()
            end
        else
            if(self._curPlayAniName == "inview")then
                self:SetBuildingAni()
            end
            --self:PlayAni(self._curPlayAniName,true)
        end

        self._curPlayAniName = nil
        local buildingObj = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
        if(buildingObj)then
            for i, v in ipairs(buildingObj.workers) do
                if(v > 0)then
                    local people = CtrlCenter.City:GetPeopleObj(v)
                    if(people)then
                        people:BuildOutView()
                    end
                end
            end
            if(self._dropHudList)then
                for i, v in pairs(self._dropHudList) do
                    v:PlayOutView()
                end
            end
        end
    end
    self:RefreshInView()
end
function LCityBuilding:BuildWork()

    if(CtrlCenter.City:BuildIsInStory(self._buildingRefId))then
        return
    end

    if(self._dropHudList)then
        for i, v in pairs(self._dropHudList) do
            v:RefreshBuildingInfo()
        end
    end
    if(self._inView)then
        return
    end
    if(self._buildingRef.workSpine == 0)then
        self:SetBuildingAni()
        return
    end
    local buildObj = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
    if(buildObj == nil)then
        self:SetBuildingAni()
        return
    end
    if(CtrlCenter.Building:CheckBuildHasWorker(self._buildingRefId) == false)then
        self:SetBuildingAni()
        return
    end


    if(self._spineDp:GetCurAniName() == "idle2")then
        return
    end
    self:PlayAni("idle2",true)
end
function LCityBuilding:BuildRest()
    if(self._dropHudList)then
        for i, v in pairs(self._dropHudList) do
            v:RefreshBuildingInfo()
        end
    end
    self:SetBuildingAni()

end
function LCityBuilding:LoadInViewSpine()
    if(checknumber(self._buildingRef.showIn) <= 0)then
        return
    end

    --副建筑
    local unLockInnerList = CtrlCenter.Building:GetInnerDepBuildings(self._buildingRefId)
    for key, build in pairs(unLockInnerList) do
        local cfg = GameTable.BuildingInRef[build]
        local innerData = CtrlCenter.Building:GetInnerBuildLvl(self._buildingRefId,BuildInnerPosition.InnerDep)
        if(innerData == nil or innerData == false)then
            return
        end
        local sideList = cfg.inSide
        for i, v in pairs(sideList) do
            local nodeName = string.split(v,"=")
            if(innerData.level >= checknumber(nodeName[2]))then
                if(self._spineDp == nil or self._spineDp:GetDpTrans() == nil or self._spineDp:IsDisposed())then
                    return
                end
                local trans = self._spineDp:GetDpTrans():Find(nodeName[1])
                if(trans == nil)then
                    if(LOG_INFO_ENABLED)then
                        print(self._spineDp:GetDpTrans().name,nodeName[1])
                    end
                    break
                end
                if(trans.childCount <= 0 and self._innerSpineList[nodeName[1]] == nil)then
                    local spineDp = require("LApp.component.dp.LxSpineDp"):new()
                    spineDp:InitDp(cfg.inSideSp,trans)
                    spineDp:SetLocalPosition(Vector3.zero)
                    spineDp:SetScale(1)
                    local order = checknumber(self._buildingRef.layer)
                    spineDp:SetRenderOrder(order + 1)
                    spineDp:SetLoadedCallback(function(dp)
                        if(self._inView)then
                            ShowObject(spineDp:GetDpGo(),true)
                        else
                            ShowObject(spineDp:GetDpGo(),false)
                        end
                    end)
                    spineDp:Load()
                    local data = {}
                    data.name = nodeName[1]
                    data.order = checknumber(nodeName[3])
                    table.insert(self._orderList,data)
                    self._innerSpineList[nodeName[1]] = spineDp
                    --table.insert(self._innerSpineList,spineDp)
                end
            end
        end
    end

    --主建筑
    local mainInnerCfg = CtrlCenter.Building:GetInnerMainBuilding(self._buildingRef.type)
    local mainInnerData = CtrlCenter.Building:GetInnerBuildLvl(self._buildingRefId,BuildInnerPosition.InnerMain)
    if(mainInnerData == false or mainInnerData == nil)then
        return
    end
    for i, v in pairs(mainInnerCfg.inSide) do
        local nodeInfo = string.split(v,"=")
        if(mainInnerData.level >= checknumber(nodeInfo[2]))then
            if(self._spineDp == nil or self._spineDp:GetDpTrans() == nil or self._spineDp:IsDisposed())then
                return
            end
            local trans = self._spineDp:GetDpTrans():Find(nodeInfo[1])
            if(trans == nil)then
                if(LOG_INFO_ENABLED)then
                    print(self._spineDp:GetDpTrans().name,nodeInfo[1])
                end
                break
            end
            if(trans.childCount <= 0 and self._innerSpineList[nodeInfo[1]] == nil)then
                local spineDp = require("LApp.component.dp.LxSpineDp"):new()
                spineDp:InitDp(mainInnerCfg.inSideSp,trans)
                spineDp:SetLocalPosition(Vector3.zero)
                spineDp:SetScale(1)
                local order = checknumber(self._buildingRef.layer)
                spineDp:SetRenderOrder(order + 1)
                spineDp:SetLoadedCallback(function(dp)
                    if(self._inView)then
                        ShowObject(spineDp:GetDpGo(),true)
                    else
                        ShowObject(spineDp:GetDpGo(),false)
                    end
                    if(self._buildingRef.workSpine > 0)then
                        local dropHud = require("LApp.gameplay.city.view.LCityBuildingDropHud"):new()
                        dropHud:InitHud(self._cityView._buildingMgr._dropHudObj,spineDp:GetDpTrans(),self._buildingRefId,i)
                        table.insert(self._dropHudList,dropHud)
                    end
                end)
                spineDp:Load()
                local data = {}
                data.name = nodeInfo[1]
                data.order = checknumber(nodeInfo[3])
                table.insert(self._orderList,data)
                self._innerSpineList[nodeInfo[1]] = spineDp
                --table.insert(self._innerSpineList,spineDp)
            end
        end
    end

    --小人用居民AI，但是挂点在建筑内
    table.sort(self._orderList, function(a,b)
        return a.order < b.order
    end)
end

function LCityBuilding:RefreshInView()
    if LOG_INFO_ENABLED then
        printError(self._orderList)
    end
    if(self._inView)then
        for i, v in pairs(self._innerSpineList) do
            v:SetRenderOrder(self:GetOrderByName(i))
            ShowObject(v:GetDpGo(),true)
        end
    else
        for i, v in pairs(self._innerSpineList) do
            ShowObject(v:GetDpGo(),false)
        end
    end
end
function LCityBuilding:GetOrderByName(nodeName)
    for i, v in pairs(self._orderList) do
        if(v.name == nodeName)then
            return self._buildingRef.layer + i * 20
        end
    end
end
function LCityBuilding:PlayAni(aniName, loop)

    if (self._spineDp) then
        self._spineDp:PlayAni(aniName, loop)
    end
end

function LCityBuilding:UpdateShow()
    local levelData = self:GetLevelData()
    if (checknumber(self._oldLevel) < checknumber(levelData.level)) then
        if (self._inited) then
            self:ShowLevelUpEffect()
        end
        self._oldLevel = levelData.level
    end
    self._inited = true
    self:SetImage(self.spriteRenderer, "")
    if (self._modelName == levelData.levelShow) then
        --self:SetBuildingAni()
        self:CheckWorkRestState()
        return
    end
    if (self._spineDp ~= nil) then
        self._spineDp:Dispose()
    end
    self._spineDp = require("LApp.component.dp.LxSpineDp"):new()
    self._modelName = levelData.levelShow
    self._spineDp:InitDp(levelData.levelShow, self.spriteRenderer.transform)
    local arr = string.split(levelData.Pos, "|")
    --local pos = Vector3(checknumber(arr[1]),checknumber(arr[2]),0)
    self._spineDp:SetLocalPosition(Vector3(0, 0, 0))
    self._spineDp:SetScale(1)
    local defaultLayer = 5
    local layerOrder = checknumber(self._buildingRef.layer)
    if (layerOrder >= 0) then
        defaultLayer = layerOrder
    end
    self._spineDp:SetRenderOrder(defaultLayer)
    self._spineDp:SetLoadedCallback(function(model)
        self:LoadedCallBack(model)
        --self:SetBuildingAni()
        self:CheckWorkRestState()
        self:SetPeopleNodeList()
        self:LoadInViewSpine()
        self:RefreshInView()
        self:OperateForEating()
    end)
    self._spineDp:Load()


end
--针对餐厅的特殊处理
function LCityBuilding:OperateForEating()

    if(self._buildingRefId == 2005)then
        self._eatingNodeNames = self._eatingNodeNames or {}
        table.dispose(self._eatingNodeNames)
        local trans = self._spineDp:GetDpTrans()
        local childCount = trans.childCount
        for i = 1, childCount do
            local childTrans = trans:GetChild(i - 1)
            if(string.startswith(childTrans.name,"CiR29"))then
                self._eatingNodeNames[childTrans] = 0
                --table.insert(self._eatingNodeNames,childTrans.name)
            end
        end
    end
end
function LCityBuilding:SetEatPeople(nodeName,peopleRefId)
    self._eatingNodeNames[nodeName] = peopleRefId
end
function LCityBuilding:CheckWorkRestState()
    local timeState = CtrlCenter.City:GetCurTimeState()
    if(timeState == 1 or timeState == 3)then
        self:BuildRest()
    else
        self:BuildWork()
    end
    self:LoadInViewSpine()
    self:RefreshInView()
end
function LCityBuilding:SetPeopleNodeList()
    if(checknumber(self._buildingRef.showIn) <= 0)then
        return
    end
    self._peopleNodeList = self._peopleNodeList or {}
    table.dispose(self._peopleNodeList)
    local mainInnerCfg = CtrlCenter.Building:GetInnerMainBuilding(self._buildingRef.type)
    if(mainInnerCfg)then
        for i, v in pairs(mainInnerCfg.peopleSide) do
            local trans = self._spineDp:GetDpTrans():Find(v)
            if(trans)then
                table.insert(self._peopleNodeList,trans)
            end
        end
    end

end
function LCityBuilding:LoadedCallBack(model)
    if (self._cbOk) then
        self._cbOk(self._cbObj, self._buildingRefId)
    end
end
function LCityBuilding:SetBuildingAni()
    if (self._spineDp == nil) then
        return
    end
    if(self._inView)then
        return
    end
    local buildData = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
    if (buildData ~= nil) then
        if (checknumber(buildData.endTime) ~= 0) then
            self:PlayAni(_aniEnums.building, true)
            return
        end
    end

    local levelData = self:GetLevelData()
    local play = true
    if(ModuleCenter.Story:IsNewbieRunning())then
        if(CtrlCenter.City:BuildIsInStory(self._buildingRefId))then
            play = false
        end
    end
    if(play)then
        if (levelData.level == 0) then
            self:PlayAni(_aniEnums.ruins, true)
        else
            ---2025.11.10 黄江让去掉特殊处理
            --针对剧情中的渔场做个特殊处理
            --if (ModuleCenter.Story:IsNewbieRunning() and self._buildingRefId == 2004) then
            ----龙蛋，0-1不处理
            --elseif (ModuleCenter.Story:IsNewbieRunning() and self._buildingRefId == 1001 and checknumber(self._oldLevel) == 0) then
            --
            --else
            --    self:PlayAni(_aniEnums.idle1, true)
            --end
            self:PlayAni(_aniEnums.idle1, true)
        end
    end



end
function LCityBuilding:ResetBuildingState(aniName)
    if (self._spineDp == nil) then
        return
    end
    self:PlayAni(aniName, true)
end
function LCityBuilding:ResetBuildingAni()
    if (self._spineDp == nil) then
        return
    end
    local buildData = ModuleCenter.Building:GetBuildingInfo(self._buildingRefId)
    if (buildData ~= nil) then
        if (checknumber(buildData.endTime) ~= 0) then
            self:PlayAni(_aniEnums.building, true)
            return
        end
    end

    local levelData = self:GetLevelData()
    if (levelData.level == 0) then
        self:PlayAni(_aniEnums.ruins, true)
        local buildHud = self._cityView._buildingMgr:GetHUD(self._buildingRefId)
        if buildHud then
            buildHud:SetBuildCreateTipsState(true)
        end
    end
end
function LCityBuilding:ShowPreBuildAni()
    if (self._spineDp == nil) then
        return
    end
    self:PlayAni(_aniEnums.build, true)
    local buildHud = self._cityView._buildingMgr:GetHUD(self._buildingRefId)
    if buildHud then
        buildHud:SetBuildCreateTipsState(false)
    end
end
function LCityBuilding:ShowLevelUpEffect()
    local levelData = self:GetLevelData()
    local t1, t2 = CtrlCenter.Story:CheckTrigger(NewbieTriggerType.BuildUpLevelUp, levelData.refId)
    if (t1 > 0 and t2 > 0) then
        CtrlCenter.Story:StartStory(t2);
        return
    end
    if(self._disPoseTimer)then
        MgrCenter.TimerMgr:RemoveTimer(self._disPoseTimer)
    end
    if (self._levelUpEffectDp ~= nil) then
        self._levelUpEffectDp:Dispose()
        self._levelUpEffectDp = nil
    end
    self._levelUpEffectDp = require("LApp.component.dp.LxEffectDp"):new()
    if (self._buildingRefId == 1001 and levelData.level == 1) then
        self._levelUpEffectDp:InitDp("fx_ui_juqing_longdanfuhua", self._buildingTrans)
        local scale = GameTable.BuildingConfigRef.longTaEffectSize
        local pos = Vector3(checknumber(GameTable.BuildingConfigRef.longTaEffectPosition[1]), checknumber(GameTable.BuildingConfigRef.longTaEffectPosition[2]), 0)
        self._levelUpEffectDp:SetScale(scale)
        self._levelUpEffectDp:SetLocalPosition(pos)
        self._levelUpEffectDp:Load()
        --local pos = Vector3()
    else
        self._levelUpEffectDp:InitDp("fx_ui_juqing_jianzhujiancheng", self._buildingTrans)
        --local levelData = self:GetLevelData()
        local scale = 1
        if (levelData.effectSize > 0) then
            scale = levelData.effectSize
        end
        self._levelUpEffectDp:SetScale(scale)
        self._levelUpEffectDp:SetLocalPosition(Vector3.zero)
        self._levelUpEffectDp:Load()
    end
    self._disPoseTimer = MgrCenter.TimerMgr:DelayTime(function()
        self._levelUpEffectDp:Dispose()
        self._levelUpEffectDp = nil
    end,self,3,false)

end
function LCityBuilding:Load()

end

function LCityBuilding:IsBuildingByGameObject(go)
    if go == self._buildingObj then
        return true
    end
end

function LCityBuilding:ResetEatNode(nodeName)
    self._eatingNodeNames[nodeName] = 0
end
function LCityBuilding:OnUpdate(deltaTime)
    if self._isDisposed then return end
    if(self._dropHudList)then
        for i, v in pairs(self._dropHudList) do
            v:OnUpdate(deltaTime)
        end
    end

end
return LCityBuilding