---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin-pc.
--- DateTime: 2023/11/29 14:35
---

local LCityBase = require("LApp.gameplay.city.base.LCityBase")
---@class LCityEventAreaMgr:LCityBase
local LCityEventAreaMgr = classX("LCityEventAreaMgr", LCityBase)
function LCityEventAreaMgr:ctor(cityView)
    LCityBase.ctor(self)

    ---@type LCityView
    self._cityView = cityView

    ---@type table<string, LCityEventArea> @id,obj
    self._eventAreaMap = {}
end

function LCityEventAreaMgr:Dispose()
    for k,v in pairs(self._eventAreaMap) do
        v:Dispose()
    end
    LCityBase.Dispose(self)
end

function LCityEventAreaMgr:Initialize()
    LCityBase.Initialize(self)
end

function LCityEventAreaMgr:InitEventAreas(datas)
    for k,v in ipairs(datas) do
        local eventData = require("LApp.gameplay.city.data.LCityEventAreaData"):new()
        eventData.id = v.id
        eventData.refId = v.id
        eventData.pos.x = v.x
        eventData.pos.y = v.y
        eventData.pos.z = v.z
        eventData.center.x = v.cx
        eventData.center.y = v.cy
        eventData.center.z = v.cz
        eventData.size.x = v.sx
        eventData.size.y = v.sy
        eventData.size.z = v.sz
        self:AddEventArea(eventData)
    end
end

---@param node GameObject
function LCityEventAreaMgr:SetRootNode(node)
    self._rootNode = node
    self._rootNodeTrans = node.transform
end

function LCityEventAreaMgr:GetEventArea(id)
    return self._eventAreaMap[id]
end

function LCityEventAreaMgr:AddEventArea(eventData)
    local id = eventData.id
    local eventArea = self._eventAreaMap[id]
    if eventArea then
        eventArea:Dispose()
        eventArea = nil
    end
    eventArea = require("LApp.gameplay.city.view.LCityEventArea"):new(self._cityView)
    self._eventAreaMap[id] = eventArea
    eventArea:InitView(eventData, self._rootNodeTrans)
    eventArea:LoadEventArea()
end


function LCityEventAreaMgr:MakeEventId()
    local id = self._id + 1
    if id > 2147483647 then
        id = 1
    end
    self._id = id
    return id
end

function LCityEventAreaMgr:OnUpdate(deltaTime)
    if self._isDisposed then return end

    for k,v in pairs(self._eventAreaMap) do
        v:OnUpdate(deltaTime)
    end
end

function LCityEventAreaMgr:ShowEventArea(eventId,bShow)
    local idData = self._eventAreaMap[eventId]
    if idData then
        idData:Show(bShow)
    end
end


return LCityEventAreaMgr