---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-27 10:37
---
------------------------------------------------------------------
---模块使用示例 需要在LModelManager的列表里填写名字
---创建完之后可以使用gModelWonderland全局变量访问实例
------------------------------------------------------------------
LXImport("..Struct.StructWonderlandGrid")
local LModel = LModel
------------------------------------------------------------------
---@class ModelWonderland:LModel
local ModelWonderland = LxClass("ModelWonderland",LModel)


ModelWonderland.DreamlandThemeRef = "DreamlandThemeRef"
ModelWonderland.DreamlandEventRef = "DreamlandEventRef"
ModelWonderland.DreamlandConfigRef = "DreamlandConfigRef"
ModelWonderland.WonderTaskRef = "WonderTaskRef"

ModelWonderland.LAYER = 20

ModelWonderland.EVENT_REFRESH_MONSTER =-2
ModelWonderland.EVENT_GIVE_UP =-1
ModelWonderland.EVENT_SELECT_GRID =0
ModelWonderland.EVENT_BOSS = 1
ModelWonderland.EVENT_SPRING = 2
ModelWonderland.EVENT_REVIVAL = 3
ModelWonderland.EVENT_HIRE = 4
ModelWonderland.EVENT_TREASURE = 5
ModelWonderland.EVENT_SHOP = 6
ModelWonderland.EVENT_BOX = 7

ModelWonderland.EVENT_GOLD_HAIR = 101
ModelWonderland.EVENT_PROTECTOR = 102
ModelWonderland.EVENT_GRANDMA =103
ModelWonderland.EVENT_DEVIL = 104

ModelWonderland.EVENT_SNOW = 201
ModelWonderland.EVENT_MIRROR = 202
ModelWonderland.EVENT_FROZEN = 203
ModelWonderland.EVENT_QUEEN = 204

ModelWonderland.EVENT_ORGAN = 301
ModelWonderland.EVENT_POISON = 302
ModelWonderland.EVENT_ARROW_TOWER = 303
ModelWonderland.EVENT_CLIP = 304
ModelWonderland.EVENT_BOX_BOSS = 398
ModelWonderland.EVENT_BOX_SELECT = 399

ModelWonderland.EVENT_BEAN_VINE = 401
ModelWonderland.EVENT_POD = 402
ModelWonderland.EVENT_WORLD_TREE = 403
ModelWonderland.EVENT_WORLD_LEAVES = 404
ModelWonderland.EVENT_SPRITE = 499

ModelWonderland.EVENT_OCTOPUS = 501
ModelWonderland.EVENT_SINGING = 502
ModelWonderland.EVENT_FOAM = 503
ModelWonderland.EVENT_BEAST = 504
ModelWonderland.EVENT_BEAST_ADD = 598
ModelWonderland.EVENT_WITCH = 599

ModelWonderland.EVENT_EMPTY= 305

ModelWonderland.EVENT_LORD= 50
ModelWonderland.EVENT_THIEF= 51
ModelWonderland.EVENT_TIME= 52
ModelWonderland.EVENT_TIME_LORD= 53
ModelWonderland.EVENT_TREA_HARD= 54

ModelWonderland.EVENT_ABYSS_LORD= 61
ModelWonderland.EVENT_TREA_TOUGH= 62


ModelWonderland.SELF_HERO = 1
ModelWonderland.HIRE_HERO = 2
ModelWonderland.ENEMY_MONSTER = 3
ModelWonderland.ENEMY_HERO = 4

ModelWonderland.NORMAL = 1
ModelWonderland.HARD = 2
ModelWonderland.TOUGH = 3



------------------------------------------------------------------
function ModelWonderland:ModelWonderland()

end

--模块初始化入口
--注册事件监听
--注册协议监听
--预处理数据
function ModelWonderland:OnModelInit()
    self:ParseConfig()

    self._gridUpStates=
    {
        [StructWonderlandGrid.PLAYER] = true,
        [StructWonderlandGrid.SELECTED] = true,
        [StructWonderlandGrid.ALLOW] = true,
    }

    self._waitRefreshEvent =
    {
        [ModelWonderland.EVENT_BEAN_VINE] = true,
        [ModelWonderland.EVENT_POD] = true

    }


    self:ModelNetMsgRecv(LProtoIds.WonderlandHeroHireResp,function(...) self:OnWonderlandHeroHireResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandHeroMonsterResp,function(...) self:OnWonderlandHeroMonsterResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandHeroOpsResp,function(...) self:OnWonderlandHeroOpsResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandScenePageResp,function(...) self:OnWonderlandScenePageResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandRefreshResp,function(...) self:OnWonderlandRefreshResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandOpsResp,function(...) self:OnWonderlandOpsResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandQuestResp,function(...) self:OnWonderlandQuestResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandItemInfoResp,function(...) self:OnWonderlandItemInfoResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandTreasureResp,function(...) self:OnWonderlandTreasureResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.WonderlandDestinationResp,function(...) self:OnWonderlandDestinationResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.PowerShowResp,function(...) self:OnPowerShowResp(...) end)
    self:ModelEventRecv("WonderlandRaceResp",function (...) self:OnWonderlandRaceResp(...) end)
end

--在协议数据处理完之后需要调用finish
function ModelWonderland:OnModelRequest()
    self:InitData()

    self:ModelFinish()
end

function ModelWonderland:InitData()
    self._heroList ={}
    self._treasureList = {}

    self._popWndList ={}
    self._waitWndList ={}


end

function ModelWonderland:InitFormation()
    if self._hasFormation then
        return
    end
    self._hasFormation = true
    gModelFormation:OnGetFormationReq(LCombatTypeConst.COMBAT_WONDERLAND)
end

----------------------------------------------------------------------
---req

function ModelWonderland:WonderlandScenePageReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandScenePageReq)
    SendMessage(pb,LProtoIds.WonderlandScenePageReq)
end

function ModelWonderland:WonderlandRefreshReq(themeRefId,pattern)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandRefreshReq)
    pb.themeRefId = themeRefId
    pb.pattern = pattern
    SendMessage(pb,LProtoIds.WonderlandRefreshReq)
end

function ModelWonderland:WonderlandOpsReq(type,moreinfo,callback)

    local isSelectReq = type == ModelWonderland.EVENT_SELECT_GRID
    if isSelectReq and self:IsProtect() then
        return
    end
    local data =
    {
        layerIndex = self:GetCurLayer() + 1,
        gridIndex = tonumber(moreinfo),
    }
    if isSelectReq then
        self._selectGrid = data
        self._selectCallBack = callback
    end


    self:AddReqProtect()

    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandOpsReq)
    pb.type = type
    if moreinfo then
        pb.moreinfo = moreinfo
    end

    SendMessage(pb,LProtoIds.WonderlandOpsReq)

end

function ModelWonderland:WonderlandQuestReq(type)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandQuestReq)
    pb.type = type
    SendMessage(pb,LProtoIds.WonderlandQuestReq)
end

function ModelWonderland:WonderlandHeroHireReq(type,moreInfo)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandHeroHireReq)
    pb.type = type
    pb.moreinfo = moreInfo
    SendMessage(pb,LProtoIds.WonderlandHeroHireReq)
end

function ModelWonderland:WonderlandHeroMonsterReq(type,layerIndex,gridIndex,lordId)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandHeroMonsterReq)
    pb.type = type
    pb.tierIndex = layerIndex
    pb.gridIndex = gridIndex
    if lordId then
        pb.eventRefId = lordId
    end
    SendMessage(pb,LProtoIds.WonderlandHeroMonsterReq)
end

function ModelWonderland:WonderlandHeroOpsReq(type)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandHeroOpsReq)
    pb.type = type
    SendMessage(pb,LProtoIds.WonderlandHeroOpsReq)
end

function ModelWonderland:WonderlandEffectReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandEffectReq)
    SendMessage(pb,LProtoIds.WonderlandEffectReq)
end

function ModelWonderland:WonderlandDestinationReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandDestinationReq)
    SendMessage(pb,LProtoIds.WonderlandDestinationReq)
end

function ModelWonderland:OnWonderlandRaceReq(type)
    local pb = LProtoHelper.CreateProto(LProtoIds.WonderlandRaceReq)
    pb.type = type
    SendMessage(pb,LProtoIds.WonderlandRaceReq)
end

--------------------------------------------------------------------------
---resp

function ModelWonderland:OnWonderlandScenePageResp(pb)
    if not self._layerInfos then
        self._layerInfos = {}

    end
    local type = pb.type
    if type == 0 then
        self._layerInfos = {}
        self._affectDataList ={}
    end

    self._gridInfos = {}
    self._layerList= {}

    self._themeId = pb.info.id
    self._countdown = pb.info.countDown
    local mapInfo = pb.info.mapInfo

    local oldState = self._isInMap
    self._isInMap = pb.info.haveMap == 1

    self._themeIdArr = pb.info.themeIdArr

    self._pattern = pb.info.pattern
    self._viaPatternType = pb.info.viaPatternType
    self._maxThemeType = pb.info.maxThemeType


    local selGridChange = false

    if self._isInMap then
        self._freeRebornCnt = mapInfo.freeCount

        self._affectDataList ={} --清除影响的格子，重新计算

        self._layerIndex = mapInfo.tierIndex
        self._gridIndex = mapInfo.gridIndex
        local oldBout = self._bout
        self._bout = mapInfo.bout

        self._themeBuff = mapInfo.themeBuff
        self._maxLayerIndex = mapInfo.maxTierIndex

        self:SetThemeMoreInfo(mapInfo.themeMoreinfo)

        self._passAwardState = mapInfo.passAwardState

        for k,v in ipairs(mapInfo.tierInfo) do

            local layerIndex = v.tierIndex
            local layer =
            {
                layerIndex = layerIndex,
            }
            local list = {}
            for k1,v1 in ipairs(v.gridInfo) do
                local grid = StructWonderlandGrid:New()
                grid:CreateByPb(v1)
                grid:SetLayerIndex(layerIndex)
                table.insert(list,grid)
            end
            table.sort(list,function(a,b) return a:GetGridIndex()< b:GetGridIndex() end)
            layer.grids = list

            self._layerInfos[layerIndex] = layer
        end


        local list = {}
        local defaultGrid = StructWonderlandGrid:New()
        defaultGrid:SetLayerIndex(0)
        defaultGrid:SetStatus(StructWonderlandGrid.PASSED)
        local defaultLayer =
        {
            layerIndex = 0,
            grids = {defaultGrid},
        }


        local gridKey = self:FormatGridKey(0,0)
        self._gridInfos[gridKey] = defaultGrid

        local oldSelGrid = self._selGrid
        self._selGrid = nil

        table.insert(list,defaultLayer)
        for k,v in pairs(self._layerInfos) do
            table.insert(list,v)
            for k1,v1 in pairs(v.grids) do
                local layerIndex = v.layerIndex
                local gridIndex = v1.gridIndex
                gridKey = self:FormatGridKey(layerIndex,gridIndex)
                self._gridInfos[gridKey] = v1

                local state = v1:GetStatus()
                if state == StructWonderlandGrid.SELECTED then
                    self._selGrid = v1
                end

                for k2,v2 in ipairs(v1.eventList) do
                    for k3,v3 in ipairs(v2.scopes) do
                        local lIndex = v3.tierIndex
                        local gIndex = v3.gridIndex
                        local gridKey  = self:FormatGridKey(lIndex,gIndex)
                        local eventId = v2.eventId
                        local affectList = self._affectDataList[gridKey]
                        if not affectList then
                            affectList = {}
                            self._affectDataList[gridKey] =affectList
                        end
                        table.insert(affectList,eventId)
                    end

                    local eventId = v2.eventId
                    local eventCfg = self:GetEventConfig(eventId)
                    local type = eventCfg.type
                    if type == ModelWonderland.EVENT_BEAST then
                        self._beastEvent = v2
                    end
                end
            end
        end

        local curGridKey = self:FormatGridKey(self._layerIndex,self._gridIndex)
        if self._curGridKey then
            local oldGrid = self._gridInfos[self._curGridKey]
            if oldGrid then
                oldGrid:SetStatus(StructWonderlandGrid.PASSED)
            end
        end

        local grid = self._gridInfos[curGridKey]
        if grid then
            grid:SetStatus(StructWonderlandGrid.PLAYER)
        end
        self._curGridKey = curGridKey


        table.sort(list,function (a,b) return a.layerIndex> b.layerIndex end)

        self._layerList = list

        self:RecordOldState()


        if oldBout ~= self._bout then
            self:OnBoutChange()
        end

        selGridChange= self:CheckSelGridEventChange(oldSelGrid,self._selGrid)
        FireEvent(EventNames.ON_DEST_REWARD_REFRESH)

    else
        self._selGrid = nil
        self._curGridKey = nil
        self._themeMoreInfo = nil
        self._beastEventData = nil
        self._beastEvent = nil
        self:ClearOldRecord()
    end



    if oldState == true and self._isInMap == false then
        local wnd = GF.FindFirstWndByName("UIEden")
        if wnd then
            GF.OpenWndBottom("UIEdenFront")
            wnd:WndClose()
            GF.ChangeMap("LCityMap")
        end
    end


    if not self._isInMap then
        FireEvent(EventNames.ON_WONDERLAND_THEME_REFRESH)
    else
        FireEvent(EventNames.ON_WONDERLAND_PAGE_CHANGE)
        if selGridChange then
            FireEvent(EventNames.ON_SEL_GRID_CHANGE)
        end
    end

end

function ModelWonderland:CheckSelGridEventChange(oldGrid,newGrid)
    if oldGrid and newGrid then
        local oldGridKey = oldGrid:GetGridKey()
        local newGridKey = newGrid:GetGridKey()
        if oldGridKey ~= newGridKey then
            return
        end

        local oldEventIdMap = {}
        local oldEventList = oldGrid:GetEventList()
        local oldCnt = #oldEventList
        local newEventList = newGrid:GetEventList()
        local newCnt = #newEventList
        if newCnt ~= oldCnt then
            return true
        end
        for k,v in ipairs(oldEventList) do
            oldEventIdMap[v.eventId] = true
        end

        for k,v in ipairs(newEventList) do
            if not oldEventIdMap[v.eventId] then
                return true
            end
        end
    end
end

function ModelWonderland:CheckShowEndBox()
    local isPass = self._passAwardState and self._passAwardState == 1
    if not isPass then
        return false
    end

    local eventData,eventInfo = self:GetTimeEvent()
    if eventInfo and not eventInfo.isEnter then
        return false
    end

    return true
end

function ModelWonderland:GetThemeSelections()
    return self._themeIdArr
end


function ModelWonderland:SetThemeMoreInfo(themeMoreinfo)
    self._themeMoreInfo = themeMoreinfo
end

function ModelWonderland:GetCurPattern()
    if self._pattern and self._pattern>= ModelWonderland.NORMAL then
        return self._pattern
    end
    return ModelWonderland.NORMAL
end

function ModelWonderland:GetThemeBuff()
    return self._themeBuff
end

function ModelWonderland:OnWonderlandRefreshResp(pb)
    self:WonderlandHeroOpsReq(0)
end

function ModelWonderland:OnWonderlandOpsResp(pb)
    local type = pb.type
    if type == ModelWonderland.EVENT_WORLD_LEAVES then
        if self._selectGrid then
            FireEvent(EventNames.ON_WONDERLAND_OPER_RET,type,self._selectGrid)
        end
    elseif self._waitRefreshEvent[type] then
        gLGpManager:FindWonderlandCopyGp():SetWaitEvent(type)
    elseif type == ModelWonderland.EVENT_SELECT_GRID then

        self:ReleaseReqProtect()

        local callback = self._selectCallBack
        self._selectCallBack = nil
        if callback then
            callback()
        end
    elseif type == ModelWonderland.EVENT_MIRROR or type == ModelWonderland.EVENT_SINGING or type == ModelWonderland.EVENT_ORGAN then
        if self._selectGrid then
            FireEvent(EventNames.ON_GAIN_ITEM,self._selectGrid,type)
        end
    end
end

function ModelWonderland:OnWonderlandQuestResp(pb)
    self._questData =
    {
        questId = pb.questId,
        schedule = pb.schedule,
        status = pb.status,
    }
end

function ModelWonderland:OnWonderlandHeroOpsResp(pb)


    if pb.syncType == 0 then
        self._heroList ={}
        for k,v in ipairs(pb.heroInfo) do
            local id = v.id
            self._heroList[id] = v
        end
    elseif pb.syncType == 2 then
        self._hpChangeHeros = {}
        for k,v in ipairs(pb.heroInfo) do
            local id = v.id
            local oldData = self._heroList[id]
            if oldData then
                oldData.curHp = v.curHp
            end
            self._hpChangeHeros[id] = true
        end

        FireEvent(EventNames.ON_WONDER_HERO_HP_CHANGE)
    else
        for k,v in ipairs(pb.heroInfo) do
            local id = v.id
            self._heroList[id] = v
        end
    end

end

function ModelWonderland:OnWonderlandHeroMonsterResp(pb)

end

function ModelWonderland:OnWonderlandHeroHireResp(pb)

end

function ModelWonderland:OnWonderlandItemInfoResp(pb)
    --if not self._itemList then
    self._itemList ={}
    --end

    for k,v in ipairs(pb.items) do
        local itemId = v.refId
        local data = self._itemList[itemId]
        if not data then
            data =
            {
                itemId = v.refId,
                itemNum = v.num
            }
            self._itemList[itemId] = data
        else
            data.itemNum = data.itemNum+ v.num
        end
    end
end

function ModelWonderland:OnWonderlandTreasureResp(pb)
    self._treasureList = {}
    for k,v in ipairs(pb.items) do
        local refId = v.refId
        local data =
        {
            itemId = v.refId,
            itemNum = v.num,
        }
        self._treasureList[refId] = data
    end
end

function ModelWonderland:OnWonderlandDestinationResp(pb)
end


function ModelWonderland:OnPowerShowResp(pb,ret)
    if not self._heroList then return end
    local showType = pb.type
    if showType == 2 then
        local _powers = pb.powers
        for i, v in ipairs(_powers) do
            local key = v.key
            local heroStruct = self._heroList[key]
            if heroStruct then
                self._heroList[key].power = v.power
            end
        end
    end
end


function ModelWonderland:OnWonderlandRaceResp(pb)
end

------------------------------------------------------------------
---get

function ModelWonderland:IsHpChangeHero(id)
    if not self._hpChangeHeros then
        return false
    end

    local isChange = self._hpChangeHeros[id]
    self._hpChangeHeros[id] = false
    return isChange
end

function ModelWonderland:GetHpChangeHeros()
    return self._hpChangeHeros
end

function ModelWonderland:ClearHpChange()
    self._hpChangeHeros = {}
end

function ModelWonderland:GetAffectByGrid(gridKey)
    return self._affectDataList[gridKey]
end

function ModelWonderland:GetCurLayer()
    return self._layerIndex or 0
end

function ModelWonderland:GetCurGrid()
    return self._gridIndex
end

function ModelWonderland:GetThemeInfoNumber()
    return tonumber(self._themeMoreInfo) or 0
end

function ModelWonderland:GetCountDownTime()
    return self._countdown
end

function ModelWonderland:GetLayerInfo()
    return self._layerList
end

function ModelWonderland:FormatGridKey(layerIndex,gridIndex)
	gridIndex = gridIndex or 0
    return layerIndex*10 + gridIndex
end

---@return StructWonderlandGrid
function ModelWonderland:GetGridData(layerIndex,gridIndex)
    if self._gridInfos then
        local gridKey = self:FormatGridKey(layerIndex,gridIndex)
        return self._gridInfos[gridKey]
    end
end

---@return StructWonderlandGrid
function ModelWonderland:GetGridDataByGridKey(gridKey)
    if self._gridInfos then
        return self._gridInfos[gridKey]
    end
end

function ModelWonderland:GetGridInfos()
    return self._gridInfos
end

function ModelWonderland:FormatEventData(layerIndex,gridIndex)
    local itemdata = self:GetGridData(layerIndex,gridIndex)
    if not itemdata then
        return
    end
    local state = itemdata:GetStatus()
    local gridIndex = itemdata:GetGridIndex()
    local layerIndex = itemdata:GetLayerIndex()

    local data = {}
    data.canSelect = state == StructWonderlandGrid.ALLOW or state == StructWonderlandGrid.SELECTED
    data.layerIndex = layerIndex
    data.gridIndex = gridIndex
    data.state = state

    local eventList = itemdata:GetEventList()
    if #eventList<=0 then
        return
    end

    local event = nil
    local prio = nil
    for k,v in ipairs(eventList) do             --优先触发普通事件
        local eventId = v.eventId
        local eventCfg = self:GetEventConfig(eventId)
        local tempPrio = eventCfg.overlayType
        if not prio then
            prio = tempPrio
            event = v
        else
            if prio > tempPrio then
                event = v
            end
        end

    end

    if not event then
        event = eventList[1]
    end


    local eventId = event.eventId
    data.eventId = eventId
    data.type = event.type
    data.moreInfo = event.moreInfo

    return data
end

function ModelWonderland:GetThemeId()
    return self._themeId
end

function ModelWonderland:GetThemeType()
    if self._themeId then
        local cfg = self:GetThemeConfig(self._themeId)
        if cfg then
            return cfg.type
        end
    end

    return 1
end

function ModelWonderland:IsInMap()
    return self._isInMap or false
end

function ModelWonderland:GetEventConfig(refId)
    local ref = self:GetModelConfig(ModelWonderland.DreamlandEventRef)
    local cfg = ref[refId]
    if not cfg then
        printErrorN(string.format("no GameTable.DreamlandEventRef refId %s",refId))
    end
    return cfg
end

function ModelWonderland:GetEventName(refId)
    local eventCfg = self:GetEventConfig(refId)
    if eventCfg then
        return ccLngText(eventCfg.name)
    end
    return ""
end

function ModelWonderland:GetChooseConfig(refId)
    return self._chooseConfig
end

function ModelWonderland:GetEventTextConfig(refId)
    return GameTable.DreamlandEventTxtRef[refId]
end

function ModelWonderland:GetHeroListInSpring()
    local list = {}
    for k,v in pairs(self._heroList) do
        if v.curHp>0 then
            table.insert(list,v)
        end

    end

    table.sort(list,function (a,b)
        if a.curHp ~= b.curHp then
            return a.curHp<b.curHp
        end

        return a.power>b.power
    end)
    return list
end

function ModelWonderland:GetHeroListInRevival()
    local list = {}
    for k,v in pairs(self._heroList) do
        table.insert(list,v)
    end

    table.sort(list,function (a,b)
        local aDead = a.curHp<=0 and 0 or 1
        local bDead = b.curHp<=0 and 0 or 1
        if aDead ~= bDead then
            return aDead<bDead
        end
        if a.curHp ~= b.curHp then
            return a.curHp<b.curHp
        end

        return a.power>b.power
    end)
    return list
end

function ModelWonderland:GetHeroListInReborn()
    local list = {}
    local select = nil
    for k,v in pairs(self._heroList) do
        table.insert(list,v)
        if not select then
            select = v
        else
            select = self:GetRebornPrio(select,v)
        end
    end

    table.sort(list,function (a,b)
        if a.power~= b.power then
            return a.power>b.power
        end

        local aDead = a.curHp<=0 and 0 or 1
        local bDead = b.curHp<=0 and 0 or 1
        if aDead ~= bDead then
            return aDead<bDead
        end


        return a.refId>b.refId
    end)
    return list,select
end

function ModelWonderland:GetRebornPrio(hero1,hero2)
    local aDead = hero1.curHp <= 0 and 1 or 2
    local bDead = hero2.curHp <= 0 and 1 or 2

    if aDead ~= bDead then
        return aDead< bDead and hero1 or hero2
    end

    local aFull = hero1.curHp < hero1.maxHp and 1 or 2
    local bFull = hero2.curHp < hero2.maxHp and 1 or 2

    if aFull ~= bFull then
        return aFull< bFull and hero1 or hero2
    end

    return hero1.power > hero2.power and hero1 or hero2
end

function ModelWonderland:GetWonderHeroList(noDead)
    local list = {}
    for k,v in pairs(self._heroList) do
        if noDead then
            if v.curHp>0 then
                table.insert(list,v)
            end
        else
            table.insert(list,v)
        end
    end
    return list
end

function ModelWonderland:GetHeroListInBattle()
    local list = {}
    for k,v in pairs(self._heroList) do
        table.insert(list,v)
    end

    table.sort(list,function (a,b)
        return a.power>b.power
    end)
    return list
end

function ModelWonderland:CheckHasHeroHurt()
    for k,v in pairs(self._heroList) do
        if v.curHp>0 and v.curHp<v.maxHp then
            return true
        end
    end
    return false
end

function ModelWonderland:CheckHasHeroDead()
    for k,v in pairs(self._heroList) do
        if v.curHp<=0 then
            return true
        end
    end
    return false
end


function ModelWonderland:GetEventReward(rewardId,floor)
    floor = floor or 0
    local level = gModelPlayer:GetPlayerLv()
    local floorList = self._rewardConfigs[rewardId]
    if not floorList then
        printErrorN(string.format("not wonder reward %s",rewardId))
        return {}
    end
    local list = floorList[floor]
    if not list then
        printInfoN(string.format("not wonder floor %s",floor))
        list = floorList[0]
    end
    if not list then
        printErrorN(string.format("not wonder reward %s",rewardId))
        return {}
    end
    for k,v in ipairs(list) do
        if level>= v.levelMin and level<= v.levelMax then
            return LxDataHelper.ParseItem(v.reward)
        end
    end
    return {}
end

function ModelWonderland:GetGoodsConfig(refId)
    return self._goodsConfig[refId]
end


function ModelWonderland:GetWonderlandPara(key)
    local ref =  self:GetModelConfig(ModelWonderland.DreamlandConfigRef)
    return ref[key]
end

function ModelWonderland:GetItemNum(itemId)
    if not self._itemList then
        return 0
    end
    local data = self._itemList[itemId]
    if data then
        return data.itemNum
    end
    return 0
end

function ModelWonderland:GetEventTextId(eventId,index)
    local cfg = self:GetEventConfig(eventId)
    local choose = cfg.choose
    local tempStrs = string.split(choose,"|")

    if #tempStrs==0 then
        return
    end

    local index = index or 1
    local textId = tempStrs[index]
    return textId and tonumber(textId)

end

function ModelWonderland:GetDefaultEventText(textId)
    local cfg =  GameTable.DreamlandEventTxtRef[textId]
    if not cfg then
        return
    end

    local answer = cfg.answer
    answer = ccLngText(answer)
    local temp = string.split(answer,"|")
    local data =
    {
        desc = ccLngText(cfg.dec),
        answer=temp
    }
    return data
end

function ModelWonderland:GetThemeConfig(refId)
    local ref = self:GetModelConfig(ModelWonderland.DreamlandThemeRef)
    return ref[refId]
end

function ModelWonderland:GetTaskConfig(refId)
    local refs = self:GetModelConfig(ModelWonderland.WonderTaskRef)
    local ref = refs[refId]
    if not ref then
        printInfoNR2("配置缺失", string.format("GameTable.WonderTaskRef[%s]", refId or "nil"))
    end
    return ref
end

--function ModelWonderland:GetThemeList()
--    local list = {}
--    for k,v in pairs(GameTable.DreamlandThemeRef) do
--        table.insert(list,v)
--    end
--    table.sort(list,function (a,b) return a.refId< b.refId end)
--    return list
--end

function ModelWonderland:GetBookEventList(themeId)
    local list ={}
    for k,v in pairs(GameTable.WonderHelpRef) do
        local mapid = v.mapId
        if mapid == 0 or mapid == themeId then
            table.insert(list,v)
        end
    end

    table.sort(list,function (a,b)
        local aMapId = a.mapId
        local bMapId = b.mapId
        if aMapId~= bMapId then
            return aMapId>bMapId
        end
        return a.refId <b.refId end)
    return list
end

function ModelWonderland:GetTreasureList()
    local list ={}
    for k,v in pairs(GameTable.DreamlandBuffRef) do
        local type = v.type
        if type ~= 0 and type ~= 4 then
            table.insert(list,v)
        end
    end

    table.sort(list,function (a,b)
        local aQua = a.quality
        local bQua = b.quality
        if aQua ~= bQua then
            return aQua>bQua
        end

        local aType = a.type
        local bType = b.type
        if aType~=bType then
            return aType>bType
        end

        local aId = a.refId
        local bId = b.refId
        return aId<bId
    end)

    return list
end

function ModelWonderland:GetTreasureConfig(refId)
    return GameTable.DreamlandBuffRef[refId]
end

function ModelWonderland:IsIndependentEvent(eventId)
    return self._independentEvents[eventId]
end

--function ModelWonderland:GetGridIconList(themeId)
--    return self._gridIconList[themeId]
--end

function ModelWonderland:GetHeroListOnTs()
    local formation = gModelFormation:GetFormation(LCombatTypeConst.COMBAT_WONDERLAND)
    local formationHeros ={}
    if formation then
        for k,v in ipairs(formation.grids) do
            local id = v.id
            formationHeros[id] = true
        end
    end

    local list = {}
    for k,v in pairs(self._heroList) do
        if v.curHp>0 then
            table.insert(list,v)
        end

    end

    table.sort(list,function (a,b)
        local aPrio = formationHeros[a.id] and 0 or 1
        local bPrio = formationHeros[b.id] and 0 or 1
        if aPrio~= bPrio then
            return aPrio<bPrio
        end
        if a.power~= b.power then
            return a.power>b.power
        end

        return a.refId<b.refId

    end)
    return list

end

function ModelWonderland:GetBattleMapId()
    local themeId = self:GetThemeId()
    themeId = themeId or 1
    local cfg = self:GetThemeConfig(themeId)
    return cfg.battleScene
end

function ModelWonderland:GetHeroData(id)
    return self._heroList[id]
end

function ModelWonderland:GetMonsterEventReward(eventId)
    local cfg = self:GetEventConfig(eventId)
    if not cfg then
        return
    end
    local reward = self:GetEventRewardId(eventId)
    local random = cfg.random
    local key,value = LxDataHelper.ParseIntKV_Equal(random)
    local ratio = value
    return reward,ratio
end

--- 生效，品质，等级，id
function ModelWonderland:GetSortedTreasureList()
    local formation = gModelFormation:GetFormation(LCombatTypeConst.COMBAT_WONDERLAND)
    local refIdList = {}
    local raceList = {}
    local careerList={}
    if formation then
        for k,v in ipairs(formation.grids) do
            local id = v.id
            local heroData = self:GetHeroData(id)
            local refId =nil
            if heroData then
                refId = heroData.refId
                refIdList[refId] = true
                local race = gModelHero:GetHeroRace(refId)
                raceList[race] = true
                local career = gModelHero:GetHeroCareerType(refId)
                careerList[career] = true
            end
        end
    end

    local dataListForSort={}
    for k,v in pairs(self._treasureList) do
        local data ={}
        data.refId = k
        local isOn = self:IsTreasureOn(k,refIdList,raceList,careerList)
        data.activePrio = isOn and 1 or 2
        local cfg = GameTable.DreamlandBuffRef[k]
        data.quality = cfg.quality
        data.level = cfg.lv
        table.insert(dataListForSort,data)
    end

    table.sort(dataListForSort,function (a,b)
        if a.activePrio~= b.activePrio then
            return a.activePrio<b.activePrio
        end
        if a.quality~= b.quality then
            return a.quality>b.quality
        end
        if a.level ~= b.level then
            return a.level>b.level
        end
        return a.refId <b.refId
    end)

    return dataListForSort

end

---加成是否生效
function ModelWonderland:IsTreasureOn(treasureId,refIdList,raceList,careerList)
    local rangeList = self._buffRangeConfigs[treasureId]
    if not rangeList then
        return false
    end


    for k,v in ipairs(rangeList) do
        local type = v.type
        local para = v.para
        local isOn = false
        if type == -1 then
            isOn = true
        elseif type == 1 then
            if para then
                isOn = refIdList[para] or false
            end
        elseif type == 2 then
            if para then
                isOn = careerList[para] or false
            end
        elseif type == 3 then
            if para then
                isOn = raceList[para] or false
            end
        end

        if isOn then
            return isOn
        end
    end

    return false
end

function ModelWonderland:GetTreasureRange(treasureId)
    return self._buffRangeConfigs[treasureId]
end

--function ModelWonderland:CheckCanSkip(showTip)
--    local limitLv = self:GetWonderlandPara("skipLevel")
--    local playLv = gModelPlayer:GetPlayerLv()
--    local canSkip = playLv>=limitLv
--    if not canSkip and showTip then
--        GF.ShowMessage(string.format("%s级可跳过",limitLv))
--    end
--    return canSkip
--end

function ModelWonderland:FormatBattleData(pb,eventName,eventId,bossType)

    local battledata = {}
    battledata.formationRefId = pb.formationRefId

    local bossList= {}
    local isMonster = false
    for k,v in ipairs(pb.heroInfo) do
        local data =
        {
            refId = v.refId,
            id = v.id,
            heroType = v.heroType,
            lvl = v.lvl,
            star = v.star,
            maxHp = v.maxHp,
            curHp = v.curHp,
            power = v.power,
            grade = v.grade,
            monsterAddCost = pb.monsterAddCost,
            skin = v.skin,
            form = v.form,
        }

        if v.heroType == ModelWonderland.ENEMY_MONSTER then
            isMonster = true
        end

        table.insert(bossList,data)
    end

    battledata.bossList  = bossList

    local grids = {}
    for k,v in ipairs(pb.grids) do
        local data =
        {
            id = v.id,
            grid = v.grid,
        }
        table.insert(grids,data)
    end

    local treasureIds = nil

    if pb.treasureSkilIds then
        treasureIds = {}
        local index = 1
        for k,v in ipairs(pb.treasureSkilIds) do
            if v>0 then
                local data =
                {
                    index = index,
                    skillId = v,
                }
                treasureIds[index] =data
            end
            index = index + 1
        end
    end


    battledata.grids = grids
    battledata.otherName = eventName
    battledata.power = pb.power
    battledata.eventName = eventName
    battledata.treasureIds = treasureIds
    battledata.eventRefId = eventId
    battledata.bossType = bossType or 1 --1,普通怪，血量限制 2,时光领主 ，无限制
    battledata.monsterAddCost = pb.monsterAddCost
    return battledata
end

function ModelWonderland:GetQuestData()
    return self._questData
end

function ModelWonderland:CanTreasureLvUp(refId)
    local curCfg = GameTable.DreamlandBuffRef[refId]
    if not curCfg then
        printErrorN(string.format("not wonderbuff refId %s ",refId))
        return false,refId,1
    end
    local group = curCfg.group
    local defaultLv = curCfg.lv
    for k,v in pairs(self._treasureList) do
        local treasureId = v.itemId
        local ownCfg = GameTable.DreamlandBuffRef[treasureId]
        local curGroup = ownCfg.group
        local curLv = ownCfg.lv
        if curGroup == group then
            local nextId = ownCfg.nextLv
            if nextId > 0 then
                return true,nextId,curLv
            end
        end
    end
    return false,refId,defaultLv
end

function ModelWonderland:GetSceneEvent(refId)
    return self._sceneEvents[refId]
end

function ModelWonderland:GetEventMonsterType(eventId)
    return self._eventMonsterList[eventId]
end

function ModelWonderland:GetFormationPower(heroIdList)
    --同组取等级最高的宝物
    local groupList = {}
    for k,v in pairs(self._treasureList) do
        local treasureId = k
        local cfg = self:GetTreasureConfig(treasureId)
        local group = cfg.group
        local lv = cfg.lv
        local list = groupList[group]
        if not list then
            list = {}
            groupList[group] = list
        end
        local data =
        {
            treasureId = treasureId,
            lv = lv
        }

        table.insert(list,data)
    end

    local treasureList ={}
    for k,v in pairs(groupList) do
        table.sort(v,function (a,b)
            return a.lv>b.lv
        end)

        local first = v[1]
        table.insert(treasureList,first)
    end

    --计算每个英雄生效系数


    local totalPower = 0
    local defaultPower = 0

    local percent = 0
    --local positiveTreas = {}
    for k,v in pairs(heroIdList) do
        local heroData = self:GetHeroData(v)
        if heroData then
            local refId = heroData.refId
            local totalFight = 0
            for k1,v1 in pairs(treasureList) do
                local treasureId = v1.treasureId
                local isPositive = self:IsTreasurePositive(refId,treasureId)
                if isPositive then
                    local cfg = self:GetTreasureConfig(treasureId)
                    local fight = cfg.fight
                    totalFight = fight + totalFight

                    --if not positiveTreas[v1] then
                    --    positiveTreas[v1] = true
                        --percent = percent+ fight
                    --end
                end
            end

            local power =math.floor(heroData.power*(1+ totalFight))
            totalPower = totalPower + power
            defaultPower = defaultPower+ heroData.power
        end
    end

    if defaultPower>0 then
        percent = totalPower/defaultPower -1
    end


    return totalPower,percent
end

function ModelWonderland:IsTreasurePositive(refId,treasureId)
    local rangeList = self._buffRangeConfigs[treasureId]
    if not rangeList then
        return false
    end
    local race = gModelHero:GetHeroRace(refId)
    local career = gModelHero:GetHeroCareerType(refId)

    for k,v in ipairs(rangeList) do
        local type = v.type
        local para = v.para
        local isOn = false
        if type == -1 then
            isOn = true
        elseif type == 1 then
            isOn = refId == para
        elseif type == 2 then
            isOn = career == para
        elseif type == 3 then
            isOn = race == para
        end

        if isOn then
            return true
        end
    end


    return false
end

function ModelWonderland:GetRoleRes(themeId)
    local cfg = self:GetThemeConfig(themeId)
    if cfg then
        return cfg.roleRes
    end
end

function ModelWonderland:GetRefreshEff(themeId)
    return self._refreshEffList[themeId]
end

function ModelWonderland:IsBossTrigger(themeId)
    local itemId,itemNum = self:GetBossTriggerCondition(themeId)
    if not itemId or not itemNum then
       return false
    end
    local ownNum = self:GetItemNum(itemId)
    if ownNum>=itemNum then
        return true
    end
end

function ModelWonderland:GetBossTriggerCondition(themeId)
    local themeCfg = self:GetThemeConfig(themeId)
    local endEvent = themeCfg.endEvent
    local eventCfg = self:GetEventConfig(endEvent)
    local parameter = eventCfg.parameter
    local tempStrs = string.split(parameter,"|")
    if #tempStrs<1 then
        return
    end
    local strs= string.split(tempStrs[1],"=")
    if #strs<2 then
        return
    end
    local itemId = tonumber(strs[1])
    local itemNum = tonumber(strs[2])
    return itemId,itemNum
end



-----------------------------------------------------------------
---配置预处理
function ModelWonderland:ParseConfig()
    local rewardConfigs = {}
    for k,v in pairs(GameTable.DreamlandRewardRef) do
        local rewardGroup = v.rewardGroup
        local reward = v.reward
        local data =
        {
            levelMin = v.levelMin,
            levelMax = v.levelMax,
            reward = reward,
        }
        local list = rewardConfigs[rewardGroup]
        if not list then
            list ={}
            rewardConfigs[rewardGroup] = list
        end
        local floor = v.floor
        local tempList = list[floor]
        if not tempList then
            tempList = {}
            list[floor] = tempList
        end
        table.insert(tempList,data)

    end

    self._rewardConfigs = rewardConfigs

    local goodsConfig = {}
    for k,v in pairs(GameTable.DreamlandGoodsRef) do
        local reward = LxDataHelper.ParseItem_3(v.reward)
        local price = LxDataHelper.ParseItem_3(v.price)
        local discount = v.fixDiscount
        local data=
        {
            reward = reward,
            price = price,
            discount = discount,
        }
        goodsConfig[k] = data
    end

    self._goodsConfig = goodsConfig

    local independentEvents = {}
    local refreshEffList ={}
    --local gridIconList ={}
    local sceneEvents ={}
    local specialEvents = {}
    --local gridStateResList = {}

    local WonderThemeRef = self:GetModelConfig(ModelWonderland.DreamlandThemeRef)
    for k,v in pairs(WonderThemeRef) do
        local themeId = v.refId
        local ownEvent = v.ownEvent
        local tempStrs = string.split(ownEvent,";")
        for k1,v1 in ipairs(tempStrs) do
            local temp = string.split(v1,"=")
            if #temp> 0 then
                local eventId = tonumber(temp[1])
                independentEvents[eventId] = true
            end
        end
        local endEvent = v.endEvent
        independentEvents[endEvent] = true

        local difEvent = v.difficultyEvent
        if not string.isempty(difEvent) then
            local tempStrs = string.split(difEvent,";")
            for k1,v1 in ipairs(tempStrs) do
                local temp = string.split(v1,"=")
                if #temp> 0 then
                    local eventId = tonumber(temp[1])
                    independentEvents[eventId] = true
                end
            end
        end

        local sceneEvent = v.sceneEvent
        if not string.isempty(sceneEvent) then
            local type,eventId = LxDataHelper.ParseIntKV_Equal(sceneEvent)
            local data =
            {
                type = type,
                eventId = eventId,
            }
            sceneEvents[themeId] = data
        end

        local refreshEff = v.refreshEffect
        local strs = string.split(refreshEff,",")
        if #strs>=3 then
            local effList = {
                outAni = strs[1],
                inAni = strs[2],
                adAni = strs[3],

            }
            refreshEffList[k] = effList
        end

        local typeList = LxDataHelper.ParseNumber_Sign(tostring(v.specialEvent))
        local typeMap = {}
        for k1,v1 in ipairs(typeList) do
            typeMap[v1] = true
        end

        specialEvents[k] = typeMap

        --strs = string.split(v.platformEffect,',')
        --gridStateResList[k] = strs
    end

    self._independentEvents = independentEvents
    --self._gridIconList = gridIconList
    self._sceneEvents = sceneEvents
    self._refreshEffList = refreshEffList
    self._specialEvents = specialEvents
    --self._gridStateEffList = gridStateResList

    self._buffRangeConfigs ={}
    local buffGroupList ={}
    for k,v in pairs(GameTable.DreamlandBuffRef) do
        local range = v.range
        local rangeList = {}

        if string.isempty(range) then
            local rangeT ={
                type = -1
            }
            table.insert(rangeList,rangeT)
        else
            local tempStr = string.split(range,"|")
            for k1,v1 in ipairs(tempStr) do
                local rangeT = {}
                local type,para = LxDataHelper.ParseIntKV_Equal(v1)
                rangeT.type = type
                rangeT.para = para
                table.insert(rangeList,rangeT)
            end

        end

        local group = v.group
        local list = buffGroupList[group]
        if not list then
            list = {}
            buffGroupList[group] = list
        end

        table.insert(list,v)

        self._buffRangeConfigs[k] = rangeList
    end

    self._buffGroupList = buffGroupList

    local eventMonsterList = {}
    local WonderEventRef = self:GetModelConfig(ModelWonderland.DreamlandEventRef)
    for k,v in pairs(WonderEventRef) do
        local monsterType = v.monsterType
        local nums = LxDataHelper.ParseNumber_Sign(monsterType,"=")
        if #nums>=3 then
            local type = tonumber(nums[2])
            eventMonsterList[k] = type
        end
    end

    self._eventMonsterList = eventMonsterList

    local hintMap = {}
    for k,v in pairs(GameTable.DreamlandHintRef) do
        local eventList = LxDataHelper.ParseNumber_Sign(v.event,";")
        for k1,v1 in ipairs(eventList) do
            hintMap[v1] = v
        end
    end

    self._hintMap = hintMap
end

function ModelWonderland:RecordOldState()
    if self._gridStateRecords then
        return
    end

    self._gridStateRecords = self:CreateStateRecord()
end


function ModelWonderland:GetGridOldState()
    if not self._gridStateRecords then
        self._gridStateRecords = self:CreateStateRecord()
    end
    return self._gridStateRecords
end

function ModelWonderland:CreateStateRecord()
    local gridStateRecords ={}

    for k,v in pairs(self._layerList) do
        for k1,v1 in pairs(v.grids) do
            local layerIndex = v1:GetLayerIndex()
            local gridIndex = v1:GetGridIndex()
            local gridKey = self:FormatGridKey(layerIndex,gridIndex)

            local state = v1:GetStatus()
            local isEnd = self:GetCurLayer() == 20
            local themeType = self:GetThemeType()
            if themeType == 4 and not isEnd then
                if state == StructWonderlandGrid.DISAPPEAR or state == StructWonderlandGrid.PASSED then
                    state = StructWonderlandGrid.FORBIDDEN
                end
            end

            gridStateRecords[gridKey] = state
        end
    end
    return gridStateRecords
end

function ModelWonderland:ClearOldRecord()

    self._gridStateRecords = nil
end

function ModelWonderland:CheckRelativeEvents(list)
    local exist = {}
    local curLayer = self:GetCurLayer()
    for k,v in pairs(self._layerInfos) do
        if k >curLayer then
            local grids = v.grids
            for k1,v1 in pairs(grids) do
                local eventList = v1:GetEventList()
                for k2,v2 in pairs(eventList) do
                    local eventCfg = self:GetEventConfig(v2.eventId)
                    local type = eventCfg.type
                    local data = list[type]
                    if data then
                        exist[data.index] = type
                    end

                end
            end
        end
    end
    return exist
end

function ModelWonderland:GetLayerGridCnt(layerIndex)
    if not self._layerInfos then
        return 1
    end
    local layer = self._layerInfos[layerIndex]
    if not layer then
        return 1
    end

    return #(layer.grids)
end

function ModelWonderland:ClearBoutChangeTag()
    self._boutChanged = false
end

function ModelWonderland:IsBoutChange()
    return self._boutChanged
end

function ModelWonderland:OnBoutChange()
    self._boutChanged = true
    --FireEvent(EventNames.ON_WONDERLAND_BOUT_CHANGE)
end

function ModelWonderland:GetRoleBuff()
    local info = self._themeMoreInfo
    local strs = string.split(info,'|')
    if #strs>=3 then
        local eventId = tonumber(strs[2])
        local round = tonumber(strs[3])
        return eventId,round
    end
end

function ModelWonderland:GetOrganNum()
    local info = self._themeMoreInfo
    local strs = string.split(info,'|')
    if #strs>=1 then
        return tonumber(strs[1])
    end
    return 0
end

function ModelWonderland:GetBout()
    return self._bout or 0
end

function ModelWonderland:GetCurFormationPower()
    local formation = gModelFormation:GetFormation(LCombatTypeConst.COMBAT_WONDERLAND)
    local idList ={}
    if formation and formation.grids then
        for k,v in ipairs(formation.grids) do
            local id = v.id
            table.insert(idList,id)
        end
    end
    if #idList ==0 then
        return 0
    end

    return self:GetFormationPower(idList)
end

function ModelWonderland:GetEventData(layerIndex,gridIndex,eventId)
    local gridData = gModelWonderland:GetGridData(layerIndex,gridIndex)
    local eventList = gridData:GetEventList()
    for k, v in ipairs(eventList) do
        if eventId == v.eventId then
            return v
        end
    end
end

function ModelWonderland:IsSpecialEvent(eventType)
    local themeId = self:GetThemeId()
    if not themeId then
        return
    end
    if not self._specialEvents then
        return
    end
    local typeMap = self._specialEvents[themeId]
    return typeMap and typeMap[eventType]
end


function ModelWonderland:GetFreeRebornCnt()
    return self._freeRebornCnt or 0
end

function ModelWonderland:HasAffectEventType(gridKey,eventType)
    local has = false
    local affectList = gModelWonderland:GetAffectByGrid(gridKey)
    if affectList then
        for k,v in ipairs(affectList) do
            local affCfg = gModelWonderland:GetEventConfig(v)
            local type = affCfg.type
            if type == eventType then
                has = true
                break
            end
        end
    end

    return has
end

function ModelWonderland:GetPlatformEffectName(oldState,newState)
    if oldState == newState then
        return
    end

    local themeId  = self:GetThemeId()
    local effResList = self:GetConfigValueImpl(ModelWonderland.DreamlandThemeRef,themeId,"platformEffect",function (value) return string.split(value,',') end)
    if not effResList then
        return
    end

    local type = nil
    local effRes = nil
    local isOldUp = self._gridUpStates[oldState]
    local isNewUp = self._gridUpStates[newState]
    if not isOldUp and isNewUp then
        effRes = effResList[1]
        type = 0
    end
    if newState == StructWonderlandGrid.PASSED then
        effRes = effResList[2]
        type = 1
    elseif newState == StructWonderlandGrid.DISAPPEAR then
        effRes = effResList[3]
        type = 1
    end
    return effRes,type
end

function ModelWonderland:IsEventShow(layerIndex,gridIndex,eventId)
    local eventCfg = self:GetEventConfig(eventId)
    local eventType = eventCfg.type
    if self:IsMapEnd() then
        if eventType== ModelWonderland.EVENT_TIME then
            return true
        end

        return false
    end
    local eventCfg = self:GetEventConfig(eventId)
    local roleLayer = self:GetCurLayer()
    local gridKey = self:FormatGridKey(layerIndex,gridIndex)

    local gridData = self:GetGridDataByGridKey(gridKey)
    local status = gridData:GetStatus()
    local eventType = eventCfg.type
    local showEvent = true

    if status == StructWonderlandGrid.DISAPPEAR then
        if eventType ~= ModelWonderland.EVENT_BEAN_VINE then
            showEvent = false
        end
    end

    local themeType = gModelWonderland:GetThemeType()

    if themeType == 4 then
        if layerIndex<= roleLayer then
            if eventType ~= ModelWonderland.EVENT_BEAN_VINE then
                showEvent = false
            end
        end
    elseif themeType== 2 then
        local hasSnow  = self:HasAffectEventType(gridKey,ModelWonderland.EVENT_SNOW)
        local isIndependent = self:IsIndependentEvent(eventId)
        if not isIndependent and hasSnow  then
            if layerIndex- roleLayer>1 then
                showEvent = false
            end
        end
    elseif themeType == 5 then
        if eventType == ModelWonderland.EVENT_BEAST then
            showEvent = false
        elseif eventType == ModelWonderland.EVENT_OCTOPUS then
            if status == StructWonderlandGrid.PASSED then
                showEvent = true
            end
        end
    elseif themeType == 1 then
        if eventType == ModelWonderland.EVENT_GRANDMA  then
            if status == StructWonderlandGrid.PASSED then
                showEvent = false
            end
        end
    end

    local hideType = eventCfg.hideType

    if hideType == 1 then
        if layerIndex-roleLayer>2 then
            showEvent = false
        end
    end

    return showEvent
end

function ModelWonderland:IsInScopes(gridKey,eventId)
    local gridData = gModelWonderland:GetGridDataByGridKey(gridKey)
    local curLayer = gModelWonderland:GetCurLayer()
    local curGrid = gModelWonderland:GetCurGrid()
    for k,v in ipairs(gridData:GetEventList()) do
        if v.eventId == eventId then
            for k1,v1 in ipairs(v.scopes) do
                if curLayer == v1.tierIndex and curGrid == v1.gridIndex then
                    return true

                end
            end
        end
    end

    return false
end


function ModelWonderland:GetBeastEventInfo()
    if string.isempty(self._themeMoreInfo) or self:IsMapEnd() then
        return false,-1
    end
    local strs =LxDataHelper.ParseNumber_Sign(self._themeMoreInfo,"|") --string.split(self._themeMoreInfo,"|")
    local isMeet = false
    local layerIndex = 0
    local gridIndex = 0
    if #strs == 3 then
        layerIndex = tonumber(strs[1])
        gridIndex = tonumber(strs[2])
        isMeet = tonumber(strs[3]) == 1
    end

    return isMeet,layerIndex,gridIndex
end

function ModelWonderland:GetBeastEvent()
    local isMeet,layerIndex,gridIndex = self:GetBeastEventInfo()
    if layerIndex ==-1 then
        return
    end

    local data = self._beastEventData
    if not data then
        data =
        {
            eventId = 50008,
            layerIndex =layerIndex,
            gridIndex = gridIndex,
            isMeet = isMeet
        }
        self._beastEventData = data
    end

    data.layerIndex = layerIndex
    data.gridIndex = gridIndex
    data.isMeet = isMeet

    return data
end
function ModelWonderland:IsMapEnd()
    return self._passAwardState and self._passAwardState>=1
end

function ModelWonderland:GetBeastSleep()
    if not self._beastEvent then
        return 0
    end

    local moreInfo = self._beastEvent.moreInfo
    local bout = tonumber(moreInfo) or 0
    return bout

end

function ModelWonderland:OnReceiveEffect(effdata)
    if not self._effectMap then
        self._effectMap = {}
    end

    self._effectMap[effdata.eventType] = effdata
end

function ModelWonderland:DeleteEffect(eventType)
    if self._effectMap then
        self._effectMap[eventType] = nil
    end
end

function ModelWonderland:ClearAllEffect()
    self._effectMap = nil
end

function ModelWonderland:CheckShowHud(eventType)
    local data =self._effectMap and self._effectMap[eventType]
    if data then
        self._effectMap[eventType] = nil
        FireEvent(EventNames.ON_SHOW_WONDER_HUD,data)

        printInfoN("show hud type "..tostring(eventType))
    end
end

function ModelWonderland:GetHintData(eventType)
    return self._hintMap[eventType]
end

function ModelWonderland:SetSkipPrepare(isSkip)
    if isSkip then
        local canSkip = gModelBattle:CanSkip(LCombatTypeConst.COMBAT_WONDERLAND,true)
        if not canSkip then
            return
        end
    end

    local value = isSkip and 1 or 0
    LPlayerPrefs.SetWonderSkipB(value)
    return true
end

function ModelWonderland:GetSkipPrepare()
    local value = tonumber(LPlayerPrefs.wonderSkipB) or 0
    return value == 1
end


function ModelWonderland:GetFormationHeroCnt(noLimit)
    local formation = gModelFormation:GetFormation(LCombatTypeConst.COMBAT_WONDERLAND)
    local cnt = 0
    local grids = {}
    if formation and formation.grids then
        for k,v in ipairs(formation.grids) do
            local id = v.id
            local heroData = self:GetHeroData(id)

            if heroData then
                if noLimit or heroData.curHp>0 then
                    cnt = cnt + 1
                    table.insert(grids,v)
                end
            end
        end
    end
    return cnt,grids
end

function ModelWonderland:EnterBattle(battleData,curWnd)

    if table.isempty(self._heroList) then
        printErrorN("no wonderland hero info")
        return
    end

    local isSkip = self:GetSkipPrepare()
    if isSkip then
        local isTimeLord = battleData.isTimeLord
        local heroCnt,newGrids  = self:GetFormationHeroCnt(isTimeLord)

        local func = function()

            GF.CloseWndByName(curWnd)

            local combatData =
            {
                combatType = LCombatTypeConst.COMBAT_WONDERLAND,
                skipBattle = true,
                eventRefId = battleData.eventRefId,
            }
            gModelBattle:OnCombatReq(combatData)

        end

        local leftFunc = function()
            gLFightManager:PrepareGoToBattle(LCombatTypeConst.COMBAT_WONDERLAND,battleData)

        end
        if heroCnt==0 then
            gModelGeneral:OpenUIOrdinTips({refId = 70012,func = leftFunc })
            return
        elseif heroCnt <5 then
            gModelGeneral:OpenUIOrdinTips({refId = 70011,func = func,leftFunc = leftFunc })
            return
        end

        func()

    else
        gLFightManager:PrepareGoToBattle(LCombatTypeConst.COMBAT_WONDERLAND,battleData)
    end
end


function ModelWonderland:GetGridIconPath(themeId,state)
    local iconPathList = self:GetConfigValueImpl(ModelWonderland.DreamlandThemeRef,themeId,"platform",function (value)
        return string.split(value,',')
    end)

    local index = nil
    if state == StructWonderlandGrid.PASSED then
        index = 2
    elseif state == StructWonderlandGrid.ALLOW or state == StructWonderlandGrid.SELECTED
            or state == StructWonderlandGrid.PLAYER then
        index = 1
    else
        index = 3
    end

    return iconPathList[index]
end

function ModelWonderland:GetCardShow(eventId)
    local eventCfg = self:GetEventConfig(eventId)
    local exchange = eventCfg.exchange
    local paras = string.split(exchange,'=')
    local exchangeId = tonumber(paras[2])
    if not exchangeId then
        printErrorN("not exchange")
        return
    end

    local exchangeCfg = self:GetEventConfig(exchangeId)
    local cardList = LxDataHelper.ParseNumber_Sign(exchangeCfg.parameter,'=')
    return cardList
end

function ModelWonderland:GetEventRewardId(eventId)
    local parseFunc = function(value)
        local strs = string.split(value,'|')
        local dataList = {}
        for k,v in ipairs(strs) do
            local temps = string.split(v,'=')
            local mode = tonumber(temps[1])
            local rewardId = tonumber(temps[2])
            dataList[mode] = rewardId
        end
        return dataList
    end
    local rewardList = self:GetConfigValueImpl(ModelWonderland.DreamlandEventRef,eventId,"reward",parseFunc)

    local curPattern = self:GetCurPattern()
    return rewardList[curPattern]
end

function ModelWonderland:GetTaskRewardId(taskId)
    local parseFunc = function(value)
        local strs = string.split(value,'|')
        local dataList = {}
        for k,v in ipairs(strs) do
            local temps = string.split(v,'=')
            local mode = tonumber(temps[1])
            local rewardId = tonumber(temps[2])
            dataList[mode] = rewardId
        end
        return dataList
    end
    local rewardList = self:GetConfigValueImpl(ModelWonderland.WonderTaskRef,taskId,"reward",parseFunc)

    local curPattern = self:GetCurPattern()
    return rewardList[curPattern]
end

function ModelWonderland:CheckSelectPattern(pattern)
    local maxPass = self._viaPatternType or 0
    local pass = maxPass>= pattern - 1
    return pass
end

function ModelWonderland:GetTimeLordShow(eventId)
    local ref = self:GetEventConfig(eventId)
    if not ref then
        printErrorN(string.format("not event ref %s",eventId))
        return
    end

    local param = ref.parameter
    local eventList = {}
    local strs = string.split(param,'=')
    for k= 2,4 do
        local monsterId = tonumber(strs[k])
        table.insert(eventList,monsterId)
    end
    return eventList
end

function ModelWonderland:GetDifIconList()
    local parseFun = function(value)
        return string.split(value,'=')
    end
    local iconPathList = self:GetParaConfigValueImpl(ModelWonderland.DreamlandConfigRef,"difficultyIcon",parseFun)
    return iconPathList
end

function ModelWonderland:EnterWonderMap()
    if self._isInMap then
        local eventData,eventInfo = self:GetTimeEvent()
        if eventInfo and eventInfo.isEnter then
            GF.ChangeMap("LWonderlordMap",false,{data = eventData})
        else
            GF.ChangeMap("LWonderlandMap")
        end
    else
        GF.ChangeMap("LCityMap")
    end
end

function ModelWonderland:CheckChangeMap()
    if not self._isInMap then
        return
    end
    local curMap = GF.GetCurMap()

    local eventData,eventInfo = self:GetTimeEvent()
    if eventInfo and eventInfo.isEnter then
        if not curMap:IsSameMap("LWonderlordMap") then
            GF.ChangeMap("LWonderlordMap",false,{data = eventData})
        end
    else
        if not curMap:IsSameMap("LWonderlandMap") then
            GF.ChangeMap("LWonderlandMap")
        end
    end
end

--function ModelWonderland:IsEnterLordMap()
--    local eventData = self:GetTimeEvent()
--    if eventData then
--        local moreInfo = eventData.moreInfo
--        local strs = string.split(moreInfo,"=")
--        return strs[1] == '1'
--    end
--    return false
--end

function ModelWonderland:ParseTimeEventInfo(moreInfo)
    local strs = string.split(moreInfo,'=')
    local isEnter = strs[1] == '1'
    local idMap = {}
    if strs[2] then
        local idList = LxDataHelper.ParseNumber_Sign(strs[2],'|')
        for k,v in ipairs(idList) do
            idMap[v] = true
        end
    end

    return {isEnter = isEnter,idMap = idMap}
end

function ModelWonderland:GetTimeEvent()
    local eventData = nil
    local curLayer = self:GetCurLayer()
    for k,v in pairs(self._layerInfos) do
        if k >curLayer then
            local grids = v.grids
            for k1,v1 in pairs(grids) do
                local eventList = v1:GetEventList()
                for k2,v2 in pairs(eventList) do
                    local eventCfg = self:GetEventConfig(v2.eventId)
                    if eventCfg then
                        local type = eventCfg.type
                        if type == ModelWonderland.EVENT_TIME then
                            eventData =
                            {
                                eventId = v2.eventId,
                                canSelect = true,
                                layerIndex = k,
                                gridIndex = v1:GetGridIndex(),
                                state = v1:GetStatus(),
                                moreInfo = v2.moreInfo,
                            }
                        end
                    else
                        printErrorN(string.format("no event cfg refId %s",v2.eventId))
                    end

                end
            end
        end
    end

    local eventInfo = nil
    if eventData then
        eventInfo = self:ParseTimeEventInfo(eventData.moreInfo)
    end

    return eventData,eventInfo
end

function ModelWonderland:IsTimeLordFinish(eventId)
    local timeEvent,eventInfo = self:GetTimeEvent()

    if eventInfo and eventInfo.idMap[eventId] then
        return true
    end

    return false
end

function ModelWonderland:GetRefreshCost(key,index)
    local parseFunc = function(value)
        return LxDataHelper.ParseItem_3List(value,';')
    end

    local costList = self:GetParaConfigValueImpl(ModelWonderland.DreamlandConfigRef,key,parseFunc)

    return costList[index]

end

function ModelWonderland:RefreshFormation(data)
    local layerIndex = data.layerIndex
    local gridIndex = data.gridIndex
    local eventId = data.eventId
    local moreInfo = string.format("%s|%s",layerIndex,gridIndex)

    if data.eventType == ModelWonderland.EVENT_TIME_LORD then
        return
    end
    local refreshFunc = function()
        self:WonderlandOpsReq(ModelWonderland.EVENT_REFRESH_MONSTER,moreInfo)
        self:WonderlandHeroMonsterReq(1,layerIndex,gridIndex,eventId)
    end

    local refreshMax = self:GetWonderlandPara("refreshNum")
    local refreshCnt = data.refreshCnt

    local curIndex= refreshMax - refreshCnt + 1

    local cost = self:GetRefreshCost("originRefreshExpend",curIndex)
    if cost then
        local itemNum = cost.itemNum
        if itemNum == 0 then
            refreshFunc()
        else
            local para =
            {
                refId = 70014,
                func = refreshFunc,
                para = {itemNum},
                consume = itemNum,
            }

            gModelGeneral:OpenUIOrdinTips(para)
        end
    end
end

function ModelWonderland:GetLordEffect()
    local parseFunc = function(value)
        return string.split(value,";")
    end

    local effList = self:GetParaConfigValueImpl(ModelWonderland.DreamlandConfigRef,'bossEffect',parseFunc)

    return effList
end

function ModelWonderland:IsBuffActivate(index)
    local key = "abyssActivate"..index
    local activeLayer = self:GetWonderlandPara(key)
    if self._maxLayerIndex >= activeLayer then
        return true
    end

    return false,activeLayer
end

function ModelWonderland:GetEventData(layerIndex,gridIndex,eventId)
    local grid = self:GetGridData(layerIndex,gridIndex)
    for k,v in ipairs(grid:GetEventList()) do
        if v.eventId == eventId then
            return v
        end
    end
end

function ModelWonderland:GetBgByPattern(pattern)
    local ref = self:GetModelConfig(ModelWonderland.DreamlandThemeRef)
    for k,v in pairs(ref) do
        if v.pattern == pattern then
            return v.auraIcon
        end
    end
end

function ModelWonderland:GetTreasureGroup(refId)
    local cfg = self:GetTreasureConfig(refId)
    if not cfg then
        return {}
    end
    local groupId = cfg.group
    local group = self._buffGroupList[groupId]

    if not group then
        return {}
    end

    table.sort(group,function (a,b)
        return a.lv<b.lv
    end)
    return group
end

function ModelWonderland:OnClickEntrance()
    local isInMap = self:IsInMap()
    if isInMap then
        local isFight = gLFightManager:IsCombatTypeInFight(LCombatTypeConst.COMBAT_WONDERLAND)
        if isFight then
            gLFightManager:PrepareGoToBattle(LCombatTypeConst.COMBAT_WONDERLAND)
            return
        end
        GF.OpenWndBottom("UIEden")
        self:EnterWonderMap()
    else
        GF.OpenWndBottom("UIEdenFront")
    end
end

-----------------------------------------------------------
---奇境弹窗管理



--清理工作
--停止计时器之类的
function ModelWonderland:OnModelClear()
    self._heroList={}
    self._treasureList={}
    self._hasFormation = false
end

function ModelWonderland:FormatWonderName(refId)
    local ref = self:GetThemeConfig(refId)
    local pattern = ref.pattern
    local patternName = nil
    if pattern == ModelWonderland.NORMAL then
        patternName = ccClientText(16793)
    elseif pattern == ModelWonderland.HARD then
        patternName = ccClientText(16794)
    else
        patternName = ccClientText(16795)
    end
    local name = string.format("%s[%s]",ccLngText(ref.name),patternName)
    return name
end

function ModelWonderland:AddReqProtect()
    self._reqTime = GetTimestamp()
end

function ModelWonderland:ReleaseReqProtect()
    self._reqTime = nil
end

function ModelWonderland:IsProtect()
    if not self._reqTime then
        return false
    end
    local timeLast = GetTimestamp() - self._reqTime
    if timeLast > 1 then
        return false
    end

    return true
end

function ModelWonderland:GetThemeByType(type,pattern)
    local ref = self:GetModelConfig(ModelWonderland.DreamlandThemeRef)
    for k,v in pairs(ref) do
        if v.type == type and v.pattern == pattern then
            return v
        end
    end
end

function ModelWonderland:CheckCanEnterType(themeType,showTip)
    if themeType > self._maxThemeType then
        if showTip then
            local themeCfg = self:GetThemeByType(self._maxThemeType,1)
            local format = ccLngText(self:GetWonderlandPara("themeOpenTips"))
            local str = string.replace(format,ccLngText(themeCfg.name))
            GF.ShowMessage(str)
        end

        return false
    end

    return true
end

function ModelWonderland:GetMaxThemeType()
    return self._maxThemeType or 1
end

function ModelWonderland:NotAllowRefreshType(eventType)
    if not self._notAllowMap then
        self._notAllowMap =
        {
            [ModelWonderland.EVENT_DEVIL] = true,
            [ModelWonderland.EVENT_QUEEN] = true,
            [ModelWonderland.EVENT_BOX_SELECT] = true,
            [ModelWonderland.EVENT_SPRITE] = true,
            [ModelWonderland.EVENT_WITCH] = true,
            [ModelWonderland.EVENT_TIME_LORD] = true,
        }
    end

    return self._notAllowMap[eventType]
end

function ModelWonderland:GetMaxUnlockPattern()
    local pattern = ModelWonderland.NORMAL
    if gModelFunctionOpen:CheckIsOpened(ModelFunctionOpen.WONDER_HARD) then
        pattern = ModelWonderland.HARD
    end
    if gModelFunctionOpen:CheckIsOpened(ModelFunctionOpen.WONDER_TOUGH) then
        pattern = ModelWonderland.TOUGH
    end
    return pattern
end

function ModelWonderland:GetEventInfoByType(eventType)
    local eventInfoMap = self._eventInfoByType
    if not eventInfoMap then
        eventInfoMap = {}
        self._eventInfoByType = eventInfoMap
    end

    local eventInfo = eventInfoMap[eventType]
    if eventInfo then
        return eventInfo
    end
    local WonderEventRef = self:GetModelConfig(ModelWonderland.DreamlandEventRef)
    for k,v in pairs(WonderEventRef) do
        eventInfoMap[v.type] = v
    end

    return eventInfoMap[eventType]
end

function ModelWonderland:IsEvilAwakeTimeChange()
    local oldTimes = self._oldAwakeTimes or 0
    local newTimes = self:GetItemNum(200005)
    if oldTimes ~= newTimes then
        self._oldAwakeTimes = newTimes
        return true
    end

    return false
end

return ModelWonderland