---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 14:40
---
------------------------------------------------------------------
---模块使用示例 需要在LModelManager的列表里填写名字
---创建完之后可以使用gModelFunctionOpen全局变量访问实例
------------------------------------------------------------------

local LModel = LModel
------------------------------------------------------------------
---@class ModelFunctionOpen:LModel
local ModelFunctionOpen = LxClass("ModelFunctionOpen", LModel)

ModelFunctionOpen.FeatureOpenRef = "FeatureOpenRef"
ModelFunctionOpen.FeaturePreviewAllRef = "FeaturePreviewAllRef"
ModelFunctionOpen.FeaturePreviewScrollRef = "FeaturePreviewScrollRef"
ModelFunctionOpen.FeaturePreviewConfigRef = "FeaturePreviewConfigRef"
ModelFunctionOpen.FeatureOpenAreaRef = "FeatureOpenAreaRef"
ModelFunctionOpen.FeatureOpenAreaSublistRef = "FeatureOpenAreaSublistRef"

ModelFunctionOpen.QUICK = 10401111      --快速特权
ModelFunctionOpen.EXCLUSIVE = 10401121  --专属特权
ModelFunctionOpen.EXPLORE = 10401131    --探索特权
ModelFunctionOpen.LIFELONG = 10401141   --终身特权
ModelFunctionOpen.PUMPKIN = 10401151    --南瓜特权
ModelFunctionOpen.TDQUICK = 10401181    --童话镇特权


ModelFunctionOpen.WONDER_HARD = 16800030 --奇境困难模式
ModelFunctionOpen.WONDER_TOUGH = 16800040 --奇境深渊模式

ModelFunctionOpen.DREAMTRIP_ENTER = 17100010

ModelFunctionOpen.INVASION = 18200000 --异界入侵

ModelFunctionOpen.RANK_TOWER = 11901300 --排行榜——试炼之藤
ModelFunctionOpen.RANK_ENDLESS = 11903400 --排行榜——无尽试炼
ModelFunctionOpen.RANK_AREA = 11901400 --排行榜——竞技场

ModelFunctionOpen.ENDLESS = 16302000 --无尽试炼

ModelFunctionOpen.GUILDBATTLE = 12106000 --联盟混战
ModelFunctionOpen.GUILDTREASURE = 12107000 --联盟宝库
ModelFunctionOpen.GUILDTRBOSS = 12108000 --联盟领主

ModelFunctionOpen.EXPLORE_TASK = 12300000

-- ModelFunctionOpen.ONE_NIGHT = 21000000 --一千零一夜

-- 【C宠物系统】删掉宠物系统相关
-- ModelFunctionOpen.PET_SPACE = 36000001 --宠物入口
-- ModelFunctionOpen.PET_COMPOUND = 36001000 --宠物合成
-- ModelFunctionOpen.PET_BATTLE = 36002000 --宠物上阵



ModelFunctionOpen.HalidomDraw = 34000001            ---- 圣物召唤功能
ModelFunctionOpen.HalidomBook = 34000002            ---- 圣物图鉴功能

ModelFunctionOpen.PET_DREAMLAND = 13910000          ---- 萌宠幻境
ModelFunctionOpen.PET_DLCALL = 13911000             ---- 萌宠签订


--地区屏蔽
ModelFunctionOpen.ITEM = 1
ModelFunctionOpen.QUEST = 2
ModelFunctionOpen.MAILNOTICE = 3
ModelFunctionOpen.MAIL = 4
ModelFunctionOpen.RANKING = 5
ModelFunctionOpen.FORESHOW = 6
ModelFunctionOpen.FORESHOWRLAY = 7
ModelFunctionOpen.FORESHOWALL = 8
ModelFunctionOpen.ITEMBAGTAB = 9
ModelFunctionOpen.ROLEPALYERHEAD = 10

ModelFunctionOpen.EntranceType = {}
ModelFunctionOpen.EntranceType.Activity = 1
ModelFunctionOpen.EntranceType.Func = 2

------------------------------------------------------------------
function ModelFunctionOpen:ModelFunctionOpen()

end

--模块初始化入口
--注册事件监听
--注册协议监听
--预处理数据

function ModelFunctionOpen:OnModelInit()

    -- self._prePostHideConList = {}【G功能预告】删除玩法预告机制（客户端&服务端
    -- self._prePostShowConList = {}【G功能预告】删除玩法预告机制（客户端&服务端
    self._functionOpenCache = {}
    -- self._preFuncOpenRecord = {}【G功能预告】删除玩法预告机制（客户端&服务端

    self._preFuncPlayMap = {}

    self:ParseConfig()
    --self._privilegeParas=
    --{
    --    [ModelFunctionOpen.EXPLORE] = 1,
    --    [ModelFunctionOpen.QUICK] = 2,
    --    [ModelFunctionOpen.EXCLUSIVE] = 3,
    --    [ModelFunctionOpen.LIFELONG] = 4,
    --    [ModelFunctionOpen.PUMPKIN] = 5,
    --    [ModelFunctionOpen.TDQUICK] = 8,
    --}

    self._checkFuncs = {
        [1] = function(...)
            return self:CheckPlayerLv(...)
        end, ---玩家等级
        [2] = function(...)
            return self:CheckBattleNum(...)
        end, ---通关的主线关卡数
        [3] = function(...)
            return self:CheckVipLv(...)
        end, ---vip等级
        [4] = function(...)
            return self:CheckWorldLv(...)
        end, ---世界等级
        [5] = function(...)
            return self:CheckInGuild(...)
        end, ---是否有公会
        [6] = function(...)
            return self:CheckHasActivity(...)
        end, ---是否有活动
        [7] = function(...)
            return self:CheckIsEndles(...)
        end, ---无尽试炼层数
        [8] = function(...)
            return self:CheckIsTower(...)
        end, ---试炼之藤层数
        [9] = function(...)
            return self:CheckCreateDay(...)
        end, ---创角天数
        [10] = function(...)
            return self:CheckMaxPower(...)
        end, ---历史最高战力
        [11] = function(...)
            return self:CheckServerOpenInter(...)
        end, ---开服天数
        [12] = function(...)
            return self:CheckTaskFinish(...)
        end, ---任务完成
        [13] = function(...)
            return self:CheckPlayOpen(...)
        end, ---限时玩法开启
        [14] = function(...)
            return self:CheckGuildLv(...)
        end, ---公会等级
        [15] = function(...)
            return self:CheckBattleNumOfBrave(...)
        end, ---玩家勇者试炼关卡数达到N
        [16] = function(...)
            return self:CheckBattleNumOfHero(...)
        end, ---玩家英雄试炼关卡数达到N
        [17] = function(...)
            return self:CheckDate(...)
        end, ---服务器日期

        [19] = function(...)
            return self:CheckDYOpt(...)
        end, ---抖音侧边栏

        [20] = function(...)
            return self:CheckRecharge(...)
        end, ---充值判断

    }

    self._checkOpenTipsFuncs = {
        [1] = function(...)
            return self:IsMeetPlayerLv(...)
        end, ---玩家等级
        [2] = function(...)
            return self:IsMeetBattleNum(...)
        end, ---通关的主线关卡数
        [3] = function(...)
            return self:IsMeetVipLv(...)
        end, ---vip等级
        [4] = function(...)
            return self:IsMeetWorldLv(...)
        end, ---世界等级
        [5] = function(...)
            return self:IsMeetInGuild(...)
        end, ---是否有公会
        [6] = function(...)
            return self:IsMeetHasActivity(...)
        end, ---是否有活动
        [7] = function(...)
            return self:IsMeetEndles(...)
        end, ---无尽试炼层数
        [8] = function(...)
            return self:IsMeetTower(...)
        end, ---试炼之藤层数
        [9] = function(...)
            return self:IsMeetCreateDay(...)
        end, ---创角天数
        [10] = function(...)
            return self:IsMeetMaxPower(...)
        end, ---历史最高战力
        [11] = function(...)
            return self:IsMeetServerOpen(...)
        end, ---开服天数
        [12] = function(...)
            return self:IsMeetTaskFinish(...)
        end, ---任务完成
        [15] = function(...)
            return self:IsMeetBattleNumBrave(...)
        end, ---玩家勇者试炼关卡数达到N
        [16] = function(...)
            return self:IsMeetBattleNumHero(...)
        end, ---玩家英雄试炼关卡数达到N
    }

    self._noCacheType = {
        [5] = true,
        [6] = true,
        [12] = true,
        [13] = true,
        [14] = true,
    }

    self._checkFuncPre = {
        [1] = function(...)
            return self:CheckPlayerLv(...)
        end,
        [2] = function(...)
            return self:CheckServerOpen(...)
        end,
        [3] = function(...)
            return self:CheckBattleNum(...)
        end,

    }

    self:ModelEventRecv(EventNames.ON_SHIELD_UPDATE, function()
        if self._isParseConfig then
            self:ParseConfig()
        end
    end)

    self:ModelEventRecv(EventNames.ON_PLAYER_LEVEL_CHANGE, function(oldLv, newLv)
        -- self:RefreshPrePostList()【G功能预告】删除玩法预告机制（客户端&服务端）
        self:OnRangeParaCheck(1, oldLv, newLv)
    end)
    self:ModelEventRecv(EventNames.ON_BATTLE_NUM_CHANGE, function()
        -- self:RefreshPrePostList()【G功能预告】删除玩法预告机制（客户端&服务端）

        local battleNum = gModelInstance:GetPassedBattleNum()
        self:OnPointParaCheck(2, { battleNum })
    end)
    self:ModelEventRecv(EventNames.PLAYER_VIP_LEVEL_CHANGE, function(oldLv, newLv)
        self:OnRangeParaCheck(3, oldLv, newLv)
    end)
    self:ModelEventRecv(EventNames.ON_WORLD_LEVEL_CHANGE, function(oldLv, newLv)
        self:OnRangeParaCheck(4, oldLv, newLv)
    end)
    self:ModelEventRecv(EventNames.ON_IN_GUILD_CHANGE, function()
        self:OnFunctionOpenStateChange()
    end)
    self:ModelEventRecv(EventNames.ON_ACTIVITY_MODELCHANGE, function(list)
        self:OnPointParaCheck(6, list)
    end)
    self:ModelEventRecv(EventNames.ON_ENDLESS_NODE_CHANGE, function(para)
        self:OnPointParaCheck(7, { para })
    end)
    self:ModelEventRecv(EventNames.ON_TOWER_FLOOR_CHANGE, function(para)
        self:OnPointParaCheck(8, { para })
    end)
    self:ModelEventRecv(EventNames.ON_MAIN_MAX_POWER_CAHNGE, function(para)
        self:OnPointParaCheck(10, { para })
    end)
    self:ModelEventRecv(EventNames.ON_TASK_FINISH, function(list)
        self:OnPointParaCheck(12, list)
    end)

    self:ModelEventRecv(EventNames.ON_TIME_ZERO, function()
        -- self:RefreshPrePostList()【G功能预告】删除玩法预告机制（客户端&服务端）

        local dayPast = gModelPlayer:GetCreateDay()
        self:OnPointParaCheck(9, { dayPast })

        local serverOpenPast = gLGameLogin:GetServerOpenDay()
        self:OnPointParaCheck(11, { serverOpenPast })
    end)

    self:ModelNetMsgRecv(LProtoIds.ForeRewardResp, function(...)
        self:OnForeRewardResp(...)
    end)
    self:ModelNetMsgRecv(LProtoIds.ForeRewardListResp, function(...)
        self:OnForeRewardListResp(...)
    end)
    self:ModelNetMsgRecv(LProtoIds.ScrollNoticeResp, function(...)
        self:OnScrollNoticeResp(...)
    end)

    self:ModelNetMsgRecv(LProtoIds.ForeshowPopResp,function(...)
        self:OnForeshowPopResp(...)
    end)

end

function ModelFunctionOpen:OnForeRewardListReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.ForeRewardListReq)
    SendMessage(pb, LProtoIds.ForeRewardListReq)
end

function ModelFunctionOpen:OnForeRewardListResp(pb)
    local dataMap = {}
    for k, v in ipairs(pb.foreId) do
        dataMap[v] = true
    end

    self._receiveForeIdMap = dataMap
    FireEvent(EventNames.ON_FORE_FUNCTION_REWARDED)
end

function ModelFunctionOpen:OnForeRewardReq(foreId)
    local pb = LProtoHelper.CreateProto(LProtoIds.ForeRewardReq)
    pb.foreId:append(foreId)
    SendMessage(pb, LProtoIds.ForeRewardReq)
end

function ModelFunctionOpen:OnForeRewardResp(pb)
    local dataMap = {}
    for k, v in ipairs(pb.receiveForeId) do
        dataMap[v] = true
    end

    self._receiveForeIdMap = dataMap
    FireEvent(EventNames.ON_FORE_FUNCTION_REWARDED)
end

function ModelFunctionOpen:OnScrollNoticeResp(pb)
    self._preFuncPlayMap = {}
    for k, v in ipairs(pb.notice) do
        self._preFuncPlayMap[v.type] = v
    end
    FireEvent(EventNames.ON_PRE_FUNC_PLAY)
end
--設置當天不彈出
function ModelFunctionOpen:OnForeshowPopRecrodReq(refId)
    local pb = LProtoHelper.CreateProto(LProtoIds.ForeshowPopRecrodReq)
    pb.refId = refId
    SendMessage(pb,LProtoIds.ForeshowPopRecrodReq)
end
function ModelFunctionOpen:OnForeshowPopResp(pb)
    local foreshowMap = {}
    if not self._foreshowPopList then 
        self._foreshowPopList = {}
    else
        for index, info in ipairs(self._foreshowPopList) do
            foreshowMap[info.refId] = index
        end
    end
    for k, v in ipairs(pb.foreshowPops or {}) do
        local indx = foreshowMap[v.refId]
        if indx then 
            self._foreshowPopList[indx] = {refId =v.refId,isPop = v.isPop ,endTime = tonumber(v.endTime)}
        else
            table.insert(self._foreshowPopList,{refId =v.refId,isPop = v.isPop ,endTime = tonumber(v.endTime)})
        end
    end
end


--在协议数据处理完之后需要调用finish
function ModelFunctionOpen:OnModelRequest()
    self:InitData()
    -- self:RecordPreFuncOpen()【G功能预告】删除玩法预告机制（客户端&服务端
    -- self:RefreshPrePostList()【G功能预告】删除玩法预告机制（客户端&服务端）

    -- self:InsertPrePost()【G功能预告】删除玩法预告机制（客户端&服务端）

    self:OnForeRewardListReq()

    self:ModelFinish()
end

function ModelFunctionOpen:InitData()
    self._functionOpenCache = {}
    -- self._preFuncOpenRecord = {}【G功能预告】删除玩法预告机制（客户端&服务端
end

function ModelFunctionOpen:OnRangeParaCheck(type, oldPara, newPara)
    if not self._isFinished then
        return
    end

    local checkMap = self._checkMapByType[type]
    if not checkMap then
        return
    end

    for i = oldPara + 1, newPara do
        if checkMap[i] then
            self:OnFunctionOpenStateChange()
            return
        end
    end
end

function ModelFunctionOpen:OnPointParaCheck(type, paraList)
    if not self._isFinished then
        return
    end

    local checkMap = self._checkMapByType[type]
    if not checkMap then
        return
    end

    for k, v in ipairs(paraList) do
        if checkMap[v] then
            self:OnFunctionOpenStateChange()
            return
        end
    end
end

function ModelFunctionOpen:OnFunctionOpenStateChange()
    if not self._isFinished then
        return
    end
    FireEvent(EventNames.REFRESH_FUNCTION_STATE)
    printInfoN(" ------ EventNames.REFRESH_FUNCTION_STATE")
    -- self:CheckPreFuncOpen()【G功能预告】删除玩法预告机制（客户端&服务端
    -- self:RecordPreFuncOpen()【G功能预告】删除玩法预告机制（客户端&服务端
end

function ModelFunctionOpen:GetFunctionOpenCfg(refId)
    return GameTable.FeatureOpenRef[refId]
end

function ModelFunctionOpen:ParseConfig()
    self._isParseConfig = true


    self._pathToId = {}
    self._groupFunctions = {}
    self._extraConditions = {}
    self._btnIndexs = {}

    self._openConditions = {}
    self._otherOpenCondition = {}

    self._checkMapByType = {}

    for k, v in pairs(GameTable.FeatureOpenRef) do
        local path = v.uiLevel
        local refId = v.refId
        self._pathToId[path] = refId

        local group = v.frameGroup
        if group > 0 then
            local dataList = self._groupFunctions[group]
            if not dataList then
                dataList = {}
                self._groupFunctions[group] = dataList
            end

            table.insert(dataList, refId)
        end

        local btnIndex = v.btnIndex
        self._btnIndexs[k] = self:ParseBtnIndex(btnIndex)

        local open = v.open
        local condition = self:ParseCondition(open)
        self._openConditions[k] = condition
        local otherOpen = v.otherOpen
        local otherCondition = self:ParseCondition(otherOpen)
        self._otherOpenCondition[k] = otherCondition

        for k, v in ipairs(condition) do
            local type = v.type
            local para = v.para
            local checkMap = self._checkMapByType[type]
            if not checkMap then
                checkMap = {}
                self._checkMapByType[type] = checkMap
            end

            checkMap[para] = true
        end

        for k, v in ipairs(otherCondition) do
            local type = v.type
            local para = v.para
            local checkMap = self._checkMapByType[type]
            if not checkMap then
                checkMap = {}
                self._checkMapByType[type] = checkMap
            end

            checkMap[para] = true
        end


    end

end

function ModelFunctionOpen:GetFuncOpenCondition(refId)
    return self._openConditions[refId]
end

function ModelFunctionOpen:GetRefIdByPath(path)
    local funcId = self._pathToId[path]
    return funcId
end

function ModelFunctionOpen:CheckIsShow(refId)
    --if refId == 10303000 then return true end

    local isAreaOpen = self:CheckAreaOpen(refId)
    if not isAreaOpen then
        local refItem = self:GetAreaOpenRef(refId)
        return refItem.show == 1
    end
    if not self:CheckIsOpenRes(refId) then
        return false
    end
    local isOpen = self:CheckIsOpened(refId)
    if not isOpen then
        local cfg = GameTable.FeatureOpenRef[refId]
        if cfg then
            return cfg.show == 1
        end
    end

    return true
end

--function ModelFunctionOpen:GetShowStatus(refId)
--    local cfg = GameTable.FeatureOpenRef[refId]
--    if not cfg then return 0 end
--    return cfg.show
--end

--function ModelFunctionOpen:GetIsShowStatus(refId)
--    local show = self:GetShowStatus(refId)
--    return show == 1
--end

function ModelFunctionOpen:GetOpenTips(refId)
    local cfg = GameTable.FeatureOpenRef[refId]
    if not cfg then
        return ""
    end

    local msg = ccLngText(cfg.openDesc)
    return msg
end

function ModelFunctionOpen:GetOpenLv(refId)
    local cfg = GameTable.FeatureOpenRef[refId]
    if not cfg or cfg.open == "" then
        return 0
    end
    local openArr = string.split(cfg.open, "=")
    return tonumber(openArr[2])
end

function ModelFunctionOpen:CheckIsOpened(refId, showTip)
    --if refId == 10303000 then return true end
    if not self:CheckAreaOpen(refId, showTip) then
        return
    end

    local cfg = GameTable.FeatureOpenRef[refId]
    if not cfg then
        return false, ''
    end

    if not self._functionOpenCache then
        self._functionOpenCache = {}
    end

    local cache = self._functionOpenCache[refId]
    if cache then
        return cache
    end

    local noCache = false
    local conditions = self._openConditions[refId]

    local extraParaList = LxDataHelper.ParseNumber_Sign(cfg.btnIndex, ',')
    local uniqueJump = extraParaList[3]
    local isOpen = true
    for k, v in ipairs(conditions) do
        local type = v.type

        local para = v.para

        if not noCache then
            noCache = self._noCacheType[type]
        end

        local checkFunc = self._checkFuncs[type]
        if checkFunc then
            isOpen = checkFunc(para, uniqueJump)
            if not isOpen then
                break
            end
        end
    end

    if isOpen then
        isOpen = self:CheckIsOpenRes(refId)
    end

    if not isOpen then

        local otherConditions = self._otherOpenCondition[refId]
        if #otherConditions > 0 then
            isOpen = true
            for k, v in ipairs(otherConditions) do
                local type = v.type
                local para = v.para

                if not noCache then
                    noCache = self._noCacheType[type]
                end

                local checkFunc = self._checkFuncs[type]
                if checkFunc then
                    isOpen = checkFunc(para, uniqueJump)
                    if not isOpen then
                        break
                    end
                end
            end
        end
    end

    if refId == ModelFunctionOpen.WONDER_HARD then
        local isPass = gModelWonderland:CheckSelectPattern(ModelWonderland.HARD)
        isOpen = isOpen and isPass
    elseif refId == ModelFunctionOpen.WONDER_TOUGH then
        local isPass = gModelWonderland:CheckSelectPattern(ModelWonderland.TOUGH)
        isOpen = isOpen and isPass
    end

    --if isOpen then
    --    if refId == ModelFunctionOpen.DREAMTRIP_ENTER then
    --        isOpen = gModelFastDreamTrip:CheckIsOpenDay()
    --    end
    --end

    local msg = ccLngText(cfg.openDesc)
    if not isOpen and showTip then

        GF.ShowMessage(msg)
    end


    local useCache = true
    if not string.isempty(cfg.resOpen) then
        useCache = false
    end
    if isOpen and not noCache and useCache then
        self._functionOpenCache[refId] = true
    end

    return isOpen, msg
end


function ModelFunctionOpen:CheckCondition(open)
    local conditions = self:ParseCondition(open)
    local isOpen = true
    for k, v in ipairs(conditions) do
        local type = v.type

        local para = v.para

        if not noCache then
            noCache = self._noCacheType[type]
        end

        local checkFunc = self._checkFuncs[type]
        if checkFunc then
            isOpen = checkFunc(para, uniqueJump)
            if not isOpen then
                break
            end
        end
    end


end

function ModelFunctionOpen:CheckPlayerLv(para)
    local lv = gModelPlayer:GetPlayerLv()
    return lv >= para
end

function ModelFunctionOpen:IsMeetPlayerLv(para)
    local lv = gModelPlayer:GetPlayerLv()
    local meet = lv >= para
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25501), para)
    end
    return meet, str
end

function ModelFunctionOpen:CheckVipLv(para)
    local lv = gModelPlayer:GetVipLevel()
    return lv >= para
end

function ModelFunctionOpen:IsMeetVipLv(para)
    local lv = gModelPlayer:GetVipLevel()
    local meet = lv >= para
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25503), para)
    end
    return meet, str
end

function ModelFunctionOpen:CheckWorldLv(para)
    local lv = gModelPlayer:GetWorldLevel()
    return lv >= para
end

function ModelFunctionOpen:IsMeetWorldLv(para)
    local lv = gModelPlayer:GetWorldLevel()
    local meet = lv >= para
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25504), para)
    end
    return meet, str
end

function ModelFunctionOpen:CheckBattleNum(para)
    return self:CheckBattleNumByDiffLvl(para, 1)
end
function ModelFunctionOpen:CheckBattleNumOfBrave(para)
    return self:CheckBattleNumByDiffLvl(para, 2)
end
function ModelFunctionOpen:CheckBattleNumOfHero(para)
    return self:CheckBattleNumByDiffLvl(para, 3)
end

function ModelFunctionOpen:CheckDate(para)

    local sign = string.sub(para, 1, 1)
    local year, month, day

    local isBefore
    if sign == "-" then
        isBefore = true
        year = tonumber(string.sub(para, 2, 5))
        month = tonumber(string.sub(para, 6, 7))
        day = tonumber(string.sub(para, 8, 9))
    else
        isBefore = false
        year = tonumber(string.sub(para, 1, 4))
        month = tonumber(string.sub(para, 5, 6))
        day = tonumber(string.sub(para, 7, 8))
    end

    local date = LUtil.OSDate("*t", GetTimestamp())
    local curYear = date.year
    local curMonth = date.month
    local curDay = date.day

    if isBefore then
        if curYear > year then
            return false
        elseif curYear == year then
            if curMonth > month then
                return false
            elseif curMonth == month then
                if curDay > day then
                    return false
                end
            end
        end
    else
        if curYear < year then
            return false
        elseif curYear == year then
            if curMonth < month then
                return false
            elseif curMonth == month then
                if curDay < day then
                    return false
                end
            end
        end
    end

    return true
end

function ModelFunctionOpen:CheckDYOpt(para)
    local typeNum = checknumber(para) or 0
    if typeNum == 1 then
        local IsCanShowScene = gLSdkImpl and gLSdkImpl:CallMethod(LSdkMethod.IsCanShowScene)
        if LOG_INFO_ENABLED then
            local openStr = IsCanShowScene and "1" or "0"
            printInfo("ModelFunctionOpen", "是否可以显示侧边栏相关功能 "..openStr)
        end
        -- 是否可以显示侧边栏相关功能
        return IsCanShowScene
    end
    return true
end

function ModelFunctionOpen:CheckRecharge(para)
    local recharge = checknumber(para) or 0
    recharge = recharge * 100
    local chargeMoney = gModelPlayer:GetChargeMoney() or 0
    return chargeMoney >= recharge
end

function ModelFunctionOpen:CheckBattleNumByDiffLvl(para, diffLvl)
    local battleNum = gModelInstance:GetBattleNum(diffLvl)
    local battleNode = gModelInstance:GetRawBattleNode()
    return battleNum > para or (battleNum >= para and battleNode == -1)
end

function ModelFunctionOpen:IsMeetBattleNum(para)
    self:IsMeetBattleNumByDiffLvl(para, 1)
end
function ModelFunctionOpen:IsMeetBattleNumBrave(para)
    self:IsMeetBattleNumByDiffLvl(para, 2)
end
function ModelFunctionOpen:IsMeetBattleNumHero(para)
    self:IsMeetBattleNumByDiffLvl(para, 3)
end

function ModelFunctionOpen:IsMeetBattleNumByDiffLvl(para, diffLvl)
    local battleNum = gModelInstance:GetPassedBattleNum(diffLvl)
    local meet = battleNum >= para
    local str = ""
    if not meet then
        local chapterId = gModelInstance:GetMissionChapterIdByNum(para, diffLvl)--获取关卡的名字
        local nameWorld = chapterId .. "-" .. para
        str = string.replace(ccClientText(34609), nameWorld)
    end
    return meet, str
end

function ModelFunctionOpen:CheckInGuild()
    local hasGuild = gModelGuild:GetBHaveGuild()
    return hasGuild
end

function ModelFunctionOpen:IsMeetInGuild(para)
    local meet = gModelGuild:GetBHaveGuild()
    local str = ""
    if not meet then
        str = ccClientText(25505)
    end
    return meet, str
end

function ModelFunctionOpen:CheckHasActivity(para, uniqueJump)
    local hasActivity = gModelActivity:ExistActivity(para, uniqueJump)
    return hasActivity
end

function ModelFunctionOpen:IsMeetHasActivity(para)
    local meet = gModelActivity:ExistActivity(para)
    local str = ""
    if not meet then
        str = ccClientText(25506)
    end
    return meet, str
end

function ModelFunctionOpen:CheckIsEndles(para)
    local maxNode = gModelEndles:GetMaxNode()
    return maxNode >= para
end

function ModelFunctionOpen:IsMeetEndles(para)
    local maxNode = gModelEndles:GetMaxNode()
    local meet = maxNode >= para
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25507), para)
    end
    return meet, str
end

function ModelFunctionOpen:CheckServerOpen(para, isSame)
    local day = tonumber(para)
    local dayPast = gLGameLogin:GetServerOpenDay()
    if isSame then
        return dayPast > day
    else
        return dayPast >= day
    end
end

function ModelFunctionOpen:CheckServerOpenInter(para)
    return self:CheckServerOpen(para)
end

function ModelFunctionOpen:IsMeetServerOpen(para)
    local day = tonumber(para)
    local dayPast = gLGameLogin:GetServerOpenDay()
    local meet = dayPast >= day
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25511), day)
    end
    return meet, str
end

function ModelFunctionOpen:CheckTaskFinish(taskId)
    return gModelQuest:IsTaskFinish(taskId)
end

function ModelFunctionOpen:IsMeetTaskFinish(taskId)
    local meet = gModelQuest:IsTaskFinish(taskId)
    local str = ""
    if not meet then
        local taskName = gModelQuest:GetTaskDescByRefId(taskId)
        str = string.replace(ccClientText(25512), taskName)
    end
    return meet, str
end

function ModelFunctionOpen:CheckPlayOpen(playenum)
    local enum = tonumber(playenum)
    if enum == 1 then
        return gModelSimuFight:IsSimulateRunning()
    elseif enum == 2 then
        -- return gModelBackflow:IsActivityOpen()
        return gModelRegression:IsOpenRegression()
    elseif enum == 3 then
        -- 【G公共支持】删除暗黑战争相关数据
        -- return gModelDarkWar:IsOpen()
    end
end
function ModelFunctionOpen:CheckGuildLv(para)
    local guildLv = tonumber(para)
    local has = gModelGuild:GetBHaveGuild()
    local guildInfo = gModelGuild:GetGuildInfo()
    if not has or not guildInfo then
        return false
    end
    local level = guildInfo.level
    return level >= guildLv
end

function ModelFunctionOpen:CheckIsTower(para)
    local node = tonumber(para)
    local layer = gModelTower:GetTasLayer(1)
    if not layer then
        return false
    end
    if (layer < node) then
        return false
    end
    return true
end

function ModelFunctionOpen:IsMeetTower(para)
    local node = tonumber(para)
    local layer = gModelTower:GetTasLayer(1)
    local meet = layer and layer > node or false
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25508), node)
    end
    return meet, str
end

function ModelFunctionOpen:CheckCreateDay(para)
    local day = tonumber(para)
    local dayPast = gModelPlayer:GetCreateDay()
    return dayPast >= day
end

function ModelFunctionOpen:IsMeetCreateDay(para)
    local day = tonumber(para)
    local dayPast = gModelPlayer:GetCreateDay()
    local meet = dayPast >= day
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25509), day)
    end
    return meet
end

function ModelFunctionOpen:CheckMaxPower(para)
    local power = tonumber(para)
    local maxPower = gModelPower:GetMaxMainPower()
    return maxPower >= power
end

function ModelFunctionOpen:IsMeetMaxPower(para)
    local power = tonumber(para)
    local maxPower = gModelPower:GetMaxMainPower()
    local meet = maxPower >= power
    local str = ""
    if not meet then
        str = string.replace(ccClientText(25510), LUtil.PowerNumberCoversion(power))
    end
    return meet, str
end

function ModelFunctionOpen:GetFunctionName(refId)
    local ref = GameTable.FeatureOpenRef[refId]
    if refId then
        return ccLngText(ref.name)
    end
    return ""
end

function ModelFunctionOpen:ParseCondition(str)
    if string.isempty(str) then
        return {}
    end
    local conditions = {}
    local strs = string.split(str, ",")
    for k, v in ipairs(strs) do
        local temp = string.split(v, '=')
        if #temp == 2 then
            local type = tonumber(temp[1])
            local para = tonumber(temp[2])
            local data = {
                type = type,
                para = para,
            }
            table.insert(conditions, data)
        end
    end

    return conditions
end

function ModelFunctionOpen:ModifyFunc(rootName, tran, func)
    local modifyFun = func
    local path = nil
    if self:IsFinished() then
        path = LxUiHelper.GetRelativePath(rootName, tran)
        if path then
            local functionRefId = self:GetRefIdByPath(path)
            if functionRefId then
                modifyFun = function()
                    if self:CheckIsOpened(functionRefId, true) then
                        if func then
                            func()
                        end

                        gModelRedPoint:OnClickFunc(functionRefId) --点击消失的红点处理
                    end
                end
            end
        end
    end

    return modifyFun
end

function ModelFunctionOpen:Jump(functionOpenId, srcWnd, func, para)
    if LOG_INFO_ENABLED then
        printInfoN(string.format("function jump refId %s", tostring(functionOpenId)))
    end
    if not functionOpenId then
        return
    end
    local cfg = GameTable.FeatureOpenRef[functionOpenId]
    if not cfg then
        if LOG_INFO_ENABLED then
            printInfoN("not functionOpenRef refId" .. functionOpenId)
        end
        return
    end

    local isOpen = self:CheckIsOpened(functionOpenId, true)
    if not isOpen then
        if LOG_INFO_ENABLED then
            printInfoN("function not open" .. functionOpenId)
        end
        return
    end

    local map = cfg.map    -- 地图名    LCityMap,LFightIdleMap,LSuburbMap,LFightMap
    local pagePara = self:ModifyWndPara(functionOpenId)
    local wndName = cfg.wndName  -- 界面名
    local combatTypeList = self:GetFuncRelaCombat(functionOpenId)

    local sensitiveList = {
        ["UISayAirWin"] = true,
        ["UISayPop"] = true,
        ["UISayFlow"] = true,
        ["UISagaComment"] = true,
        ["UIBulletSaySendPop"] = true,
        ["UIInvasionSay"] = true,
    }
    if sensitiveList[wndName] then
        local sensitive = gModelPlayer:GetChatForbid(ModelPlayer.SENSITIVE_TYPE_1)
        if not sensitive then
            GF.ShowMessage(ccClientText(30800))
            return
        end
    end


    -- 个人信息界面需要请求信息后打开
    --if wndName == "UIPersonAreaWin" then
    --	local playerId = gModelPlayer:GetPlayerId()
    --	gModelPlayerSpace:OpenSpaceWnd(playerId)
    --	return
    --end

    local skipSave = false
    local uilayer = cfg.uilayer    -- 界面层级
    local jumpType = cfg.jumpType
    if jumpType == 10 then
        --- 侧边栏跳转
        gLSdkImpl:CallMethod(LSdkMethod.NavigateToScene)
        return
    end
    
    
    if jumpType == 3 then
        if functionOpenId ~= 12100000 then
            local has = gModelGuild:GetBHaveGuild()
            if not has then
                local str = ccClientText(12567)
                GF.ShowMessage(str)
                return
            end
        end
    -- elseif jumpType == 4 then
    --     local isInMap = gModelWonderland:IsInMap()

    --     if functionOpenId == 16800010 then
    --         if not isInMap then
    --             return
    --         end
    --     elseif functionOpenId == 16800020 then
    --         if isInMap then
    --             return
    --         end
    --     end

    --     local temp = isInMap and "UIEden" or "UIEdenFront"
    --     gLGameUI:SaveBackWnd(temp)
    --     skipSave = true
    elseif jumpType == 4 then
        --map = ""
        skipSave = true
    elseif jumpType == 8 then
        skipSave = true
    end

    if not skipSave then
        gLGameUI:SaveBackWnd(wndName)
    end

    FireEvent(EventNames.ON_JUMP)

    local mainBtnIndex = pagePara.mainIndex or 0
    local page = pagePara.page or 0
    local subPage = pagePara.subPage or 0

    local isFight = false
    local combatType = nil
    for k, v in pairs(combatTypeList) do
        isFight = gLFightManager:IsCombatTypeInFight(k)
        if isFight then
            combatType = k
            break
        end
    end

    local exceptsWnd = {}    --需要保留的界面

    if jumpType == 1 and srcWnd then
        self:AddWndRecord(exceptsWnd, srcWnd)
    end

    if isFight then
        gLFightManager:PrepareGoToBattle(combatType, {})
        self:AddWndRecord(exceptsWnd, "UIFight")
        return exceptsWnd, true
    else
        if not string.isempty(map) then
            if GF.GetCurMap():IsSameMap(map) and map == "LFightIdleMap" then
            else
                GF.ChangeMap(map)
            end
        end

        local jumpMapPos = cfg.jumpMapPos --主场景跳转至指定坐标
        local curMap = GF.GetCurMap()

        if not string.isempty(jumpMapPos) then
            local pos = LxDataHelper.ParseVector(jumpMapPos)
            if curMap and curMap.MoveCamera then
                curMap:MoveCamera(pos, nil, 0)
            end
        end

        local isIgnore = false
        local closeWndList = {}  --需要关闭的界面
        local closeAll = false   --是否清理全部界面
        if jumpType == 2 then
            self:AddWndRecord(closeWndList, srcWnd)
        elseif jumpType == 3 then
            if not gModelGuild:GetBHaveGuild() then
                --local wndSeekPop = gLGameLanguage:IsUSARegion() and "UIGdSeekPopEn" or "UIGdSeekPop"
                local wndSeekPop = "UIGdSeekPop"
                GF.OpenWndBottom(wndSeekPop)
                isIgnore = true
                self:AddWndRecord(exceptsWnd, wndSeekPop)
            end
        elseif jumpType == 4 then
            -- if functionOpenId == 16800000 then
            --     local isInMap = gModelWonderland:IsInMap()
            --     if isInMap then
            --         --gLGameUI:SaveBackWnd("UIEden")
            --         GF.OpenWndBottom("UIEden")
            --         gModelWonderland:EnterWonderMap()
            --         self:AddWndRecord(exceptsWnd, "UIEden")
            --     else
            --         --gLGameUI:SaveBackWnd("UIEdenFront")
            --         GF.OpenWndBottom("UIEdenFront")
            --         GF.ChangeMap("LCityMap")
            --         self:AddWndRecord(exceptsWnd, "UIEdenFront")
            --     end

            --     closeAll = true
            --     isIgnore = true
            -- end
            if functionOpenId == ModelDesireTrail.MainFuncId then
                closeAll = true
                --isIgnore = true

                gModelGeneral:DesireTrailEntrance()
                self:AddWndRecord(exceptsWnd, "UIDesireTrail")
            end

        elseif jumpType == 5 then
            closeAll = true
            FireEvent(EventNames.SHOW_MAIN_MORE_FUN, false)
        elseif jumpType == 8 then
            --[[            if functionOpenId == 17100400 then
                            local isSelMap = gModelDreamTrip:IsSelMap()
                            if isSelMap then
                                local selHeroList = gModelDreamTrip:GetSelHeroList()
                                if #selHeroList < 1 then
                                    GF.OpenWnd("UIHopeSelSaga",{func = func})
                                    self:AddWndRecord(exceptsWnd,"UIHopeSelSaga")
                                else
                                    GF.ChangeMap("LDreamTripMap",true,{isFirst = self._isFirst,mapType = ModelCommonDreamTrip.MAP_TYPE_NORMAL})
                                    GF.OpenWndBottom("UIHope")
                                    self:AddWndRecord(exceptsWnd,"UIHope")
                                end
                            else
                                GF.OpenWnd("UIHopeMin",{func = func})
                                self:AddWndRecord(exceptsWnd,"UIHopeMin")
                            end
                            closeAll = true
                            isIgnore = true
                        end]]
        elseif jumpType == 9 then
            local wndIns = GF.FindFirstWndByName("UIBadgeWear")
            if wndIns then
                GF.CloseWndByName("UIBadgeWear")
            end
            closeAll = true
            FireEvent(EventNames.SHOW_MAIN_MORE_FUN, false)
            GF.OpenWndBottom("UIGenWin")
            self:AddWndRecord(exceptsWnd, "UIGenWin")
        end

        --if functionOpenId == ModelFunctionOpen.ONE_NIGHT then
        --    isIgnore = true
        --    gModelOneNight:Entrance()
        --
        --    self:AddWndRecord(exceptsWnd,"UIOneNightSpaceOpenEffect")
        --    self:AddWndRecord(exceptsWnd,"UIOneNightSpaceCreate")
        --end

        --if curMap and curMap:IsSameMap("LOneNightSpaceMap") then
        --	self:AddWndRecord(exceptsWnd,"WndOneNightSpaceMain")
        --	self:AddWndRecord(exceptsWnd,"UIOneNightSpaceOrnament")
        --
        --end

        if string.isempty(wndName) then
            if LOG_INFO_ENABLED then
                printInfoN(string.format("jump para wndname is null refId %s", functionOpenId))
            end
            isIgnore = true
        end

        if not isIgnore then
            local arg = {}
            arg.jumpCallback = func
            arg.isFromJump = true
            arg.functionId = functionOpenId
            if para then
                arg.isFromBubble = para.isFromBubble
                arg.goodsId = para.goodsId
                arg.itemId = para.itemId

                if para.privilegeGiftRef then
                    arg.ref = para.privilegeGiftRef
                end
            end

            if wndName == "UIDian" and page == ModelShop.ACTIVITY then
                subPage = gModelActivity:GetSidByUniqueJump(subPage)
            end

            if page > 0 then
                arg.page = page
            end
            if subPage > 0 then
                arg.subPage = subPage
            end

            local extra = gModelNormalActivity:GetRefIdByJumpId(functionOpenId)
            if extra then
                arg.extra = extra
            end

            if wndName == "WndCrossServerChampion" or wndName == "WndCrossServerLadder" then
                -- 跨服里面有独立商店，调整会有问题，加额外代码处理
                GF.CloseWndByName("WndCrossServerChampion")
                GF.CloseWndByName("WndCrossServerLadder")

            end
            if wndName == "UIFarmHappy" then--临时处理
                local sid = gModelActivity:GetSidByUniqueJump(subPage)
                arg.activityData = gModelActivity:GetActivityBySid(sid)
                arg.playerId = gModelPlayer:GetPlayerId()
            end


            self:AddWndRecord(exceptsWnd, wndName)
            gLGameUI:OpenWndWithLayer(uilayer, wndName, arg)
        end

        if mainBtnIndex > 0 then
            local sendData = {
                index = mainBtnIndex,
                extraWnds = exceptsWnd,
            }
            FireEvent(EventNames.ONLY_CHANGE_MAIN_BTN_ON, sendData)
        end

        if closeAll then

            gLGameUI:CloseAllButExcept(exceptsWnd)
        else
            for k, v in pairs(closeWndList) do
                if not exceptsWnd[k] then
                    GF.CloseWndByName(k)
                end
            end
        end

        return exceptsWnd, true
    end
end

function ModelFunctionOpen:AddWndRecord(dataMap, wndName)
    if string.isempty(wndName) then
        return
    end
    if dataMap[wndName] then
        return
    end

    dataMap[wndName] = true
end

function ModelFunctionOpen:ModifyWndPara(refId)
    local group = GameTable.FeatureOpenRef[refId].frameGroup
    if group <= 0 or group == 8 or group == 9 then
        ---商店的使用id
        return self._btnIndexs[refId]
    end

    local dataList = self._groupFunctions[group]
    local hideIndex = {}
    for k, v in ipairs(dataList) do
        local isShow = self:CheckIsShow(v)
        if not isShow then
            local btnIndex = self._btnIndexs[v]
            if not table.isempty(btnIndex) then
                if btnIndex.subPage > 0 then
                    table.insert(hideIndex, btnIndex.subPage)
                elseif btnIndex.page > 0 then
                    table.insert(hideIndex, btnIndex.page)
                end
            end
        end
    end

    local selfBtnIndex = self._btnIndexs[refId]

    local btnIndex = table.clone(selfBtnIndex)
    if selfBtnIndex.subPage > 0 then
        for k, v in ipairs(hideIndex) do
            if selfBtnIndex.subPage > v then
                btnIndex.subPage = btnIndex.subPage - 1
            end
        end
    elseif selfBtnIndex.page > 0 then
        for k, v in ipairs(hideIndex) do
            if selfBtnIndex.page > v then
                btnIndex.page = btnIndex.page - 1
            end
        end
    end

    return btnIndex
end

function ModelFunctionOpen:ParseBtnIndex(str)
    if string.isempty(str) then
        return { mainIndex = 0, page = 0, subPage = 0 }
    end

    local t = {}
    local s, e, cap1, cap2, cap3 = string.find(str, "(%d+),(%d+),(%d+)")
    if cap1 and cap2 and cap3 then
        t.mainIndex = tonumber(cap1)
        t.page = tonumber(cap2)
        t.subPage = tonumber(cap3)
    end
    return t
end

--function ModelFunctionOpen:CheckIsOpenByKey(key,showTip)
--    local funcId = GameTable.FunctionOpenConfigRef[key]
--    if funcId then
--        return self:CheckIsOpened(funcId,showTip)
--    end
--    return false
--end

function ModelFunctionOpen:GetPath(refId)
    local cfg = GameTable.FeatureOpenRef[refId]
    if cfg then
        return cfg.uiLevel
    end

end

function ModelFunctionOpen:GetLevelLimit(refId)
    if not self._openConditions then
        return 1
    end
    local limit = self._openConditions[refId]
    if not limit then
        return 1
    end
    for k, v in ipairs(limit) do
        local type = v.type
        local para = v.para
        if type == 1 then
            return para
        end
    end

    return 1
end

-- 【G功能预告】删除玩法预告机制（客户端&服务端
-- function ModelFunctionOpen:GetPrePostList()
--    return self._curPrePostList
-- end

-- 【G功能预告】删除玩法预告机制（客户端&服务端
-- function ModelFunctionOpen:RefreshPrePostList()
--     local dataList = {}
--     for k,v in pairs(GameTable.ForeshowRlayRef) do
--         if not self:CheckRefDisable(ModelFunctionOpen.FORESHOWRLAY,v.refId) then
--             local isShow = self:CheckPrePostShow(v.refId)
--             if isShow then
--                 table.insert(dataList,v)
--             end
--         end

--     end

--     table.sort(dataList,function (a,b)
--         return a.priority< b.priority
--     end)
--     self._curPrePostList = dataList


--     FireEvent(EventNames.REFRESH_PREPOST)
-- end

-- function ModelFunctionOpen:GetForeShowRef(refId)
--     return GameTable.ForeshowRlayRef[refId]
-- end

-- 【G功能预告】删除玩法预告机制（客户端&服务端
-- function ModelFunctionOpen:RecordPreFuncOpen()
--     for k,v in pairs(GameTable.ForeshowRlayRef) do
--         local isFuncOpen = self:CheckIsOpened(v.FunctionId)
--         self._preFuncOpenRecord[v.refId] = isFuncOpen
--     end
-- end

-- 【G功能预告】删除玩法预告机制（客户端&服务端
-- function ModelFunctionOpen:CheckPrePostShow(refId)
--     local ref = GameTable.ForeshowRlayRef[refId]
--     if not ref then
--         return
--     end
--     local conList = self._prePostHideConList[refId]
--     if not conList then
--         conList = {}
--         local conditions = string.split(ref.closeCond,";")
--         for k,v in ipairs(conditions) do
--             local condition = LxDataHelper.ParseNumber_Sign(v,'=')
--             if #condition == 2 then
--                 local data =
--                 {
--                     type = condition[1],
--                     para = condition[2],
--                 }

--                 table.insert(conList,data)
--             end


--         end

--         self._prePostHideConList[refId] = conList
--     end

--     local isFill = true
--     for k,v in ipairs(conList) do
--         local type = v.type
--         local checkFun = self._checkFuncPre[type]
--         isFill = checkFun and checkFun(v.para)
--         if not isFill then
--             break
--         end
--     end

--     if isFill then
--         return false
--     end

--     conList = self._prePostShowConList[refId]
--     if not conList then
--         conList = {}
--         local conditions = string.split(ref.showCond,";")
--         for k,v in ipairs(conditions) do
--             local condition = LxDataHelper.ParseNumber_Sign(v,'=')
--             if #condition == 2 then
--                 local data =
--                 {
--                     type = condition[1],
--                     para = condition[2],
--                 }

--                 table.insert(conList,data)
--             end


--         end

--         self._prePostShowConList[refId] = conList
--     end

--     local isFill = true
--     for k,v in ipairs(conList) do
--         local type = v.type
--         local checkFun = self._checkFuncPre[type]
--         isFill = checkFun and checkFun(v.para)
--         if not isFill then
--             break
--         end
--     end

--     return isFill

-- end

-- 【G功能预告】删除玩法预告机制（客户端&服务端
-- function ModelFunctionOpen:CheckPreFuncOpen()


--     local list = {}
--     for k,v in pairs(GameTable.ForeshowRlayRef) do

--         if not self:CheckRefDisable(ModelFunctionOpen.FORESHOWRLAY,v.refId) then
--             local funcId = v.FunctionId
--             local isOpen = self:CheckIsOpened(funcId)
--             local record =self._preFuncOpenRecord and self._preFuncOpenRecord[v.refId]
--             if isOpen and not record then
--                 table.insert(list,v)
--             end
--         end

--     end

--     local cnt = #list
--     if cnt>0 then
--         local curOpen = list[cnt]
--         if curOpen.touchOff == 1 then
--             printInfoN("SHOW_PREFUN_OPEN ----- 1 refid "..curOpen.refId)
--             self._curOpen = curOpen
--             FireEvent(EventNames.SHOW_PREFUN_OPEN,curOpen)
--         end
--     end

-- end

function ModelFunctionOpen:ClearCurOpen()
    self._curOpen = nil
end

function ModelFunctionOpen:GetCurOpen()
    return self._curOpen
end

function ModelFunctionOpen:CheckShowMainTop()

    local guideType = gModelGuide:GetGuideType()
    local funcId = 10000011
    if guideType == 2 then
        funcId = 50400001
    elseif guideType == 3 then
        funcId = 50400002
    elseif guideType == 5 then
        funcId = 50400005
    end

    local isShow = self:CheckIsShow(funcId)
    return isShow or self._debugTag
end

function ModelFunctionOpen:CheckShowHurdle()
    local funcId = 10000012
    local isShow = self:CheckIsShow(funcId)
    return isShow or self._debugTag
end

function ModelFunctionOpen:DebugTag()
    self._debugTag = true

    FireEvent(EventNames.REFRESH_FUNCTION_STATE)
end

function ModelFunctionOpen:CheckOpenCondition(open)
    local conditions = self:ParseCondition(open)
    for k, v in ipairs(conditions) do
        local type = v.type
        local para = v.para
        local checkFunc = self._checkFuncs[type]
        if checkFunc then
             if not checkFunc(para) then
                return false
             end
        end
    end

    return true
end

function ModelFunctionOpen:GetOpenCondition(openPara, showTips)
    local conditions = self:ParseCondition(openPara)
    local meet = true
    local meetStr = ""
    for k, v in ipairs(conditions) do
        local type = v.type
        local para = v.para
        local checkFunc = self._checkOpenTipsFuncs[type]
        if checkFunc then
            meet, meetStr = checkFunc(para)
            if not meet then
                break
            end
        end
    end
    if showTips and not meet then
        GF.ShowMessage(meetStr)
    end
    return meetStr
end

-- 【G功能预告】删除玩法预告机制（客户端&服务端）
-- function ModelFunctionOpen:InsertPrePost()

--     if self:IsTodayNoTip() then
--         return
--     end

--     local list = self:GetPrePostList()
--     if not list or #list ==0 then
--         return
--     end

--     local data =
--     {
--         uiName = "WndPrePost",
--         para = {}
--     }

--     gModelGeneral:InsertTimeLimitWndEx(data)
-- end

function ModelFunctionOpen:IsTodayNoTip()
    local recordTime = tonumber(LPlayerPrefs.prePostAlert) or 0

    local dayPast = LUtil.GetDayPast(recordTime)
    if dayPast < 2 then
        return true
    end

    return false
end


--清理工作
--停止计时器之类的
function ModelFunctionOpen:OnModelClear()

end

function ModelFunctionOpen:GetFuncRelaCombat(refId)
    local parseFunc = function(value)
        local numList = LxDataHelper.ParseNumber_Sign(value, ",")
        local record = {}
        for k, v in ipairs(numList) do
            if v > 0 then
                record[v] = true
            end
        end

        return record
    end

    local value = self:GetConfigValueImpl(ModelFunctionOpen.FeatureOpenRef, refId, "combatType", parseFunc) or {}
    return value

end

function ModelFunctionOpen:GetOpenPara(refId, type)
    local conditions = self._openConditions[refId]
    for k, v in pairs(conditions) do
        if v.type == type then
            return v.para
        end
    end
end
---1,可领取 2,不可领取 3,已领取
function ModelFunctionOpen:GetForeFuncState(refId)
    local isRewarded = self._receiveForeIdMap and self._receiveForeIdMap[refId]
    if isRewarded then
        return 3
    else
        local ref = self:GetModelConfig(ModelFunctionOpen.FeaturePreviewAllRef)
        local data = ref[refId]
        local isOpen = self:CheckIsOpened(data.functionOpen)
        if isOpen then
            return 1
        else
            return 2
        end
    end
end

function ModelFunctionOpen:GetSortForeList()
    local ref = self:GetModelConfig(ModelFunctionOpen.FeaturePreviewAllRef)
    local dataList = {}

    local limitCnt = self:GetForShowPara("listMax")
    local notOpenList = {}
    for k, v in pairs(ref) do

        if not self:CheckRefDisable(ModelFunctionOpen.FORESHOWALL, v.refId) then
            local state = self:GetForeFuncState(v.refId)
            local data = {
                conf = v,
                state = state
            }

            if state == 1 then
                table.insert(dataList, data)
            elseif state == 2 then
                table.insert(notOpenList, data)
            end
        end

    end

    table.sort(notOpenList, function(a, b)
        return a.conf.sort < b.conf.sort
    end)

    for k, v in ipairs(notOpenList) do
        if k <= limitCnt then
            table.insert(dataList, v)
        else
            break
        end
    end

    table.sort(dataList, function(a, b)
        if a.state ~= b.state then
            return a.state < b.state
        end

        return a.conf.sort < b.conf.sort
    end)

    return dataList
end

function ModelFunctionOpen:GetForeAdList()
    local ref = self:GetModelConfig(ModelFunctionOpen.FeaturePreviewAllRef)
    local canGetList = {}
    local notOpenList = {}

    local limitCnt = self:GetForShowPara("cityListMax")
    limitCnt = limitCnt and limitCnt  or 0
    for k, v in pairs(ref) do

        if not self:CheckRefDisable(ModelFunctionOpen.FORESHOWALL, v.refId) then
            local state = self:GetForeFuncState(v.refId)

            if state == 1 then
                table.insert(canGetList, v)
            elseif state == 2 then
                table.insert(notOpenList, v)
            end
        end

    end

    if #canGetList > 0 then
        table.sort(canGetList, function(a, b)
            return a.sort < b.sort
        end)

        local list = {}

        for k, v in ipairs(canGetList) do
            if k <= limitCnt then
                table.insert(list, v)
            else
                break
            end
        end

        return list
    elseif #notOpenList > 0 then
        table.sort(notOpenList, function(a, b)
            return a.sort < b.sort
        end)

        return { notOpenList[1] }
    end

    return {}
end

function ModelFunctionOpen:GetForShowPara(key)
    return self:GetParaConfigValueImpl(ModelFunctionOpen.FeaturePreviewConfigRef, key)
end

function ModelFunctionOpen:GetWndRelaCombatType(wndName)
    local wndRelaMap = self._wndRelaMap
    if not wndRelaMap then
        wndRelaMap = {}
        local ref = self:GetModelConfig(ModelFunctionOpen.FeatureOpenRef)
        for k, v in pairs(ref) do
            local temp = v.wndName
            if not string.isempty(temp) and not wndRelaMap[temp] then
                local record = self:GetFuncRelaCombat(v.refId)
                if table.keysize(record) > 0 then
                    wndRelaMap[temp] = record
                end
            end
        end

        self._wndRelaMap = wndRelaMap
    end

    return wndRelaMap[wndName]
end

function ModelFunctionOpen:CheckAreaOpen(refId, showTip)
    local refItem = self:GetAreaOpenRef(refId)
    if refItem and refItem.openState == 1 then
        if showTip then
            GF.ShowMessage(ccLngText(refItem.openTips))
        end
        return false
    end

    return true
end

function ModelFunctionOpen:GetAreaOpenRef(refId)
    local ref = self:GetModelConfig(ModelFunctionOpen.FeatureOpenAreaRef)
    local refItem = ref[refId]
    return refItem
end

function ModelFunctionOpen:CheckRefDisable(type, refId)

    local maskDataMap = self._maskRefMap
    if not maskDataMap then
        maskDataMap = {}
        self._maskRefMap = maskDataMap
        local ref = self:GetModelConfig(ModelFunctionOpen.FeatureOpenAreaSublistRef)
        for k, v in pairs(ref) do
            local list = maskDataMap[v.type]
            if not list then
                list = {}
                maskDataMap[v.type] = list
            end
            table.insert(list, v)
        end


    end

    local isMask = false
    local dataList = maskDataMap[type]
    if not dataList then
        return isMask
    end
    for k, v in ipairs(dataList) do

        if not self:CheckAreaOpen(v.functionOpen) then
            if refId >= v.shieldMin and refId <= v.shieldMax then
                isMask = true
                break
            end
        end

    end

    if isMask then
        printInfoN2("地区屏蔽", string.format("屏蔽配置 type: %s,refId %s", type, refId))
    end

    return isMask
end

-- 主界面滚屏预告配置表
function ModelFunctionOpen:GetForeshowRefList()
    if not self._foreshowScrollList then
        local ref = self:GetModelConfig(ModelFunctionOpen.FeaturePreviewScrollRef) or {}
        local list = {}
        for _, v in pairs(ref) do
            table.insert(list, v)
        end
        self._foreshowScrollList = list
    end
    return self._foreshowScrollList
end

-- true,表示玩法可以显示
function ModelFunctionOpen:CanForeshow(data, refId)
    data = data or self._preFuncPlayMap[refId]
    if not data then
        return false
    end

    if data.startTime == -1 then
        return false
    end

    if data.endTime == 0 then
        return true
    end

    if data.endTime <= data.startTime then
        return false
    end

    local curTime = GetTimestamp()
    if curTime <= data.endTime and curTime >= data.startTime then
        return true
    end
    return false
end

-- 获取玩法数据
function ModelFunctionOpen:GetForeshowData(refId)
    return self._preFuncPlayMap[refId]
end
--获取拍脸数据
function ModelFunctionOpen:GetForeshowPopList()
    return self._foreshowPopList
end

-- 获取主界面滚屏预告表
function ModelFunctionOpen:GetForeshowList(needSort)
    local funcList = {}
    if PRODUCT_G_VER == 1 or PRODUCT_G_VER == 2 then
        return funcList
    end
    -- for k, v in ipairs(self:GetForeshowRefList()) do
    --     if self:CheckIsOpened(v.functionOpen, false) and self:CanForeshow(nil, v.refId) then
    --         table.insert(funcList, v)
    --     end
    -- end

    local ForeshowScrollRef = GameTable.FeaturePreviewScrollRef
    for refId, data in pairs(self._preFuncPlayMap) do
        local ref = ForeshowScrollRef[refId]
        if ref and self:CheckIsOpened(ref.functionOpen, false) and self:CanForeshow(data) then
            table.insert(funcList, ref)
        end
    end

    local activeList = gModelActivity:GetMainEntranceActivityList()

    local EntranceType = ModelFunctionOpen.EntranceType

    local list = {}
    local index = 1
    for k, v in ipairs(activeList) do
        index = index + 1
        table.insert(list, { type = EntranceType.Activity, index = index, pb = v, data = self:ParseActivityConfig(v) })
    end
    for k, v in ipairs(funcList) do
        index = index + 1
        table.insert(list, { type = EntranceType.Func, index = index, data = v})
    end
    if needSort then
        table.sort(list, function(a, b)
            -- if a.data.sort ~= b.data.sort then
            --     return a.data.sort < b.data.sort
            -- end
            -- if a.type ~= b.type then
            --     return a.type < b.type
            -- end
            -- return a.index < b.index
            if a.type ~= b.type then
                return a.type > b.type
            else
                if a.type==EntranceType.Func then 
                    return a.data.sort < b.data.sort
                else
                    return a.pb.startTime < b.pb.startTime
                end
            end
        end)
    end
    return list
end

function ModelFunctionOpen:ParseActivityConfig(pb)
    local tab = string.split(pb.scrollConfig, ";")
    local data = {}
    for k, v in ipairs(tab) do
        local tab2 = string.split(v, "=")
        if tab2[1] == "1" then
            data.icon = tab2[2]
        elseif tab2[1] == "2" then
            data.iconTxt = tab2[2]
        elseif tab2[1] == "3" then
            data.cellBg = tab2[2]
        elseif tab2[1] == "4" then
            data.cellBgTxt = tab2[2]
        elseif tab2[1] == "5" then
            data.cellNameDec = tab2[2]
        end
    end
    data.sort = pb.sort
    return data
end

function ModelFunctionOpen:OpenForeshowPop()
    if not self._foreshowPopList then return end
    local aRef , bRef 
    table.sort(self._foreshowPopList,function(a,b)
        aRef = GameTable.ForeshowPopRef[a.refId]
        bRef = GameTable.ForeshowPopRef[b.refId]
        return aRef.sort<bRef.sort
    end)
    local info = table.remove(self._foreshowPopList,1)
    GF.OpenWnd("UIForeshowPop",{info = info})
end

-- 滚屏时间间隔
function ModelFunctionOpen:GetForeshowScrollTime()
    local ref = self:GetModelConfig(ModelFunctionOpen.FeaturePreviewConfigRef)
    return ref.scrollTimes
end


-- 功能开启的预告
function ModelFunctionOpen:GetFunctionOpenShowInfo()
    --插入
    local list = gModelInstance:GetInstanceFunctionRef()
    local showListData = {}
    for k, v in ipairs(list) do
        local isOpen = self:CheckIsOpened(v.functionId)
        if (not isOpen) and #showListData <= 2 then

            table.insert(showListData, v.functionId)
        end
    end

    --如果有信息就进行构建
    if #showListData > 0 then
        --functionId -> des
        showListData = self:CreateOpenShowInfo(showListData)
    end

    return showListData
end

function ModelFunctionOpen:CreateOpenShowInfo(showListData)
    --[17012]	[騎士大人，<color=#feeba7>#a1#</color>已開啟！]
    --[17013]	[冒險<color=#68e6ac> #a1#關 </color>後開啟新功能：<color=#fef01e>#a2#</color>]
    --[17016]	[再挑戰<color=#139057>#a1#關</color>，並且再通過<color=#139057>#a2#</color>天開啟<color=#139057>#a3#</color>！]
    --[17017]	[再挑戰<color=#139057>#a1#關</color>，或者再通過<color=#139057>#a2#</color>天開啟<color=#139057>#a3#</color>！]
    --[17018]	[騎士再提升<color=#68e6ac> #a1#級 </color>後開啟新功能：<color=#fef01e>#a2#</color>]
    --[17019]	[騎士再提升<color=#68e6ac> #a1#級 </color>，並且再通過<color=#139057>#a2#</color>天開啟<color=#139057>#a3#</color>！]

    --开服天数
    local serverDay = gLGameLogin:GetServerOpenDay()
    --当前通过
    local battleNode = gModelInstance:GetBattleNode()
    local curbattleNode = gModelInstance:GetLastBattleNode(1, battleNode)
    local iRef = gModelInstance:GetMissionCfg(curbattleNode)
    local num = iRef.num

    local playerlv = gModelPlayer:GetPlayerLv()

    local resultList = {}
    --就一个des
    for _, functionId in ipairs(showListData) do
        local showType = 1
        local battleNum = 0
        local openDay = 0
        local level = 0
        local foRef = self:GetFunctionOpenCfg(functionId)
        -- 并且部分的检查
        if not foRef then
            printInfoNR2("配置错误---","InstanceFunctionRef--配置的functionId"..functionId.."不存在FunctionOpenRef中")
        else
            if not string.isempty(foRef.open) then
                local open = string.split(foRef.open, ",")
                for j, condition in ipairs(open) do
                    local arr = string.split(condition, "=")
                    local type = tonumber(arr[1])

                    if type == 2 then
                        battleNum = tonumber(arr[2]) - num
                        showType = 2
                    elseif type == 11 then
                        openDay = tonumber(arr[2]) - serverDay

                    elseif type == 1 then

                        level = tonumber(arr[2]) - playerlv

                        showType = 5
                    end
                end

                if battleNum > 0 and openDay > 0 then
                    showType = 3
                end

                if level > 0 and openDay > 0 then
                    showType = 6
                end
                --
                if level < 0 and openDay > 0 then
                    level= 0
                    showType = 6
                end
            end
            -- 或的条件检查
            if not string.isempty(foRef.otherOpen) and (battleNum == 0 or openDay == 0) then
                local otherOpen = string.split(foRef.otherOpen, ",")
                for j, k in ipairs(otherOpen) do
                    local arr = string.split(k, "=")
                    local type = tonumber(arr[1])
                    if type == 2 then
                        battleNum = tonumber(arr[2]) - num
                        showType = 2
                    elseif type == 11 then
                        openDay = tonumber(arr[2]) - serverDay
                    end
                end
                showType = 4
            end


            --创建对应的des
            local name = ccLngText(foRef.name)
            local str
            if showType == 1 then
                str = string.replace(ccClientText(17012), name)
            elseif showType == 2 then
                str = string.replace(ccClientText(17013), battleNum, name)
            elseif showType == 3 then
                str = string.replace(ccClientText(17016), battleNum, openDay, name)
            elseif showType == 4 then
                str = string.replace(ccClientText(17017), battleNum, openDay, name)
            elseif showType == 5 then
                str = string.replace(ccClientText(17018), level, name)
            elseif showType == 6 then
                str = string.replace(ccClientText(17019), level, openDay, name)
            end

            table.insert(resultList, str)
        end


    end

    return resultList
end

function ModelFunctionOpen:GetCheckFuns(type)
    return self._checkFuncs[type]
end

function ModelFunctionOpen:CheckIsOpenRes(refId)
    local cfg = GameTable.FeatureOpenRef[refId]
    if cfg then
        local resOpen = cfg.resOpen
        if not string.isempty(resOpen) then
            local isOpenRes = false
            local resType = LPlayerPrefs.GetLocalization()
            resOpen = string.split(resOpen,",")
            for i,v in ipairs(resOpen) do
                if resType == checknumber(v) then
                    isOpenRes = true
                    break
                end
            end
            return isOpenRes
        end
    end
    return true
end

function ModelFunctionOpen:GetFunctionCfgBtnIndex(refId)
    return self._btnIndexs[refId]
end

return ModelFunctionOpen