---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 14:40
---
------------------------------------------------------------------
---模块使用示例 需要在LModelManager的列表里填写名字
---创建完之后可以使用gModelTemplate全局变量访问实例
------------------------------------------------------------------
LXImport("..Struct.StructTemplate")

local LModel = LModel
------------------------------------------------------------------
---@class ModelHeroSpirit:LModel
local ModelHeroSpirit = LxClass("ModelHeroSpirit", LModel)

ModelHeroSpirit.RETURN_TYPE_1 = 1            -- 聚灵殿，回退功能
ModelHeroSpirit.RETURN_TYPE_2 = 2            -- 聚灵殿，转生功能
ModelHeroSpirit.RETURN_TYPE_3 = 3            -- 道具回退
------------------------------------------------------------------
function ModelHeroSpirit:ModelHeroSpirit()
    self._upStarSelHero = {}
end

--模块初始化入口
--注册事件监听
--注册协议监听
--预处理数据
function ModelHeroSpirit:OnModelInit()

    self:ModelNetMsgRecv(LProtoIds.HeroRebirthResp, function(...)
        self:OnHeroRebirthResp(...)
    end)
    self:ModelNetMsgRecv(LProtoIds.HeroReturn2Resp, function(...)
        self:OnHeroReturn2Resp(...)
    end)

    self:InitStr()
end

--在协议数据处理完之后需要调用finish
function ModelHeroSpirit:OnModelRequest()
    self._upStarSelHero = {}
    self:ModelFinish()
end

function ModelHeroSpirit:InitStr()
    local configRef = GameTable.CharacterConfigRef

    -- 英雄献祭参数
    self._xianjiData = {}
    self._xianjiData.race = {}
    local heroSacrificeRace = configRef["heroSacrificeRace"]
    heroSacrificeRace = string.split(heroSacrificeRace, ",")
    --for i,v in ipairs(heroSacrificeRace) do table.insert(self._xianjiData.race,tonumber(v)) end
    for i, v in ipairs(heroSacrificeRace) do
        local race = tonumber(v)
        self._xianjiData.race[race] = race
    end

    -- 英雄融合参数
    self._rongheData = {}
    self._rongheData.race = {}
    local heroFuseRace = configRef["heroFuseRace"]
    heroFuseRace = string.split(heroFuseRace, ",")
    --for i,v in ipairs(heroFuseRace) do table.insert(self._rongheData.race,tonumber(v)) end
    for i, v in ipairs(heroFuseRace) do
        local race = tonumber(v)
        self._rongheData.race[race] = race
    end

    -- 英雄转换参数
    self._zhuanhuanData = {}
    self._zhuanhuanData.race = {}
    local heroChangeRace = configRef["heroChangeRace"]
    heroChangeRace = string.split(heroChangeRace, ",")
    --for i,v in ipairs(heroChangeRace) do table.insert(self._zhuanhuanData.race,tonumber(v)) end
    for i, v in ipairs(heroChangeRace) do
        local race = tonumber(v)
        self._zhuanhuanData.race[race] = race
    end
    self._zhuanhuanData.star = {}
    local heroChangeStar = configRef["heroChangeStar"]
    heroChangeStar = string.split(heroChangeStar, ";")
    for i, v in ipairs(heroChangeStar) do
        v = string.split(v, ",")
        local temp = string.split(v[2], "=")
        table.insert(self._zhuanhuanData.star, { heroStar = tonumber(v[1]), refId = tonumber(temp[2]), num = tonumber(temp[3]) })
    end

    -- 英雄置换参数
    self._zhihuanData = {}
    self._zhihuanData.race = {}
    local heroDiSplaceRace = configRef["heroDiSplaceRace"]
    heroDiSplaceRace = string.split(heroDiSplaceRace, ",")
    --for i,v in ipairs(heroDiSplaceRace) do table.insert(self._zhihuanData.race,tonumber(v)) end
    for i, v in ipairs(heroDiSplaceRace) do
        local race = tonumber(v)
        self._zhihuanData.race[race] = race
    end
    self._zhihuanData.star = {}
    local heroDiSplaceStar = configRef["heroDiSplaceStar"]
    heroDiSplaceStar = string.split(heroDiSplaceStar, ";")
    for i, v in ipairs(heroDiSplaceStar) do
        v = string.split(v, ":")
        local need = string.split(v[3], "=")
        local data = { heroStar = tonumber(v[1]), heroNum = tonumber(v[2]), refId = tonumber(need[2]), num = tonumber(need[3]) }
        table.insert(self._zhihuanData.star, data)
    end

    -- 英雄重生参数
    self._chongshengData = {}
    self._chongshengData.race = {}
    local heroLevelRebornRace = configRef["heroLevelRebornRace"]
    heroLevelRebornRace = string.split(heroLevelRebornRace, ",")
    --for i,v in ipairs(heroLevelRebornRace) do table.insert(self._chongshengData.race,tonumber(v)) end
    for i, v in ipairs(heroLevelRebornRace) do
        local race = tonumber(v)
        self._chongshengData.race[race] = race
    end
    self._chongshengData.rebornNeed = {}
    local heroLevelRebornNeed = configRef["heroLevelRebornNeed"]
    heroLevelRebornNeed = string.split(heroLevelRebornNeed, ";")
    for i, v in ipairs(heroLevelRebornNeed) do
        v = string.split(v, "=")
        table.insert(self._chongshengData.rebornNeed, { refId = tonumber(v[2]), num = tonumber(v[3]) })
    end

    -- 英雄回退参数
    self._huituiData = {}
    self._huituiData.race = {}
    local heroReturnRace = configRef["heroReturnRace"]
    heroReturnRace = string.split(heroReturnRace, ",")
    --for i,v in ipairs(heroReturnRace) do table.insert(self._huituiData.race,tonumber(v)) end
    for i, v in ipairs(heroReturnRace) do
        local race = tonumber(v)
        self._huituiData.race[race] = race
    end

    self._zhuanshengData = {}
    self._zhuanshengData.race = {}
    local heroReturnRace1 = configRef["heroReturnRace1"]
    heroReturnRace1 = string.split(heroReturnRace1, ",")
    --for i,v in ipairs(heroReturnRace1) do table.insert(self._zhuanshengData.race,tonumber(v)) end
    for i, v in ipairs(heroReturnRace1) do
        local race = tonumber(v)
        self._zhuanshengData.race[race] = race
    end

    local heroReturnKeyList = {}
    self._heroReturnRef = {}
    local star, type, returnStar, race
    for k, v in pairs(GameTable.CharacterReturnRef) do
        type = v.type
        race = tonumber(v.race)
        star = v.star
        returnStar = v.returnStar

        local data = {}
        data.race = race
        data.star = star
        data.type = type
        data.returnStar = returnStar
        local need = string.split(v.need, "=")
        data.need = { itemType = tonumber(need[1]), refId = tonumber(need[2]), num = tonumber(need[3]) }

        local fixRewardList = {}
        local fixReward = string.split(v.fixReward, ",")
        for _i, _v in ipairs(fixReward) do
            _v = string.split(_v, "=")
            table.insert(fixRewardList, { itemType = tonumber(_v[1]), refId = tonumber(_v[2]), num = tonumber(_v[3]) })
        end
        data.fixReward = fixRewardList

        data.getNoumenonNum = v.getNoumenonNum

        local coreMaterialsList = {}
        local coreMaterials = string.split(v.coreMaterials, ",")
        for _i, _v in ipairs(coreMaterials) do
            _v = string.split(_v, "=")
            table.insert(coreMaterialsList, { itemType = tonumber(_v[1]), refId = tonumber(_v[2]), num = tonumber(_v[3]) })
        end
        data.coreMaterials = coreMaterialsList
        data.heroType = v.heroType or  0
        self._heroReturnRef[k] = data

        local typeInfo = heroReturnKeyList[type]
        if not typeInfo then
            typeInfo = {}
            heroReturnKeyList[type] = typeInfo
        end
        local raceInfo = typeInfo[race]
        if not raceInfo then
            raceInfo = {}
            typeInfo[race] = raceInfo
        end
        local starInfo = raceInfo[star]
        if not starInfo then
            starInfo = {}
            raceInfo[star] = starInfo
        end
        local returnStarInfo = starInfo[returnStar]
        if returnStarInfo then
            if LOG_INFO_ENABLED then
                printInfoN("======= 配置一致 refId:" .. k .. "，类型:" .. type .. "，星级:" .. star .. "，回退星级:" .. returnStar)
            end
        else
            starInfo[returnStar] = k
        end
    end
    self._heroReturnKeyList = heroReturnKeyList            -- 索引到refId

    self._heroUpStarLimit = {}
    local heroUpStarLimit = configRef["heroUpStarLimit"]
    heroUpStarLimit = string.split(heroUpStarLimit, ",")
    for i, v in ipairs(heroUpStarLimit) do
        v = string.split(v, "=")
        local star, lv = tonumber(v[1]), tonumber(v[2])
        self._heroUpStarLimit[star] = lv
    end
end

------------------------------------------------------------------------
function ModelHeroSpirit:OnHeroRebirthReq(heroId)
    local pb = LProtoHelper.CreateProto(LProtoIds.HeroRebirthReq)
    pb.heroId = heroId
    SendMessage(pb, LProtoIds.HeroRebirthReq)
end

function ModelHeroSpirit:OnHeroRebirthResp(pb, ret)
    FireEvent(EventNames.On_Item_Change)
end

function ModelHeroSpirit:OnHeroReturn2Req(heroId)
    local pb = LProtoHelper.CreateProto(LProtoIds.HeroReturn2Req)
    pb.heroId = heroId
    SendMessage(pb, LProtoIds.HeroReturn2Req)
end

function ModelHeroSpirit:OnHeroReturn2Resp(pb, ret)

end
------------------------------------------------------------------------

function ModelHeroSpirit:GetHeroSpiritData()
    return self._xianjiData, self._rongheData, self._zhuanhuanData, self._zhihuanData, self._chongshengData, self._huituiData, self._zhuanshengData
end

function ModelHeroSpirit:GetZhiHuanData()
    return self._zhihuanData
end

function ModelHeroSpirit:GetUpStarLimit()
    return self._heroUpStarLimit
end

function ModelHeroSpirit:GetChongshengData()
    return self._chongshengData
end

function ModelHeroSpirit:GetHeroReturnRefByRefId(refId)
    return self._heroReturnRef[refId]
end

function ModelHeroSpirit:GetHeroReturnData(race, star, returnType, heroType)
    for k, v in pairs(self._heroReturnRef) do
        if v.race == race
                and v.star == star
                and returnType == v.type
                and heroType == v.heroType
        then
            return v
        end
    end
end

-- 聚灵殿
function ModelHeroSpirit:GetHeroSortListBySpirit(heroTypeList, page, needList, tabIndex)
    local heroList = gModelHero:GetHeroList()
    if not heroList then
        return {}
    end
    local sortHeroList = {}
    for k, v in pairs(heroList) do
        local star, lv = v._star, v._level
        if not heroTypeList then
            if page ~= 3 and page ~= 4 then
                if page == 1 then
                    if needList then
                        if star <= needList then
                            table.insert(sortHeroList, v)
                        end
                    else
                        table.insert(sortHeroList, v)
                    end
                else
                    table.insert(sortHeroList, v)
                end
            else
                if page == 3 then
                    if needList[star] then
                        table.insert(sortHeroList, v)
                    end
                elseif page == 4 then
                    if tabIndex == 1 then
                        if lv >= needList then
                            table.insert(sortHeroList, v)
                        end
                    else
                        if star > needList then
                            table.insert(sortHeroList, v)
                        end
                    end
                end
            end
        else
            local race = gModelHero:GetHeroType(v._refId)
            if heroTypeList[race] then
                if page ~= 3 and page ~= 4 then
                    if page == 1 then
                        if needList then
                            if star <= needList then
                                table.insert(sortHeroList, v)
                            end
                        else
                            table.insert(sortHeroList, v)
                        end
                    else
                        table.insert(sortHeroList, v)
                    end
                else
                    if page == 3 then
                        if needList[star] then
                            table.insert(sortHeroList, v)
                        end
                    elseif page == 4 then
                        if tabIndex == 1 then
                            if lv >= needList then
                                table.insert(sortHeroList, v)
                            end
                        else
                            if star > needList then
                                table.insert(sortHeroList, v)
                            end
                        end
                    end
                end
            end
        end
    end
    table.sort(sortHeroList, function(hero1, hero2)
        local status1, status2 = hero1:GetStatus(), hero2:GetStatus()
        if status1 == status2 and status1 == 0 then
            local star1, star2 = hero1:GetStar(), hero2:GetStar()
            if star1 == star2 then
                local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
                if lv1 == lv2 then
                    --[[					local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                        if pow1 == pow2 then
                                            local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                            if refId1 == refId2 then
                                                local id1,id2 = hero1:GetId(),hero2:GetId()
                                                return id1 > id2
                                            else
                                                return refId1 < refId2
                                            end
                                        else
                                            return pow1 < pow2
                                        end]]

                    local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                    if refId1 == refId2 then
                        local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
                        if pow1 == pow2 then
                            local id1, id2 = hero1:GetId(), hero2:GetId()
                            return id1 > id2
                        else
                            return pow1 < pow2
                        end
                    else
                        return refId1 < refId2
                    end
                else
                    return lv1 < lv2
                end
            else
                return star1 < star2
            end
            --[[		elseif (not status1) and (not status2) then
                        local combat1,combat2 = hero1:GetCombatStatus(),hero2:GetCombatStatus()
                        if combat1 == combat2 and combat1 == 0 then
                            local resonance1,resonance2 = hero1:GetResonanceStatus(),hero2:GetResonanceStatus()
                            if resonance1 == resonance2 and resonance1 == 0 then
                                local lock1,lock2 = hero1:GetLockStatus(),hero2:GetLockStatus()
                                return lock1 < lock2
                            else
                                return resonance1 < resonance2
                            end
                        else
                            return combat1 < combat2
                        end]]
        else
            return status1 < status2
        end
    end)
    return sortHeroList
end

-- heroTypeList:种族限制
-- needList:可以转换/置换的英雄星级限制
-- 聚灵殿 献祭
function ModelHeroSpirit:GetHeroSortListBySpiritPage1(heroTypeList, needList)
    local heroList = gModelHero:GetHeroList()
    if not heroList then
        return {}
    end
    local sortHeroList = {}
    for k, v in pairs(heroList) do
        local refId, star = v:GetRefId(), v:GetStar()
        if heroTypeList then
            local ref = gModelHero:GetHeroRef(refId)
            if ref then
                local raceType = ref.raceType
                if heroTypeList[raceType] then
                    --local starId = gModelHero:GetStarId(starType,star)
                    --local starRef = gModelHero:GetHeroStarById(starId)
                    local starRef = gModelHero:GetStarRefById(v:GetId())

                    local sacrifice = starRef.sacrifice
                    if sacrifice == 1 then
                        if needList then
                            if star <= needList then
                                table.insert(sortHeroList, v)
                            end
                        else
                            table.insert(sortHeroList, v)
                        end
                    end
                end
            else
                printInfoNR("========== 没有找到对应的refId数据 ：" .. refId)
            end
        else
            table.insert(sortHeroList, v)
        end
    end
    table.sort(sortHeroList, function(hero1, hero2)
        local status1, status2 = hero1:GetStatus(), hero2:GetStatus()
        if status1 == status2 and status1 == 0 then
            local star1, star2 = hero1:GetStar(), hero2:GetStar()
            if star1 == star2 then
                local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
                if lv1 == lv2 then
                    --[[					local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                        if pow1 == pow2 then
                                            local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                            if refId1 == refId2 then
                                                local id1,id2 = hero1:GetId(),hero2:GetId()
                                                return id1 > id2
                                            else
                                                return refId1 < refId2
                                            end
                                        else
                                            return pow1 < pow2
                                        end]]
                    local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                    if refId1 == refId2 then
                        local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
                        if pow1 == pow2 then
                            local id1, id2 = hero1:GetId(), hero2:GetId()
                            return id1 > id2
                        else
                            return pow1 < pow2
                        end
                    else
                        return refId1 < refId2
                    end
                else
                    return lv1 < lv2
                end
            else
                return star1 < star2
            end
        elseif status1 == status2 and status1 == 1 then
            local combat1, combat2 = hero1:GetCombatStatus(), hero2:GetCombatStatus()
            if combat1 ~= combat2 then
                return combat1 > combat2
            else
                local lock1, lock2 = hero1:GetLockStatus(), hero2:GetLockStatus()
                if lock1 ~= lock2 then
                    return lock1 > lock2
                else
                    local resonance1, resonance2 = hero1:GetResonanceStatus(), hero2:GetResonanceStatus()
                    if resonance1 ~= resonance2 then
                        return resonance1 > resonance2
                    else
                        local star1, star2 = hero1:GetStar(), hero2:GetStar()
                        if star1 == star2 then
                            local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
                            if lv1 == lv2 then
                                --[[								local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                                                if pow1 == pow2 then
                                                                    local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                                                    if refId1 == refId2 then
                                                                        local id1,id2 = hero1:GetId(),hero2:GetId()
                                                                        return id1 > id2
                                                                    else
                                                                        return refId1 < refId2
                                                                    end
                                                                else
                                                                    return pow1 < pow2
                                                                end]]
                                local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                                if refId1 == refId2 then
                                    local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
                                    if pow1 == pow2 then
                                        local id1, id2 = hero1:GetId(), hero2:GetId()
                                        return id1 > id2
                                    else
                                        return pow1 < pow2
                                    end
                                else
                                    return refId1 < refId2
                                end
                            else
                                return lv1 < lv2
                            end
                        else
                            return star1 < star2
                        end
                    end
                end
            end
        else
            return status1 < status2
        end
    end)
    return sortHeroList
end

-- 聚灵殿 融合
function ModelHeroSpirit:GetHeroSortListBySpiritPage2(heroTypeList)
    local sortHeroList = self:GetHeroUpStarStatus(heroTypeList)
    table.sort(sortHeroList, function(hero1, hero2)
        local isFuse1, isFuse2 = hero1:GetFuseStatus(), hero2:GetFuseStatus()
        local upStar1, upStar2 = hero1:GetUpStar(), hero2:GetUpStar()
        local star1, star2 = hero1:GetStar(), hero2:GetStar()
        local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
        local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
        local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
        local id1, id2 = hero1:GetId(), hero2:GetId()
        if isFuse1 == isFuse2 then
            if upStar1 == upStar2 and upStar1 == 1 then
                if star1 == star2 then
                    if lv1 == lv2 then
                        if refId1 == refId2 then
                            if pow1 == pow2 then
                                return id1 > id2
                            else
                                return pow1 < pow2
                            end
                        else
                            return refId1 < refId2
                        end
                    else
                        return lv1 > lv2
                    end
                else
                    return star1 > star2
                end
            else
                if upStar1 ~= upStar2 then
                    return upStar1 < upStar2
                else
                    if star1 == star2 then
                        if lv1 == lv2 then
                            if refId1 == refId2 then
                                if pow1 == pow2 then
                                    return id1 > id2
                                else
                                    return pow1 < pow2
                                end
                            else
                                return refId1 < refId2
                            end
                        else
                            return lv1 > lv2
                        end
                    else
                        return star1 > star2
                    end
                end
            end
        else
            if upStar1 == upStar2 and upStar1 == 1 then
                return isFuse1 > isFuse2
            else
                return upStar1 < upStar2
            end
        end
    end)
    return sortHeroList
end

function ModelHeroSpirit:GetHeroUpStarStatus(heroTypeList, status)
    local heroList = gModelHero:GetHeroList()
    if not heroList then
        return {}
    end
    local sortHeroList = {}
    local resonanceLevel = gModelResonance:GetResonanceLv()
    local getUpStarStatus = false
    local heroUpStarLimit = self:GetUpStarLimit()
    for k, v in pairs(heroList) do
        if getUpStarStatus then
            break
        end
        local refId = v._refId
        local ref = gModelHero:GetHeroRef(refId)
        if ref then
            local goNext = true
            local raceType = ref.raceType
            if heroTypeList then
                goNext = heroTypeList[raceType] ~= nil
            end

            --if v._refId == 2702 and v._star == 8 then
            --    printInfoN2("--","--")
            --end


            if goNext then
                local id, star = v._id, v._star
                local upStarInfo = gModelHero:GetUpStarHeroInfoByHeroRefIdAndStar(refId, star)
                if upStarInfo then
                    local upStar = upStarInfo.upStar
                    if upStar ~= 0 then
                        local nextStar = star + 1
                        local data = {}
                        local fuse1, fuse2, fuse3 = true, true, true
                        local upStarAppoint, upStarRange, upStarItem = upStarInfo.upStarAppoint, upStarInfo.upStarRange, upStarInfo.upStarItem
                        local needRefId, needStar, needNum
                        for _i, _v in ipairs(upStarAppoint) do
                            if not fuse1 then
                                break
                            end
                            needRefId, needStar, needNum = _v.needRefId, _v.needStar, _v.needNum
                            local dataList = gModelHero:FilterHero(needRefId, needStar, nil, id, {}, needNum)
                            local haveNum = table.keysize(dataList)
                            local tempList = {}
                            local aaa = 0
                            for key, val in pairs(dataList) do
                                if aaa >= needNum then
                                    break
                                end
                                tempList[key] = val
                                aaa = aaa + 1
                            end
                            table.insert(data, tempList)
                            fuse1 = haveNum >= needNum
                        end
                
                        
                        if fuse1 then
                            local _condition = {}

                            for _i, _v in ipairs(upStarRange) do

                                local needRefId, needStar, needNum = _v.needRefId  ,_v.needStar , _v.needNum
                                _condition[needRefId] = _condition[needRefId] or {}
                                _condition[needRefId][needStar] = _condition[needRefId][needStar] or 0
                                _condition[needRefId][needStar] = needNum + _condition[needRefId][needStar]
                            end
                            
                            for _i, _v in ipairs(upStarRange) do
                                if not fuse2 then
                                    break
                                end

                                local needHeroRefId, needHeroStar  =  _v.needRefId,_v.needStar


                                needRefId, needStar, needNum = _v.needRefId, _v.needStar, _v.needNum
                                --local dataList, yinghunItemList = gModelHero:FilterHero(needRefId, needStar, needRefId, id, {}, needNum)

                                local dataList, yinghunItemList = gModelHero:FilterHero(needHeroRefId, needHeroStar, needHeroRefId, id, {})
                                local haveNum = table.keysize(dataList) + table.keysize(yinghunItemList)
                                local selNum = 0
                                for dataIndex, dataVal in ipairs(data) do
                                    for key, value in pairs(dataVal) do
                                        if dataList[key] then
                                            selNum = selNum + 1
                                        end
                                    end
                                end
                                haveNum = haveNum - selNum

                                local checkNeedNum = 0
                                if needHeroRefId == 0 then
                                    for kcondition, condition in pairs(_condition) do
                                        checkNeedNum = checkNeedNum + checknumber(condition[needHeroStar])
                                    end

                                elseif needHeroRefId == 6 then
                                    -- 计算三系列的消耗
                                    -- 1   2  3
                                    for kcondition, condition in pairs(_condition) do
                                        if k ==1 or k == 2 or k == 3 then
                                            checkNeedNum = checkNeedNum + checknumber(condition[needHeroStar])
                                        end
                                    end
                                elseif needHeroRefId == 7 then
                                    --计算光暗 两系的消耗  4  5 
                                    for kcondition, condition in pairs(_condition) do
                                        if kcondition ==4 or kcondition == 5  then
                                            checkNeedNum = checkNeedNum + checknumber(condition[needStar])
                                        end
                                    end

                                else
                                    -- 只需计算0 和自己本身的消耗
                                    for kcondition, condition in pairs(_condition) do
                                        if kcondition ==0 or kcondition== needHeroRefId then
                                            checkNeedNum = checkNeedNum + checknumber(condition[needHeroStar])
                                        end
                                    end
                                end




                                fuse2 = haveNum >= checkNeedNum
                                
                            end
                            if fuse2 then
                                local itemRefId, num
                                for _i, _v in ipairs(upStarItem) do
                                    if not fuse3 then
                                        break
                                    end
                                    itemRefId, num = _v.itemId, _v.itemNum
                                    local haveNum = gModelItem:GetNumByRefId(itemRefId)
                                    fuse3 = haveNum >= num
                                end
                            end
                        end
                        local temp = 0
                        local fuse = fuse1 and fuse2 and fuse3
                        if fuse then
                            local maxStar = ref.maxStar
                            local upStarLimit
                            if maxStar < nextStar then
                                upStarLimit = heroUpStarLimit[star]
                            else
                                upStarLimit = heroUpStarLimit[nextStar]
                            end
                            local isAdd = true
                            if upStarLimit then
                                isAdd = upStarLimit <= resonanceLevel
                            end
                            if isAdd then
                                temp = 1
                            end
                        end
                        if status and temp == 1 then
                            getUpStarStatus = true
                        end
                        v:SetFuseStatus(temp)
                        table.insert(sortHeroList, v)
                    end
                    v:SetUpStar(upStar)
                end
            else
                printInfoNR("========== 没有找到对应的refId数据 ：" .. refId)
            end
        end
    end
    if status then
        return getUpStarStatus
    else
        return sortHeroList
    end
end

-- 聚灵殿 转换/置换
function ModelHeroSpirit:GetHeroSortListBySpiritPage3(heroTypeList, needList)
    local changeHeroSort = gModelHero:GeConfigByKey("changeHeroSort")
    if changeHeroSort == nil then
        changeHeroSort = "3=3;2=2;1=1"
    end
    local sortList = {}
    changeHeroSort = string.split(changeHeroSort, ";")
    for i, v in ipairs(changeHeroSort) do
        v = string.split(v, "=")
        local race, sort = tonumber(v[1]), tonumber(v[2])
        sortList[race] = sort
    end
    local heroList = gModelHero:GetHeroList()
    if not heroList then
        return {}
    end
    local sortHeroList = {}
    for k, v in pairs(heroList) do
        local refId, star = v._refId, v._star
        if heroTypeList then
            if needList[star] then
                local ref = gModelHero:GetHeroRef(refId)
                if ref then
                    local raceType = ref.raceType
                    if heroTypeList[raceType] then
                        table.insert(sortHeroList, v)
                    end
                else
                    printInfoNR("========== 没有找到对应的refId数据 ：" .. refId)
                end
            end
        else
            table.insert(sortHeroList, v)
        end
    end

    --[[	table.sort(sortHeroList,function(hero1,hero2)
            local status1,status2 = hero1:GetStatus(),hero2:GetStatus()
            if status1 == status2 and status1 == 0 then
                local star1,star2 = hero1:GetStar(),hero2:GetStar()
                if star1 == star2 then
                    local lv1,lv2 = hero1:GetLv(),hero2:GetLv()
                    if lv1 == lv2 then
                        local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                        if refId1 == refId2 then
                            local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                            if pow1 == pow2 then
                                local id1,id2 = hero1:GetId(),hero2:GetId()
                                return id1 > id2
                            else
                                return pow1 < pow2
                            end
                        else
                            return refId1 < refId2
                        end
                    else
                        return lv1 < lv2
                    end
                else
                    return star1 < star2
                end
            elseif status1 == status2 and status1 == 1 then
                local combat1,combat2 = hero1:GetCombatStatus(),hero2:GetCombatStatus()
                if combat1 ~= combat2 then
                    return combat1 > combat2
                else
                    local lock1,lock2 = hero1:GetLockStatus(),hero2:GetLockStatus()
                    if lock1 ~= lock2 then
                        return lock1 > lock2
                    else
                        local resonance1,resonance2 = hero1:GetResonanceStatus(),hero2:GetResonanceStatus()
                        if resonance1 ~= resonance2 then
                            return resonance1 > resonance2
                        else
                            local star1,star2 = hero1:GetStar(),hero2:GetStar()
                            if star1 == star2 then
                                local lv1,lv2 = hero1:GetLv(),hero2:GetLv()
                                if lv1 == lv2 then
                                    local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                    if refId1 == refId2 then
                                        local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                        if pow1 == pow2 then
                                            local id1,id2 = hero1:GetId(),hero2:GetId()
                                            return id1 > id2
                                        else
                                            return pow1 < pow2
                                        end
                                    else
                                        return refId1 < refId2
                                    end
                                else
                                    return lv1 < lv2
                                end
                            else
                                return star1 < star2
                            end
                        end
                    end
                end
            else
                return status1 < status2
            end
        end)]]

    table.sort(sortHeroList, function(hero1, hero2)
        local status1, status2 = hero1:GetStatus(), hero2:GetStatus()
        if status1 == status2 and status1 == 0 then
            local star1, star2 = hero1:GetStar(), hero2:GetStar()
            if star1 == star2 then
                local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                local race1, race2 = gModelHero:GetHeroRace(refId1), gModelHero:GetHeroRace(refId2)
                if race1 == race2 then
                    local q1, q2 = gModelHero:GetHeroInitQualityByRefId(refId1), gModelHero:GetHeroInitQualityByRefId(refId2)
                    if q1 == q2 then
                        return refId1 < refId2
                    else
                        return q1 < q2
                    end
                else
                    return sortList[race1] < sortList[race2]
                end
            else
                return star1 > star2
            end
        elseif status1 == status2 and status1 == 1 then
            local star1, star2 = hero1:GetStar(), hero2:GetStar()
            if star1 == star2 then
                local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                local race1, race2 = gModelHero:GetHeroRace(refId1), gModelHero:GetHeroRace(refId2)
                if race1 == race2 then
                    local q1, q2 = gModelHero:GetHeroInitQualityByRefId(refId1), gModelHero:GetHeroInitQualityByRefId(refId2)
                    if q1 == q2 then
                        return refId1 < refId2
                    else
                        return q1 < q2
                    end
                else
                    return sortList[race1] < sortList[race2]
                end
            else
                return star1 > star2
            end
        else
            return status1 < status2
        end
    end)

    return sortHeroList
end

-- 聚灵殿 重生/回退/转生
function ModelHeroSpirit:GetHeroSortListBySpiritPage4(heroTypeList, needList, tabIndex)
    local tempNeedList = {}
    if type(needList) == "table" then
        tempNeedList[1] = tonumber(needList[1])
        tempNeedList[2] = tonumber(needList[2])
    end
    local heroList = gModelHero:GetHeroList()
    if not heroList then
        return {}
    end
    local sortHeroList = {}
    for k, v in pairs(heroList) do
        local refId, star, level = v._refId, v._star, v._realLevel
        if heroTypeList then
            local ref = gModelHero:GetHeroRef(refId)
            if ref then
                local raceType = ref.raceType
                if heroTypeList[raceType] then
                    if needList then
                        if tabIndex == 1 then
                            if level >= needList then
                                table.insert(sortHeroList, v)
                            end
                        else
                            if star >= tempNeedList[1] and star <= tempNeedList[2] then
                                table.insert(sortHeroList, v)
                            end
                        end
                    else
                        table.insert(sortHeroList, v)
                    end
                end
            else
                printInfoNR("========== 没有找到对应的refId数据 ：" .. refId)
            end
        else
            table.insert(sortHeroList, v)
        end
    end
    table.sort(sortHeroList, function(hero1, hero2)
        local status1, status2 = hero1:GetStatus(), hero2:GetStatus()
        if status1 == status2 and status1 == 0 then
            local star1, star2 = hero1:GetStar(), hero2:GetStar()
            if star1 == star2 then
                local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
                if lv1 == lv2 then
                    --[[					local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                        if pow1 == pow2 then
                                            local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                            if refId1 == refId2 then
                                                local id1,id2 = hero1:GetId(),hero2:GetId()
                                                return id1 > id2
                                            else
                                                return refId1 < refId2
                                            end
                                        else
                                            return pow1 < pow2
                                        end]]
                    local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                    if refId1 == refId2 then
                        local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
                        if pow1 == pow2 then
                            local id1, id2 = hero1:GetId(), hero2:GetId()
                            return id1 > id2
                        else
                            return pow1 < pow2
                        end
                    else
                        return refId1 < refId2
                    end
                else
                    return lv1 < lv2
                end
            else
                return star1 < star2
            end
        elseif status1 == status2 and status1 == 1 then
            local combat1, combat2 = hero1:GetCombatStatus(), hero2:GetCombatStatus()
            if combat1 ~= combat2 then
                return combat1 > combat2
            else
                local lock1, lock2 = hero1:GetLockStatus(), hero2:GetLockStatus()
                if lock1 ~= lock2 then
                    return lock1 > lock2
                else
                    local resonance1, resonance2 = hero1:GetResonanceStatus(), hero2:GetResonanceStatus()
                    if resonance1 ~= resonance2 then
                        return resonance1 > resonance2
                    else
                        local star1, star2 = hero1:GetStar(), hero2:GetStar()
                        if star1 == star2 then
                            local lv1, lv2 = hero1:GetLv(), hero2:GetLv()
                            if lv1 == lv2 then
                                --[[								local pow1,pow2 = hero1:GetPower(),hero2:GetPower()
                                                                if pow1 == pow2 then
                                                                    local refId1,refId2 = hero1:GetRefId(),hero2:GetRefId()
                                                                    if refId1 == refId2 then
                                                                        local id1,id2 = hero1:GetId(),hero2:GetId()
                                                                        return id1 > id2
                                                                    else
                                                                        return refId1 < refId2
                                                                    end
                                                                else
                                                                    return pow1 < pow2
                                                                end]]
                                local refId1, refId2 = hero1:GetRefId(), hero2:GetRefId()
                                if refId1 == refId2 then
                                    local pow1, pow2 = hero1:GetPower(), hero2:GetPower()
                                    if pow1 == pow2 then
                                        local id1, id2 = hero1:GetId(), hero2:GetId()
                                        return id1 > id2
                                    else
                                        return pow1 < pow2
                                    end
                                else
                                    return refId1 < refId2
                                end
                            else
                                return lv1 < lv2
                            end
                        else
                            return star1 < star2
                        end
                    end
                end
            end
        else
            return status1 < status2
        end
    end)
    return sortHeroList
end

-- 英雄共鸣
function ModelHeroSpirit:HeroUnResonanceOpt(opt)
    local func, heroId = opt.func, opt.heroId
    if (not func) and (not heroId) then
        LogError("没有设置回调函数或英雄Id")
        return
    end
    local wndId = 50906
    func = func or function()
        local pos = gModelResonance:GetResonanceHeroPos(heroId)
        if pos then
            gModelResonance:OnResonanceHeroReq(heroId, pos, 2)
        end
    end

    local resonanceTime = GameTable.LevelShareConfigRef["resonanceTime"]
    local subTime = gModelGrade:GetHeroResonanceEffectValue()
    resonanceTime = resonanceTime - subTime
    local hour = math.floor(resonanceTime / 3600)
    gModelGeneral:OpenUIOrdinTips({ refId = wndId, func = func, para = { hour } })

    --local openFunc = function() GF.OpenWnd("UIOrdinTip",{refId = wndId,func = func}) end
    --gModelGeneral:ShowUIOrdinTip(wndId,func,openFunc)
end

-- 英雄下阵
function ModelHeroSpirit:HeroUnCombatOpt(opt)
    local func, heroId = opt.func, opt.heroId
    if (not func) and (not heroId) then
        LogError("没有设置回调函数或英雄Id")
        return
    end
    local wndId = 50901
    func = func or function()
        gModelFormation:OnHeroRemoveFormationReq(heroId)
    end

    gModelGeneral:OpenUIOrdinTips({ refId = wndId, func = func })
    --local openFunc = function() GF.OpenWnd("UIOrdinTip",{refId = wndId,func = func}) end
    --gModelGeneral:ShowUIOrdinTip(wndId,func,openFunc)
end

-- 英雄解锁
function ModelHeroSpirit:HeroUnLockOpt(opt)
    local func, heroId = opt.func, opt.heroId
    if (not func) and (not heroId) then
        LogError("没有设置回调函数或英雄Id")
        return
    end
    local wndId = 50902
    func = func or function()
        gModelHero:OnHeroLockReq(heroId, 1)
    end
    gModelGeneral:OpenUIOrdinTips({ refId = wndId, func = func })
    --local openFunc = function() GF.OpenWnd("UIOrdinTip",{refId = wndId,func = func}) end
    --gModelGeneral:ShowUIOrdinTip(wndId,func,openFunc)
end

function ModelHeroSpirit:ClearUpStarSelHeroList()
    self._upStarSelHero = {}
end

function ModelHeroSpirit:SetSelHeroId(id)
    local selHeroList = self._upStarSelHero
    if not selHeroList then
        selHeroList = {}
        self._upStarSelHero = selHeroList
    end
    local b = self:IsHeroIdSel(id)
    if b then
        selHeroList[id] = nil
    else
        selHeroList[id] = id
    end
end

-- true:选中了 false:没选中
function ModelHeroSpirit:IsHeroIdSel(id)
    local selHeroList = self._upStarSelHero
    if table.isempty(selHeroList) then
        return false
    end
    if selHeroList[id] then
        return true
    else
        return false
    end
end

function ModelHeroSpirit:FilterHero(hRefId, hStar, hType, selHeroId, selHeroList, needNum)
    local filterList = {}
    -- 英雄筛选
    local heroList = gModelHero:GetHeroList()
    if heroList then
        for k, v in pairs(heroList) do
            local data
            local id = v:GetId()
            local heroStatus = v:GetStatus()
            if id ~= selHeroId and heroStatus == 0 then
                if hType then
                    local star = v:GetStar()
                    if hType == 0 and star == hStar then
                        if selHeroList[id] then
                            data = v
                        else
                            if not self:IsHeroIdSel(id) then
                                data = v
                            end
                        end
                    else
                        local refId = v:GetRefId()
                        local heroRef = gModelHero:GetHeroRef(refId)
                        if heroRef then
                            local rType = heroRef.raceType
                            if rType == hType and star == hStar then
                                if selHeroList[id] then
                                    data = v
                                else
                                    if not self:IsHeroIdSel(id) then
                                        data = v
                                    end
                                end
                            end
                        end
                    end
                else
                    local refId = v:GetRefId()
                    local star = v:GetStar()
                    if refId == hRefId and star == hStar then
                        if selHeroList[id] then
                            data = v
                        else
                            if not self:IsHeroIdSel(id) then
                                data = v
                            end
                        end
                    end
                end
            end
            if data then
                filterList[k] = data
            end
        end
    end
    local serHeroRace
    if selHeroId then
        local refId = gModelHero:GetRefIdById(selHeroId)
        local ref = gModelHero:GetHeroRef(refId)
        if ref then
            serHeroRace = ref.raceType
        end
    end
    local itemList = {}
    if hType then
        -- 英魂筛选(道具)
        local bagYingHunList = gModelItem:GetBagYingHunList()
        for k, v in pairs(bagYingHunList) do
            local itemRefData = gModelItem:GetYingHunRefByRefId(k)
            if itemRefData then
                local isIns = false
                local refRace, refStar = itemRefData.race, itemRefData.star
                if serHeroRace and serHeroRace == refRace and refStar == hStar then
                    isIns = true
                elseif refRace == 0 and refStar == hStar then
                    isIns = true
                elseif refRace == hType and refStar == hStar then
                    isIns = true
                elseif refStar == hStar then
                    local other = ModelItem.RaceTypeList[refRace]
                    isIns = other and other[hType] or false
                end
                if isIns then
                    local itemStruct = gModelItem:GetItemServerDataByRefId(k)
                    if itemStruct then
                        local num = itemStruct._num
                        for i = 1, num do
                            if needNum and needNum < i then
                                break
                            end
                            local key = "itemRace_" .. refRace .. "_" .. i
                            itemList[key] = itemStruct
                        end
                    end
                end
            end
        end
    end
    return filterList, itemList
end

function ModelHeroSpirit:CheckIsCanUpStar(heroRefId, star, id)
    local fuse = false
    local upStarInfo = gModelHero:GetUpStarHeroInfoByHeroRefIdAndStar(heroRefId, star)
    if upStarInfo then
        local heroUpStarLimit = gModelHeroSpirit:GetUpStarLimit()
        local selHeroList = {}
        local fuse1, fuse2, fuse3 = true, true, true
        local upStarAppoint, upStarRange, upStarItem = upStarInfo.upStarAppoint, upStarInfo.upStarRange, upStarInfo.upStarItem
        for i, v in ipairs(upStarAppoint) do
            if not fuse1 then
                break
            end
            local needRefId, needStar, needNum = v.needRefId, v.needStar, v.needNum
            local dataList = self:FilterHero(needRefId, needStar, nil, id, {}, needNum)
            local haveNum = table.keysize(dataList)
            local tempList = {}
            local aaa = 0
            for key, val in pairs(dataList) do
                if aaa >= needNum then
                    break
                end
                tempList[key] = val
                aaa = aaa + 1
            end
            table.insert(selHeroList, tempList)
            fuse1 = haveNum >= needNum
        end
        for i, v in ipairs(upStarRange) do
            if not fuse2 then
                break
            end
            local needRefId, needStar, needNum = v.needRefId, v.needStar, v.needNum
            local dataList, yinghunItemList = self:FilterHero(needRefId, needStar, needRefId, id, {}, needNum)
            local haveNum = table.keysize(dataList) + table.keysize(yinghunItemList)
            local selNum = 0
            for dataIndex, dataVal in ipairs(selHeroList) do
                for key, value in pairs(dataVal) do
                    if dataList[key] then
                        selNum = selNum + 1
                    end
                end
            end
            haveNum = haveNum - selNum
            fuse2 = haveNum >= needNum
        end
        for i, v in ipairs(upStarItem) do
            if not fuse3 then
                break
            end
            local itemRefId, num = v.itemId, v.itemNum
            local haveNum = gModelItem:GetNumByRefId(itemRefId)
            fuse3 = haveNum >= num
        end
        fuse = fuse1 and fuse2 and fuse3
        if heroUpStarLimit then
            local maxStar = gModelHero:GetMaxStarByRefId(heroRefId)
            local upStarLimit
            local nextStar = star + 1
            if maxStar < nextStar then
                upStarLimit = heroUpStarLimit[star]
            else
                upStarLimit = heroUpStarLimit[nextStar]
            end
            if upStarLimit then
                -- 魔镜等级小于限制等级，显示文字隐藏按钮
                local resonanceLevel = gModelResonance:GetResonanceLv()
                if resonanceLevel < upStarLimit then
                    fuse = false
                end
            end
        end
    end
    return fuse
end

-- 一键升星机制
function ModelHeroSpirit:CheckAutoUpStarHeroStatus()
    local status = false
    local isOpen = gModelFunctionOpen:CheckIsOpened(16200201)
    if not isOpen then
        return status
    end
    local heroStarList = gModelHero:GetStarHeroList()
    for idx, heroInfo in ipairs(heroStarList) do
        if status then
            break
        end
        local refId, star, id = heroInfo.refId, heroInfo.star, heroInfo.id
        status = self:CheckIsCanUpStar(refId, star, id)
    end
    return status
end

function ModelHeroSpirit:GetAutoUpStarHeroList()
    local resonanceLevel = gModelResonance:GetResonanceLv()
    local heroUpStarLimit = gModelHeroSpirit:GetUpStarLimit()
    local allSelHeroIdKeyList = {}
    local allSelItemIdKeyList = {}
    local allSelHeroList = {}
    local heroStarList, refIdNumList = gModelHero:GetStarHeroList()
    table.sort(heroStarList, function(a, b)
        local refIdA, refIdB = a.refId, b.refId
        local haveNumA, haveNumB = refIdNumList[refIdA] or 1, refIdNumList[refIdB] or 1
        if haveNumA ~= haveNumB then
            return haveNumA > haveNumB
        else
            local fightPowerA, fightPowerB = a.fightPower, b.fightPower
            if fightPowerA ~= fightPowerB then
                return fightPowerA > fightPowerB
            else
                return refIdA > refIdB
            end
        end
    end)
    local curSelRefId = nil
    local sortFunc = function(a, b)
        local refIdA, refIdB = a:GetRefId(), b:GetRefId()
        local isSameSelA = refIdA == curSelRefId and 1 or 0
        local isSameSelB = refIdB == curSelRefId and 1 or 0
        if isSameSelA ~= isSameSelB then
            return isSameSelA < isSameSelB
        else
            local haveNumA, haveNumB = refIdNumList[refIdA] or 1, refIdNumList[refIdB] or 1
            if haveNumA ~= haveNumB then
                return haveNumA < haveNumB
            else
                local fightPowerA, fightPowerB = a:GetPower(), b:GetPower()
                if fightPowerA ~= fightPowerB then
                    return fightPowerA < fightPowerB
                else
                    return refIdA < refIdB
                end
            end
        end
    end
    for idx, heroInfo in ipairs(heroStarList) do
        local refId, star = heroInfo.refId, heroInfo.star
        local upStarInfo = gModelHero:GetUpStarHeroInfoByHeroRefIdAndStar(refId, star)
        if upStarInfo then
            local id = heroInfo.id
            if not allSelHeroIdKeyList[id] then
                local tData = {}
                local appointedlist = {}
                local rangelist = {}
                local rangItemList = {}
                tData.appointedlist = appointedlist
                tData.rangelist = rangelist
                tData.rangItemList = rangItemList
                curSelRefId = refId
                local fuse1, fuse2, fuse3 = true, true, true
                local upStarAppoint, upStarRange, upStarItem = upStarInfo.upStarAppoint, upStarInfo.upStarRange, upStarInfo.upStarItem
                for index, refData in ipairs(upStarAppoint) do
                    local tAppointedList = {}
                    appointedlist[index] = tAppointedList
                    if not fuse1 then
                        break
                    end
                    local needRefId, needStar, needNum = refData.needRefId, refData.needStar, refData.needNum
                    local dataList = self:FilterHero(needRefId, needStar, nil, id, {}, needNum)
                    local num = 0
                    local filtrateList = {}
                    for k, v in pairs(dataList) do
                        local tId = v:GetId()
                        local heroStatus = v:GetStatus()
                        if not allSelHeroIdKeyList[tId] and heroStatus == 0 then
                            table.insert(filtrateList, v)
                            num = num + 1
                        end
                    end
                    if num > 0 then
                        table.sort(filtrateList, sortFunc)
                        local addNum = 0
                        for i, v in ipairs(filtrateList) do
                            if i > needNum then
                                break
                            end
                            local tId = v:GetId()
                            allSelHeroIdKeyList[tId] = tId
                            tAppointedList[tId] = tId
                            addNum = addNum + 1
                        end
                        fuse1 = addNum >= needNum
                    else
                        fuse1 = false
                    end
                end
                if fuse1 then
                    for index, refData in ipairs(upStarRange) do
                        local tRangelist = {}
                        rangelist[index] = tRangelist
                        if not fuse2 then
                            break
                        end
                        local needRefId, needStar, needNum = refData.needRefId, refData.needStar, refData.needNum
                        local dataList = self:FilterHero(needRefId, needStar, needRefId, id, {}, needNum)
                        local num = 0
                        local filtrateList = {}
                        for k, v in pairs(dataList) do
                            local tId = v:GetId()
                            local heroStatus = v:GetStatus()
                            if not allSelHeroIdKeyList[tId] and heroStatus == 0 then
                                table.insert(filtrateList, v)
                                num = num + 1
                            end
                        end
                        if num > 0 then
                            table.sort(filtrateList, sortFunc)
                            local addNum = 0
                            for i, v in ipairs(filtrateList) do
                                if i > needNum then
                                    break
                                end
                                local tId = v:GetId()
                                allSelHeroIdKeyList[tId] = tId
                                tRangelist[tId] = tId
                                addNum = addNum + 1
                            end
                            fuse2 = addNum >= needNum
                            if not fuse2 then
                                for k, v in pairs(tRangelist) do
                                    allSelHeroIdKeyList[k] = nil
                                end
                            end
                        else
                            fuse2 = false
                        end
                    end
                else
                    fuse2 = false
                end
                if fuse1 and fuse2 then
                    for index, refData in ipairs(upStarItem) do
                        local tRangItemList = {}
                        rangItemList[index] = tRangItemList
                        if not fuse3 then
                            break
                        end
                        local itemRefId, num = refData.itemId, refData.itemNum
                        local haveNum = gModelItem:GetNumByRefId(itemRefId)
                        local selItemNum = allSelItemIdKeyList[itemRefId] or 0
                        haveNum = haveNum - selItemNum
                        fuse3 = haveNum >= num
                        if fuse3 then
                            tRangItemList[itemRefId] = num
                            allSelItemIdKeyList[itemRefId] = selItemNum + num
                        end
                    end
                else
                    fuse3 = false
                end
                local fuse = fuse1 and fuse2 and fuse3
                if heroUpStarLimit and fuse then
                    local maxStar = gModelHero:GetMaxStarByRefId(refId)
                    local upStarLimit
                    local nextStar = star + 1
                    if maxStar < nextStar then
                        upStarLimit = heroUpStarLimit[star]
                    else
                        upStarLimit = heroUpStarLimit[nextStar]
                    end
                    if upStarLimit then
                        if resonanceLevel < upStarLimit then
                            fuse = false
                        end
                    end
                end
                if fuse then
                    tData.id = id
                    table.insert(allSelHeroList, tData)
                    allSelHeroIdKeyList[id] = id
                else
                    for i, v in ipairs(appointedlist) do
                        for key, val in pairs(v) do
                            allSelHeroIdKeyList[key] = nil
                        end
                    end
                    for i, v in ipairs(rangelist) do
                        for key, val in pairs(v) do
                            allSelHeroIdKeyList[key] = nil
                        end
                    end
                    for i, v in ipairs(rangItemList) do
                        for itemRefId, num in pairs(v) do
                            local selItemIdNum = allSelItemIdKeyList[itemRefId]
                            if selItemIdNum then
                                allSelItemIdKeyList[itemRefId] = selItemIdNum - num
                            end
                        end
                    end
                end
            end
        end
    end
    local len = #allSelHeroList
    local status = len > 0
    return allSelHeroList, status
end

-- 时光沙漏功能
function ModelHeroSpirit:GetHeroReturnRefId(returnType, race, star, returnStar)
    local heroReturnKeyList = self._heroReturnKeyList
    if heroReturnKeyList then
        local typeInfo = heroReturnKeyList[returnType] or {}
        local raceInfo = typeInfo[race] or {}
        local starInfo = raceInfo[star] or {}
        return starInfo[returnStar]
    end
end

function ModelHeroSpirit:UseItemReturnHeroRewardList(itemRefId, heroServerData)
    if not heroServerData then
        return {}
    end
    if not itemRefId then
        return {}
    end
    local itemInfo = gModelItem:GetTimeHourGlassInfoByRefId(itemRefId)
    if not itemInfo then
        return {}
    end
    local star = heroServerData.star
    local heroStar = itemInfo.heroStar
    if star ~= heroStar then
        return {}
    end
    local returnToStar = itemInfo.returnToStar
    local heroRefId = heroServerData.refId
    local lv = heroServerData.lv
    local id = heroServerData.id

    local heroRace = gModelHero:GetHeroType(heroRefId)
    if not heroRace then
        return {}
    end
    local returnRefId = self:GetHeroReturnRefId(ModelHeroSpirit.RETURN_TYPE_3, heroRace, heroStar, returnToStar)
    if not returnRefId then
        return {}
    end
    local returnRef = self:GetHeroReturnRefByRefId(returnRefId)
    if not returnRef then
        return {}
    end
    local fixReward = returnRef.fixReward
    local heroRef = gModelHero:GetHeroRef(heroRefId)
    if not heroRef then
        return {}
    end
    --local starType = heroRef.starType
    --local starId = gModelHero:GetStarId(starType,star)
    local starRef = gModelHero:GetStarRefById(id, star)
    if not starRef then
        return {}
    end
    --local retStarId = gModelHero:GetStarId(starType,returnToStar)
    local retStarRef = gModelHero:GetStarRefById(id, returnToStar)
    if not retStarRef then
        return {}
    end
    local returnPayList = {}
    local retMaxLevel = retStarRef.maxLevel
    if retMaxLevel <= lv then
        local keyList = {}
        local starAndLvList = gModelHero:GetPayItemNumByStarAndEndLv(id, retMaxLevel, lv, retMaxLevel, returnToStar)
        for i, v in ipairs(starAndLvList) do
            local info = keyList[v.refId] or 0
            keyList[v.refId] = info + v.num
        end
        local classType = heroRef.classType
        local sortHeroClassList = gModelHero:GetSortHeroClassRefListByClassType(classType)
        if sortHeroClassList then
            local grade = heroServerData.grade
            for i, v in ipairs(sortHeroClassList) do
                if grade > v.grade and lv >= v.needLevel and v.needStar == star then
                    local needItem = string.split(v.needItem, ",")
                    for idx, val in ipairs(needItem) do
                        val = string.split(val, "=")
                        local tRefId = tonumber(val[2])
                        local tNum = tonumber(val[3])
                        local info = keyList[tRefId] or 0
                        keyList[tRefId] = info + tNum
                    end
                end
            end
        end
        for k, v in pairs(keyList) do
            table.insert(returnPayList, {
                refId = k, num = v
            })
        end
    else
        returnPayList = gModelRune:GetRuneUpItemList(id, lv, returnToStar)
    end
    local returnPayKeyList = {}
    for i, v in ipairs(returnPayList) do
        returnPayKeyList[v.refId] = v.num
    end
    for i, v in ipairs(fixReward) do
        local refId = v.refId
        local tNum = returnPayKeyList[refId] or 0
        returnPayKeyList[refId] = tNum + v.num
    end
    local list = {}
    local itemList = {}
    for k, v in pairs(returnPayKeyList) do
        table.insert(itemList, {
            itemType = LItemTypeConst.TYPE_ITEM,
            itemId = k,
            itemNum = v
        })
    end
    table.sort(itemList, function(a, b)
        local orderA, orderB = gModelItem:GetItemOrderByRefId(a.refId), gModelItem:GetItemOrderByRefId(b.refId)
        return orderA < orderB
    end)
    table.insert(list, {
        itemType = LItemTypeConst.TYPE_HERO,
        itemId = heroRefId,
        itemNum = returnRef.getNoumenonNum,
        returnStar = returnRef.returnStar
    })
    for i, v in ipairs(itemList) do
        table.insert(list, v)
    end
    return list
end

function ModelHeroSpirit:GetReturnItemInfo(itemId, selHeroId)
    if not itemId or not selHeroId then
        return
    end
    local itemInfo = gModelItem:GetTimeHourGlassInfoByRefId(itemId)
    if not itemInfo then
        return
    end
    if not selHeroId then
        return
    end
    local serverData = gModelHero:GetHeroServerDataById(selHeroId)
    if not serverData then
        return
    end
    local heroRefId = serverData.refId
    local raceType = gModelHero:GetHeroType(heroRefId)
    if not raceType then
        return
    end
    local heroStar = itemInfo.heroStar
    local returnToStar = itemInfo.returnToStar
    if not heroStar or not returnToStar then
        return
    end
    local returnRefId = self:GetHeroReturnRefId(ModelHeroSpirit.RETURN_TYPE_3, raceType, heroStar, returnToStar)
    if not returnRefId then
        return
    end
    local returnRef = self:GetHeroReturnRefByRefId(returnRefId)
    if not returnRef then
        return
    end
    local need = returnRef.need or {}
    return need.refId, need.num
end

--清理工作
--停止计时器之类的
function ModelHeroSpirit:OnModelClear()

end

return ModelHeroSpirit