---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BY.
--- DateTime: 2023/10/11 17:27
---
------------------------------------------------------------------
LXImport("..Struct.StructRegressionLoginAward")
LXImport("..Struct.StructRegressionGift")
LXImport("..Struct.StructRegressionMonster")
local LModel = LModel
------------------------------------------------------------------
---@class ModelBackflow:LModel
local ModelBackflow = LxClass("ModelBackflow",LModel)
------------------------------------------------------------------
function ModelBackflow:ModelBackflow()

end

ModelBackflow.BACKFLOW_PAGE_1 = 1           --每日登录
ModelBackflow.BACKFLOW_PAGE_2 = 2           --重逢特权
ModelBackflow.BACKFLOW_PAGE_3 = 3           --回归活跃
ModelBackflow.BACKFLOW_PAGE_4 = 4           --超值特惠
ModelBackflow.BACKFLOW_PAGE_5 = 5           --重回战线

ModelBackflow.TASK_TYPE_91 = 91             --每日任务
ModelBackflow.TASK_TYPE_92 = 92             --周期任务
ModelBackflow.TASK_TYPE_93 = 93             --累计任务

ModelBackflow.SELECT_NEW2_1 = 1             --内置活动 - 回流活动

--模块初始化入口
--注册事件监听
--注册协议监听
--预处理数据
function ModelBackflow:OnModelInit()
    self:InitData()
    self:ModelNetMsgRecv(LProtoIds.RegressionInfoResp,function(...) self:OnRegressionInfoResp(...) end)
    -- self:ModelNetMsgRecv(LProtoIds.RegressionLoginAwardResp,function(...) self:OnRegressionLoginAwardResp(...) end)
    self:ModelNetMsgRecv(LProtoIds.RegressionPrivilegeResp,function(...) self:OnRegressionPrivilegeResp(...) end)
    -- self:ModelNetMsgRecv(LProtoIds.RegressionGiftResp,function(...) self:OnRegressionGiftResp(...) end)
    -- self:ModelNetMsgRecv(LProtoIds.RegressionMonsterResp,function(...) self:OnRegressionMonsterResp(...) end)
end

function ModelBackflow:OnModelRequest()
    self:ModelFinish()
end

--清理工作
--停止计时器之类的
function ModelBackflow:OnModelClear()

end
function ModelBackflow:InitData()
    local _taskByQuestList = {}
    for i, v in pairs(GameTable.ReturnBackActiveTaskRef) do
        _taskByQuestList[v.quest] = v
    end
    self._taskByQuestList = _taskByQuestList
end
----------------------------------------------
-- Msg Begin
--回归相关数据，登陆收到该协议，说明活动开启
function ModelBackflow:OnRegressionInfoResp(pb)
    local _endTime = pb.endTime or 0
    local rewardAddition = pb.rewardAddition or 100
    local shopEndTime = pb.shopEndTime
    self._endTime = _endTime
    self._rewardAddition = rewardAddition
    self._shopEndTime = shopEndTime
    if tonumber(_endTime) <= 0 or GetTimestamp() > tonumber(pb.endTime)/1000 then
        GF.CloseWndByName("UIBackin")
        return
    end
    self:RegressionPrivilegeReq()
end
--请求登陆奖励信息
function ModelBackflow:RegressionLoginAwardReq(day)
    local pb = LProtoHelper.CreateProto(LProtoIds.RegressionLoginAwardReq)
    pb.day = day or 0                       --day == 0：请求所有登陆奖励信息；day > 0:领取固定和挂机奖励
    SendMessage(pb,LProtoIds.RegressionLoginAwardReq)
end
function ModelBackflow:OnRegressionLoginAwardResp(pb)
    local day = pb.day                      --请求所有登陆奖励信息；refId>0:领取指定天的奖励
    local awardInfo = pb.awardInfo          --登陆奖励信息
    local list = self._awardInfo or {}
    if day <= 0 then
        list = {}
    end
    for i, v in ipairs(awardInfo) do
        local info = StructRegressionLoginAward:New()
        info:CreateByPb(v)
        list[info.day] = info
    end
    self._awardInfo = list
end
--获得特权信息
function ModelBackflow:RegressionPrivilegeReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.RegressionPrivilegeReq)
    SendMessage(pb,LProtoIds.RegressionPrivilegeReq)
end
function ModelBackflow:OnRegressionPrivilegeResp(pb)
    local refIds = pb.refId
    local list = {}
    for i, v in ipairs(refIds) do
        local ref = gModelBackflow:GetRegressionPrivilegesShowRefByRefId(v)
        if not ref then
            printErrorN("ModelBackflow nil ref RegressionPrivilegesRef :"..v)
        else
            local type = ref.Type
            local _list = list[type] or {}
            table.insert(_list,ref)
            list[type] = _list
        end
    end
    self._privilegesTypeList = list
end
--获得直购礼包信息
function ModelBackflow:RegressionGiftReq(type,refId,selected)
    local pb = LProtoHelper.CreateProto(LProtoIds.RegressionGiftReq)
    pb.type = type                                  --type == 1请求所有礼包信息;type == 2保存;type == 3购买;
    pb.refId = refId or 0                           --直购礼包refId ==0时请求所有礼包信息，>0时：选定某个礼包固定奖励
    if selected then
        pb.selected = selected                      --选择奖励 ","分割
    end
    SendMessage(pb,LProtoIds.RegressionGiftReq)
end
function ModelBackflow:OnRegressionGiftResp(pb)
    local type = pb.type                            --type == 1请求所有礼包信息;type == 2保存;type == 3购买;
    local refId = pb.refId                          --直购礼包refId ==0时请求所有礼包信息，>0时：选定某个礼包固定奖励
    local giftList = pb.giftList                    --可购买礼包列表
    local list = self._giftList or {}
    if type == 1 then
        list = {}
    end
    for i, v in ipairs(giftList) do
        local info = StructRegressionGift:New()
        info:CreateByPb(v)
        list[info.refId] = info
    end
    self._giftList = list
end
function ModelBackflow:RegressionMonsterReq()
    local pb = LProtoHelper.CreateProto(LProtoIds.RegressionMonsterReq)
    SendMessage(pb,LProtoIds.RegressionMonsterReq)
end
function ModelBackflow:OnRegressionMonsterResp(pb)
    local refIds = pb.refId
    local endTime = pb.endTime
    local list = {}
    for i, v in ipairs(refIds) do
        local info = StructRegressionMonster:New()
        info:CreateByPb(v)
        table.insert(list,info)
    end
    self._monsterInfos = list
    self._monsterEndTime = endTime
end
----------------------------------------------
-- Get pb
--活动剩余时间
function ModelBackflow:GetResidueTime()
    local _endTime = self._endTime or 0
    local time = tonumber(_endTime)/1000 - GetTimestamp()
    return time
end
function ModelBackflow:GetRewardAddition()
    local _rewardAddition = self._rewardAddition
    return _rewardAddition and _rewardAddition/100 or 1
end
function ModelBackflow:GetShopEndTime()
    local _shopEndTime = self._shopEndTime
    return _shopEndTime and tonumber(_shopEndTime)/1000 or 0
end
--登录奖励信息
function ModelBackflow:GetAwardInfos()
    local list = {}
    for i, v in pairs(self._awardInfo) do
        table.insert(list,v)
    end
    return list
end
function ModelBackflow:GetPrivilegesTypeList()
    local list = self._privilegesTypeList or {}
    local _list = {}
    for i, v in pairs(list) do
        table.insert(_list,{type = i,showList = v})
    end
    return _list
end
function ModelBackflow:GetPrivilegesTypeListByType(type)
    local list = self._privilegesTypeList or {}
    return list[type]
end
--超值特惠礼包列表
function ModelBackflow:GetGiftList()
    return self._giftList
end
--当天重返火线boss列表
function ModelBackflow:GetMonsterInfo()
    return self._monsterInfos or {} ,self._monsterEndTime or 0
end
-- Get config
function ModelBackflow:RegressionConfigRefByKey(key)
    return GameTable.ReturnBackConfigRef[key]
end
function ModelBackflow:RegressionBackflowRefByRefId(refId)
    return GameTable.ReturnBackBackflowRef[refId]
end
function ModelBackflow:RegressionBackflowRef()
    local list = {}
    for i, v in pairs(GameTable.ReturnBackBackflowRef) do
        table.insert(list,v)
    end
    table.sort(list,function (a,b)
        return a.refId < b.refId
    end)
    return list
end
function ModelBackflow:RegressionFixedRewardRefByRefId(refId)
    return GameTable.ReturnBackFixedRewardRef[refId]
end
function ModelBackflow:RegressionOnhookRewardRefByRefId(refId)
    return GameTable.RegressionOnhookRewardRef[refId]
end
function ModelBackflow:GetRegressionPrivilegesRefByRefId(refId)
    return GameTable.RegressionPrivilegesRef[refId]
end
function ModelBackflow:GetRegressionPrivilegesShowRefByRefId(refId)
    return GameTable.ReturnBackPrivilegesShowRef[refId]
end
function ModelBackflow:RegressionPrivilegesShowRefByType(type)
    for i, v in pairs(GameTable.ReturnBackPrivilegesShowRef) do
        if v.Type == type then
            return v
        end
    end
    return nil
end
function ModelBackflow:RegressionActiveTaskRefByQuest(quest)
    local ref = self._taskByQuestList[quest]
    if not ref then
        return false
    end
    local functionOpen = ref.functionOpen
    if functionOpen <= 0 then
        return true
    end
    local bool = gModelFunctionOpen:CheckIsOpened(functionOpen,false)
    return bool
end
function ModelBackflow:RegressionPreferentialRefByRefId(refId)
    return GameTable.ReturnBackPreferentialRef[refId]
end
function ModelBackflow:RegressionChallengeRefByRefId(refId)
    return GameTable.ReturnBackChallengeRef[refId]
end
function ModelBackflow:RegressionChallengeRef()
    local list = {}
    for i, v in pairs(GameTable.ReturnBackChallengeRef) do
        table.insert(list,v)
    end
    table.sort(list,function (a,b)
        return a.refId < b.refId
    end)
    return list
end
-- Msg End
----------------------------------------------
-- Func Begin
--function ModelBackflow:SetPrivileBtn(btnTr,type,holdWnd)
--    local list = self:GetPrivilegesTypeListByType(type)
--    CS.ShowObject(btnTr,list)
--    if list and btnTr then
--        local text = holdWnd:FindWndTrans(btnTr,"Root/name")
--        if text then
--            holdWnd:SetWndText(text, ccClientText(23515))
--        end
--        holdWnd:SetWndClick(btnTr, function ()
--            self:ShowPriviTips(btnTr,type,holdWnd)
--        end)
--
--        self:ShowPriviTips(btnTr,type,holdWnd,true)
--    end
--    return list
--end
-----@param holdWnd LWnd
--function ModelBackflow:ShowPriviTips(btnTran,type,holdWnd,delayClose)
--    local list = self:GetPrivilegesTypeListByType(type)
--    if not list then
--        return
--    end
--
--    local strList = {}
--    for i, v in ipairs(list) do
--        local ref = GameTable.SysBuffRef[v.sysbuff]
--        table.insert(strList,ccLngText(ref.desc))
--    end
--
--    local desc = table.concat(strList,"\n")
--    local tipTran = holdWnd:FindWndTrans(btnTran,"tips")
--    holdWnd:SetTextTile(tipTran,desc)
--
--    if not delayClose then
--        return
--    end
--
--    local seqCom = holdWnd:GetSeqCom()
--    local seq = seqCom:CreateSeq("delayHideTip")
--    seq:AppendInterval(2)
--    local canvasGroup = holdWnd:GetCanvasGroup(tipTran)
--    local tween = canvasGroup:DOFade(0,0.5)
--    seq:Append(tween)
--    seq:OnComplete(function ()
--        seqCom:DeleteSeq("delayHideTip")
--        CS.ShowObject(tipTran,false)
--    end)
--    seq:PlayForward()
--end

--function ModelBackflow:OnClickPrivile(btnTr,type,openType)
--    local list = self:GetPrivilegesTypeListByType(type)
--    if not list then
--        return
--    end
--    local wndIns = GF.FindFirstWndByName("UIActMinGame")
--    if wndIns then return end
--    local _list = {}
--    for i, v in ipairs(list) do
--        local ref = GameTable.SysBuffRef[v.sysbuff]
--        table.insert(_list,ccLngText(ref.desc))
--    end
--    local para = {
--        name = ccClientText(23515),
--        icon = "achievement_icon7",
--        list = _list
--    }
--    GF.OpenWnd("UIPrigeTips",{root = btnTr,para = para,type = openType})
--end
function ModelBackflow:GetBackShopIsOpent()
    local _shopEndTime = self:GetShopEndTime()
    local endTime = _shopEndTime
    if endTime <= 0 then
        return false
    end
    local time = GetTimestamp()
    local timespan = endTime - time
    if timespan <= 0 then
        return false
    end
    return true
end
-- Func End

function ModelBackflow:IsActivityOpen()
    return self:GetResidueTime() > 0
end
----------------------------------------------
return ModelBackflow