---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 14:40
---
------------------------------------------------------------------
---模块使用示例 需要在LModelManager的列表里填写名字
---创建完之后可以使用gModelHeroExtra全局变量访问实例
------------------------------------------------------------------
LXImport("..Struct.StructTemplate")
local LModel = LModel
------------------------------------------------------------------
---@class ModelHeroExtra:LModel
local ModelHeroExtra = LxClass("ModelHeroExtra",LModel)

--- UINewSagaInfo：伙伴预览界面
--- UIGolemMain：魔偶界面
--- UISaga：伙伴列表界面
--- UISagaSpreadNew：伙伴分享界面

--- 最多显示字符数
ModelHeroExtra.NAME_MAX_CHARNUM = 8

------------------------------------------------------------------
function ModelHeroExtra:ModelHeroExtra()
end

--模块初始化入口
--注册事件监听
--注册协议监听
--预处理数据
function ModelHeroExtra:OnModelInit()
	self:ModelNetMsgRecv(LProtoIds.HeroSetNameResp,function (...) self:OnHeroSetNameResp(...) end)
	self:ModelNetMsgRecv(LProtoIds.HeroFavorabilityInfoResp,function (...) self:OnHeroFavorabilityInfoResp(...) end)
	self:ModelNetMsgRecv(LProtoIds.HeroSetShowResp, function(...) self:OnHeroSetShowResp(...) end)
	self:ModelNetMsgRecv(LProtoIds.HeroGiveGiftResp, function(...) self:OnHeroGiveGiftResp(...) end)
	self:ModelNetMsgRecv(LProtoIds.HeroInteractionResp, function(...) self:OnHeroInteractionResp(...) end)
	-- self:ModelNetMsgRecv(LProtoIds.HeroInteractQuestResp, function(...) self:OnHeroInteractQuestResp(...) end)
	self:ModelNetMsgRecv(LProtoIds.HeroInteractGameOpsResp, function(...) self:OnHeroInteractGameOpsResp(...) end)

	self:InitHeroFavorabilityRef()
end


--在协议数据处理完之后需要调用finish
function ModelHeroExtra:OnModelRequest()
	self:ModelFinish()
end
-- 童话英雄改版修改，宠物验收反馈优化修改，攻略芳心通关章节优化，调整英雄品质读取方式
---------------------------------------------------------------------------
--- req
function ModelHeroExtra:OnHeroSetNameReq(heroId,name)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroSetNameReq)
	pb.heroId = heroId
	pb.name = name
	SendMessage(pb,LProtoIds.HeroSetNameReq)
end

function ModelHeroExtra:OnHeroSetShowReq(heroEffId)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroSetShowReq)
	pb.effectId = heroEffId
	SendMessage(pb,LProtoIds.HeroSetShowReq)
end
function ModelHeroExtra:OnHeroGiveGiftReq(id,itemData)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroGiveGiftReq)
	pb.refId = id
	for k,v in pairs(itemData) do
		local item = pb.items:add()
		item.refId = v._refId
		item.num = v._num
	end
	SendMessage(pb,LProtoIds.HeroGiveGiftReq)
end
function ModelHeroExtra:OnHeroInteractionReq(heroRefId,effId,status)--1/2
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroInteractionReq)
	pb.heroRefId = heroRefId
	interactr = pb.interactionList:add()
	interactr.effId = effId
	local loveInfo = gModelHero:GetFavorabilityInfo(heroRefId)
	interactr.status = status+(loveInfo and (loveInfo.interactionList[effId] or 0) or 0)
	SendMessage(pb,LProtoIds.HeroInteractionReq)
end

--- 英雄觉醒激活额外技能
function ModelHeroExtra:OnHeroTreeActiveExtraSkillReq(heroTreeActInfo)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroTreeActiveExtraSkillReq)
	pb.heroId = heroTreeActInfo.heroId
	pb.pointRefId = heroTreeActInfo.pointRefId
	pb.extraSkillCostRefId = heroTreeActInfo.extraSkillCostRefId

	local appointedList = heroTreeActInfo.appointedList
	for k,v in pairs(appointedList) do
		for _k,id in pairs(v) do
			table.insert(pb.appointeds,id)
		end
	end

	local rangeList = heroTreeActInfo.rangeList
	for k,v in pairs(rangeList) do
		for _k,id in pairs(v) do
			table.insert(pb.ranges,id)
		end
	end

	local items = pb.items
	local itemsList = heroTreeActInfo.rangItemList
	for i,v in pairs(itemsList) do
		for refId,num in pairs(v) do
			local tNum = tonumber(num)
			if tNum > 0 then
				local itemInfo = items:add()
				itemInfo.refId = tonumber(refId)
				itemInfo.num = tNum
			end
		end
	end
	SendMessage(pb,LProtoIds.HeroTreeActiveExtraSkillReq)
end
--英雄互动任务信息*/
function ModelHeroExtra:OnHeroInteractQuestReq()
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroInteractQuestReq)
	SendMessage(pb,LProtoIds.HeroInteractQuestReq)
end
--英雄互动任务小游戏操作
function ModelHeroExtra:OnHeroInteractGameOpsReq(type,reward,clientData)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroInteractGameOpsReq)
	pb.type = type
	pb.reward = reward
	pb.clientData = clientData
	SendMessage(pb,LProtoIds.HeroInteractGameOpsReq)
end

function ModelHeroExtra:OnHeroFavorabilityUnlockReq(type,refId)
	local pb = LProtoHelper.CreateProto(LProtoIds.HeroFavorabilityUnlockReq)
	pb.type = type
	pb.refId = refId
	SendMessage(pb,LProtoIds.HeroFavorabilityUnlockReq)
end

---------------------------------------------------------------------------
--- resp

--- 设置英雄名字
function ModelHeroExtra:OnHeroSetNameResp(pb)

end
--- 英雄好感度
function ModelHeroExtra:OnHeroFavorabilityInfoResp(pb)
	local effectId = gModelHero._gardenShowHeroEffRefId
	gModelHero:OnHeroFavorabilityInfoResp(pb)	
	if effectId>0 and pb.effectId ~= effectId then 
		GF.ShowMessage(ccClientText(41626))
		FireEvent(EventNames.FAVORABILITY_SPINE_UPDATE,pb.effectId)
	end
end
function ModelHeroExtra:OnHeroSetShowResp(pb)
	local effectId = gModelHero._gardenShowHeroEffRefId
	gModelHero._gardenShowHeroEffRefId = pb.effectId
	if effectId>0 and pb.effectId ~= effectId then 
		GF.ShowMessage(ccClientText(41626))
		FireEvent(EventNames.FAVORABILITY_SPINE_UPDATE,pb.effectId)
	end
end

function ModelHeroExtra:OnHeroGiveGiftResp(pb)
	local heroRefId = pb.favorabilityInfo.heroRefId
	local oldLoveInfo = gModelHero:GetFavorabilityInfo(heroRefId)
	local oldLoveLv = oldLoveInfo and oldLoveInfo.loveLevel or 0
	local newLoveLv = pb.favorabilityInfo.loveLevel
	gModelHero:OnSetHeroFavorability(pb.favorabilityInfo)
	local oldTotalLv = gModelHero._loveTotalLevel
	local oldTotalValue = gModelHero._loveTotalValue
	gModelHero._loveTotalLevel = pb.loveLevel
	gModelHero._loveTotalValue = pb.loveValue
	local isPrivilege = false
	local ref = GameTable.CharacterFavorabilityRef[newLoveLv]
	if oldLoveLv~=newLoveLv and ref and (ref.text1~="" or ref.text2~="") then 
		isPrivilege = true
	end
	if pb.addLoveValue and pb.addLoveValue>0 then
		-- GF.ShowMessage(string.replace(ccClientText(41629),pb.addLoveValue))
		FireEvent(EventNames.FAVORABILITY_EXP_UPDATE,pb.addLoveValue)
	end

	if oldTotalLv ~= pb.loveLevel or oldTotalValue ~=  pb.loveValue then
		FireEvent(EventNames.FAVORABILITY_EXP_CHANGED)
	end
	if oldTotalLv~=0 and gModelHero._loveTotalLevel~=oldTotalLv then 
		FireEvent(EventNames.FAVORABILITY_LOVE_UPLV,{isPrivilege=isPrivilege,heroRefId = heroRefId,isTotal = true,addExp=pb.addLoveValue })
	elseif isPrivilege then
		FireEvent(EventNames.FAVORABILITY_LOVE_UPLV,{isPrivilege=isPrivilege,heroRefId = heroRefId,isTotal = false,addExp=pb.addLoveValue })
	end
	
end

function ModelHeroExtra:OnHeroInteractionResp(pb)
	local loveInfo  = gModelHero:GetFavorabilityInfo(pb.heroRefId)
	if loveInfo then
		loveInfo:OnUpdateInteractionList(pb.interactionList)
		FireEvent(EventNames.FAVORABILITY_INTERACT)
	end
end
function ModelHeroExtra:OnHeroInteractQuestResp(pb)
	self.interactHeroRefId = pb.heroRefId
	self.interactEvtRefid = pb.eventRefId --事件Id
	self.interactMoreInfo = pb.moreInfo--当前事件的附加数据（当事件类型是1或2答题时，为题库RefId）
	-- self.interactClientDat = pb.clientData --前端自己记录的数据（GameOpsReq协议传什么就记录什么）
	-- FireEvent(EventNames.FAVORABILITY_INTERACT_QUEST)

end
function ModelHeroExtra:OnHeroInteractGameOpsResp(pb)
	-- self.interactClientDat = pb.clientData 
end

--- 英雄觉醒激活额外技能
function ModelHeroExtra:OnHeroTreeActiveExtraSkillResp(pb)
	local heroId = pb.heroId
	local heroServerData = gModelHero:GetHeroServerDataById(heroId)
	if not heroServerData then return end
	local pointRefId = pb.pointRefId
	local extraSkillCostRefId = pb.extraSkillCostRefId
	self:OpenHeroTreeExtraSkillActWnd({
		viewType = 1,
		heroId = heroId,
		awakenTreePointId = pointRefId,
		extraSkillCostRefId = extraSkillCostRefId,
	})
end

---------------------------------------------------------------------------
--- 获取伙伴备注名字符长度
function ModelHeroExtra:GetHeroResetNameCharNum()
	local nameNum = gModelHero:GeConfigByKey("nameNum")
	if not nameNum then
		nameNum = ModelHeroExtra.NAME_MAX_CHARNUM
		if LOG_INFO_ENABLED then
			printInfoNR("HeroConfigRef 可配置 nameNum 字段，表示当前的可设置英雄备注名字符长度，默认长度为：" .. nameNum)
		end
	end
	return nameNum
end

function ModelHeroExtra:GetHeroNameByServerData(serverData)
	if not serverData then return "" end
	return serverData.name
end

function ModelHeroExtra:IsResetHeroNameByServerData(serverData)
	local isInit = self:IsInitHeroNameByServerData(serverData)
	return not isInit
end

function ModelHeroExtra:IsInitHeroNameByServerData(serverData)
	if not serverData then return false end
	local name = self:GetHeroNameByServerData(serverData)
	if string.isempty(name) then return true end
	if self:CheckResetNameIsSameInitName(serverData) then
		return true
	end
	return false
end

function ModelHeroExtra:GetHeroConfigNameByServerData(serverData,needColor)
	if not serverData then  return "" end
	local refId = serverData.refId
	local star = serverData.star
	local form = serverData.form
	if needColor then
		return gModelHero:GetColoredHeroName(refId, star,form)
	else
		return gModelHero:GetHeroNameByRefId(refId, star,form)
	end
end

function ModelHeroExtra:CheckResetNameIsSameInitName(heroData)
	if not heroData then return false end
	local name = self:GetHeroNameByServerData(heroData)
	if string.isempty(name) then return false end
	local configName = self:GetHeroConfigNameByServerData(heroData)
	return configName == name
end

--- heroData：英雄serverData
--- needColor：需要根据星级变化颜色
function ModelHeroExtra:GetHeroSetName(heroData,needColor)
	if not heroData then  return "" end
	local refId = heroData.refId
	local star = heroData.star
	local name = self:GetHeroNameByServerData(heroData)
	local isEmpty = string.isempty(name)
	if isEmpty then
		--- 空的取英雄名字
		name = self:GetHeroConfigNameByServerData(heroData,needColor)
	else
		if needColor then
			local color = gModelHero:GetHeroNameColorByRefId(refId, star)
			if color then
				name = LUtil.FormatColorStr(name, "#" .. color)
			end
		end
	end
	return name
end

function ModelHeroExtra:CheckIsMyHero(id)
	local serverData = gModelHero:GetHeroServerDataById(id)
	return serverData and serverData ~= nil or false
end

---------------------------------------------------------------------------
--- 额外觉醒技消耗表

function ModelHeroExtra:OpenHeroTreeSkillActWnd(argList)
	GF.OpenWnd("UISagaTreeJNAct",argList)
end

function ModelHeroExtra:OpenHeroTreeSkillLvUpWnd(argList)
	GF.OpenWnd("UISagaTreeJNLvUp",argList)
end

function ModelHeroExtra:OpenHeroTreeExtraSkillActWnd(argList)
	GF.OpenWnd("UISagaTreeExtraJNAct",argList)
end

function ModelHeroExtra:OpenHeroTreeSkillWnd(argList)
	GF.OpenWnd("UISagaTreeJN",argList)
end

function ModelHeroExtra:OpenHeroTreeSkillPreviewWnd(argList)
	argList = argList or {}
	argList.viewType = 4
	GF.OpenWnd("UISagaTreeJN",argList)
end

function ModelHeroExtra:DisposeUpSelf(upSelf,heroServerData,upSelfList,upSelfConfigList)
	local heroRefId = heroServerData.refId
	local heroId = heroServerData.id
	local fuse1 = true
	if upSelf then
		if type(upSelf) == "number" then
			if upSelf > 0 then
				local heroStar = gModelHero:GetHeroInitStarByRefId(heroRefId) or ModelHero.AWAKEN_UP_SELF_STAR
				local dataList = gModelHero:AwakenFilterHero(heroRefId,heroStar,nil,heroId,{})
				local selNum = 0
				local selInfo = {}
				for k,v in pairs(dataList) do
					selNum = selNum + 1
					table.insert(selInfo,v)
				end
				table.insert(upSelfList,selInfo)
				fuse1 = selNum >= upSelf
				table.insert(upSelfConfigList,{
					needRefId = heroRefId,
					needStar = heroStar,
					needNum = upSelf,
					canCompound = fuse1,
					itemType = LItemTypeConst.TYPE_HERO,
				})
			end
		else
			if not string.isempty(upSelf) then
				local heroStar,needNum
				local reachNum = 0
				local upSelfInfos = string.split(upSelf,",")
				for i,v in ipairs(upSelfInfos) do
					v = string.split(v,"=")
					needNum = tonumber(v[1])
					heroStar = tonumber(v[2])
					local dataList = gModelHero:AwakenFilterHero(heroRefId,heroStar,nil,heroId,{})
					local selNum = 0
					local selInfo = {}
					for _k,_v in pairs(dataList) do
						selNum = selNum + 1
						table.insert(selInfo,_v)
					end
					table.insert(upSelfList,selInfo)
					if selNum >= needNum then
						reachNum = reachNum + 1
					end
					table.insert(upSelfConfigList,{
						needRefId = heroRefId,
						needStar = heroStar,
						needNum = needNum,
						canCompound = selNum >= needNum,
						itemType = LItemTypeConst.TYPE_HERO,
					})
				end
				fuse1 = reachNum >= #upSelfInfos
			end
		end
	end
	return fuse1
end

function ModelHeroExtra:GetHeroTreeActNeedItemListByConfig(upSelf,upRange,upItem,heroServerData)
	local fuse1,fuse2,fuse3 = true,true,true
	local heroId = heroServerData.id
	local upSelfConfigList = {}
	local upSelfList = {}
	fuse1 = self:DisposeUpSelf(upSelf,heroServerData,upSelfList,upSelfConfigList)


	local upRangeConfigList = {}
	local upRangeList = {}
	if not string.isempty(upRange) then
		local recordRangHeroIdMap = {}
		local recordRangFullMap = {}
		local needRefId,needStar,needNum
		local range = string.split(upRange,',')
		for i,v in ipairs(range) do
			v = string.split(v,"=")
			needRefId,needStar,needNum = tonumber(v[1]),tonumber(v[2]),tonumber(v[3])
			local dataList,yinghunItemList = gModelHero:AwakenFilterHero(needRefId,needStar,needRefId,heroId,{})
			local selNum = 0
			local selInfo = {}
			for key,val in pairs(dataList) do
				if not recordRangHeroIdMap[key] then
					selNum = selNum + 1
					recordRangHeroIdMap[key] = val
					table.insert(selInfo,val)
				end
			end
			table.insert(upRangeList,selInfo)

			local haveNum = selNum + table.keysize(yinghunItemList)
			local isFull = haveNum >= needNum
			recordRangFullMap[i] = isFull and 1 or 0
			table.insert(upRangeConfigList,{
				needRefId = needRefId,
				needStar = needStar,
				needNum = needNum,
				canCompound = isFull,
				itemType = LItemTypeConst.TYPE_HERO,
			})
		end
		local isFull = true
		for k,v in ipairs(recordRangFullMap) do
			if v < 0 then
				isFull = false
				break
			end
		end
		fuse2 = isFull
	end

	local upItemConfigList = {}
	local upItemList = {}
	if not string.isempty(upItem) then
		local haveNum
		local recordItemFullMap = {}
		local itemType,itemId,itemNum
		local upLvItem = string.split(upItem,",")
		for i,v in ipairs(upLvItem) do
			v = string.split(v,"=")
			itemType,itemId,itemNum = tonumber(v[1]),tonumber(v[2]),tonumber(v[3])
			haveNum = gModelItem:GetNumByRefId(itemId)
			local isFull = haveNum >= itemNum
			recordItemFullMap[i] = isFull and 1 or 0
			table.insert(upItemList,{
				itemType = itemType,
				itemId = itemId,
				itemNum = itemNum,
				needRefId = itemId,
				needNum = itemNum,
				haveNum = haveNum,
			})
			table.insert(upItemConfigList,{
				itemType = itemType,
				itemId = itemId,
				itemNum = itemNum,
				needRefId = itemId,
				needNum = itemNum,
				canCompound = isFull,
				itemType = LItemTypeConst.TYPE_ITEM,
			})
		end
		local isFull = true
		for k,v in ipairs(recordItemFullMap) do
			if v < 0 then
				isFull = false
				break
			end
		end
		fuse3 = isFull
	end

	return {
		upSelfInfo = {
			configList = upSelfConfigList,
			selList = upSelfList,
			fuse = fuse1,
		},
		upRangeInfo = {
			configList = upRangeConfigList,
			selList = upRangeList,
			fuse = fuse2,
		},
		upItemInfo = {
			configList = upItemConfigList,
			selList = upItemList,
			fuse = fuse3,
		},
	}
end

function ModelHeroExtra:AwakenFilterHero(hRefId,hStar,hType,selHeroId,selHeroList,needNum,isSelWnd)
	local saveHeroInfoList = gModelHero:GetSaveHeroInfoList()

	local filterList = {}
	local heroStarList = saveHeroInfoList.heroStarList or {}
	local heroStarSelInfo = heroStarList[hStar] or {}
	local isStatusJoin = false
	local isSpiritHeroJoin = false
	local curAllLv,maxLv
	
	local checkFunc = function(heroStruct,tHeroId)
		isStatusJoin = false
		if gModelSpiritHero:CheckIsSpiritHero(heroStruct:GetRefId()) then
			isSpiritHeroJoin = gModelSpiritHero:CheckSpiritHeroIsHaveLink(heroStruct)
			if isSpiritHeroJoin then
				curAllLv,maxLv = gModelHero:GetTreePointsLvlData(tHeroId)
				if curAllLv then
					if curAllLv < 1 then
						isStatusJoin = true
					end
				end
			else
				isStatusJoin = true
			end
		else
			isStatusJoin = true
		end
		return isStatusJoin
	end

	if hType then
		if hType == 0 then
			for tHeroId, tHeroStruct in pairs(heroStarSelInfo) do
				if tHeroId ~= selHeroId and not tHeroStruct:IsTryHero() then
					if checkFunc(tHeroStruct,tHeroId) then
						filterList[tHeroId] = tHeroStruct
					end
				end
			end
		else
			for tHeroId, tHeroStruct in pairs(heroStarSelInfo) do
				if tHeroId ~= selHeroId and not tHeroStruct:IsTryHero() then
					local raceType = gModelHero:GetHeroType(tHeroStruct:GetRefId())
					if raceType == hType and checkFunc(tHeroStruct,tHeroId) then
						filterList[tHeroId] = tHeroStruct
					end
				end
			end
		end
	else
		local heroRefIdList = saveHeroInfoList.heroRefIdList or {}
		local heroRefIdSelInfo = heroRefIdList[hRefId] or {}
		for tHeroId, tHeroStruct in pairs(heroRefIdSelInfo) do
			if tHeroId ~= selHeroId and not tHeroStruct:IsTryHero() then
				isStatusJoin = isSelWnd or tHeroStruct:GetLockStatus() ~= 1
				if isStatusJoin and heroStarSelInfo[tHeroId] and checkFunc(tHeroStruct,tHeroId) then
					filterList[tHeroId] = tHeroStruct
				end
			end
		end
	end
	local serHeroRace
	if selHeroId then
		local refId = gModelHero:GetRefIdById(selHeroId)
		local ref = refId and gModelHero:GetHeroRef(refId)
		if ref then
			serHeroRace = ref.raceType
		end
	end
	local itemList = {}
	if hType then
		-- 英魂筛选(道具)
		local bagYingHunList = gModelItem:GetBagYingHunList()
		for k,v in pairs(bagYingHunList) do
			local itemRefData = gModelItem:GetYingHunRefByRefId(k)
			if itemRefData then
				local isIns = false
				local refRace,refStar = itemRefData.race,itemRefData.star
				if serHeroRace and serHeroRace == refRace and refStar == hStar then
					isIns = true
				elseif refRace == 0 and refStar == hStar then
					isIns = true
				elseif (hType == 0 or refRace == hType) and refStar == hStar then
					-- 填0时为任意种族都可以
					isIns = true
				elseif refStar == hStar then
					local other = ModelItem.RaceTypeList[refRace]
					isIns = other and other[hType] or false
				end
				if isIns then
					local itemStruct = gModelItem:GetItemServerDataByRefId(k)
					if itemStruct then
						local num = itemStruct._num
						for i = 1,num do
							if needNum and needNum < i then break end
							local key = "itemRace_" .. refRace .. "_" .. i
							itemList[key] = itemStruct
						end
					end
				end
			end
		end
	end
	return filterList,itemList
end

function ModelHeroExtra:GetHeroTreeActNeedItemListByStaticConfig(upSelf,upRange,upItem,heroServerData)
	local fuse1,fuse2,fuse3 = true,true,true
	local heroId = heroServerData.id
	local upSelfConfigList = {}
	local upSelfList = {}
	fuse1 = self:DisposeUpSelf(upSelf,heroServerData,upSelfList,upSelfConfigList)

	local upRangeConfigList = {}
	local upRangeList = {}
	if not string.isempty(upRange) then
		local recordRangHeroIdMap = {}
		local recordRangFullMap = {}
		local needRefId,needStar,needNum
		local range = string.split(upRange,',')
		for i,v in ipairs(range) do
			v = string.split(v,"=")
			needRefId,needStar,needNum = tonumber(v[1]),tonumber(v[2]),tonumber(v[3])
			local dataList,yinghunItemList = self:AwakenFilterHero(needRefId,needStar,needRefId,heroId,{})
			local selNum = 0
			local selInfo = {}
			for key,val in pairs(dataList) do
				if not recordRangHeroIdMap[key] then
					selNum = selNum + 1
					recordRangHeroIdMap[key] = val
					table.insert(selInfo,val)
				end
			end
			table.insert(upRangeList,selInfo)

			local haveNum = selNum + table.keysize(yinghunItemList)
			local isFull = haveNum >= needNum
			recordRangFullMap[i] = isFull and 1 or 0
			table.insert(upRangeConfigList,{
				needRefId = needRefId,
				needStar = needStar,
				needNum = needNum,
				canCompound = isFull,
				itemType = LItemTypeConst.TYPE_HERO,
			})
		end
		local isFull = true
		for k,v in ipairs(recordRangFullMap) do
			if v < 0 then
				isFull = false
				break
			end
		end
		fuse2 = isFull
	end

	local upItemConfigList = {}
	local upItemList = {}
	if not string.isempty(upItem) then
		local haveNum
		local recordItemFullMap = {}
		local itemType,itemId,itemNum
		local upLvItem = string.split(upItem,",")
		for i,v in ipairs(upLvItem) do
			v = string.split(v,"=")
			itemType,itemId,itemNum = tonumber(v[1]),tonumber(v[2]),tonumber(v[3])
			haveNum = gModelItem:GetNumByRefId(itemId)
			local isFull = haveNum >= itemNum
			recordItemFullMap[i] = isFull and 1 or 0
			table.insert(upItemList,{
				itemType = itemType,
				itemId = itemId,
				itemNum = itemNum,
				needRefId = itemId,
				needNum = itemNum,
				haveNum = haveNum,
			})
			table.insert(upItemConfigList,{
				itemType = itemType,
				itemId = itemId,
				itemNum = itemNum,
				needRefId = itemId,
				needNum = itemNum,
				canCompound = isFull,
				itemType = LItemTypeConst.TYPE_ITEM,
			})
		end
		local isFull = true
		for k,v in ipairs(recordItemFullMap) do
			if v < 0 then
				isFull = false
				break
			end
		end
		fuse3 = isFull
	end

	return {
		upSelfInfo = {
			configList = upSelfConfigList,
			selList = upSelfList,
			fuse = fuse1,
		},
		upRangeInfo = {
			configList = upRangeConfigList,
			selList = upRangeList,
			fuse = fuse2,
		},
		upItemInfo = {
			configList = upItemConfigList,
			selList = upItemList,
			fuse = fuse3,
		},
	}
end

function ModelHeroExtra:GetHeroTreeExtraSkillCostByConfigAndHeroServerData(refId,heroServerData)
	local heroExtraSkillCostRef = self:GetHeroExtraSkillCostRefByRefId(refId)
	if not heroExtraSkillCostRef then return end
	return self:GetHeroTreeActNeedItemListByStaticConfig(heroExtraSkillCostRef.upSelf,heroExtraSkillCostRef.upRange,heroExtraSkillCostRef.upItem,heroServerData)
end

function ModelHeroExtra:GetHeroTreeSkillList(ref)
	local pointSkillList = {}
	--table.insert(pointSkillList,ref.skill)
	local skill = string.split(ref.skill,"|")
	for i,v in ipairs(skill) do
		table.insert(pointSkillList,checknumber(v))
	end
	return {
		skill = pointSkillList,
	}
end

function ModelHeroExtra:GetHeroExtraSkillCostRefByRefId(refId)
	return GameTable.HeroExtraSkillCostRef[refId]
end

function ModelHeroExtra:CheckHeroTreeExtraSkillPayEnough(payInfo)
	if not payInfo then return false end
	local recordHeroIdMap = {}

	local sortSelList,selList,configList,dataList
	local needNum,needStar
	local autoSelId

	local upSelfInfo = payInfo.upSelfInfo
	if upSelfInfo then
		selList = upSelfInfo.selList
		configList = upSelfInfo.configList
		for i,v in ipairs(configList) do
			dataList = selList[i] or {}
			sortSelList = gModelHero:SortFillHeroList(dataList)
			if #sortSelList > 0 then
				needNum = v.needNum
				local recordNum = 0
				local status = false
				for selIdx,selHeroData in ipairs(sortSelList) do
					autoSelId = selHeroData._id
					recordHeroIdMap[autoSelId] = autoSelId
					recordNum = recordNum + 1
					status = recordNum >= needNum
					if status then break end
				end
				if not status then return false end
			else
				return false
			end
		end
	end

	local upRangeInfo = payInfo.upRangeInfo
	if upRangeInfo then
		configList = upRangeInfo.configList
		selList = upRangeInfo.selList
		for i,v in ipairs(configList) do
			needStar = v.needStar
			dataList = selList[i] or {}
			needNum = v.needNum
			sortSelList = gModelHero:SortFillHeroList(dataList)
			if #sortSelList > 0 then
				local recordNum = 0
				local status = false
				for selIdx,selHeroData in ipairs(sortSelList) do
					autoSelId = selHeroData._id
					if not recordHeroIdMap[autoSelId] then
						recordHeroIdMap[autoSelId] = autoSelId
						recordNum = recordNum + 1
						status = recordNum >= needNum
						if status then break end
					end
				end
			else
				return false
			end
		end
	end

	local upItemInfo = payInfo.upItemInfo
	if upItemInfo then
		configList = upItemInfo.configList
		selList = upItemInfo.selList
		local itemId,itemNum,haveNum
		for i,v in ipairs(configList) do
			itemId = v.itemId
			itemNum = v.itemNum
			haveNum = gModelItem:GetNumByRefId(itemId)
			if haveNum < itemNum then return false end
		end
	end

	return true
end

function ModelHeroExtra:CheckCanUpExtraSkillByHeroServerData(heroServerData,lvRefId)

	--local isFuncOpen = gModelFunctionOpen:CheckIsOpened(10306003)
	local isFuncOpen = false
	if not isFuncOpen then
		return false
	end

	if not heroServerData then return false end

	local treeInfo = heroServerData.treeInfo
	if not treeInfo then return false end

	local extraSkillCostRefIdMap = treeInfo.extraSkillCostRefIdMap
	if not extraSkillCostRefIdMap then return false end

	if not lvRefId then return false end

	local curPointLvRef = gModelHero:GetHeroTreePointLvRef(lvRefId)
	if not curPointLvRef then return false end

	local skillInfo = self:GetHeroTreeSkillList(curPointLvRef)
	if not skillInfo then return false end

	return false
end

--- 检查是否有额外技能可激活
function ModelHeroExtra:CheckHeroTreeIsHaveExtraSkillActByHeroServerData(heroServerData)
	if not heroServerData then return false end

	local heroId = heroServerData.id
	local treeInfoPoints = gModelHero:GetHeroServerTreePoints(heroId)
	if not treeInfoPoints then return false end

	local lvRefId,pointRefId
	local pointLvList
	for k,v in pairs(treeInfoPoints) do
		pointRefId = v.pointRefId
		pointLvList = gModelHero:GetHeroTreePointLvList(pointRefId)
		if pointLvList.pointType == ModelHero.TREE_POINT_TYPE_SKILL then
			lvRefId = v.lvRefId
			if self:CheckCanUpExtraSkillByHeroServerData(heroServerData,lvRefId) then
				return true
			end
		end
	end

	return false
end
---------------------------------------------------------------------------

---@param effRef HeroEffectRef
---@param trans Transform
---@return Vector3
function ModelHeroExtra:GetHeroShowLH1(effRef,trans)
	if not effRef then return Vector3.zero end

	local initEffectHeroShowLH1 = self._initEffectHeroShowLH1
	if not initEffectHeroShowLH1 then
		initEffectHeroShowLH1 = {}
		self._initEffectHeroShowLH1 = initEffectHeroShowLH1
	end

	local data = initEffectHeroShowLH1[effRef.refId]
	if not data then
		local curLiHuiPos = trans.localPosition
		local x,y,z = curLiHuiPos.x,curLiHuiPos.y,curLiHuiPos.z
		--local heroShowLH1 = effRef.heroShowLH1
		--if type(heroShowLH1) == "number" then
		--	y = heroShowLH1
		--elseif type(heroShowLH1) == "string" and not string.isempty(heroShowLH1) then
		--	local heroShowLH1s = string.split(heroShowLH1,"|")
		--	x = tonumber(heroShowLH1s[1]) or x
		--	y = tonumber(heroShowLH1s[2]) or y
		--end
		data = Vector3(x,y,z)
	end
	return data
end


--region 可出售的伙伴，需满足以下条件
--开发需求 #12142
--【后台活动】分表条目类型3支持配置伙伴作为现价（客户端&服务端）
function ModelHeroExtra:CheckBeCapableOfSellHero(heroData)
	local heroRefId = heroData:GetRefId()
	local heroRef = gModelHero:GetHeroRef(heroRefId)
	local heroServerData = heroData:GetServerData()
	--
	local isTry = heroData:IsTryHero()
	--初始星级
	local initStar =heroRef.initStar
	local isInitStar = heroData:GetStar() == initStar
	--出战/锁定/魔晶共鸣
	local heroStatus = heroData:GetStatus()
	local notUsed = heroStatus == 0
	--星灵连结
	local isSpiritLink = gModelSpiritHero:CheckHeroIsHaveLink(heroServerData)
	--星灵觉醒等级/核心等级
	local isSpirtHero =gModelSpiritHero:CheckIsSpiritHero(heroRefId)
	local isInitLvlSpirit = true
	if(isSpirtHero)then
		local treeInfo = heroData:GetTreeInfo()
		local curLvl,maxLvl = gModelHero:GetTreePointsCurLvAndMaxLv(treeInfo)--觉醒等级
		isInitLvlSpirit = curLvl == 0
	end
	return not isTry and isInitStar and notUsed and not isSpiritLink and isInitLvlSpirit
end
--endregion
--region 获取x个可出售伙伴Id
function ModelHeroExtra:GetBeCapableOfSellHeroIdList(refId,num)
	local idList = {}
	local playerHeroList = gModelHero:GetHeroList()
	for i, v in pairs(playerHeroList) do
		local heroData = v
		if(heroData:GetRefId() == refId)then
			local beCapableOfSell = self:CheckBeCapableOfSellHero(heroData)
			if(beCapableOfSell)then
				table.insert(idList,v:GetId())
			end
		end
	end
	local list = {}
	for i, v in pairs(idList) do
		if(num and #list <num)then
			table.insert(list,v)
		end
	end
	table.sort(list, function(a,b)
			return  a>b
	end)
	return num and list or idList
end
--endregion

function ModelHeroExtra:GetMonsterAttrCostRef(refId)
	return GameTable.MonsterAttrCostRef[refId]
end



--- 是否静止 http://192.168.16.2:3002/issues/1168
function ModelHeroExtra:CheckBookIsCalm(skinRefId)
	local effectRef = GameTable.CharacterEffectRef[skinRefId]
	if not effectRef then return true end
	local refId = effectRef.heroType
	if refId and refId > 0 then
		if not gModelHeroBook:FindHeroInfoStatusByHeroRefId(refId) then
			--- 未获得英雄
			return true
		end
	end
	if not gModelHero:GetOriginId(skinRefId) then
		--- 非变形
		local isHeroSkin = gModelHero:CheckHeroRefIdHasSkinId(skinRefId)
		local notActSkin = gModelHero:GetHeroSkinInfoByRefId(skinRefId) == nil
		if isHeroSkin and notActSkin then
			--- 皮肤未激活
			return true
		end
		return false
	end
	--- 如果本身没有皮肤，静止状态
	local skinInfo = gModelHero:GetHeroSkinInfoByRefId(skinRefId)
	return skinInfo == nil or false
end

ModelHeroExtra.SKILL_SOUND_1 = "skillSound1"
ModelHeroExtra.SKILL_SOUND_2 = "skillSound2"

ModelHeroExtra.RECORD_SKILLSOUND_MAP = {
	[ModelHeroExtra.SKILL_SOUND_1] = 1,
	[ModelHeroExtra.SKILL_SOUND_2] = 2,
}

function ModelHeroExtra:InitHeroFavorabilityRef()
	local recordBattleSounds = {}
	local SpActionSound
	for k,v in pairs(GameTable.CharacterFavorabilityRef) do
		SpActionSound = v.SpActionSound
		if ModelHeroExtra.RECORD_SKILLSOUND_MAP[SpActionSound] then
			table.insert(recordBattleSounds,{
				SpActionSound = SpActionSound,
				refId = v.refId
			})
		end
	end
	table.sort(recordBattleSounds,function(a, b) return a.refId > b.refId end)
	self._recordBattleSounds = recordBattleSounds
end

function ModelHeroExtra:GetHeroFavorabilitySounds(loveLevel,effData)
	if not effData then return end

	local skinSkillType = effData.skinSkillType
	if not skinSkillType then return end

	local SpActionSound
	for i,v in ipairs(self._recordBattleSounds) do
		if loveLevel >= v.refId then
			SpActionSound = v.SpActionSound
			if ModelHeroExtra.RECORD_SKILLSOUND_MAP[SpActionSound] == skinSkillType then
				return SpActionSound
			end
		end
	end
end

function ModelHeroExtra:CheckIsOpenForm()
	return gModelFunctionOpen:CheckIsOpened(10309000)
end

function ModelHeroExtra:CheckIsOpenSkin()
	return gModelFunctionOpen:CheckIsOpened(10309001)
end

--- 升星珍稀 类型 7：为道具(光暗)
local UPSTAR_RARETYPE = {
	[4] = true,[5] = true,[7] = true,
}

--- 升星里面是否选择了种族 4,5 的英雄或者仙灵道具
function ModelHeroExtra:CheckUpStarIsSelRare(rSelHeroMap,rSelItemMap,rangNeedInfo)
	local isSelRare = false
	---@type StructHero
	local sHero
	local raceType
	local yinhunTypeData
	local heroList = gModelHero:GetHeroList()
	for i,v in ipairs(rangNeedInfo) do
		if isSelRare then break end
		if v.needRefId == 0 then
			--- 全种族，需要检测
			local rSelHeros = rSelHeroMap[i]
			if rSelHeros then
				for heroId,status in pairs(rSelHeros) do
					sHero = heroList[heroId]
					if sHero then
						raceType = gModelHero:GetHeroRace(sHero:GetRefId())
						if UPSTAR_RARETYPE[raceType] then
							isSelRare = true
							break
						end
					end
				end
			end
			local rSelItems = rSelItemMap[i]
			if rSelItems then
				for itemId,itemNum in pairs(rSelItems) do
					yinhunTypeData = gModelItem:GetYingHunRefByRefId(itemId)
					if yinhunTypeData and UPSTAR_RARETYPE[yinhunTypeData.race] then
						isSelRare = true
						break
					end
				end
			end
		end
	end
	return isSelRare
end


function ModelHeroExtra:GetMaxGradeByClassType(classType,grade,star)
	local maxGrade
	local isStarLimit = false
	local sortClassList = gModelHero:GetSortHeroClassRefListByClassType(classType)
	local needStar,rGrade
	for i,v in ipairs(sortClassList) do
		rGrade = v.grade
		if rGrade >= grade then
			needStar = v.needStar
			if needStar > 0 then
				if star >= needStar then
					maxGrade = rGrade
				else
					--- 星级限制，但是等级可以升上去
					isStarLimit = true
					maxGrade = rGrade
					break
				end
			else
				maxGrade = rGrade
			end
		end
	end
	if not maxGrade then
		maxGrade = self:OnlyCalcMaxGradeByClassType(classType)
	end
	return maxGrade,isStarLimit
end

function ModelHeroExtra:OnlyCalcMaxGradeByClassType(classType)
	if not self._initClassTypeMaxGradeMap then
		self._initClassTypeMaxGradeMap = {}
	end
	local maxGrade = self._initClassTypeMaxGradeMap[classType]
	if not maxGrade then
		for k,v in pairs(GameTable.CharacterClassRef) do
			if v.type == classType then
				if not maxGrade then
					maxGrade = v.grade
				elseif maxGrade < v.grade then
					maxGrade = v.grade
				end
			end
		end
		self._initClassTypeMaxGradeMap[classType] = maxGrade
	end
	return maxGrade
end


function ModelHeroExtra:IsTreeSkillMore()
	return true
end


function ModelHeroExtra:GetCommonBattleY(spineName)
	if spineName == "LH_Bazhuayu01" or spineName == "LH_Bazhuayu02" then
		return -110
	end
	return 0
end

function ModelHeroExtra:GetConfigHeroLHCloudHX()
	if not self._heroLHCloudHXMap then
		local heroLHCloudHX = gModelHero:GeConfigByKey("heroLHCloudHX") or {}
		self:SetConfigHeroLHCloudHX(heroLHCloudHX)
	end
	return self._heroLHCloudHXMap
end

function ModelHeroExtra:SetConfigHeroLHCloudHX(heroLHCloudHX)
	local heroLHCloudHXMap = {}
	for i,v in ipairs(heroLHCloudHX) do
		heroLHCloudHXMap[v] = true
	end
	self._heroLHCloudHXMap = heroLHCloudHXMap
end

function ModelHeroExtra:CheckIsHeroLHCloudHX(wndName)
	local heroLHCloudHXMap = self:GetConfigHeroLHCloudHX()
	return heroLHCloudHXMap[wndName]
end

function ModelHeroExtra:GetParseHeroDrawingAllAges(effectId)
	local parseHeroDrawingAllAges = self._parseHeroDrawingAllAges
	if not parseHeroDrawingAllAges then
		parseHeroDrawingAllAges = {}
		self._parseHeroDrawingAllAges = parseHeroDrawingAllAges
	end
	local parseHeroDrawingAllAge = parseHeroDrawingAllAges[effectId]
	if parseHeroDrawingAllAge then
		return parseHeroDrawingAllAge
	end

	local heroEffRef = gModelHero:GetShowEffectById(effectId)
	if not heroEffRef then return end

	parseHeroDrawingAllAge = self:SetHeroDrawingAllAgesData(effectId,heroEffRef.heroDrawingAllAges)
	return parseHeroDrawingAllAge
end

function ModelHeroExtra:SetHeroDrawingAllAgesData(effId,heroDrawingAllAges)
	local parseHeroDrawingAllAges = self._parseHeroDrawingAllAges
	if not parseHeroDrawingAllAges then
		parseHeroDrawingAllAges = {}
		self._parseHeroDrawingAllAges = parseHeroDrawingAllAges
	end
	local parseHeroDrawingAllAge = {}
	if heroDrawingAllAges and #heroDrawingAllAges > 0 then
		for i,v in ipairs(heroDrawingAllAges) do
			v = string.split(v,"=")
			table.insert(parseHeroDrawingAllAge,{
				res = v[1],
				pos = LxDataHelper.ParseVector2NotEmpty(v[2]),
				scale = checknumber(v[3]),
				isFlip = checknumber(v[4]) == 1,
			})
		end
	end
	parseHeroDrawingAllAges[effId] = parseHeroDrawingAllAge
	return parseHeroDrawingAllAge
end

---@param spine LDisplaySpine
---@param wndCls LWnd
function ModelHeroExtra:CheckNeedShowCloud(effectId,spine,wndCls)
	if not effectId or effectId < 1 then return end
	if not spine then return end
	local heroEffRef = gModelHero:GetShowEffectById(effectId)
	if not heroEffRef then return end
	if not spine:IsDpValid() then return end
	if not wndCls:IsWndValid() then return end
	local wndName = wndCls:GetWndName()
	if not self:CheckIsHeroLHCloudHX(wndName) then return end

	local parseDatas = self:GetParseHeroDrawingAllAges(effectId)
	if not parseDatas or #parseDatas < 1 then return end

	wndCls:CreateHeroSpineCloudShow(parseDatas,spine)
end

---@param spine LDisplaySpine
---@param wndCls LWnd
function ModelHeroExtra:CheckNeedShowCloudBySpineName(spineName,spine,wndCls)
	if string.isempty(spineName) then return end

	self:CheckNeedShowCloudNew(spineName,spine,wndCls)


	--local heroDrawing2EffectIds = gModelHero:GetHeroDrawing2EffectIds(spineName)
	--if not heroDrawing2EffectIds or #heroDrawing2EffectIds < 1 then return end
	--
	--local effId = heroDrawing2EffectIds[1]
	--self:CheckNeedShowCloud(effId,spine,wndCls)
end



---@param spine LDisplaySpine
---@param wndCls LWnd
function ModelHeroExtra:CheckNeedShowCloudNew(spineName,spine,wndCls)
	if not spine then return end
	if not spine:IsDpValid() then return end
	if not wndCls:IsWndValid() then return end
	local wndName = wndCls:GetWndName()
	if not self:CheckIsHeroLHCloudHX(wndName) then return end

	local parseDatas = self:GetHeroDrawingAllAgesByPrefabName(spineName)
	if not parseDatas or #parseDatas < 1 then return end

	wndCls:CreateHeroSpineCloudShow(parseDatas,spine)
end

function ModelHeroExtra:GetHeroDrawingAllAgesByPrefabName(spineName)
	local ref = gLGameLanguage:GetShieldLHjdRef(spineName)
	if not ref then return end

	local parseShieldHeroDrawingAllAges = self._parseShieldHeroDrawingAllAges
	if not parseShieldHeroDrawingAllAges then
		parseShieldHeroDrawingAllAges = {}
		self._parseShieldHeroDrawingAllAges = parseShieldHeroDrawingAllAges
	end
	local parseShieldHeroDrawingAllAge = parseShieldHeroDrawingAllAges[spineName]
	if parseShieldHeroDrawingAllAge then return parseShieldHeroDrawingAllAge end


	local heroDrawingAllAges = ref.heroDrawingAllAges
	local resType = LPlayerPrefs.GetLocalization()
	if resType then
		if resType == 3 then
			heroDrawingAllAges = ref.heroDrawingAllAges1
		elseif resType == 4 then
			heroDrawingAllAges = ref.heroDrawingAllAges2
		end
	end
	parseShieldHeroDrawingAllAge = self:SetHeroDrawingAllAgesByPrefabName(spineName,heroDrawingAllAges)
	return parseShieldHeroDrawingAllAge
end

function ModelHeroExtra:SetHeroDrawingAllAgesByPrefabName(spineName,heroDrawingAllAges)
	local parseShieldHeroDrawingAllAges = self._parseShieldHeroDrawingAllAges
	if not parseShieldHeroDrawingAllAges then
		parseShieldHeroDrawingAllAges = {}
		self._parseShieldHeroDrawingAllAges = parseShieldHeroDrawingAllAges
	end
	local parseShieldHeroDrawingAllAge = {}
	if heroDrawingAllAges and #heroDrawingAllAges > 0 then
		for i,v in ipairs(heroDrawingAllAges) do
			v = string.split(v,"=")
			table.insert(parseShieldHeroDrawingAllAge,{
				res = v[1],
				pos = LxDataHelper.ParseVector2NotEmpty(v[2]),
				scale = checknumber(v[3]),
				rotate = checknumber(v[4]),
			})
		end
	end
	parseShieldHeroDrawingAllAges[spineName] = parseShieldHeroDrawingAllAge
	return parseShieldHeroDrawingAllAge
end


function ModelHeroExtra:GetParseLHDrawingAllAges(effectId)
	local parseLHDrawingAllAges = self._parseLHDrawingAllAges
	if not parseLHDrawingAllAges then
		parseLHDrawingAllAges = {}
		self._parseLHDrawingAllAges = parseLHDrawingAllAges
	end
	local parseLHKPDrawingAllAge = parseLHDrawingAllAges[effectId]
	if parseLHKPDrawingAllAge then
		return parseLHKPDrawingAllAge
	end

	local heroEffRef = gModelHero:GetShowEffectById(effectId)
	if not heroEffRef then return end

	parseLHKPDrawingAllAge = self:SetLHDrawingAllAgesData(effectId,heroEffRef.LHDrawingAllAges)
	return parseLHKPDrawingAllAge
end



function ModelHeroExtra:SetLHDrawingAllAgesData(effId,LHDrawingAllAges)
	local parseLHDrawingAllAges = self._parseLHDrawingAllAges
	if not parseLHDrawingAllAges then
		parseLHDrawingAllAges = {}
		self._parseLHDrawingAllAges = parseLHDrawingAllAges
	end
	local parseLHKPDrawingAllAge = {}
	if LHDrawingAllAges and #LHDrawingAllAges > 0 then
		for i,v in ipairs(LHDrawingAllAges) do
			v = string.split(v,"=")
			table.insert(parseLHKPDrawingAllAge,{
				res = v[1],
				pos = LxDataHelper.ParseVector2NotEmpty(v[2]),
				scale = checknumber(v[3]),
				rotate = checknumber(v[4]),
			})
		end
	end
	parseLHDrawingAllAges[effId] = parseLHKPDrawingAllAge
	return parseLHKPDrawingAllAge
end

function ModelHeroExtra:GetLHDrawingAllAgesDataByPrefabName(spineName)
	local parseShieldLHDrawingAllAges = self._parseShieldLHDrawingAllAges
	if not parseShieldLHDrawingAllAges then
		parseShieldLHDrawingAllAges = {}
		self._parseShieldLHDrawingAllAges = parseShieldLHDrawingAllAges
	end
	local parseShieldLHDrawingAllAge = parseShieldLHDrawingAllAges[spineName]
	if parseShieldLHDrawingAllAge then return parseShieldLHDrawingAllAge end

	local ref = gLGameLanguage:GetShieldLHjdRef(spineName)
	if not ref then return nil end

	local LHDrawingAllAges = ref.LHDrawingAllAges
	local resType = LPlayerPrefs.GetLocalization()
	if resType then
		if resType == 3 then
			LHDrawingAllAges = ref.LHDrawingAllAges1
		elseif resType == 4 then
			LHDrawingAllAges = ref.LHDrawingAllAges2
		end
	end
	parseShieldLHDrawingAllAge = self:SetLHDrawingAllAgesDataByPrefabName(spineName,LHDrawingAllAges)
	return parseShieldLHDrawingAllAge
end

function ModelHeroExtra:SetLHDrawingAllAgesDataByPrefabName(spineName,LHDrawingAllAges)
	local parseShieldLHDrawingAllAges = self._parseShieldLHDrawingAllAges
	if not parseShieldLHDrawingAllAges then
		parseShieldLHDrawingAllAges = {}
		self._parseShieldLHDrawingAllAges = parseShieldLHDrawingAllAges
	end
	local parseShieldLHDrawingAllAge = {}
	if LHDrawingAllAges and #LHDrawingAllAges > 0 then
		for i,v in ipairs(LHDrawingAllAges) do
			v = string.split(v,"=")
			table.insert(parseShieldLHDrawingAllAge,{
				res = v[1],
				pos = LxDataHelper.ParseVector2NotEmpty(v[2]),
				scale = checknumber(v[3]),
				rotate = checknumber(v[4]),
			})
		end
	end
	parseShieldLHDrawingAllAges[spineName] = parseShieldLHDrawingAllAge
	return parseShieldLHDrawingAllAge
end

function ModelHeroExtra:GetPolymorphismNew(refId)
	local tempList = gModelHero:GetPolymorphism(refId)
	if tempList and #tempList > 0 then
		local list = {}
		table.insert(list,{ refId = refId, needStar = 0 })
		for i,v in ipairs(tempList) do
			if self:NeedCheckResType() then
				if not self:CheckBookIsCalm(v.refId) then
					table.insert(list,v)
				end
			else
				table.insert(list,v)
			end
		end
		return list
	end
end

function ModelHeroExtra:NeedCheckResType()
	local resType = LPlayerPrefs.GetLocalization()
	return resType == 3
end

---@param iconBig string 原来的icon
---@param heroEffectRef V_HeroEffectRef
function ModelHeroExtra:GetShieldIconBig(iconBig,heroEffectRef)
	if not heroEffectRef then return iconBig end
	local heroDrawing = gLGameLanguage:GetPrefabName(heroEffectRef.heroDrawing)
	local shieldLHRef = gLGameLanguage:GetShieldLHjdRef(heroDrawing)
	if shieldLHRef then
		local replaceIconBig
		local resType = LPlayerPrefs.GetLocalization()
		if resType then
			if resType == 3 then
				if not string.isempty(shieldLHRef.iconBigHX1) then
					replaceIconBig = shieldLHRef.iconBigHX1
				end
			elseif resType == 4 then
				if not string.isempty(shieldLHRef.iconBigHX2) then
					replaceIconBig = shieldLHRef.iconBigHX2
				end
			end
		end
		if not replaceIconBig and not string.isempty(shieldLHRef.iconBigHX) then
			replaceIconBig = shieldLHRef.iconBigHX
		end
		if replaceIconBig then
			iconBig = replaceIconBig
		end
	end
	return iconBig
end

--清理工作
--停止计时器之类的
function ModelHeroExtra:OnModelClear()
end

return ModelHeroExtra