---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/11 21:42
---

---@class LFDTGridUnitViewMgr
local LFDTGridUnitViewMgr = LxClass("LFDTGridUnitViewMgr")

function LFDTGridUnitViewMgr:LFDTGridUnitViewMgr()
    ---@type LFDTManager
    self._mgr = nil

    ---@type LFastDreamTripMap
    self._mapCls = nil

    ---@type UIObjPool
    self._objPool = nil

    ---@type Transform
    self._gridRoot = nil

    ---@type table<number,Transform>
    self._gridTransMap = {}

    ---@type table<number,LDisplayEffect> 特效列表
    self._gridOnEffectDpMap = {}
end

function LFDTGridUnitViewMgr:Dispose()
    if self._gridOnEffectDpMap then
        for k,v in pairs(self._gridOnEffectDpMap) do
            v:Destroy()
            self._gridOnEffectDpMap[k] = nil
        end

    end
    if self._objPool then
        self._objPool:DestroyAllObj()
        self._objPool = nil
    end
end

---@param mgr LFDTManager
function LFDTGridUnitViewMgr:InitData(mgr,data)
    self._mgr = mgr
    self._mapCls = mgr:GetMap()
    if not self._objPool then
        self._objPool = UIObjPool:New()
        self._objPool:Create(data.templateRoot,data.template)
    end
end

function LFDTGridUnitViewMgr:SetParentRoot(gridRoot)
    self._gridRoot = gridRoot
    self._objPool:ReturnAllObj()
end

---@param objPool UIObjPool
function LFDTGridUnitViewMgr:SetObjPool(objPool)
    self._objPool = objPool
end

---@param ref any MapDreamTripRef
---@param platformRef any DreamTripPlatformRef
---@param themeCfg V_DreamTripMapRef DreamTripMapRef
---@param cb function 加载完回调
function LFDTGridUnitViewMgr:CreateGrid(ref,platformRef,themeCfg,platformImgs,cb)
    if not self._objPool then return end
    if not self._gridRoot then return end

    local platformNum = platformRef.platformNum

    local itemNew = self._objPool:GetObj()

    ---@type Transform
    local itemTrans = itemNew.transform
    itemTrans:SetParent(self._gridRoot.transform, false)
    itemNew.name = string.format("item{%s_%s}",platformNum,themeCfg.endPlatform)

    local GridIcon = CS.FindTrans(itemTrans,"Root/GridIcon")
    CS.ShowObject(GridIcon,true)
    local isHasImgs = platformImgs and #platformImgs > 0
    local resName = isHasImgs and platformImgs[1] or "MapDT_ui_1"
    self._mapCls:SetSprite(GridIcon,resName,nil)

    local GridIcon_on = CS.FindTrans(itemTrans,"Root/GridIcon_on")
    CS.ShowObject(GridIcon_on,false)
    resName = isHasImgs and platformImgs[2] or "MapDT_ui_1_on"
    self._mapCls:SetSprite(GridIcon_on,resName,nil)

    local pos = ref.pos
    itemTrans.localPosition = Vector3(pos.x,pos.y,pos.z)
    itemTrans.localScale = Vector3.zero

    self:SetClick(itemTrans,function()
        self._mgr:ExecuteClick(platformNum)
    end)

    local DiceTag = CS.FindTrans(itemTrans,"Root/DiceTag")

    local gridTagTrans = CS.FindTrans(itemTrans,"Root/GridTag")

    self._gridTransMap[platformNum] = {
        itemTrans = itemTrans,
        gridIconObj = GridIcon,
        gridIconOnObj = GridIcon_on,
        gridTagTrans = gridTagTrans,
        gridForkTrans = CS.FindTrans(itemTrans,"Root/GridFork"),
        diceTagTrans = DiceTag,
        topLeftTrans = CS.FindTrans(DiceTag,"TopLeft"),
        topRightTrans = CS.FindTrans(DiceTag,"TopRight"),
        botLeftTrans = CS.FindTrans(DiceTag,"BotLeft"),
        botRightTrans = CS.FindTrans(DiceTag,"BotRight"),
    }

    self:SetGridTagShowState(platformNum,false)

    local bShow = gModelFastDreamTrip:GetForkEventPointForkShowState(themeCfg.refId,platformNum)
    self:ShowGridForkTarget(platformNum,bShow)

    local forkStateMap = {}
    ---@param eventInfo StructDreamTripEventInfo
    local isFork,eventInfo = gModelFastDreamTrip:CheckIndexEventIsFork(platformNum)
    if isFork and eventInfo then
        local parameterList = gModelFastDreamTrip:GetForkroadParameter(eventInfo.eventRefId)
        if parameterList then
            local mapGameId = gModelFastDreamTrip:GetDreamTripMapGameId()
            local curPos = gModelFastDreamTrip:GetMapDreamTripGridPos(mapGameId,platformNum)
            local gridStartIndex
            for i,v in ipairs(parameterList) do
                gridStartIndex = v.gridStartIndex
                local gridPos = gModelFastDreamTrip:GetMapDreamTripGridPos(mapGameId,gridStartIndex)
                if gridPos then
                    local isLeft,isDown = false,false
                    local topX = gridPos.x - curPos.x
                    local topY = gridPos.y - curPos.y
                    if topY ~= 0 then
                        isDown = topY < 0
                    end
                    if topX ~= 0 then
                        isLeft = topX < 0
                    end
                    local dire
                    if isDown then
                        dire = isLeft and ModelFastDreamTrip.TYPE_BOT_LEFT or ModelFastDreamTrip.TYPE_BOT_RIGHT
                    else
                        dire = isLeft and ModelFastDreamTrip.TYPE_TOP_LEFT or ModelFastDreamTrip.TYPE_TOP_RIGHT
                    end
                    forkStateMap[dire] = true
                end
            end
        end
    end
    self:ShowDiceTag(platformNum,isFork,forkStateMap)


    local isNormal = themeCfg.dice == 1
    local effRes = isNormal and "fx_ui_zuanshimijing_caigezi_1" or "fx_ui_zuanshimijing_caigezi_2"
    ---@type LDisplayEffect
    local effectDp = LDisplayEffect:New()
    effectDp:CreateEffect(gridTagTrans, effRes)
    effectDp:SetRenderOrder(0)
    effectDp:SetLoadedFunction(function(eff)
        if cb then cb() end
    end)
    effectDp:StartLoadEffect()
end

function LFDTGridUnitViewMgr:SetClick(trans,func)
    local comp = CS.BuildingClick.Get(trans.gameObject)
    local mapName = self._mgr:GetMap():GetMapName()
    local path = LxUiHelper.GetRelativePath(mapName,trans)
    local modifyFun = function()
        printInfoN(string.format("path %s",path))
        if func then func() end
    end
    comp.ClickDelegate = modifyFun
end

---@return Transform
function LFDTGridUnitViewMgr:GetGridTransByGridIdx(gridIdx)
    if not self._gridTransMap[gridIdx] then return end
    return self._gridTransMap[gridIdx].itemTrans
end

function LFDTGridUnitViewMgr:SetGridTagShowState(gridIdx,bShow)
    if not self._gridTransMap[gridIdx] then return end
    local gridTransInfo = self._gridTransMap[gridIdx]
    local gridTagTrans = gridTransInfo.gridTagTrans
    local gridIconObj = gridTransInfo.gridIconObj
    local gridIconOnObj = gridTransInfo.gridIconOnObj
    CS.ShowObject(gridTagTrans,bShow)
    CS.ShowObject(gridIconObj,not bShow)
    CS.ShowObject(gridIconOnObj,bShow)
end

function LFDTGridUnitViewMgr:ShowGridForkTarget(gridIdx,bShow)
    if not self._gridTransMap[gridIdx] then return end

    local gridTrans = self._gridTransMap[gridIdx]
    local gridForkTrans = gridTrans.gridForkTrans
    if not gridForkTrans then return end

    CS.ShowObject(gridForkTrans,bShow)
end

function LFDTGridUnitViewMgr:ShowDiceTag(gridIdx,bShow,forkStateMap)
    if not self._gridTransMap[gridIdx] then return end

    local gridTrans = self._gridTransMap[gridIdx]
    if not gridTrans then return end

    CS.ShowObject(gridTrans.diceTagTrans,bShow)
    if not bShow then return end


    CS.ShowObject(gridTrans.topLeftTrans,forkStateMap[ModelFastDreamTrip.TYPE_TOP_LEFT])
    CS.ShowObject(gridTrans.topRightTrans,forkStateMap[ModelFastDreamTrip.TYPE_TOP_RIGHT])
    CS.ShowObject(gridTrans.botLeftTrans,forkStateMap[ModelFastDreamTrip.TYPE_BOT_LEFT])
    CS.ShowObject(gridTrans.botRightTrans,forkStateMap[ModelFastDreamTrip.TYPE_BOT_RIGHT])
end

return LFDTGridUnitViewMgr