---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/11 21:41
---
---@class LFDTGridUnitView
local LFDTGridUnitView = LxClass("LFDTGridUnitView")

function LFDTGridUnitView:LFDTGridUnitView()
    ---@type LFDTManager
    self._mgr = nil
end

function LFDTGridUnitView:Dispose()

end

function LFDTGridUnitView:Create(mgr,trans,data)
    self._mgr = mgr
end

return LFDTGridUnitView