---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 15:00
---
------------------------------------------------------------------
---数据结构数据示例
---多模块使用的数据结构应该有对应的类声明
------------------------------------------------------------------
---@class StructPetDreamLandRankReport
local StructPetDreamLandRankReport = LxClass("StructPetDreamLandRankReport", nil)
function StructPetDreamLandRankReport:StructPetDreamLandRankReport()
	---@type string 战报id
	self.reportId = ""

	---@type table<StructRewardItem> 奖励物品列表（若是防守则为丢失奖励）
	self.itemList = {}

	--- 展示用的
	self.showRewardList = {}

	---@type number 战斗方式1-进攻，2-防守
	self.type = 0

	---@type number 战斗结果1-抢夺成功，2-抢夺失败，3-偷袭成功，4-偷袭失败
	self.result = 0

	---@type number 战斗开始时间(秒)
	self.startTime = 0

	--- 玩家信息
	self.playerInfo = nil

	---@type number 跨服字段： 战报所在服务器Id
	self.serverId = nil

	---@type number 敌方玩家战力
	self.fightPower = 0
end

function StructPetDreamLandRankReport:CreateByPb(pb)
	self.reportId = pb.reportId

	--- 1-进攻，2-防守
	self.type = pb.type

	--- 1-抢夺成功，2-抢夺失败，3-偷袭成功，4-偷袭失败
	self.result = pb.result

	local isAdd = false
	local color
	if self.type == ModelPetDreanLand.TYPE_REPORT_ATTACK then
		if self.result == 1 or self.result == 3 then
			color = "#139057"
			isAdd = true
		end
	else
		if self.result == 1 or self.result == 3 then
			color = "#C81212"
		end
	end

	self.itemList = {}
	self.showRewardList = {}
	local itemList = pb.itemList or {}
	for i,v in ipairs(itemList) do
		---@type StructRewardItem
		local data = StructRewardItem:New()
		data:CreateByPb(v)
		table.insert(self.itemList,data)
		
		table.insert(self.showRewardList,{
			reward = data,
			color = color,
			isAdd = isAdd
		})
	end

	self.startTime = tonumber(pb.startTime) / 1000

	self.playerInfo = nil
	if pb.playerInfo then
		self.playerInfo = pb.playerInfo
	end

	self.serverId = pb.serverId

	self.fightPower = pb.fightPower
end

---@return string 玩家名字
function StructPetDreamLandRankReport:GetPlayerName()
	return self.playerInfo and self.playerInfo.name or ""
end

---@return number 玩家战力
function StructPetDreamLandRankReport:GetPlayerPower()
	--return self.playerInfo and self.playerInfo.power or 0
	return self.fightPower
end

---@return number 玩家头像
function StructPetDreamLandRankReport:GetPlayerHead()
	return self.playerInfo and self.playerInfo.head
end

---@return number 玩家头像框
function StructPetDreamLandRankReport:GetPlayerHeadFrame()
	return self.playerInfo and self.playerInfo.headFrame
end

---@return number 玩家等级
function StructPetDreamLandRankReport:GetPlayerGrade()
	return self.playerInfo and self.playerInfo.grade
end

---@return number 玩家Id
function StructPetDreamLandRankReport:GetPlayerId()
	return self.playerInfo and self.playerInfo.playerId
end

function StructPetDreamLandRankReport:GetRewardStr()
	local itemStrs = {}
	---@param v StructRewardItem
	for i,v in ipairs(self.itemList) do
		local str = string.replace(ccClientText(43362),gModelItem:GetNameByRefId(v.itemId),LUtil.NumberCoversion(v.count))
		table.insert(itemStrs,str)
	end
	return table.concat(itemStrs,ccClientText(43356))
end

function StructPetDreamLandRankReport:GetReportDesc()
	--- 1-进攻，2-防守
	local type = self.type

	--- 1-抢夺成功，2-抢夺失败，3-偷袭成功，4-偷袭失败
	local result = self.result

	local playerName = self:GetPlayerName()
	local rewardStr = self:GetRewardStr()
	local str = ""
	if type == ModelPetDreanLand.TYPE_REPORT_ATTACK then
		if result == 1 then
			str = string.replace(ccClientText(43340),playerName,rewardStr)
		elseif result == 2 then
			str = string.replace(ccClientText(43357),playerName)
		elseif result == 3 then
			str = string.replace(ccClientText(43359),playerName,rewardStr)
		elseif result == 4 then
			str = string.replace(ccClientText(43363),playerName)
		end
	else
		if result == 1 then
			str = string.replace(ccClientText(43360),playerName,rewardStr)
		elseif result == 2 then
			str = string.replace(ccClientText(43364),playerName)
		elseif result == 3 then
			str = string.replace(ccClientText(43361),playerName,rewardStr)
		elseif result == 4 then
			str = string.replace(ccClientText(43332),playerName)
		end
	end
	return str
end

---@return boolean 是否可以复仇
function StructPetDreamLandRankReport:CheckIsCanRevenge()
	if self.type == ModelPetDreanLand.TYPE_REPORT_DEFEND then
		if self.result == 1 or self.result == 3 then
			return true
		end
	end
	return false
end

function StructPetDreamLandRankReport:GetReportTitle()
	local str
	--- 1-抢夺成功，2-抢夺失败，3-偷袭成功，4-偷袭失败
	local result = self.result
	if self.type == ModelPetDreanLand.TYPE_REPORT_ATTACK then
		if result == 1 or result == 3 then
			str = ccClientText(43337)
		else
			str = ccClientText(43338)
		end
	else
		if result == 1 or result == 3 then
			str = ccClientText(43329)
		else
			str = ccClientText(43328)
		end
	end
	return str
end

function StructPetDreamLandRankReport:GetNoLoseTxt()
	if #self.showRewardList > 0 then return "" end

	if self.type == ModelPetDreanLand.TYPE_REPORT_ATTACK then
		return ccClientText(43358)
	else
		return ccClientText(43401)
	end
end

return StructPetDreamLandRankReport