---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 15:00
---
------------------------------------------------------------------
---数据结构数据示例
---多模块使用的数据结构应该有对应的类声明
------------------------------------------------------------------
---@class StructHeroLoveInfo
local StructHeroLoveInfo = LxClass("StructHeroLoveInfo", nil)
function StructHeroLoveInfo:StructHeroLoveInfo()
	self.heroRefId = 0
	self.love = 0
	self.allLoveNum = false
end

function StructHeroLoveInfo:CreateByPb(pb)
	self.heroRefId = pb.heroRefId
	local love =  pb.love
	local isLove = love and love == 1 or false
	self.love = isLove
	self.allLoveNum = pb.allLoveNum
end

function StructHeroLoveInfo:GetHeroRefId()
	return self.heroRefId
end

function StructHeroLoveInfo:GetLove()
	return self.love
end

function StructHeroLoveInfo:GetAllLoveNum()
	return self.allLoveNum
end

function StructHeroLoveInfo:GetServerData()
	return {
		heroRefId = self.heroRefId,
		love = self.love,
		allLoveNum = self.allLoveNum,
	}
end

return StructHeroLoveInfo