---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BY.
--- DateTime: 2023/10/16 21:16
---
------------------------------------------------------------------
---数据结构数据示例
---多模块使用的数据结构应该有对应的类声明
------------------------------------------------------------------
---@class StructRegressionGift
local StructRegressionGift = LxClass("StructRegressionGift", nil)
function StructRegressionGift:StructRegressionGift()
    self.refId = 0                      --礼包id
    self.buyNum = 0                     --剩余可购买数量
    self.selected = ""                  --选中的奖励
end

function StructRegressionGift:CreateByPb(pb)
    self.refId = pb.refId
    self.buyNum = pb.buyNum
    self.selected = pb.selected
end

return StructRegressionGift