---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 15:00
---
------------------------------------------------------------------
---数据结构数据示例
---多模块使用的数据结构应该有对应的类声明
------------------------------------------------------------------
---@class StructArenaGuessInfo
local StructArenaGuessInfo = LxClass("StructArenaGuessInfo", nil)
function StructArenaGuessInfo:StructArenaGuessInfo()
	self._playerId 	= 0		--竞猜玩家Id
	self._targetId	= 0 	--押注目标玩家Id
	self._guessCoin	= 0 	--押注金额
	self._round		= 0 	--押注轮次
	self._result	= 0 	--押注结果 （结算后才有）
	self._odds		= 0 	--押注赔率（结算后才有） -- 海外表示：0未结算1竞猜正确2竞猜失败3未投注
	self._buffBack	= 0 	--特权找回
	self._guessCondition = 0 	--竞猜条件
	self._value		= 0 	--竞猜是否成立 1：成立 2：不成立(海外)
	self._targetInfo = nil 	--目标玩家信息(海外)
    self._time      = 0     -- 竞猜时间(海外)
	self._reportId	= ""	-- 最后一场战报
	self._schedule  = -1	--事件进度值（排名or其他进度）
end

function StructArenaGuessInfo:CreateByPb(pb)
	self._playerId 	= pb.playerId
	self._targetId	= pb.targetId
	self._guessCoin	= pb.guessCoin
	self._round		= pb.round
	self._result	= pb.result
	self._odds		= pb.odds
	self._buffBack	= pb.buffBack
	self._guessCondition = pb.guessCondition
	self._value		= pb.value
    self._time      = pb.time
	self._reportId	= pb.reportId
	self._schedule	= pb.schedule

	if pb.targetInfo then
		self._targetInfo  	= gModelGeneral:SetPlayerInfo(pb.targetInfo)
	end
end

function StructArenaGuessInfo:GetPlayerId()
	return self._playerId
end

function StructArenaGuessInfo:GetTargetId()
	return self._targetId
end

function StructArenaGuessInfo:GetGuessCoin()
	return self._guessCoin
end

function StructArenaGuessInfo:GetRound()
	return self._round
end

function StructArenaGuessInfo:GetResult()
	return self._result
end

function StructArenaGuessInfo:GetOdds()
	return self._odds
end

function StructArenaGuessInfo:GetBuffBack()
	return self._buffBack
end

function StructArenaGuessInfo:GetGuessCondition()
	return self._guessCondition
end

function StructArenaGuessInfo:GetValue()
	return self._value
end

function StructArenaGuessInfo:GetTargetInfo()
	return self._targetInfo
end

function StructArenaGuessInfo:GetTime()
    return self._time
end

function StructArenaGuessInfo:GetReportId()
	return self._reportId
end

function StructArenaGuessInfo:GetSchedule()
	return self._schedule
end

function StructArenaGuessInfo:Destroy()
    table.removeall(self)
end

return StructArenaGuessInfo