---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023-10-24 15:00
---
------------------------------------------------------------------
---数据结构数据示例
---多模块使用的数据结构应该有对应的类声明
------------------------------------------------------------------
---@class StructFarmLand
local StructFarmLand = LxClass("StructFarmLand", nil)


function StructFarmLand:StructFarmLand()
    --地块下标
    self.index = 0
    --种子
    self.seed = 0
    ---作物
    self.crop = 0
    --种植时间，秒
    self.starTime = 0
    --成熟时间 秒
    self.endTime = 0
    --丢失的积分
    self.loseScore = 0
    --已经被偷取次数
    self.stealCount = 0
    --自己是否已偷取
    self.steal = 0
end

function StructFarmLand:CreateByPb(pb)
    self.index = pb.index
    self.seed = pb.seed
    self.crop = pb.crop
    self.starTime = pb.starTime
    self.endTime = pb.endTime
    self.loseScore = pb.loseScore
    self.stealCount = pb.stealCount
    self.steal = pb.steal
end

function StructFarmLand:GetRemainTime()
    local curTime = GetTimestamp()
    local remain = self.endTime - curTime
    return remain>0 and remain or 0
end
--作物是否成熟  --1幼苗 2生长期 3成熟
function StructFarmLand:IsMatureCrop(activityId)
    local state = GetTimestamp()>=self.endTime and 3 or 0
    if state~=3 and activityId then 
        local seedInfo = gModelFarm:GetCropGrowInfo(activityId,self.crop)
        local remainTime = math.max(self.endTime - GetTimestamp(),0)
        state = (remainTime/seedInfo.growTime)>=0.7 and 1 or 2
    end
    return state==3,state
end


return StructFarmLand