---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BY.
--- DateTime: 2023/10/24 19:46
------------------------------------------------------------------------
---@class StructActivity
local StructActivity = LxClass("StructActivity", nil)

function StructActivity:StructActivity()
    self.sid = 0            --活动Id
    self.title = ""         --活动标题
    self.desc = ""          --活动描述
    self.status = 0         --状态（1-生效&显示中，2-失效&显示中，3-不显示）
    self.startTime = 0      --开始时间(秒)
    self.endTime = 0        --结束时间(秒),0永久
    self.showEndTime = 0    --显示结束时间(秒)
    self.sort = 0           --活动排序序号（数据类型：int）
    self.icon = ""           --活动图标
    self.model = 0          --活动模板号
    self.type = 0           --活动入口的类型
    self.showScene = 0  --活动是否要显示在主界面特殊按钮区域
    self.showSceneIcon = "" --在主界面的特殊按钮区域的入口图标,仅当showScene字段填写1时读取
    self.moreInfo = ""      --josn格式活动额外数据,用于特殊活动参数
    self.verifyTime = ""    --审核时间
    self.uniqueJump = 0
    self.shopId =  0
    self.iconEffect = "" --特效
    self.iconName = "" --特效对应的文本
    self.goldBuy = nil
    self.exploreTask = nil
    self.wonderLand = nil
    self.wonderLandReward = nil
    self.showEffect = nil
    self.packId = nil
end

function StructActivity:CreateByPb(pb)
    self.sid = pb.sid
    self.title = gModelActivity:GetLngNameById(pb.title) or ""
    self.desc = pb.desc
    self.status = pb.status
    self.startTime = pb.startTime
    self.endTime = pb.endTime
    self.showEndTime = pb.showEndTime
    self.sort = pb.sort
    self.icon = pb.icon
    self.model = pb.model
    self.type=pb.type
    self.showScene = pb.showScene
    self.showSceneIcon = pb.showSceneIcon
    self.moreInfo=pb.moreInfo
    self.verifyTime = pb.verifyTime    --审核时间
    self.uniqueJump = pb.uniqueJump
    self.shopId = pb.shopId
    self.iconEffect = pb.iconEffect
    self.iconName = pb.iconName

    self.goldBuy = pb.goldBuy
    self.exploreTask = pb.exploreTask
    self.wonderLand = pb.wonderLand
    self.wonderLandReward = pb.wonderLandReward
    self.showEffect = pb.showEffect
    self.scrollConfig = pb.scrollConfig

    self.titleId = pb.title

    self.packId = pb.packId
end

function StructActivity:GetMoreInfo()
    if not self._decode_moreInfo then
        if not string.isempty(self.moreInfo) then
            self._decode_moreInfo = JSON.decode(self.moreInfo)
        end
        if not self._decode_moreInfo then
            self._decode_moreInfo = {}
        end
    end
    return self._decode_moreInfo
end

function StructActivity:Clone()
    local info = StructActivity:New()
    info.sid = self.sid
    info.title = self.title
    info.desc = self.desc
    info.status = self.status
    info.startTime = self.startTime
    info.endTime = self.endTime
    info.showEndTime = self.showEndTime
    info.sort = self.sort
    info.icon = self.icon
    info.model = self.model
    info.type=self.type
    info.showScene = self.showScene
    info.showSceneIcon = self.showSceneIcon
    info.moreInfo=self.moreInfo
    info.verifyTime = self.verifyTime    --审核时间
    info.uniqueJump = self.uniqueJump
    info.shopId = self.shopId
    info.iconEffect = self.iconEffect
    info.iconName = self.iconName
    info.goldBuy = self.goldBuy
    info.exploreTask = self.exploreTask
    info.wonderLand = self.wonderLand
    info.wonderLandReward = self.wonderLandReward
    info.showEffect = self.showEffect
    info.scrollConfig = self.scrollConfig
    info.titleId = self.title
    return info
end

function StructActivity:SetStatus(state)
    self._status = state
end

return StructActivity